import {
  BUTTON_COLOR,
  BUTTON_COLORS,
  BUTTON_SIZE,
  BUTTON_SIZES,
  BUTTON_VARIANT,
  BUTTON_VARIANTS,
} from '@ovhcloud/ods-react';

export {
  BUTTON_COLOR,
  BUTTON_COLORS,
  BUTTON_SIZE,
  BUTTON_SIZES,
  BUTTON_VARIANTS,
  BUTTON_VARIANT,
};
