export const ROUTES_URLS = {
  root: '/',
  listing: '/',
  onboarding: '/onboarding',
  terminateOkms: '/terminate',
  createKeyManagementService: 'create',
  okmsId: ':okmsId',
  okmsUpdateName: 'update-name',
  keys: 'keys',
  keyId: ':keyId',
  createKmsServiceKey: 'create',
  serviceKeyEditName: 'edit-name',
  serviceKeyDeactivate: 'deactivate',
  credentials: 'credentials',
  createCredential: 'create',
  createCredentialAddUserModal: 'add-users',
  createCredentialAddGroupsModal: 'add-groups',
  createCredentialAddServiceAccountModal: 'add-service-account',
  credentialId: ':credentialId',
  credentialIdentities: 'identities',
  credentialDelete: 'delete',
};
