export const GUIDES = [
  {
    title: 'cda_onboarding_guide1_title',
    description: 'cda_onboarding_guide1_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/ceph/faq/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/ceph/faq/',
      IE: 'https://docs.ovh.com/ie/en/storage/ceph/faq/',
      GB: 'https://docs.ovh.com/gb/en/storage/ceph/faq/',
      CA: 'https://docs.ovh.com/ca/en/storage/ceph/faq/',
      QC: 'https://docs.ovh.com/ca/fr/storage/ceph/faq/',
      AU: 'https://docs.ovh.com/au/en/storage/ceph/faq/',
      SG: 'https://docs.ovh.com/sg/en/storage/ceph/faq/',
      FR: 'https://docs.ovh.com/fr/storage/ceph/faq/',
      WE: 'https://docs.ovh.com/us/en/storage/ceph/faq/',
      WS: 'https://docs.ovh.com/us/en/storage/ceph/faq/',
      US: 'https://docs.ovh.com/us/en/storage/ceph/faq/',
    },
  },
  {
    title: 'cda_onboarding_guide2_title',
    description: 'cda_onboarding_guide2_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/ceph/use-ceph-with-proxmox/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/ceph/use-ceph-with-proxmox/',
      DE: 'https://docs.ovh.com/de/storage/ceph/use-ceph-with-proxmox/',
      ES: 'https://docs.ovh.com/es/storage/ceph/utilizar-ceph-con-proxmox/',
      IE: 'https://docs.ovh.com/ie/en/storage/ceph/use-ceph-with-proxmox/',
      IT: 'https://docs.ovh.com/it/storage/ceph/use-ceph-with-proxmox/',
      PL: 'https://docs.ovh.com/pl/storage/ceph/use-ceph-with-proxmox/',
      PT: 'https://docs.ovh.com/pt/storage/ceph/use-ceph-with-proxmox/',
      GB: 'https://docs.ovh.com/gb/en/storage/ceph/use-ceph-with-proxmox/',
      CA: 'https://docs.ovh.com/ca/en/storage/ceph/use-ceph-with-proxmox/',
      QC: 'https://docs.ovh.com/ca/fr/storage/ceph/utiliser-ceph-avec-proxmox/',
      AU: 'https://docs.ovh.com/au/en/storage/ceph/use-ceph-with-proxmox/',
      SG: 'https://docs.ovh.com/sg/en/storage/ceph/use-ceph-with-proxmox/',
      FR: 'https://docs.ovh.com/fr/storage/ceph/utiliser-ceph-avec-proxmox/',
      WE: 'https://docs.ovh.com/us/en/storage/ceph/use-ceph-with-proxmox/',
      WS: 'https://docs.ovh.com/us/en/storage/ceph/use-ceph-with-proxmox/',
      US: 'https://docs.ovh.com/us/en/storage/ceph/use-ceph-with-proxmox/',
    },
  },
];

export const CTAS = {
  DEFAULT: 'https://ovhcloud.com/en/cloud-disk-array',
  ASIA: 'https://ovhcloud.com/asia/cloud-disk-array',
  DE: 'https://ovhcloud.com/de/cloud-disk-array',
  ES: 'https://ovhcloud.com/es-es/cloud-disk-array',
  IE: 'https://ovhcloud.com/en-ie/cloud-disk-array',
  IT: 'https://ovhcloud.com/it/cloud-disk-array',
  NL: 'https://ovhcloud.com/nl/cloud-disk-array',
  PL: 'https://ovhcloud.com/pl/cloud-disk-array',
  PT: 'https://ovhcloud.com/pt/cloud-disk-array',
  GB: 'https://ovhcloud.com/en-gb/cloud-disk-array',
  CA: 'https://ovhcloud.com/en-ca/cloud-disk-array',
  QC: 'https://ovhcloud.com/fr-ca/cloud-disk-array',
  MA: 'https://ovhcloud.com/fr-ma/cloud-disk-array',
  SN: 'https://ovhcloud.com/fr-sn/cloud-disk-array',
  TN: 'https://ovhcloud.com/fr-tn/cloud-disk-array',
  AU: 'https://ovhcloud.com/en-au/cloud-disk-array',
  SG: 'https://ovhcloud.com/en-sg/cloud-disk-array',
  FR: 'https://ovhcloud.com/fr/cloud-disk-array',
  CZ: 'https://ovhcloud.com/cz-cs/cloud-disk-array',
  FI: 'https://ovhcloud.com/fi/cloud-disk-array',
  LT: 'https://ovhcloud.com/lt/cloud-disk-array',
  WE: 'https://ovhcloud.com/us-en/cloud-disk-array',
  WS: 'https://ovhcloud.com/us-en/cloud-disk-array',
};
