export const GUIDES = [
  {
    title: 'cda_onboarding_guide1_title',
    description: 'cda_onboarding_guide1_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/ceph/faq/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/ceph/faq/',
      IE: 'https://docs.ovh.com/ie/en/storage/ceph/faq/',
      GB: 'https://docs.ovh.com/gb/en/storage/ceph/faq/',
      CA: 'https://docs.ovh.com/ca/en/storage/ceph/faq/',
      QC: 'https://docs.ovh.com/ca/fr/storage/ceph/faq/',
      AU: 'https://docs.ovh.com/au/en/storage/ceph/faq/',
      SG: 'https://docs.ovh.com/sg/en/storage/ceph/faq/',
      FR: 'https://docs.ovh.com/fr/storage/ceph/faq/',
      WE: 'https://docs.ovh.com/us/en/storage/ceph/faq/',
      WS: 'https://docs.ovh.com/us/en/storage/ceph/faq/',
      US: 'https://docs.ovh.com/us/en/storage/ceph/faq/',
    },
  },
  {
    title: 'cda_onboarding_guide2_title',
    description: 'cda_onboarding_guide2_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/ceph/use-ceph-with-proxmox/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/ceph/use-ceph-with-proxmox/',
      DE: 'https://docs.ovh.com/de/storage/ceph/use-ceph-with-proxmox/',
      ES: 'https://docs.ovh.com/es/storage/ceph/utilizar-ceph-con-proxmox/',
      IE: 'https://docs.ovh.com/ie/en/storage/ceph/use-ceph-with-proxmox/',
      IT: 'https://docs.ovh.com/it/storage/ceph/use-ceph-with-proxmox/',
      PL: 'https://docs.ovh.com/pl/storage/ceph/use-ceph-with-proxmox/',
      PT: 'https://docs.ovh.com/pt/storage/ceph/use-ceph-with-proxmox/',
      GB: 'https://docs.ovh.com/gb/en/storage/ceph/use-ceph-with-proxmox/',
      CA: 'https://docs.ovh.com/ca/en/storage/ceph/use-ceph-with-proxmox/',
      QC: 'https://docs.ovh.com/ca/fr/storage/ceph/utiliser-ceph-avec-proxmox/',
      AU: 'https://docs.ovh.com/au/en/storage/ceph/use-ceph-with-proxmox/',
      SG: 'https://docs.ovh.com/sg/en/storage/ceph/use-ceph-with-proxmox/',
      FR: 'https://docs.ovh.com/fr/storage/ceph/utiliser-ceph-avec-proxmox/',
      WE: 'https://docs.ovh.com/us/en/storage/ceph/use-ceph-with-proxmox/',
      WS: 'https://docs.ovh.com/us/en/storage/ceph/use-ceph-with-proxmox/',
      US: 'https://docs.ovh.com/us/en/storage/ceph/use-ceph-with-proxmox/',
      IN: 'https://docs.ovh.com/asia/en/storage/ceph/use-ceph-with-proxmox/',
    },
  },
];

export const CTAS = {
  DEFAULT: 'https://www.ovh.com/fr/cloud-disk-array',
  PL: 'https://www.ovh.pl/cloud-disk-array',
  FR: 'https://www.ovh.com/fr/cloud-disk-array',
};
