export const testIds = {
  formSubmitCta: 'form-submit-cta',
  formPreviousCta: 'form-previous-cta',
  toggleFieldInput: 'toggle-field-input',
  summaryUpdateCta: 'summary-update-cta',
  summaryFieldValue: 'summary-field-value',
  summaryDownloadLink: 'summary-download-link',
  formFileUpload: 'installation-form-file-upload',
  hubLinkSapHanaDocs: 'hub-link-sap-hana-documentation',
  hubLinkInfraAsCodeDocs: 'hub-link-infrastructure-as-code-documentation',
  hubLinkInfraAsCodeGit: 'hub-link-infrastructure-as-code-git',
  hubLinkBackintDownload: 'hub-link-backint-download',
  hubLinkSapHanaBackupDocs: 'hub-link-sap-hana-backup-documentation',
  hubLinkWizardStart: 'hub-link-wizard-start',
  hubLinkWizardDocs: 'hub-link-wizard-documentation',
  hubLinkInstallationHistory: 'hub-link-installation-history',
  hubLinkAnalysisDocs: 'hub-link-analysis-documentation',
  hubLinkAnalysisGit: 'hub-link-analysis-git',
} as const;
