export const DEFAULT_DURATION = 'P1M';
export const DEFAULT_TYPE = 'periodic';
export const SUSPENDED_SERVICE = 'suspended';

export const SERVICE_TYPE = {
  EMAIL_DOMAIN: 'EMAIL_DOMAIN',
  EXCHANGE: 'EMAIL_EXCHANGE',
  HOSTING_WEB_EXTRA_SQL_PERSO: 'HOSTING_WEB_EXTRA_SQL_PERSO',
  HOSTING_PRIVATE_DATABASE: 'HOSTING_PRIVATE_DATABASE',
  HOSTING_WEB: 'HOSTING_WEB',
  LICENSE_HYCU: 'LICENSE_HYCU',
  OVH_CLOUD_CONNECT: 'OVH_CLOUD_CONNECT',
  PACK_XDSL: 'PACK_XDSL',
  SMS: 'SMS',
  TELEPHONY: 'TELEPHONY',
  ALL_DOM: 'ALL_DOM',
  OKMS: 'OKMS_RESOURCE',
  VEEAM_BACKUP: 'VMWARE_CLOUD_DIRECTOR_BACKUP',
  VPS: 'VPS',
  VRACK_SERVICES: 'VRACK_SERVICES_RESOURCE',
  VRACK: 'VRACK',
  VMWARE_CLOUD_DIRECTOR_ORGANIZATION: 'VMWARE_CLOUD_DIRECTOR_ORGANIZATION',
  ZIMBRA_SLOT: 'ZIMBRA_SLOT',
  DOMAIN: 'DOMAIN',
  DOMAIN_RESELLER: 'DOMAIN_RESELLER',
};

export default {
  DEFAULT_DURATION,
  DEFAULT_TYPE,
  SERVICE_TYPE,
};
