export const ONBOARDING_TRACKING_PREFIX =
  'PublicCloud::pci::projects::project::octavia-loadbalancer::onboarding';

export const GUIDES = [
  {
    title: 'octavia_load_balancer_onboarding_guide1_title',
    description: 'octavia_load_balancer_onboarding_guide1_description',
    links: {
      DEFAULT:
        'https://support.us.ovhcloud.com/hc/en-us/articles/18610207964051-Getting-Started-with-Load-Balancer-on-Public-Cloud',
      ASIA:
        'https://help.ovhcloud.com/csm/asia-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050195',
      AU:
        'https://help.ovhcloud.com/csm/en-au-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050198',
      CA:
        'https://help.ovhcloud.com/csm/en-ca-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050188',
      DE:
        'https://help.ovhcloud.com/csm/de-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0037842',
      ES:
        'https://help.ovhcloud.com/csm/es-es-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050208',
      FR:
        'https://docs.ovh.com/fr/load-balancer-octavia/premiers-pas-avec-load-balancer-public-cloud/',
      GB:
        'https://help.ovhcloud.com/csm/en-gb-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050203',
      IE:
        'https://help.ovhcloud.com/csm/en-ie-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050193',
      IT:
        'https://help.ovhcloud.com/csm/it-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050199',
      MA:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050200',
      NL:
        'https://help.ovhcloud.com/csm/en-ie-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050193',
      PL:
        'https://help.ovhcloud.com/csm/pl-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050201',
      PT:
        'https://help.ovhcloud.com/csm/pt-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050202',
      QC:
        'https://help.ovhcloud.com/csm/fr-ca-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050196',
      SN:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050200',
      SG:
        'https://help.ovhcloud.com/csm/en-sg-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050206',
      TN:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050200',
      US:
        'https://support.us.ovhcloud.com/hc/en-us/articles/18610207964051-Getting-Started-with-Load-Balancer-on-Public-Cloud',
      WE:
        'https://support.us.ovhcloud.com/hc/en-us/articles/18610207964051-Getting-Started-with-Load-Balancer-on-Public-Cloud',
      WS:
        'https://help.ovhcloud.com/csm/es-public-cloud-network-getting-started-load-balancer?id=kb_article_view&sysparm_article=KB0050197',
    },
  },
  {
    title: 'octavia_load_balancer_onboarding_guide2_title',
    description: 'octavia_load_balancer_onboarding_guide2_description',
    links: {
      DEFAULT:
        'https://support.us.ovhcloud.com/hc/en-us/articles/21133261407251-Concepts-Load-Balancer',
      ASIA:
        'https://help.ovhcloud.com/csm/asia-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0037954',
      AU:
        'https://help.ovhcloud.com/csm/en-au-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050293',
      CA:
        'https://help.ovhcloud.com/csm/en-ca-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050292',
      DE:
        'https://help.ovhcloud.com/csm/de-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050302',
      ES:
        'https://help.ovhcloud.com/csm/es-es-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050307',
      FR:
        'https://docs.ovh.com/fr/publiccloud/network-services/octavia-lbaas-in-openstack-env-deep-dive/',
      GB:
        'https://help.ovhcloud.com/csm/en-gb-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050294',
      IE:
        'https://help.ovhcloud.com/csm/en-ie-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050296',
      IT:
        'https://help.ovhcloud.com/csm/it-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050300',
      MA:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050299',
      NL:
        'https://help.ovhcloud.com/csm/en-ie-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050296',
      PL:
        'https://help.ovhcloud.com/csm/pl-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050301',
      PT:
        'https://help.ovhcloud.com/csm/pt-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050311',
      QC:
        'https://help.ovhcloud.com/csm/fr-ca-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050298',
      SN:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050299',
      SG:
        'https://help.ovhcloud.com/csm/en-sg-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050295',
      TN:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050299',
      US:
        'https://support.us.ovhcloud.com/hc/en-us/articles/21133261407251-Concepts-Load-Balancer',
      WE:
        'https://support.us.ovhcloud.com/hc/en-us/articles/21133261407251-Concepts-Load-Balancer',
      WS:
        'https://help.ovhcloud.com/csm/es-public-cloud-network-octavia-use-lbaas-openstack?id=kb_article_view&sysparm_article=KB0050306',
    },
  },
  {
    title: 'octavia_load_balancer_onboarding_guide3_title',
    description: 'octavia_load_balancer_onboarding_guide3_description',
    links: {
      DEFAULT:
        'https://support.us.ovhcloud.com/hc/en-us/articles/21194412563219-Configuring-a-Secure-Load-Balancer-with-Let-s-Encrypt',
      ASIA:
        'https://help.ovhcloud.com/csm/asia-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0037974',
      AU:
        'https://help.ovhcloud.com/csm/en-au-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050303',
      CA:
        'https://help.ovhcloud.com/csm/en-ca-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050304',
      DE:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050318',
      ES:
        'https://help.ovhcloud.com/csm/es-es-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050308',
      FR:
        'https://docs.ovh.com/fr/load-balancer-octavia/load-balancer-avec-letsencrypt/',
      GB:
        'https://help.ovhcloud.com/csm/en-gb-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050305',
      IE:
        'https://help.ovhcloud.com/csm/en-ie-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050314',
      IT:
        'https://help.ovhcloud.com/csm/it-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050320',
      MA:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050318',
      NL:
        'https://help.ovhcloud.com/csm/en-ie-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050314',
      PL:
        'https://help.ovhcloud.com/csm/pl-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050317',
      PT:
        'https://help.ovhcloud.com/csm/pt-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050313',
      QC:
        'https://help.ovhcloud.com/csm/fr-ca-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050310',
      SN:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050318',
      SG:
        'https://help.ovhcloud.com/csm/en-sg-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050315',
      TN:
        'https://help.ovhcloud.com/csm/fr-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050318',
      US:
        'https://support.us.ovhcloud.com/hc/en-us/articles/21194412563219-Configuring-a-Secure-Load-Balancer-with-Let-s-Encrypt',
      WE:
        'https://support.us.ovhcloud.com/hc/en-us/articles/21194412563219-Configuring-a-Secure-Load-Balancer-with-Let-s-Encrypt',
      WS:
        'https://help.ovhcloud.com/csm/fr-ca-public-cloud-network-load-balancer-letsencrypt?id=kb_article_view&sysparm_article=KB0050310',
    },
  },
];

export const PRIVATE_NETWORK_HELP = {
  DEFAULT:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  ASIA:
    'https://docs.ovh.com/asia/en/publiccloud/network-services/networking-concepts/',
  AU:
    'https://docs.ovh.com/au/en/publiccloud/network-services/networking-concepts/',
  CA:
    'https://docs.ovh.com/ca/en/publiccloud/network-services/networking-concepts/',
  DE:
    'https://docs.ovh.com/de/publiccloud/network-services/networking-concepts/',
  ES:
    'https://docs.ovh.com/es/publiccloud/network-services/networking-concepts/',
  FR:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  GB:
    'https://docs.ovh.com/gb/en/publiccloud/network-services/networking-concepts/',
  IE:
    'https://docs.ovh.com/ie/en/publiccloud/network-services/networking-concepts/',
  IT:
    'https://docs.ovh.com/it/publiccloud/network-services/networking-concepts/',
  MA:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  NL:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  PL:
    'https://docs.ovh.com/pl/publiccloud/network-services/networking-concepts/',
  PT:
    'https://docs.ovh.com/pt/publiccloud/network-services/networking-concepts/',
  QC:
    'https://docs.ovh.com/ca/fr/publiccloud/network-services/networking-concepts/',
  SN:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  SG:
    'https://docs.ovh.com/sg/en/publiccloud/network-services/networking-concepts/',
  TN:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  US:
    'https://docs.ovh.com/us/en/publiccloud/network-services/networking-concepts/',
  WE:
    'https://docs.ovh.com/asia/en/publiccloud/network-services/networking-concepts/',
  WS:
    'https://docs.ovh.com/us/es/publiccloud/network-services/networking-concepts/',
};
