import { eslintSharedConfig } from '@ovh-ux/manager-static-analysis-kit';

export default [
  ...eslintSharedConfig,
  {
    rules: {
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/unbound-method': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-enum-comparison': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/no-duplicate-enum-values': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      'check-file/folder-naming-convention': 'off',
      'check-file/filename-naming-convention': 'off',
      'jsx-a11y/interactive-supports-focus': 'off',
      'react/no-multi-comp': 'off',
      'css/no-important': 'off',
      'vitest/no-identical-title': 'off',
      'vitest/expect-expect': 'off',
      'import/named': 'off',
      'import/no-cycle': 'off',
      'react/jsx-uses-react': 'off',
      'import/no-unresolved': 'off',
      'max-lines-per-function': 'off',
      'check-file/no-index': 'off',
      'check-file/folder-match-with-fex': 'off',
      'react-hooks/rules-of-hooks': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/incompatible-library': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/static-components': 'off',
    },
  },
];
