import {
  MESSAGE_COLOR,
  MESSAGE_COLORS,
  MESSAGE_I18N,
  MESSAGE_VARIANT,
  MESSAGE_VARIANTS,
} from '@ovhcloud/ods-react';

export { MESSAGE_COLOR, MESSAGE_COLORS, MESSAGE_I18N, MESSAGE_VARIANT, MESSAGE_VARIANTS };
