packages:
  - .

overrides:
  "@ovh-ux/manager-account-migration": "link:../../modules/account-migration"
  "@ovh-ux/manager-advices": "link:../../modules/advices"
  "@ovh-ux/manager-at-internet-configuration": "link:../../modules/at-internet-configuration"
  "@ovh-ux/manager-banner": "link:../../modules/banner"
  "@ovh-ux/manager-beta-preference": "link:../../modules/beta-preference"
  "@ovh-ux/manager-billing": "link:../../modules/billing"
  "@ovh-ux/manager-billing-components": "link:../../modules/billing-components"
  "@ovh-ux/manager-bm-server-components": "link:../../modules/bm-server-components"
  "@ovh-ux/manager-catalog-price": "link:../../modules/catalog-price"
  "@ovh-ux/manager-cda": "link:../../modules/cda"
  "@ovh-ux/manager-cloud-connect": "link:../../modules/cloud-connect"
  "@ovh-ux/manager-cloud-styles": "link:../../modules/cloud-styles"
  "@ovh-ux/manager-components": "link:../../modules/manager-components"
  "@ovh-ux/manager-config": "link:../../modules/config"
  "@ovh-ux/manager-core": "link:../../modules/core"
  "@ovh-ux/manager-dbaas-logs": "link:../../modules/dbaas-logs"
  "@ovh-ux/manager-error-page": "link:../../modules/error-page"
  "@ovh-ux/manager-exchange": "link:../../modules/exchange"
  "@ovh-ux/manager-filters": "link:../../modules/filters"
  "@ovh-ux/manager-iplb": "link:../../modules/iplb"
  "@ovh-ux/manager-metrics": "link:../../modules/metrics"
  "@ovh-ux/manager-models": "link:../../modules/models"
  "@ovh-ux/manager-nasha": "link:../../modules/nasha"
  "@ovh-ux/manager-netapp": "link:../../modules/netapp"
  "@ovh-ux/manager-ng-layout-helpers": "link:../../modules/ng-layout-helpers"
  "@ovh-ux/manager-nutanix": "link:../../modules/nutanix"
  "@ovh-ux/manager-support": "link:../../modules/support"
  "@ovh-ux/manager-trusted-nic": "link:../../modules/trusted-nic"
  "@ovh-ux/manager-veeam-enterprise": "link:../../modules/veeam-enterprise"
  "@ovh-ux/manager-vps": "link:../../modules/vps"
  "@ovh-ux/manager-vrack": "link:../../modules/vrack"
  "@ovh-ux/ng-at-internet": "link:../../../components/ng-at-internet"
  "@ovh-ux/ng-at-internet-ui-router-plugin": "link:../../../components/ng-at-internet-ui-router-plugin"
  "@ovh-ux/ng-ovh-browser-alert": "link:../../../components/ng-ovh-browser-alert"
  "@ovh-ux/ng-ovh-chart": "link:../../../components/ng-ovh-chart"
  "@ovh-ux/ng-ovh-cloud-universe-components": "link:../../modules/cloud-universe-components"
  "@ovh-ux/ng-ovh-contacts": "link:../../../components/ng-ovh-contacts"
  "@ovh-ux/ng-ovh-contracts": "link:../../../components/ng-ovh-contracts"
  "@ovh-ux/ng-ovh-doc-url": "link:../../../components/ng-ovh-doc-url"
  "@ovh-ux/ng-ovh-export-csv": "link:../../../components/ng-ovh-export-csv"
  "@ovh-ux/ng-ovh-feature-flipping": "link:../../../components/ng-ovh-feature-flipping"
  "@ovh-ux/ng-ovh-http": "link:../../../components/ng-ovh-http"
  "@ovh-ux/ng-ovh-jquery-ui-draggable": "link:../../../components/ng-ovh-jquery-ui-draggable"
  "@ovh-ux/ng-ovh-order-tracking": "link:../../modules/ng-ovh-order-tracking"
  "@ovh-ux/ng-ovh-otrs": "link:../../../components/ng-ovh-otrs"
  "@ovh-ux/ng-ovh-payment-method": "link:../../../components/ng-ovh-payment-method"
  "@ovh-ux/ng-ovh-proxy-request": "link:../../../components/ng-ovh-proxy-request"
  "@ovh-ux/ng-ovh-request-tagger": "link:../../modules/request-tagger"
  "@ovh-ux/ng-ovh-responsive-popover": "link:../../../components/ng-ovh-responsive-popover"
  "@ovh-ux/ng-ovh-sidebar-menu": "link:../../../components/ng-ovh-sidebar-menu"
  "@ovh-ux/ng-ovh-sso-auth": "link:../../../components/ng-ovh-sso-auth"
  "@ovh-ux/ng-ovh-swimming-poll": "link:../../../components/ng-ovh-swimming-poll"
  "@ovh-ux/ng-ovh-toaster": "link:../../../components/ng-ovh-toaster"
  "@ovh-ux/ng-ovh-utils": "link:../../../components/ng-ovh-utils"
  "@ovh-ux/ng-ovh-web-universe-components": "link:../../modules/web-universe-components"
  "@ovh-ux/ng-pagination-front": "link:../../../components/ng-pagination-front"
  "@ovh-ux/ng-q-allsettled": "link:../../../components/ng-q-allsettled"
  "@ovh-ux/ng-shell-tracking": "link:../../../components/ng-shell-tracking"
  "@ovh-ux/ng-tail-logs": "link:../../../components/ng-tail-logs"
  "@ovh-ux/ng-translate-async-loader": "link:../../../components/ng-translate-async-loader"
  "@ovh-ux/ng-ui-router-breadcrumb": "link:../../../components/ng-ui-router-breadcrumb"
  "@ovh-ux/ng-ui-router-layout": "link:../../../components/ng-ui-router-layout"
  "@ovh-ux/request-tagger": "link:../../core/request-tagger"
  "@ovh-ux/shell": "link:../../../components/ovh-shell"
  "@ovh-ux/sign-up": "link:../../modules/sign-up"
  "@ovh-ux/manager-webpack-config": "link:../../tools/webpack-config"
  "@ovh-ux/manager-ng-apiv2-helper": "link:../../modules/ng-apiv2-helper"
