const DEFAULT_POLLING_INTERVAL = 30_000;
const METRICS_POLLING_INTERVAL = 60_000;

export const POLLING = {
  SERVICES: DEFAULT_POLLING_INTERVAL,
  SERVICE: DEFAULT_POLLING_INTERVAL,
  BACKUPS: DEFAULT_POLLING_INTERVAL,
  DATABASES: DEFAULT_POLLING_INTERVAL,
  LOGS: DEFAULT_POLLING_INTERVAL,
  METRICS: METRICS_POLLING_INTERVAL,
  USERS: DEFAULT_POLLING_INTERVAL,
  CURRENT_QUERIES: DEFAULT_POLLING_INTERVAL,
  INTEGRATIONS: DEFAULT_POLLING_INTERVAL,
  POOLS: DEFAULT_POLLING_INTERVAL,
  NAMESPACES: DEFAULT_POLLING_INTERVAL,
  MAINTENANCE: DEFAULT_POLLING_INTERVAL,
};

export const USER_INACTIVITY_TIMEOUT = 5 * 60_000;

export const TERMINATE_CONFIRMATION = 'TERMINATE';
