feature: ['feature/*', 'feat/*']
bug: ['fix/*','bugfix/*', 'hotfix/*']
refactor: ['chore/*','refactor/*']
release: ['develop', 'release*']
build: build/*
continuous-integration: ci/*
documentation: docs/*
performance: perf/*
