/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OVHcloud API specification
 * Specification for OVHcloud API
 * OpenAPI spec version: 1.0
 */
export type GetVmwareCloudDirectorOrganizationOrganizationIdVirtualDataCenterParams = {
/**
 * Filter resources on IAM tags
 */
iamTags?: {[key: string]: IamResourceTagFilterOVH[]};
};

export type GetVmwareCloudDirectorOrganizationParams = {
/**
 * Filter resources on IAM tags
 */
iamTags?: {[key: string]: IamResourceTagFilterOVH[]};
};

export type GetVmwareCloudDirectorBackupParams = {
/**
 * Filter resources on IAM tags
 */
iamTags?: {[key: string]: IamResourceTagFilterOVH[]};
};

/**
 * Target specification of organization Virtual DataCenter service
 */
export interface VmwareCloudDirectorVirtualDataCenterTargetSpecOVH {
  /** Description of your VMware Cloud Director organization Virtual DataCenter */
  description: string;
  /** Effective vCPU speed (GHz) for VMs in your organization Virtual DataCenter */
  vCPUSpeed: number;
}

/**
 * Update specification of organization Virtual DataCenter service
 */
export interface VmwareCloudDirectorVirtualDataCenterUpdateOVH {
  /** New target specification for the organization Virtual DataCenter */
  targetSpec: VmwareCloudDirectorVirtualDataCenterTargetSpecOVH;
}

/**
 * Current status of organization Virtual DataCenter service
 */
export interface VmwareCloudDirectorVirtualDataCenterCurrentStateOVH {
  /** Commercial range of your VMware Cloud Director project */
  readonly commercialRange?: VmwareCloudDirectorCommercialRangeEnumOVH;
  /** Description of your organization Virtual DataCenter */
  readonly description?: string;
  /** IP address quota assigned to your organization Virtual DataCenter */
  readonly ipQuota?: number;
  /** Memory quota (GB) assigned to your organization Virtual DataCenter */
  readonly memoryQuota?: number;
  /** Name of your organization Virtual DataCenter */
  readonly name?: string;
  /** Datacenter where your VMware Cloud Director organization is physically located */
  readonly region?: VmwareCloudDirectorRegionNameEnumOVH;
  /** Storage quota (GB) assigned to your organization Virtual DataCenter */
  readonly storageQuota?: number;
  /** vCPU core count allocated to your organization Virtual DataCenter */
  readonly vCPUCount?: number;
  /** Effective vCPU speed (GHz) for VMs in your organization Virtual DataCenter */
  readonly vCPUSpeed?: number;
}

/**
 * Current status of organization Virtual DataCenter storage resource
 */
export interface VmwareCloudDirectorStorageCurrentStateOVH {
  /** Billing type of your organization Virtual DataCenter storage resource */
  readonly billingType?: VmwareCloudDirectorBillingTypeEnumOVH;
  /** Capacity available (GB) for the given resource in your organization Virtual DataCenter storage resource */
  readonly capacity?: number;
  /** Name of your organization Virtual DataCenter storage resource */
  readonly name?: string;
  /** Profile of your organization Virtual DataCenter storage resource */
  readonly profile?: string;
  /** Type of your organization Virtual DataCenter storage resource */
  readonly type?: string;
}

/**
 * Target specification of VMware Cloud Director organization service
 */
export interface VmwareCloudDirectorOrganizationTargetSpecOVH {
  /** Description of your VMware Cloud Director organization on OVHcloud */
  description?: string;
  /** Human readable full name of your VMware Cloud Director organization */
  fullName: string;
}

/**
 * Update specification of VMware Cloud Director organization service
 */
export interface VmwareCloudDirectorOrganizationUpdateOVH {
  /** New target specification for the VMware Cloud Director organization */
  targetSpec: VmwareCloudDirectorOrganizationTargetSpecOVH;
}

/**
 * Current status of VMware Cloud Director organization service
 */
export interface VmwareCloudDirectorOrganizationCurrentStateOVH {
  /** API URL to interact with your VMware Cloud Director organization on OVHcloud */
  readonly apiUrl?: string;
  /** Billing type of your VMware Cloud Director project */
  readonly billingType?: VmwareCloudDirectorBillingTypeEnumOVH;
  /** Description of your VMware Cloud Director organization on OVHcloud */
  readonly description?: string;
  /** Human readable full name of your VMware Cloud Director organization */
  readonly fullName?: string;
  /** Name of your VMware Cloud Director organization */
  readonly name?: string;
  /** Datacenter where your VMware Cloud Director organization is physically located */
  readonly region?: VmwareCloudDirectorRegionNameEnumOVH;
  /** SPLA licensing state */
  readonly spla?: boolean;
  /** URL to administrate your VMware Cloud Director organization on OVHcloud */
  readonly webInterfaceUrl?: string;
}

/**
 * Possible Storage
 */
export interface VmwareCloudDirectorOrderableResourceStorageOVH {
  /** Capacity available (GB) for the given resource in your organization Virtual DataCenter storage resource */
  readonly capacity?: number;
  /** Name of your organization Virtual DataCenter storage resource */
  readonly name?: string;
  /** Profile (plan code) of your organization Virtual DataCenter storage resource */
  readonly profile?: string;
  /** Type of your organization Virtual DataCenter storage resource */
  readonly type?: string;
}

/**
 * Possible Virtual Host
 */
export interface VmwareCloudDirectorOrderableResourceComputeOVH {
  /** Memory quota (GB) assigned to your organization Virtual DataCenter compute profile */
  readonly memoryQuota?: number;
  /** Name of your organization Virtual DataCenter compute profile */
  readonly name?: string;
  /** Profile (plan code) of your organization Virtual DataCenter compute profile */
  readonly profile?: string;
  /** vCPU core count allocated to your organization Virtual DataCenter compute profile */
  readonly vCPUCount?: number;
  /** Effective vCPU speed (GHz) for VMs in your organization Virtual DataCenter compute profile */
  readonly vCPUSpeed?: number;
}

/**
 * Current status of organization Virtual DataCenter compute resource
 */
export interface VmwareCloudDirectorComputeCurrentStateOVH {
  /** Billing type of your organization Virtual DataCenter compute resource */
  readonly billingType?: VmwareCloudDirectorBillingTypeEnumOVH;
  /** Memory quota (GB) assigned to your organization Virtual DataCenter compute resource */
  readonly memoryQuota?: number;
  /** Name of your organization Virtual DataCenter compute resource */
  readonly name?: string;
  /** Profile of your organization Virtual DataCenter compute resource */
  readonly profile?: string;
  /** vCPU core count allocated to your organization Virtual DataCenter compute resource */
  readonly vCPUCount?: number;
}

/**
 * VMware Cloud Director Backup target
 */
export interface VmwareCloudDirectorBackupTargetOfferOVH {
  /** Backup service offer type (BRONZE|SILVER|GOLD) */
  name: VmwareCloudDirectorBackupOfferNameEnumOVH;
  /** Backup repository quota in TB */
  quotaInTB: number;
}

/**
 * VMware Cloud Director Backup target spec
 */
export interface VmwareCloudDirectorBackupTargetSpecOVH {
  /** List of your VMware Cloud Director backup offers */
  offers: VmwareCloudDirectorBackupTargetOfferOVH[];
}

/**
 * Update specification of VMware Cloud Director Backup service
 */
export interface VmwareCloudDirectorBackupBackupDetailsUpdateOVH {
  /** New target specification for the VMware Cloud Director organization backup service and offers */
  targetSpec: VmwareCloudDirectorBackupTargetSpecOVH;
}

/**
 * VMware Cloud Director Backup current state
 */
export interface VmwareCloudDirectorBackupCurrentStateOfferOVH {
  /** Backup service offer type (BRONZE|SILVER|GOLD) */
  readonly name?: VmwareCloudDirectorBackupOfferNameEnumOVH;
  /** Backup repository quota in TB */
  readonly quotaInTB?: number;
  /** Backup offer status */
  readonly status?: VmwareCloudDirectorBackupResourceStatusEnumOVH;
  /** Backup repository used space in GB */
  readonly usedSpaceInGB?: number;
}

/**
 * VMware Cloud Director Backup service current state
 */
export interface VmwareCloudDirectorBackupCurrentStateOVH {
  /** Availability zone of VMware Cloud Director organization backup */
  readonly azName?: VmwareCloudDirectorAZNameEnumOVH;
  /** List of your VMware Cloud Director organization backup offers */
  readonly offers?: readonly VmwareCloudDirectorBackupCurrentStateOfferOVH[];
}

/**
 * IAM resource metadata
 * @nullable
 */
export type VmwareCloudDirectorBackupBackupDetailsWithIAMOVHIam = IamResourceMetadataOVH | null;

/**
 * VMware Cloud Director Backup service
 */
export interface VmwareCloudDirectorBackupBackupDetailsWithIAMOVH {
  /** Datetime when backup was enabled */
  readonly createdAt?: string;
  readonly currentState?: VmwareCloudDirectorBackupCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the VMware Cloud Director organization backup service
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /**
   * IAM resource metadata
   * @nullable
   */
  readonly iam?: VmwareCloudDirectorBackupBackupDetailsWithIAMOVHIam;
  /** Unique identifier of the VMware Cloud Director backup */
  readonly id?: string;
  /** Reflects the readiness of the VMware Cloud Director organization backup service. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: VmwareCloudDirectorBackupResourceStatusEnumOVH;
  readonly targetSpec?: VmwareCloudDirectorBackupTargetSpecOVH;
  /** Datetime when backup is modified */
  readonly updatedAt?: string;
}

/**
 * VMware Cloud Director Backup service
 */
export interface VmwareCloudDirectorBackupBackupDetailsOVH {
  /** Datetime when backup was enabled */
  readonly createdAt?: string;
  readonly currentState?: VmwareCloudDirectorBackupCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the VMware Cloud Director organization backup service
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /** Unique identifier of the VMware Cloud Director backup */
  readonly id?: string;
  /** Reflects the readiness of the VMware Cloud Director organization backup service. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: VmwareCloudDirectorBackupResourceStatusEnumOVH;
  readonly targetSpec?: VmwareCloudDirectorBackupTargetSpecOVH;
  /** Datetime when backup is modified */
  readonly updatedAt?: string;
}

/**
 * IAM resource metadata
 * @nullable
 */
export type VmwareCloudDirectorVirtualDataCenterWithIAMOVHIam = IamResourceMetadataOVH | null;

/**
 * Organization Virtual DataCenter service
 */
export interface VmwareCloudDirectorVirtualDataCenterWithIAMOVH {
  readonly currentState?: VmwareCloudDirectorVirtualDataCenterCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the organization Virtual DataCenter
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /**
   * IAM resource metadata
   * @nullable
   */
  readonly iam?: VmwareCloudDirectorVirtualDataCenterWithIAMOVHIam;
  /** Unique identifier */
  readonly id?: string;
  /** Reflects the readiness of the organization Virtual DataCenter. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: CommonResourceStatusEnumOVH;
  readonly targetSpec?: VmwareCloudDirectorVirtualDataCenterTargetSpecOVH;
  readonly updatedAt?: string;
}

/**
 * Organization Virtual DataCenter service
 */
export interface VmwareCloudDirectorVirtualDataCenterOVH {
  readonly currentState?: VmwareCloudDirectorVirtualDataCenterCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the organization Virtual DataCenter
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /** Unique identifier */
  readonly id?: string;
  /** Reflects the readiness of the organization Virtual DataCenter. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: CommonResourceStatusEnumOVH;
  readonly targetSpec?: VmwareCloudDirectorVirtualDataCenterTargetSpecOVH;
  readonly updatedAt?: string;
}

/**
 * Organization Virtual DataCenter storage resource
 */
export interface VmwareCloudDirectorStorageOVH {
  readonly currentState?: VmwareCloudDirectorStorageCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the organization Virtual DataCenter storage resource
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /** Unique identifier */
  readonly id?: string;
  /** Reflects the readiness of the organization Virtual DataCenter storage resource. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: CommonResourceStatusEnumOVH;
  readonly updatedAt?: string;
}

/**
 * The region of your VMware Cloud Director project
 */
export type VmwareCloudDirectorRegionNameEnumOVH = typeof VmwareCloudDirectorRegionNameEnumOVH[keyof typeof VmwareCloudDirectorRegionNameEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorRegionNameEnumOVH = {
  'ap-south-mum': 'ap-south-mum',
  'ap-southeast-sgp': 'ap-southeast-sgp',
  'ap-southeast-syd': 'ap-southeast-syd',
  'ca-east-bhs': 'ca-east-bhs',
  'eu-central-waw': 'eu-central-waw',
  'eu-west-eri': 'eu-west-eri',
  'eu-west-gra': 'eu-west-gra',
  'eu-west-lim': 'eu-west-lim',
  'eu-west-par': 'eu-west-par',
  'eu-west-rbx': 'eu-west-rbx',
  'eu-west-sbg': 'eu-west-sbg',
  'us-east-vin': 'us-east-vin',
  'us-west-hil': 'us-west-hil',
} as const;

/**
 * The region of your VMware Cloud Director project
 */
export type VmwareCloudDirectorRegionLocationEnumOVH = typeof VmwareCloudDirectorRegionLocationEnumOVH[keyof typeof VmwareCloudDirectorRegionLocationEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorRegionLocationEnumOVH = {
  'Asia_Pacific_(Australia_-_Sydney)': 'Asia Pacific (Australia - Sydney)',
  'Asia_Pacific_(Singapore_-Singapore)': 'Asia Pacific (Singapore -Singapore)',
  'Europe_(France_-_Gravelines)': 'Europe (France - Gravelines)',
  'Europe_(France_-_Paris)': 'Europe (France - Paris)',
  'Europe_(France_-_Roubaix)': 'Europe (France - Roubaix)',
  'Europe_(France_-_Strasbourg)': 'Europe (France - Strasbourg)',
  'Europe_(Germany_-_Limburg)': 'Europe (Germany - Limburg)',
  'Europe_(Poland_-_Warsaw)': 'Europe (Poland - Warsaw)',
  'Europe_(United_Kingdom_-_Erith)': 'Europe (United Kingdom - Erith)',
  'North_America_(Canada_-_East_-_Beauharnois)': 'North America (Canada - East - Beauharnois)',
  'North_America_(US_-_East_-_Vinthill)': 'North America (US - East - Vinthill)',
  'North_America_(US_-_West_-_Hillsboro)': 'North America (US - West - Hillsboro)',
} as const;

/**
 * Hosting location
 */
export interface VmwareCloudDirectorRegionOVH {
  /** Location */
  readonly location?: VmwareCloudDirectorRegionLocationEnumOVH;
  /** Region */
  readonly region?: VmwareCloudDirectorRegionNameEnumOVH;
}

/**
 * IAM resource metadata
 * @nullable
 */
export type VmwareCloudDirectorOrganizationWithIAMOVHIam = IamResourceMetadataOVH | null;

/**
 * VMware Cloud Director organization service
 */
export interface VmwareCloudDirectorOrganizationWithIAMOVH {
  readonly currentState?: VmwareCloudDirectorOrganizationCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the VMware Cloud Director organization
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /**
   * IAM resource metadata
   * @nullable
   */
  readonly iam?: VmwareCloudDirectorOrganizationWithIAMOVHIam;
  /** Unique identifier */
  readonly id?: string;
  /** Reflects the readiness of the VMware Cloud Director organization. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: CommonResourceStatusEnumOVH;
  readonly targetSpec?: VmwareCloudDirectorOrganizationTargetSpecOVH;
  readonly updatedAt?: string;
}

/**
 * VMware Cloud Director organization service
 */
export interface VmwareCloudDirectorOrganizationOVH {
  readonly currentState?: VmwareCloudDirectorOrganizationCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the VMware Cloud Director organization
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /** Unique identifier */
  readonly id?: string;
  /** Reflects the readiness of the VMware Cloud Director organization. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: CommonResourceStatusEnumOVH;
  readonly targetSpec?: VmwareCloudDirectorOrganizationTargetSpecOVH;
  readonly updatedAt?: string;
}

/**
 * Available orderable resources
 */
export interface VmwareCloudDirectorOrderableResourceOVH {
  /** Available orderable compute resources to your organization Virtual DataCenter */
  readonly compute?: readonly VmwareCloudDirectorOrderableResourceComputeOVH[];
  /** Available orderable storage resources to your organization Virtual DataCenter */
  readonly storage?: readonly VmwareCloudDirectorOrderableResourceStorageOVH[];
}

/**
 * The commercial range of your VMware Cloud Director project
 */
export type VmwareCloudDirectorCommercialRangeEnumOVH = typeof VmwareCloudDirectorCommercialRangeEnumOVH[keyof typeof VmwareCloudDirectorCommercialRangeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorCommercialRangeEnumOVH = {
  NSX: 'NSX',
  STANDARD: 'STANDARD',
  'VSAN-NSX': 'VSAN-NSX',
} as const;

/**
 * The billing type of your VMware Cloud Director project
 */
export type VmwareCloudDirectorBillingTypeEnumOVH = typeof VmwareCloudDirectorBillingTypeEnumOVH[keyof typeof VmwareCloudDirectorBillingTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorBillingTypeEnumOVH = {
  DEMO: 'DEMO',
  MONTHLY: 'MONTHLY',
} as const;

/**
 * Status of VMware Cloud Director backup service
 */
export type VmwareCloudDirectorBackupResourceStatusEnumOVH = typeof VmwareCloudDirectorBackupResourceStatusEnumOVH[keyof typeof VmwareCloudDirectorBackupResourceStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorBackupResourceStatusEnumOVH = {
  CREATING: 'CREATING',
  DISABLED: 'DISABLED',
  DISABLING: 'DISABLING',
  READY: 'READY',
  REMOVED: 'REMOVED',
  REMOVING: 'REMOVING',
  UPDATING: 'UPDATING',
} as const;

/**
 * The backup offer type of your VMware Cloud Director project
 */
export type VmwareCloudDirectorBackupOfferNameEnumOVH = typeof VmwareCloudDirectorBackupOfferNameEnumOVH[keyof typeof VmwareCloudDirectorBackupOfferNameEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorBackupOfferNameEnumOVH = {
  BRONZE: 'BRONZE',
  GOLD: 'GOLD',
  SILVER: 'SILVER',
} as const;

/**
 * The AZ Name of your VMware Cloud Director project
 */
export type VmwareCloudDirectorAZNameEnumOVH = typeof VmwareCloudDirectorAZNameEnumOVH[keyof typeof VmwareCloudDirectorAZNameEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VmwareCloudDirectorAZNameEnumOVH = {
  'ca-east-bhs-a': 'ca-east-bhs-a',
  'eu-central-waw-a': 'eu-central-waw-a',
  'eu-west-eri-a': 'eu-west-eri-a',
  'eu-west-lim-a': 'eu-west-lim-a',
  'eu-west-rbx-a': 'eu-west-rbx-a',
  'eu-west-sbg-a': 'eu-west-sbg-a',
} as const;

/**
 * Time (e.g., 15:04:05)
 */
export type TimeOVH = string;

/**
 * Phone number
 */
export type PhoneNumberOVH = string;

/**
 * MAC address (e.g., 2001:4860:4860::8844)
 */
export type MacAddressOVH = string;

/**
 * IPv6 CIDR notation (e.g., 2001:41d0::/128)
 */
export type Ipv6BlockOVH = string;

/**
 * IPv6 address (e.g., 2001:41d0:1:1994::1)
 */
export type Ipv6OVH = string;

/**
 * IPv4 CIDR notation (e.g., 192.0.2.0/24)
 */
export type Ipv4BlockOVH = string;

/**
 * IPv4 address (e.g., 192.0.2.0)
 */
export type Ipv4OVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpInterfaceOVH = string;

/**
 * IP (v4 or v6) CIDR notation (e.g., 192.0.2.0/24)
 */
export type IpBlockOVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpOVH = string;

/**
 * International phone number
 */
export type InternationalPhoneNumberOVH = string;

/**
 * Operator that can be used in order to filter resources tags
 */
export type IamResourceTagFilterOperatorEnumOVH = typeof IamResourceTagFilterOperatorEnumOVH[keyof typeof IamResourceTagFilterOperatorEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IamResourceTagFilterOperatorEnumOVH = {
  EQ: 'EQ',
  EXISTS: 'EXISTS',
  ILIKE: 'ILIKE',
  LIKE: 'LIKE',
  NEQ: 'NEQ',
  NEXISTS: 'NEXISTS',
} as const;

/**
 * Operator to use in order to filter on the value (defaults to 'EQ')
 * @nullable
 */
export type IamResourceTagFilterOVHOperator = IamResourceTagFilterOperatorEnumOVH | null;

/**
 * Resource tag filter
 */
export interface IamResourceTagFilterOVH {
  /**
   * Operator to use in order to filter on the value (defaults to 'EQ')
   * @nullable
   */
  readonly operator?: IamResourceTagFilterOVHOperator;
  /** Value to use in order to filter tags */
  readonly value?: string;
}

/**
 * Resource tags. Tags that were internally computed are prefixed with ovh:
 * @nullable
 */
export type IamResourceMetadataOVHTags = {[key: string]: string} | null;

/**
 * IAM resource metadata embedded in services models
 */
export interface IamResourceMetadataOVH {
  /**
   * Resource display name
   * @nullable
   */
  readonly displayName?: string | null;
  /** Unique identifier of the resource */
  readonly id?: string;
  /**
   * Resource tags. Tags that were internally computed are prefixed with ovh:
   * @nullable
   */
  readonly tags?: IamResourceMetadataOVHTags;
  /** Unique resource name used in policies */
  readonly urn?: string;
}

/**
 * Email address (e.g., api@ml.ovh.net)
 */
export type EmailOVH = string;

/**
 * Duration (e.g., P1Y2M3DT4H6M9S)
 */
export type DurationOVH = string;

/**
 * TaskStatusEnum
 */
export type CommonTaskStatusEnumOVH = typeof CommonTaskStatusEnumOVH[keyof typeof CommonTaskStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonTaskStatusEnumOVH = {
  DONE: 'DONE',
  ERROR: 'ERROR',
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  SCHEDULED: 'SCHEDULED',
} as const;

/**
 * Detailed information about an asynchronous operation progress steps
 */
export interface CommonTaskProgressOVH {
  /** Progress step name */
  readonly name?: string;
  /** Current status of the progress step */
  readonly status?: CommonTaskStatusEnumOVH;
}

/**
 * Errors that occured on the task
 */
export interface CommonTaskErrorOVH {
  /** Error description */
  readonly message?: string;
}

/**
 * Asynchronous operation
 */
export interface CommonTaskOVH {
  /** Creation date of the task */
  readonly createdAt?: string;
  /**
   * Errors that occured on the task
   * @nullable
   */
  readonly errors?: readonly CommonTaskErrorOVH[] | null;
  /**
   * Ending date of the task
   * @nullable
   */
  readonly finishedAt?: string | null;
  /** Identifier of the task */
  readonly id?: string;
  /** Link to the related resource */
  readonly link?: string;
  /** Description of the task */
  readonly message?: string;
  /** Progress steps of the asynchronous operation */
  readonly progress?: readonly CommonTaskProgressOVH[];
  /**
   * Starting date of the task
   * @nullable
   */
  readonly startedAt?: string | null;
  /** Current global status of the task */
  readonly status?: CommonTaskStatusEnumOVH;
  /** Type of the task */
  readonly type?: string;
  /** Last update of the task */
  readonly updatedAt?: string;
}

/**
 * ResourceStatusEnum
 */
export type CommonResourceStatusEnumOVH = typeof CommonResourceStatusEnumOVH[keyof typeof CommonResourceStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonResourceStatusEnumOVH = {
  CREATING: 'CREATING',
  DELETING: 'DELETING',
  ERROR: 'ERROR',
  READY: 'READY',
  UPDATING: 'UPDATING',
} as const;

/**
 * List all defined values for an event type field
 */
export type CommonEventTypeEnumOVH = typeof CommonEventTypeEnumOVH[keyof typeof CommonEventTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonEventTypeEnumOVH = {
  TARGET_SPEC_UPDATE: 'TARGET_SPEC_UPDATE',
  TASK_ERROR: 'TASK_ERROR',
  TASK_START: 'TASK_START',
  TASK_SUCCESS: 'TASK_SUCCESS',
} as const;

/**
 * Represents an event for an async envelope
 */
export interface CommonEventOVH {
  /** Creation date of the event */
  readonly createdAt?: string;
  /** Nature of the event */
  readonly kind?: string;
  /**
   * Link to the event related resource
   * @nullable
   */
  readonly link?: string | null;
  /** Description of what happened on the event */
  readonly message?: string;
  /** Type of the event */
  readonly type?: CommonEventTypeEnumOVH;
}

/**
 * Current status of a task. A task in ERROR cannot be retried without your inputs. PENDING tasks will be executed as soon as possible. A RUNNING task is currently executing your original request. SCHEDULED is used for tasks that will be executed in the future
 */
export type CommonCurrentTaskStatusEnumOVH = typeof CommonCurrentTaskStatusEnumOVH[keyof typeof CommonCurrentTaskStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommonCurrentTaskStatusEnumOVH = {
  ERROR: 'ERROR',
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  SCHEDULED: 'SCHEDULED',
} as const;

/**
 * Current global status of the current task
 * @nullable
 */
export type CommonCurrentTaskOVHStatus = CommonCurrentTaskStatusEnumOVH | null;

/**
 * Asynchronous operation currently running
 */
export interface CommonCurrentTaskOVH {
  /** Identifier of the current task */
  readonly id?: string;
  /** Link to the task details */
  readonly link?: string;
  /**
   * Current global status of the current task
   * @nullable
   */
  readonly status?: CommonCurrentTaskOVHStatus;
  /** Type of the current task */
  readonly type?: string;
}

/**
 * Organization Virtual DataCenter compute resource
 */
export interface VmwareCloudDirectorComputeOVH {
  readonly currentState?: VmwareCloudDirectorComputeCurrentStateOVH;
  /**
   * Asynchronous operations ongoing on the organization Virtual DataCenter compute resource
   * @nullable
   */
  readonly currentTasks?: readonly CommonCurrentTaskOVH[] | null;
  /** Unique identifier */
  readonly id?: string;
  /** Reflects the readiness of the organization Virtual DataCenter compute resource. A new target specification request will be accepted only in `READY` status */
  readonly resourceStatus?: CommonResourceStatusEnumOVH;
  readonly updatedAt?: string;
}

