export const subRoutes = {
  root: 'public-vcf-aas',
  onboarding: 'onboarding',
  dashboard: ':id',
  editName: 'edit-name',
  editDescription: 'edit-description',
  addPublicIpBlock: 'add-public-ip-block',
  vdcId: ':vdcId',
  virtualDatacenters: 'virtual-datacenters',
  networkAcl: 'network-acl',
  datacentreStorage: 'storage',
  datacentreStorageOrder: 'order-storage',
  datacentreCompute: 'compute',
  datacentreComputeOrder: 'order-compute',
  resetPassword: 'reset-password',
  vrackSegments: 'vrack-segments',
  vrackSegmentId: ':vrackSegmentId',
  vrackEditVlanId: 'edit-vlan-id',
  vrackNetwork: 'vrack-networks',
  vrackNetworkId: ':vrackNetworkId',
  addNetwork: 'add-network',
  deleteSegment: 'delete-segment',
  deleteNetwork: 'delete-network',
  terminate: 'terminate',
  addNetworkAcl: 'add-network-acl',
  deleteNetworkAcl: 'delete-network-acl',
  editNetworkAcl: 'edit-network-acl',
} as const;

export const urls = {
  vmwareRoot: `/vmware`,
  root: `/${subRoutes.root}`,
  listing: `/${subRoutes.root}`,
  onboarding: `/${subRoutes.root}/${subRoutes.onboarding}`,
  dashboard: `/${subRoutes.root}/${subRoutes.dashboard}`,
  resetPassword: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.resetPassword}`,
  editName: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.editName}`,
  editDescription: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.editDescription}`,
  datacentres: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}`,
  datacentreDashboard: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}`,
  datacentreEditDescription: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.editDescription}`,
  datacentreAddPublicIpBlock: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.addPublicIpBlock}`,
  datacentreStorage: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.datacentreStorage}`,
  datacentreStorageOrder: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.datacentreStorage}/${subRoutes.datacentreStorageOrder}`,
  datacentreCompute: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.datacentreCompute}`,
  datacentreComputeOrder: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.datacentreCompute}/${subRoutes.datacentreComputeOrder}`,
  vrackSegments: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.vrackSegments}`,
  vrackSegmentDelete: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.vrackSegments}/${subRoutes.vrackSegmentId}/${subRoutes.deleteSegment}`,
  vrackSegmentEditVlanId: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.vrackSegments}/${subRoutes.vrackSegmentId}/${subRoutes.vrackEditVlanId}`,
  vrackSegmentAddNetwork: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.vrackSegments}/${subRoutes.vrackSegmentId}/${subRoutes.addNetwork}`,
  vrackSegmentDeleteNetwork: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.virtualDatacenters}/${subRoutes.vdcId}/${subRoutes.vrackSegments}/${subRoutes.vrackSegmentId}/${subRoutes.vrackNetwork}/${subRoutes.vrackNetworkId}/${subRoutes.deleteNetwork}`,
  networkAcl: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.networkAcl}`,
  networkAclAdd: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.networkAcl}/${subRoutes.addNetworkAcl}`,
  networkAclEdit: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.networkAcl}/${subRoutes.editNetworkAcl}`,
  networkAclDelete: `/${subRoutes.root}/${subRoutes.dashboard}/${subRoutes.networkAcl}/${subRoutes.deleteNetworkAcl}`,
} as const;

export const veeamBackupAppName = 'veeam-backup';
