packages:
  - 'docs'
  - 'packages/components/*'
  - 'packages/manager/apps/*'
  - 'packages/manager/core/*'
  - 'packages/manager/modules/*'
  - 'packages/manager/tools/*'
  - 'packages/manager-react-components'
