export const urls = {
  root: '',
  onboarding: '/onboarding',
  listing: '/license',
  dashboard: '/license/:serviceName',
  generalInformation: '/license/:serviceName',
  license: '/license/:serviceName/license',
  users: '/license/:serviceName/users',
  users_edit: '/license/:serviceName/users/edit',
  users_delete: '/license/:serviceName/users/delete',
  order_licenses: '/license/:serviceName/users/order-licenses',
  order_users: '/license/:serviceName/users/order-users',
  change_password: '/license/:serviceName/users/change-password',
  consumption: '/license/:serviceName/consumption',
};
