const BADGE_MARGIN_RIGHT = 4;

const BADGE_MARGIN_LEFT = 0;

const BADGE_PADDING_LEFT = 8;

const BADGE_PADDING_RIGHT = 8;

export const BADGE_SPACINGS =
  BADGE_MARGIN_RIGHT +
  BADGE_MARGIN_LEFT +
  BADGE_PADDING_LEFT +
  BADGE_PADDING_RIGHT;

export const MORE_TAGS_ICON_WIDTH = 12;
