export const HOST_STATUS = {
  AVAILABLE: 'BAREMETAL_STATUS_AVAILABLE',
  DELETING: 'BAREMETAL_STATUS_SUPPRESSING',
  DELIVERING: 'BAREMETAL_STATUS_DELIVERING',
  IN_MAINTENANCE: 'BAREMETAL_STATUS_IN_MAINTENANCE',
  IN_USE: 'BAREMETAL_STATUS_IN_USE',
  RESTARTING: 'BAREMETAL_STATUS_RESTARTING',
  UNKNOWN: 'BAREMETAL_STATUS_UNSPECIFIED',
};

export const STATUS = {
  ACTIVE: 'ACTIVE',
  ERROR: 'ERROR',
  PENDING: 'PENDING',
};

export default {
  HOST_STATUS,
  STATUS,
};
