export const kmsIamActions = {
  credentialCreate: 'okms:apiovh:credential/create',
  credentialGet: 'okms:apiovh:credential/get',
  credentialDelete: 'okms:apiovh:credential/delete',
  serviceKeyCreate: 'okms:apiovh:serviceKey/create',
  serviceKeyActivate: 'okms:apiovh:serviceKey/activate',
  serviceKeyDeactivate: 'okms:apiovh:serviceKey/deactivate',
  serviceKeyDelete: 'okms:apiovh:serviceKey/delete',
  serviceKeyUpdate: 'okms:apiovh:serviceKey/update',
  secretGet: 'okms:apiovh:secret/get',
  secretVersionGetData: 'okms:apiovh:secret/version/getData',
  secretVersionCreate: 'okms:apiovh:secret/version/create',
  secretVersionUpdate: 'okms:apiovh:secret/version/edit',
  secretVersionDelete: 'okms:apiovh:secret/version/delete',
  secretVersionActivate: 'okms:apiovh:secret/version/activate',
  secretVersionDeactivate: 'okms:apiovh:secret/version/deactivate',
};
