// @source: https://en.wikipedia.org/wiki/VAT_identification_number
export const COUNTRIES_VAT_LABEL = {
  AT: 'UID',
  BE: 'TVA',
  CY: 'ΦΠΑ',
  CZ: 'DIČ',
  DE: 'USt-IdNr.',
  DK: 'CVR',
  EE: 'KMKR',
  GR: 'ΑΦΜ',
  ES: 'NIF',
  FI: 'ALV nro',
  FR: 'TVA',
  HR: 'PDV-ID',
  HU: 'ANUM',
  IE: 'VAT',
  IT: 'IVA',
  LT: 'PVM kodas',
  LU: 'TVA',
  LV: 'PVN',
  MT: 'Vat No.',
  NL: 'Btw-nr.',
  PL: 'NIP',
  PT: 'NIF',
  RO: 'CIF',
  SE: 'Momsnr.',
  SI: 'ID za DDV',
  SK: 'IČ DPH',
  AL: 'NIPT',
  MK: 'ЕДБ',
  AU: 'ABN',
  BY: 'УНП / UNP',
  CA: 'BN / NE',
  IS: 'VSK / VASK',
  IN: 'VAT TIN / CST TIN',
  ID: 'NPWP',
  KZ: 'БСН / BIN',
  NZ: 'GST/IRD',
  NG: 'VAT',
  NO: 'Orgnr',
  PH: 'TIN',
  RU: 'ИНН',
  SM: 'C.O.E.',
  RS: 'PIB',
  CH: 'MWST / TVA / IVA',
  TR: 'KDV',
  UA: 'ІНПП',
  GB: 'VAT Reg No',
  UZ: 'СТИР',
  AR: 'CUIT',
  BO: 'NIT',
  BR: 'CNPJ',
  CL: 'RUT',
  CO: 'NIT',
  EC: 'RUC',
  SV: 'NIT',
  GT: 'NIT',
  HN: 'RTN',
  MX: 'RFC',
  NI: 'RUC',
  PA: 'RUC',
  PY: 'RUC',
  PE: 'RUC',
  DO: 'RNC',
  UY: 'RUT',
  VE: 'RIF',
  MA: 'ICE',
};

const SIRET_TRACKING_PREFIX = 'accountcreation::company-search';
export const COMPANY_CREATED_PREFIX = `${SIRET_TRACKING_PREFIX}::company-created`;
export const COMPANY_NOT_CREATED_PREFIX = `${SIRET_TRACKING_PREFIX}::company-not-created`;

export default {
  COMPANY_CREATED_PREFIX,
  COMPANY_NOT_CREATED_PREFIX,
  COUNTRIES_VAT_LABEL,
};
