import dedicatedIcons from './icons/dedicatedIcons';
import telecomIcons from './icons/telecomIcons';
import webIcons from './icons/webIcons';
import OdsIconWrapper from './utils/OdsIconWrapper';
import {
  HOSTING_SVG,
  OFFICE365_SVG,
  PROJECTCLOUD_SVG,
  TELECOMETHERNET_SVG,
  HEADSET_SVG,
  TELEPHONY_SVG,
  EXCHANGE_SVG,
  IP_SVG,
  VPS_SVG,
  NUTANIX_SVG,
  MANAGEDBM_SVG,
  VMWARE_SVG,
  NAS_SVG,
  VEEAM_SVG,
  VRACK_SVG,
  LINECOMMUNICATING_SVG,
  SERVER_SVG,
  SvgIconWrapper,
} from './utils/SvgIconWrapper';
import {
  TelecomEthernet,
  Headset,
  Telephony,
  Hosting,
  Office365,
  Exchange,
  ProjectCloud,
  Server,
  IP,
  VPS,
  Nutanix,
  ManagedBM,
  VmWare,
  NAS,
  VEEAM,
  VRACK,
  LineCommunicating,
} from './assets-icon-svg/icons';
import OvhProductName from './utils/OvhProductNameEnum';

export { OvhProductName };
export {
  dedicatedIcons,
  telecomIcons,
  webIcons,
  OdsIconWrapper,
  SvgIconWrapper,
  HOSTING_SVG,
  OFFICE365_SVG,
  PROJECTCLOUD_SVG,
  HEADSET_SVG,
  TELECOMETHERNET_SVG,
  TELEPHONY_SVG,
  EXCHANGE_SVG,
  IP_SVG,
  VPS_SVG,
  NUTANIX_SVG,
  MANAGEDBM_SVG,
  VMWARE_SVG,
  NAS_SVG,
  VEEAM_SVG,
  VRACK_SVG,
  LINECOMMUNICATING_SVG,
  SERVER_SVG,
  TelecomEthernet,
  Headset,
  Telephony,
  Hosting,
  Office365,
  Exchange,
  ProjectCloud,
  Server,
  IP,
  VPS,
  Nutanix,
  ManagedBM,
  VmWare,
  NAS,
  VEEAM,
  VRACK,
  LineCommunicating,
};
