export const subRoutes = {
  root: '/ip',
  onboarding: 'onboarding',
  order: 'order',
  byoip: 'byoip',
  configureReverseDns: 'configure-reverse-dns',
  manageOrganisations: 'manage-organisations',
  openOrganisations: 'open',
  byoipOrder: 'byoip-order',
  terminateIp: 'terminate',
  terminateByoip: 'terminate-byoip',
  upsertDescription: 'upsert-description',
  configureGameFirewall: 'game-firewall',
  configureEdgeNetworkFirewall: 'edge-network-firewall',
  addVirtualMac: 'add-virtual-mac',
  service: 'service',
  viewVirtualMac: 'view-virtual-mac',
  deleteVirtualMac: 'delete-virtual-mac',
  importIpFromSys: 'import-ip-from-sys',
  moveIp: 'move-ip',
  unblockAntiHack: 'unblock-anti-hack',
  exportIpToCsv: 'export-ip-to-csv',
};

export const urlDynamicParts = {
  parentId: ':parentId',
  id: ':id',
  optionalId: ':id?',
  organisationId: ':organisationId',
  service: ':service',
};

export const urls = {
  root: subRoutes.root,
  onboarding: `${subRoutes.root}/${subRoutes.onboarding}`,
  listing: subRoutes.root,
  listingIpTerminate: `${subRoutes.root}/${subRoutes.terminateIp}/${urlDynamicParts.id}`,
  listingByoipTerminate: `${subRoutes.root}/${subRoutes.terminateByoip}/${urlDynamicParts.id}`,
  listingImportIpFromSys: `${subRoutes.root}/${subRoutes.importIpFromSys}`,
  listingMoveIp: `${subRoutes.root}/${subRoutes.moveIp}/${urlDynamicParts.id}`,
  listingExportIpToCsv: `${subRoutes.root}/${subRoutes.exportIpToCsv}`,
  upsertDescription: `${subRoutes.root}/${subRoutes.upsertDescription}/${urlDynamicParts.parentId}/${urlDynamicParts.optionalId}`,
  configureEdgeNetworkFirewall: `${subRoutes.root}/${urlDynamicParts.id}/${subRoutes.configureEdgeNetworkFirewall}`,
  addVirtualMac: `${subRoutes.root}/${urlDynamicParts.id}/${subRoutes.service}/${urlDynamicParts.service}/${subRoutes.addVirtualMac}`,
  viewVirtualMac: `${subRoutes.root}/${urlDynamicParts.id}/${subRoutes.service}/${urlDynamicParts.service}/${subRoutes.viewVirtualMac}`,
  deleteVirtualMac: `${subRoutes.root}/${urlDynamicParts.id}/${subRoutes.service}/${urlDynamicParts.service}/${subRoutes.deleteVirtualMac}`,
  unblockAntiHack: `${subRoutes.root}/${urlDynamicParts.parentId}/${subRoutes.service}/${urlDynamicParts.service}/${subRoutes.unblockAntiHack}/${urlDynamicParts.id}`,
  configureGameFirewall: `${subRoutes.root}/${urlDynamicParts.id}/${subRoutes.configureGameFirewall}`,
  order: `${subRoutes.root}/${subRoutes.order}`,
  byoip: `${subRoutes.root}/${subRoutes.byoip}`,
  manageOrganisations: `${subRoutes.root}/${subRoutes.manageOrganisations}`,
  openOrganisationsModal: `${subRoutes.root}/${subRoutes.manageOrganisations}/${urlDynamicParts.organisationId}/${subRoutes.openOrganisations}`,
  listingConfigureReverseDns: `${subRoutes.root}/${subRoutes.configureReverseDns}/${urlDynamicParts.parentId}/${urlDynamicParts.optionalId}`,
  byoipOrderModal: `${subRoutes.root}/${subRoutes.byoip}/${subRoutes.byoipOrder}`
};
