export const GUIDES = [
  {
    title: 'iplb_onboarding_guide1_title',
    description: 'iplb_onboarding_guide1_description',
    links: {
      DEFAULT:
        'https://docs.ovh.com/gb/en/load-balancer/loadbalancer-introduction/',
      ASIA:
        'https://docs.ovh.com/asia/en/load-balancer/loadbalancer-introduction/',
      DE: 'https://docs.ovh.com/de/load-balancer/einfuehrung-lb/',
      ES: 'https://docs.ovh.com/es/load-balancer/presentacion-load-balancer/',
      IT: 'https://docs.ovh.com/it/load-balancer/iplb-presentazione/',
      PL: 'https://docs.ovh.com/pl/load-balancer/lb-prezentacja/',
      PT: 'https://docs.ovh.com/pt/load-balancer/lb-presentation/',
      GB: 'https://docs.ovh.com/gb/en/load-balancer/loadbalancer-introduction/',
      CA: 'https://docs.ovh.com/ca/en/load-balancer/loadbalancer-introduction/',
      QC: 'https://docs.ovh.com/ca/fr/load-balancer/iplb-presentation/',
      AU: 'https://docs.ovh.com/au/en/load-balancer/loadbalancer-introduction/',
      SG: 'https://docs.ovh.com/sg/en/load-balancer/loadbalancer-introduction/',
      FR: 'https://docs.ovh.com/fr/load-balancer/iplb-presentation/',
      WE: 'https://docs.ovh.com/us/en/load-balancer/loadbalancer-introduction/',
      WS: 'https://docs.ovh.com/us/en/load-balancer/loadbalancer-introduction/',
      US: 'https://docs.ovh.com/us/en/load-balancer/loadbalancer-introduction/',
    },
  },
  {
    title: 'iplb_onboarding_guide2_title',
    description: 'iplb_onboarding_guide2_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/load-balancer/using-iplb/',
      ASIA: 'https://docs.ovh.com/asia/en/load-balancer/usage-loadbalancer/',
      DE: 'https://docs.ovh.com/de/load-balancer/verwendung-lb/',
      ES: 'https://docs.ovh.com/es/load-balancer/uso-iplb/',
      IT: 'https://docs.ovh.com/it/load-balancer/utilizzo-lb/',
      PL: 'https://docs.ovh.com/pl/load-balancer/konfiguracja-loadbalancer/',
      PT: 'https://docs.ovh.com/pt/load-balancer/utilizacao-iplb/',
      GB: 'https://docs.ovh.com/gb/en/load-balancer/using-iplb/',
      CA: 'https://docs.ovh.com/ca/en/load-balancer/usage-loadbalancer/',
      QC: 'https://docs.ovh.com/ca/fr/load-balancer/utilisation-loadbalancer/',
      AU: 'https://docs.ovh.com/au/en/load-balancer/usage-loadbalancer/',
      SG: 'https://docs.ovh.com/sg/en/load-balancer/usage-loadbalancer/',
      FR: 'https://docs.ovh.com/fr/load-balancer/utilisation-iplb/',
      WE: 'https://docs.ovh.com/us/en/load-balancer/usage-loadbalancer/',
      WS: 'https://docs.ovh.com/us/en/load-balancer/usage-loadbalancer/',
      US: 'https://docs.ovh.com/us/en/load-balancer/usage-loadbalancer/',
    },
  },
  {
    title: 'iplb_onboarding_guide3_title',
    description: 'iplb_onboarding_guide3_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/load-balancer/lb-http2/',
      ASIA: 'https://docs.ovh.com/asia/en/load-balancer/lb-http2/',
      DE: 'https://docs.ovh.com/de/load-balancer/lb-http2/',
      ES: 'https://docs.ovh.com/es/load-balancer/load-balancer-http2/',
      IT: 'https://docs.ovh.com/it/load-balancer/iplb-http2/',
      PL: 'https://docs.ovh.com/pl/load-balancer/lb-http2/',
      PT: 'https://docs.ovh.com/pt/load-balancer/iplb-http2/',
      GB: 'https://docs.ovh.com/gb/en/load-balancer/lb-http2/',
      CA: 'https://docs.ovh.com/ca/en/load-balancer/lb-http2/',
      QC: 'https://docs.ovh.com/ca/fr/load-balancer/iplb-http2/',
      AU: 'https://docs.ovh.com/au/en/load-balancer/lb-http2/',
      SG: 'https://docs.ovh.com/sg/en/load-balancer/lb-http2/',
      FR: 'https://docs.ovh.com/fr/load-balancer/iplb-http2/',
      WE: 'https://docs.ovh.com/us/en/load-balancer/lb-http2/',
      WS: 'https://docs.ovh.com/us/en/load-balancer/lb-http2/',
      US: 'https://docs.ovh.com/us/en/load-balancer/lb-http2/',
    },
  },
];

export const CTAS = {
  DEFAULT: 'https://www.ovhcloud.com/en/network/load-balancer/',
  ASIA: 'https://www.ovhcloud.com/asia/network/load-balancer/',
  IN: 'https://www.ovhcloud.com/en-in/network/load-balancer/',
  DE: 'https://www.ovhcloud.com/de/network/load-balancer/',
  ES: 'https://www.ovhcloud.com/es-es/network/load-balancer/',
  IE: 'https://www.ovhcloud.com/en-ie/network/load-balancer/',
  IT: 'https://www.ovhcloud.com/it/network/load-balancer/',
  NL: 'https://www.ovhcloud.com/nl/network/load-balancer/',
  PL: 'https://www.ovhcloud.com/pl/network/load-balancer/',
  PT: 'https://www.ovhcloud.com/pt/network/load-balancer/',
  GB: 'https://www.ovhcloud.com/en-gb/network/load-balancer/',
  CA: 'https://www.ovhcloud.com/en-ca/network/load-balancer/',
  QC: 'https://www.ovhcloud.com/fr-ca/network/load-balancer/',
  MA: 'https://www.ovhcloud.com/fr-ma/network/load-balancer/',
  SN: 'https://www.ovhcloud.com/fr-sn/network/load-balancer/',
  TN: 'https://www.ovhcloud.com/fr-tn/network/load-balancer/',
  AU: 'https://www.ovhcloud.com/en-au/network/load-balancer/',
  SG: 'https://www.ovhcloud.com/en-sg/network/load-balancer/',
  FR: 'https://www.ovhcloud.com/fr/network/load-balancer/',
  WE: 'https://www.ovhcloud.com/en-ie/network/load-balancer/',
  WS: 'https://www.ovhcloud.com/es/network/load-balancer/',
  US: 'https://us.ovhcloud.com/network/load-balancer/',
};

export default {
  GUIDES,
  CTAS,
};
