/** Possible state of a query */
export enum StateEnum {
  'ACTIVE' = 'ACTIVE',
  'DISABLED' = 'DISABLED',
  'FASTPATH_FUNCTION_CALL' = 'FASTPATH_FUNCTION_CALL',
  'IDLE' = 'IDLE',
  'IDLE_IN_TRANSACTION' = 'IDLE_IN_TRANSACTION',
  'IDLE_IN_TRANSACTION_ABORTED' = 'IDLE_IN_TRANSACTION_ABORTED',
}
