import { nanoid } from 'nanoid';

export const getAutoGeneratedName = (prefix = ''): string => {
  const today = new Date();
  const date = `${today.getDate()}${today.getMonth() + 1}`;
  const randomNumber = nanoid(5);
  const prefixPart = prefix ? `${prefix}-` : '';

  return `${prefixPart}${date}-${randomNumber}`;
};
