export const catalogData = {
  'Hosted Private Cloud': [
    {
      categories: [
        'Catalogs',
        'Hosted Private Cloud',
        'Platform',
        'VMware',
        'VMware on OVHcloud',
      ],
      category: 'Platform',
      description:
        'VMware on OVHcloud is a unique solution on the market, offering cloud scalability on a 100% dedicated hardware infrastructure. Your infrastructure virtualisation is powered by VMware technology, and entirely managed by OVHcloud. ',
      featureAvailability: 'dedicated-cloud:order',
      highlight: true,
      id: 20414,
      lang: 'en_GB',
      name: 'VMware on OVHcloud',
      order:
        'https://www.ovhcloud.com/it/enterprise/products/hosted-private-cloud/prices/',
      productName: 'PRIVATE_CLOUD',
      regionTags: ['EU', 'US', 'CA'],
      universe: 'Hosted Private Cloud',
      url: 'https://mockup.url.com',
    },
    {
      categories: [
        'Catalogs',
        'Hosted Private Cloud',
        'Platform',
        'SAP HANA on Private Cloud',
      ],
      category: 'Platform',
      description:
        'This new platform combines SAP HANA-certified HCI servers with our VMware on OVHcloud infrastructure. It enables secure hosting and effortless deployment of your most critical SAP environments in a sovereign cloud.',
      featureAvailability: 'dedicated-cloud:sapHanaOrder',
      highlight: true,
      id: 21725,
      lang: 'en_GB',
      name: 'SAP HANA on Private Cloud',
      order: 'https://www.ovhcloud.com/it/hosted-private-cloud/sap-hana/',
      productName: 'SAP_HANA',
      regionTags: ['EU', 'CA'],
      universe: 'Hosted Private Cloud',
      url: 'https://mockup.url.com',
    },
  ],
  'Bare Metal Cloud': [
    {
      categories: ['Catalogs', 'Bare Metal Cloud', 'Dedicated Servers'],
      category: 'Dedicated Servers',
      description:
        'Choose the best infrastructure for your business applications. We offer different ranges of highly efficient dedicated servers, adapted to the most demanding needs of all companies.',
      featureAvailability: 'dedicated-server:order',
      highlight: true,
      id: 20804,
      lang: 'en_GB',
      name: 'Dedicated Servers',
      order: 'https://www.ovhcloud.com/it/bare-metal/prices/',
      productName: 'DEDICATED_SERVER',
      regionTags: ['EU', 'US', 'CA'],
      universe: 'Bare Metal Cloud',
      url: 'https://ovhcloud.com/en-gb/bare-metal',
    },
    {
      categories: ['Catalogs', 'Bare Metal Cloud', 'Virtual Private Servers'],
      category: 'Virtual Private Servers',
      description:
        'A virtual private server, also referred to as a VPS, is a virtual dedicated server. Unlike web hosting — (also known as shared hosting), where the technical aspects are managed by OVHcloud — you are the administrator of your VPS, and fully manage it.',
      featureAvailability: 'vps',
      highlight: true,
      id: 20817,
      lang: 'en_GB',
      name: 'Virtual Private Servers',
      order: 'https://www.ovh.it/vps/',
      productName: 'VPS',
      regionTags: ['EU', 'US', 'CA'],
      universe: 'Bare Metal Cloud',
      url: 'https://ovhcloud.com/en-gb/vps',
    },
    {
      categories: ['Catalogs', 'Bare Metal Cloud', 'Managed Bare Metal'],
      category: 'Managed Bare Metal',
      description:
        'Your scalable dedicated cloud, hosted and monitored by OVHcloud, available in just 90 minutes. With the Essentials range, opt for highly available VMware virtualisation, and stay focused on your business.',
      featureAvailability: 'managed-bare-metal',
      highlight: true,
      id: 20820,
      lang: 'en_GB',
      name: 'Managed Bare Metal',
      order: 'https://www.ovhcloud.com/it/managed-bare-metal/',
      productName: 'ESSENTIALS',
      regionTags: ['EU', 'US', 'CA'],
      universe: 'Bare Metal Cloud',
      url: 'https://ovhcloud.com/en-gb/managed-bare-metal/',
    },
    {
      categories: [
        'Catalogs',
        'Bare Metal Cloud',
        'Storage and Backup',
        'Enterprise File Storage',
      ],
      category: 'Storage and Backup',
      description:
        'Enterprise File Storage, powered by NetApp. Connect of all your OVHcloud solutions to a high-performance file storage service for your most critical business applications.',
      featureAvailability: 'netapp',
      highlight: true,
      id: 20825,
      lang: 'en_GB',
      name: 'Enterprise File Storage',
      order: 'https://www.ovh.com/manager/#/dedicated/netapp/new',
      productName: 'NETAPP',
      regionTags: ['EU', 'CA'],
      universe: 'Bare Metal Cloud',
      url:
        'https://ovhcloud.com/en-gb/storage-solutions/enterprise-file-storage/',
    },
  ],
};

export const rawCatalogData = [
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Block Storage',
    ],
    category: 'Storage and Backup',
    description:
      'Create storage volumes, which can be used as additional disks and secured via triple replication for data.',
    id: 20374,
    lang: 'en_GB',
    name: 'Block Storage',
    order: 'https://www.ovhcloud.com/it/public-cloud/block-storage',
    productName: 'BLOCK_STORAGE',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Cloud Archive',
    ],
    category: 'Storage and Backup',
    description:
      'Archive your data over the long term in a cloud storage space, accessible via standard protocols.',
    id: 20375,
    lang: 'en_GB',
    name: 'Cloud Archive',
    order: 'https://www.ovhcloud.com/it/public-cloud/cloud-archive',
    productName: 'CLOUD_ARCHIVE',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Data Analytics',
      'Data Processing',
    ],
    category: 'Data Analytics',
    description: 'Launch your Apache Spark processing tasks quickly and easily',
    featureAvailability: 'data-processing',
    id: 20379,
    lang: 'en_GB',
    name: 'Data Processing',
    order: 'https://www.ovhcloud.com/it/public-cloud/data-processing',
    productName: 'DATA_PROCESSING',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Web Hosting & Domains',
      'Email solutions',
      'Email Pro',
    ],
    category: 'Email solutions',
    description:
      'As the most comprehensive and widely-used business email solution on the market, Exchange offers many features — including contact, folder and calendar sharing, and email syncing.',
    featureAvailability: 'email-pro',
    id: 20385,
    lang: 'en_GB',
    name: 'Email Pro',
    order: 'https://www.ovh.it/emails/email-pro/',
    productName: 'EMAIL_PRO',
    regions: ['EU'],
    regionTags: ['EU'],
    universe: 'Web Hosting & Domains',
    url: 'https://ovhcloud.com/en-gb/emails/email-pro/',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Instance Backup',
    ],
    category: 'Storage and Backup',
    description: 'Get a backup service for your instances',
    id: 20390,
    lang: 'en_GB',
    name: 'Instance Backup',
    order: 'https://www.ovhcloud.com/it/public-cloud/instance-backup',
    productName: 'INSTANCES_BACKUP',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Web Hosting & Domains',
      'Collaborative Solutions',
      'Microsoft 365',
    ],
    category: 'Collaborative Solutions',
    description:
      'Securely access and edit your documents anytime, anywhere, so you can work however you work best. ',
    featureAvailability: 'office',
    id: 20394,
    lang: 'en_GB',
    name: 'Microsoft 365',
    order: 'https://www.ovh.it/office-365/',
    productName: 'LICENSE_OFFICE',
    regionTags: ['EU'],
    universe: 'Web Hosting & Domains',
    url: 'https://ovhcloud.com/en-gb/collaborative-tools/microsoft-365/',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Containers and orchestration',
      'Managed Kubernetes Service',
    ],
    category: 'Containers and orchestration',
    description:
      'Orchestrate your containerised applications with a CNCF-certified Kubernetes cluster',
    featureAvailability: 'kubernetes',
    id: 20398,
    lang: 'en_GB',
    name: 'Managed Kubernetes Service',
    order: 'https://www.ovhcloud.com/it/public-cloud/kubernetes',
    productName: 'MANAGED_KUBERNETES',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Containers and orchestration',
      'Managed Private Registry',
    ],
    category: 'Containers and orchestration',
    description:
      'Manage a repository for your software building blocks, in the form of Docker images or Helm charts',
    id: 20399,
    lang: 'en_GB',
    name: 'Managed Private Registry',
    order: 'https://www.ovhcloud.com/it/public-cloud/managed-private-registry',
    productName: 'MANAGED_PRIVATE_REGISTRY',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Object Storage',
    ],
    category: 'Storage and Backup',
    description: 'Enjoy unlimited on-demand storage, accessible via S3 API.',
    id: 20407,
    lang: 'en_GB',
    name: 'Object Storage',
    order: 'https://www.ovhcloud.com/it/public-cloud/object-storage',
    productName: 'OBJECT_STORAGE',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Hosted Private Cloud',
      'Platform',
      'VMware',
      'VMware on OVHcloud',
    ],
    category: 'Platform',
    description:
      'VMware on OVHcloud is a unique solution on the market, offering cloud scalability on a 100% dedicated hardware infrastructure. Your infrastructure virtualisation is powered by VMware technology, and entirely managed by OVHcloud. ',
    featureAvailability: 'dedicated-cloud:order',
    highlight: true,
    id: 20414,
    lang: 'en_GB',
    name: 'VMware on OVHcloud',
    order:
      'https://www.ovhcloud.com/it/enterprise/products/hosted-private-cloud/prices/',
    productName: 'PRIVATE_CLOUD',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Hosted Private Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Web Hosting & Domains',
      'Databases',
      'Private SQL Databases',
    ],
    category: 'Databases',
    description:
      'Works perfectly alongside all of our OVHcloud products, e.g. VPS, dedicated servers, Public Cloud instances and Cloud Web hosting',
    featureAvailability: 'private-database',
    id: 20415,
    lang: 'en_GB',
    name: 'Webcloud Databases',
    order: 'https://www.ovh.it/hosting-web/opzioni-sql.xml',
    productName: 'PRIVATE_DATABASE',
    regionTags: ['EU', 'CA'],
    universe: 'Web Hosting & Domains',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Web Hosting & Domains',
      'Web Hosting options',
      'Shared Content Delivery Network (CDN)',
    ],
    category: 'Web Hosting options',
    description:
      'Optimise your website traffic with the Shared CDN option for an optimal user experience',
    featureAvailability: 'hosting:shared-cdn',
    id: 20418,
    lang: 'en_GB',
    name: 'Shared Content Delivery Network (CDN)',
    order: 'https://www.ovh.it/hosting-web/cdn.xml',
    productName: 'SHARED_CDN',
    regionTags: ['EU', 'CA'],
    universe: 'Web Hosting & Domains',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Web Hosting & Domains',
      'Web Hosting options',
      'Visibility Pro',
    ],
    category: 'Web Hosting options',
    description:
      'Get your business on the map, wherever your customers are. Receive alerts, and reply quickly to customer reviews. Save time with an easy-to-use, centralised management interface.',
    id: 20425,
    lang: 'en_GB',
    name: 'Visibility Pro',
    productName: 'VISIBILITY_PRO',
    regionTags: ['EU'],
    universe: 'Web Hosting & Domains',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Volume Snapshot',
    ],
    category: 'Storage and Backup',
    description: 'Trigger a snapshot on your Block Storage volumes',
    id: 20426,
    lang: 'en_GB',
    name: 'Volume Snapshot',
    order: 'https://www.ovhcloud.com/it/public-cloud/volume-snapshot',
    productName: 'VOLUME_SNAPSHOT',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Web Hosting & Domains',
      'Web PaaS',
      'Web PaaS Powered by Platform.sh',
    ],
    category: 'Web PaaS',
    description:
      'A development platform designed for developers and their teams to design, deploy and run web applications.',
    featureAvailability: 'web-paas',
    id: 20430,
    lang: 'en_GB',
    name: 'Web PaaS Powered by Platform.sh',
    order: 'https://www.ovh.com/manager/#/web/paas/webpaas/new',
    productName: 'WEB_PAAS',
    regionTags: ['EU'],
    universe: 'Web Hosting & Domains',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Containers and orchestration',
      'Workflow Management',
    ],
    category: 'Containers and orchestration',
    description:
      'Automate your tasks to operate cloud resources based on your business logic, and adapt them to suit any situation',
    id: 20431,
    lang: 'en_GB',
    name: 'Workflow Management',
    order: 'https://www.ovhcloud.com/it/public-cloud/orchestration',
    productName: 'WORKFLOW_MANAGEMENT',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Hosted Private Cloud',
      'Platform',
      'Nutanix on OVHcloud',
    ],
    category: 'Platform',
    description:
      'The Nutanix on OVHcloud solution combines Nutanix Cloud Platform software licences with dedicated, Nutanix-qualified OVHcloud Hosted Private Cloud infrastructure — so you can pre-deploy a Nutanix hyperconverged environment (HCI) in just a few hours.',
    excludeSubsidiaries: ['ASIA', 'AU', 'SG'],
    featureAvailability: 'nutanix',
    id: 20447,
    lang: 'en_GB',
    name: 'Nutanix on OVHcloud',
    productName: 'NUTANIX',
    regionTags: ['EU', 'CA', 'US'],
    universe: 'Hosted Private Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Public Cloud', 'Compute'],
    category: 'Compute',
    description:
      'Deploy an option from our range of instances, and harness the flexibility of the cloud to grow in a way that suits your needs.',
    id: 20449,
    lang: 'en_GB',
    name: 'Compute',
    order: 'https://www.ovhcloud.com/it/public-cloud/',
    productName: 'PCI_INSTANCES',
    regionTags: ['EU'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Public Cloud', 'Storage and Backup', 'Databases'],
    category: 'Storage and Backup',
    description:
      'Harness the power of your data by maintaining control of your resources.',
    featureAvailability: 'databases',
    id: 20466,
    lang: 'en_GB',
    name: 'Databases',
    order: 'https://www.ovhcloud.com/it/public-cloud/databases',
    productName: 'DATABASES',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'AI & machine learning',
      'AI Notebooks',
    ],
    category: 'AI & machine learning',
    description:
      'Get a quick, simple start launching your Jupyter or VS Code notebooks in the cloud',
    featureAvailability: 'notebooks',
    id: 20470,
    lang: 'en_GB',
    name: 'AI Notebooks',
    order: 'https://www.ovhcloud.com/it/public-cloud/ai-notebooks',
    productName: 'NOTEBOOKS',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'AI & machine learning',
      'AI Training',
    ],
    category: 'AI & machine learning',
    description:
      'Train your AI, machine learning and deep learning models efficiently and easily, and optimise your GPU usage.',
    id: 20473,
    lang: 'en_GB',
    name: 'AI Training',
    order: 'https://www.ovhcloud.com/it/public-cloud/ai-training/',
    productName: 'AI_TRAINING',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Management Interfaces',
      'Horizon',
    ],
    category: 'Management Interfaces',
    description:
      'Use the original OpenStack web interface to effortlessly manage your cloud resources',
    id: 20633,
    lang: 'en_GB',
    name: 'Horizon',
    order: 'https://docs.ovh.com/it/public-cloud/horizon/',
    productName: 'HORIZON',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Bare Metal Cloud', 'Dedicated Servers'],
    category: 'Dedicated Servers',
    description:
      'Choose the best infrastructure for your business applications. We offer different ranges of highly efficient dedicated servers, adapted to the most demanding needs of all companies.',
    featureAvailability: 'dedicated-server:order',
    highlight: true,
    id: 20804,
    lang: 'en_GB',
    name: 'Dedicated Servers',
    order: 'https://www.ovhcloud.com/it/bare-metal/prices/',
    productName: 'DEDICATED_SERVER',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Bare Metal Cloud',
    url: 'https://ovhcloud.com/en-gb/bare-metal',
  },
  {
    categories: ['Catalogs', 'Bare Metal Cloud', 'Virtual Private Servers'],
    category: 'Virtual Private Servers',
    description:
      'A virtual private server, also referred to as a VPS, is a virtual dedicated server. Unlike web hosting — (also known as shared hosting), where the technical aspects are managed by OVHcloud — you are the administrator of your VPS, and fully manage it.',
    featureAvailability: 'vps',
    highlight: true,
    id: 20817,
    lang: 'en_GB',
    name: 'Virtual Private Servers',
    order: 'https://www.ovh.it/vps/',
    productName: 'VPS',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Bare Metal Cloud',
    url: 'https://ovhcloud.com/en-gb/vps',
  },
  {
    categories: ['Catalogs', 'Bare Metal Cloud', 'Managed Bare Metal'],
    category: 'Managed Bare Metal',
    description:
      'Your scalable dedicated cloud, hosted and monitored by OVHcloud, available in just 90 minutes. With the Essentials range, opt for highly available VMware virtualisation, and stay focused on your business.',
    featureAvailability: 'managed-bare-metal',
    highlight: true,
    id: 20820,
    lang: 'en_GB',
    name: 'Managed Bare Metal',
    order: 'https://www.ovhcloud.com/it/managed-bare-metal/',
    productName: 'ESSENTIALS',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Bare Metal Cloud',
    url: 'https://ovhcloud.com/en-gb/managed-bare-metal/',
  },
  {
    categories: [
      'Catalogs',
      'Bare Metal Cloud',
      'Storage and Backup',
      'Enterprise File Storage',
    ],
    category: 'Storage and Backup',
    description:
      'Enterprise File Storage, powered by NetApp. Connect of all your OVHcloud solutions to a high-performance file storage service for your most critical business applications.',
    featureAvailability: 'netapp',
    highlight: true,
    id: 20825,
    lang: 'en_GB',
    name: 'Enterprise File Storage',
    order: 'https://www.ovh.com/manager/#/dedicated/netapp/new',
    productName: 'NETAPP',
    regionTags: ['EU', 'CA'],
    universe: 'Bare Metal Cloud',
    url:
      'https://ovhcloud.com/en-gb/storage-solutions/enterprise-file-storage/',
  },
  {
    categories: ['Catalogs', 'Network', 'Network Services', 'Floating IP'],
    category: 'Network Services',
    description:
      'Assign and move public and flexible IPs between Public Cloud instances and network features (e.g. LBaaS, Gateway).',
    featureAvailability: 'additional-ips',
    id: 20836,
    lang: 'en_GB',
    name: 'Floating IP',
    order: 'https://www.ovhcloud.com/it/public-cloud/floating-ip/',
    productName: 'FLOATING_IP',
    regionTags: ['EU'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Network',
      'Network Services',
      'OVHcloud Load Balancer',
    ],
    category: 'Network Services',
    description:
      'Scale to meet your demand with any of our cloud solutions, in any of our datacentres.  With the OVHcloud Load Balancer, you can balance the load between services spread across multiple datacentres.',
    featureAvailability: 'ip-load-balancer',
    id: 20837,
    lang: 'en_GB',
    name: 'OVHcloud Load Balancer',
    order: 'https://www.ovh.it/soluzioni/load-balancer/',
    productName: 'IP_LOAD_BALANCER',
    regionTags: ['EU', 'CA'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Network', 'Network Services', 'vRack'],
    category: 'Network Services',
    description:
      'With vRack (virtual rack) technology, you can connect, isolate and distribute OVHcloud products within one or more private networks, if they are compatible.',
    id: 20838,
    lang: 'en_GB',
    name: 'vRack',
    order:
      "https://www.ovh.it/order/express/#/new/express/resume?products=~(~(planCode~'vrack~quantity~1~productId~'vrack))",
    productName: 'VRACK',
    regionTags: ['EU', 'US', 'CA'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Network', 'Network Services', 'OVHcloud Connect'],
    category: 'Network Services',
    description:
      'With our OVHcloud Connect hybrid connection solution, you can form a secure, high-performance link between your company network and the OVHcloud vRack.',
    featureAvailability: 'cloud-connect',
    id: 20839,
    lang: 'en_GB',
    name: 'OVHcloud Connect',
    productName: 'OVH_CLOUD_CONNECT',
    regionTags: ['EU', 'CA'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Bare Metal Cloud',
      'Storage and Backup',
      'Veeam Cloud Connect',
    ],
    category: 'Storage and Backup',
    description:
      'Easily and automatically outsource backups in the OVHcloud secure cloud. Using the Veeam Availability Suite®, you can ensure that your data is replicated in our datacentres.',
    featureAvailability: 'veeam-cloud-connect',
    id: 20847,
    lang: 'en_GB',
    name: 'Veeam Cloud Connect',
    productName: 'VEEAM_CLOUD_CONNECT',
    regionTags: ['EU', 'CA'],
    universe: 'Bare Metal Cloud',
    url: 'https://ovhcloud.com/en/storage-solutions/veeam-cloud-connect',
  },
  {
    categories: [
      'Catalogs',
      'Hosted Private Cloud',
      'Storage and Backup',
      'Veeam Enterprise',
    ],
    category: 'Storage and Backup',
    description:
      'Unlock the power of Veeam Backup & Replication. With OVHcloud, you can enjoy total freedom in terms of how you configure your backups once you have deployed your solution.',
    featureAvailability: 'veeam-enterprise:order',
    id: 20854,
    lang: 'en_GB',
    name: 'Veeam Enterprise',
    order: 'https://www.ovh.it/storage-solutions/veeam-enterprise.xml',
    productName: 'VEEAM_ENTERPRISE',
    regionTags: ['EU', 'CA'],
    universe: 'Hosted Private Cloud',
    url: 'https://ovhcloud.com/en-gb/storage-solutions/veeam-enterprise',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Data Analytics',
      'Logs Data Platform',
    ],
    category: 'Data Analytics',
    description:
      'Index and analyse logs in real time. Receive alerts if anything stops working. Share your data with your employees.',
    id: 20872,
    lang: 'en_GB',
    name: 'Logs Data Platform',
    order: 'https://www.ovhcloud.com/it/public-cloud/big-data-hadoop/',
    productName: 'ANALYTICS_DATA_PLATFORM',
    regionTags: ['EU'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Network', 'Network Services', 'Private Network'],
    category: 'Network Services',
    description:
      'Deploy private networks to implement virtual switches that can hot-connect your project instances in real time, without any service interruptions.',
    id: 20895,
    lang: 'en_GB',
    name: 'Private Network',
    order: 'https://www.ovhcloud.com/it/public-cloud/private-network',
    productName: 'PRIVATE_NETWORK',
    regionTags: ['EU'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Network', 'Network Services', 'Gateway'],
    category: 'Network Services',
    description:
      'Connect your private instances to the internet securely and use floating IPs to expose your private network services flexibly on the web.',
    featureAvailability: 'public-gateways',
    id: 20934,
    lang: 'en_GB',
    name: 'Gateway',
    order: 'https://www.ovhcloud.com/it/public-cloud/gateway/',
    productName: 'GATEWAYS',
    regionTags: ['EU'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Cold Archive',
    ],
    category: 'Storage and Backup',
    description:
      'Get our most cost-effective storage type for long-term data archiving on a tape storage infrastructure.',
    id: 21197,
    lang: 'en_GB',
    name: 'Cold Archive',
    order: 'https://www.ovhcloud.com/it/public-cloud/cold-archive/',
    productName: 'COLD_ARCHIVE',
    regionTags: ['EU'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Storage and Backup',
      'Volume Backup',
    ],
    category: 'Storage and Backup',
    description:
      'Back up your Block Storage volumes. The backed-up data is stored on our Object Storage service.',
    id: 21227,
    lang: 'en_GB',
    name: 'Volume Backup',
    order: 'https://www.ovhcloud.com/it/public-cloud/volume-backup/',
    productName: 'VOLUME_BACKUP',
    regionTags: ['EU', 'CA', 'US'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'AI & machine learning',
      'AI Deploy',
    ],
    category: 'AI & machine learning',
    description:
      'Easily deploy machine learning models and applications to production, create your API access points effortlessly, and make effective predictions.',
    id: 21429,
    lang: 'en_GB',
    name: 'AI Deploy',
    order: 'https://www.ovhcloud.com/it/public-cloud/ai-deploy/',
    productName: 'AI_DEPLOY',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://www.ovhcloud.com/en-gb/public-cloud/ai-deploy/',
  },
  {
    categories: [
      'Catalogs',
      'Hosted Private Cloud',
      'Platform',
      'SAP HANA on Private Cloud',
    ],
    category: 'Platform',
    description:
      'This new platform combines SAP HANA-certified HCI servers with our VMware on OVHcloud infrastructure. It enables secure hosting and effortless deployment of your most critical SAP environments in a sovereign cloud.',
    featureAvailability: 'dedicated-cloud:sapHanaOrder',
    highlight: true,
    id: 21725,
    lang: 'en_GB',
    name: 'SAP HANA on Private Cloud',
    order: 'https://www.ovhcloud.com/it/hosted-private-cloud/sap-hana/',
    productName: 'SAP_HANA',
    regionTags: ['EU', 'CA'],
    universe: 'Hosted Private Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Containers and orchestration',
      'Kubernetes Load Balancer',
    ],
    category: 'Containers and orchestration',
    description:
      'Automatic distribution of traffic on the Managed Kubernetes Service',
    featureAvailability: 'kubernetes',
    id: 21763,
    lang: 'en_GB',
    name: 'Kubernetes Load Balancer',
    order: 'https://www.ovhcloud.com/it/public-cloud/kubernetes',
    productName: 'KUBERNETES_LOAD_BALANCER',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://mockup.url.com',
  },
  {
    categories: ['Catalogs', 'Network', 'Network Services', 'Load Balancer'],
    category: 'Network Services',
    description: 'Automatic traffic distribution on Public Cloud resources',
    featureAvailability: 'octavia-load-balancer',
    id: 21764,
    lang: 'en_GB',
    name: 'Load Balancer',
    order: 'https://www.ovhcloud.com/it/public-cloud/private-network',
    productName: 'OCTAVIA_LOAD_BALANCER',
    regionTags: ['EU', 'CA'],
    universe: 'Network',
    url: 'https://mockup.url.com',
  },
  {
    categories: [
      'Catalogs',
      'Public Cloud',
      'Containers and orchestration',
      'Containers and orchestration',
    ],
    category: 'Containers and orchestration',
    description:
      'Seamlessly deploy and manage your containerised applications in a multi-cluster Kubernetes environment, using a multi-cloud or hybrid cloud approach.',
    featureAvailability: 'pci-rancher',
    id: 100001,
    lang: 'en_GB',
    name: 'Managed Rancher Service',
    order: 'https://www.ovhcloud.com/it/public-cloud/managed-rancher-service',
    productName: 'MANAGED_RANCHER_SERVICE',
    regionTags: ['EU', 'CA'],
    universe: 'Public Cloud',
    url: 'https://www.ovhcloud.com/en-gb/public-cloud/managed-rancher-service/',
  },
];
