export const SAVINGS_PLAN_INFO_URL = {
  DEFAULT: 'https://ovhcloud.com/en/public-cloud/savings-plan/',
  ASIA: 'https://ovhcloud.com/asia/public-cloud/savings-plan/',
  DE: 'https://ovhcloud.com/de/public-cloud/savings-plan/',
  ES: 'https://www.ovhcloud.com/es-es/public-cloud/savings-plan/',
  IE: 'https://ovhcloud.com/en-ie/public-cloud/savings-plan/',
  IT: 'https://ovhcloud.com/it/public-cloud/savings-plan/',
  NL: 'https://ovhcloud.com/nl/public-cloud/savings-plan/',
  PL: 'https://ovhcloud.com/pl/public-cloud/savings-plan/',
  PT: 'https://ovhcloud.com/pt/public-cloud/savings-plan/',
  GB: 'https://ovhcloud.com/en-gb/public-cloud/savings-plan/',
  CA: 'https://ovhcloud.com/en-ca/public-cloud/savings-plan/',
  QC: 'https://ovhcloud.com/fr-ca/public-cloud/savings-plan/',
  MA: 'https://ovhcloud.com/fr-ma/public-cloud/savings-plan/',
  SN: 'https://ovhcloud.com/fr-sn/public-cloud/savings-plan/',
  TN: 'https://ovhcloud.com/fr-tn/public-cloud/savings-plan/',
  AU: 'https://ovhcloud.com/en-au/public-cloud/savings-plan/',
  SG: 'https://ovhcloud.com/en-sg/public-cloud/savings-plan/',
  FR: 'https://ovhcloud.com/fr/public-cloud/savings-plan/',
  WE: 'https://ovhcloud.com/us-en/public-cloud/savings-plan/',
  WS: 'https://ovhcloud.com/us-en/public-cloud/savings-plan/',
  US: 'https://us.ovhcloud.com/public-cloud/savings-plan/',
};
