export const urls = {
  domainRoot: '/domain',
  domainOnboarding: '/domain/onboarding',
  domainDetail: '/domain/:serviceName',
  domainTabInformation: '/domain/:serviceName/information',
  domainTabZone: '/domain/:serviceName/zone',
  domainTabDns: '/domain/:serviceName/dns',
  domainTabOrderAnycast: '/domain/:serviceName/anycast/order',
  domainTabDnsModify: '/domain/:serviceName/dns-modify',
  domainTabRedirection: '/domain/:serviceName/redirection',
  domainTabDynHost: '/domain/:serviceName/dynhost',
  domainTabHost: '/domain/:serviceName/host',
  domainTabDnssec: '/domain/:serviceName/dnssec',
  domainTabContactManagement: '/domain/:serviceName/contact-management',
};
