export const urls = {
  domainRoot: '/domain',
  domainOnboarding: '/domain/onboarding',
  domainDetail: '/domain/:serviceName',
  domainTabInformation: '/domain/:serviceName/information',
  domainTabZone: '/domain/:serviceName/zone',
  domainTabDns: '/domain/:serviceName/dns',
  domainTabOrderAnycast: '/domain/:serviceName/anycast/order',
  domainTabWebHostingOrder: '/domain/:serviceName/webhosting/order',
  domainTabDnsModify: '/domain/:serviceName/dns-modify',
  domainTabRedirection: '/domain/:serviceName/redirection',
  domainTabDynHost: '/domain/:serviceName/dynhost',
  domainTabHost: '/domain/:serviceName/hosts',
  domainTabHostDelete: '/domain/:serviceName/hosts/:hostname/delete',
  domainTabDnssec: '/domain/:serviceName/dnssec',
  domainTabDsrecords: '/domain/:serviceName/ds-records',
  domainTabDsrecordsDelete: '/domain/:serviceName/ds-records/:keyTag/delete',
  domainTabContactManagement: '/domain/:serviceName/contact-management',
};
