import { ODS_COUNTRY_ISO_CODE } from '@ovhcloud/ods-common-core';

export const regionInputName = 'region';

export const regionNameToIsoCode: { [prop: string]: ODS_COUNTRY_ISO_CODE } = {
  RBX: ODS_COUNTRY_ISO_CODE.FR,
  GRA: ODS_COUNTRY_ISO_CODE.FR,
  PAR: ODS_COUNTRY_ISO_CODE.FR,
  SBG: ODS_COUNTRY_ISO_CODE.FR,
  MRS: ODS_COUNTRY_ISO_CODE.FR,
  WAW: ODS_COUNTRY_ISO_CODE.PL,
  ERI: ODS_COUNTRY_ISO_CODE.GB,
  TOR: ODS_COUNTRY_ISO_CODE.CA,
  BHS: ODS_COUNTRY_ISO_CODE.CA,
  SGP: ODS_COUNTRY_ISO_CODE.SG,
  SYD: ODS_COUNTRY_ISO_CODE.AU,
  MUM: ODS_COUNTRY_ISO_CODE.IN,
  BRU: ODS_COUNTRY_ISO_CODE.BE,
  MAD: ODS_COUNTRY_ISO_CODE.ES,
  LIM: ODS_COUNTRY_ISO_CODE.DE,
  VIN: ODS_COUNTRY_ISO_CODE.US,
  HIL: ODS_COUNTRY_ISO_CODE.US,
  DAL: ODS_COUNTRY_ISO_CODE.US,
  LAX: ODS_COUNTRY_ISO_CODE.US,
  CHI: ODS_COUNTRY_ISO_CODE.US,
  NYC: ODS_COUNTRY_ISO_CODE.US,
  MIA: ODS_COUNTRY_ISO_CODE.US,
  PAO: ODS_COUNTRY_ISO_CODE.US,
  DEN: ODS_COUNTRY_ISO_CODE.US,
  ATL: ODS_COUNTRY_ISO_CODE.US,
};
