import { StepComponent } from '@ovh-ux/manager-react-components';
import { useTranslation } from 'react-i18next';
import {
  OsdsButton,
  OsdsFormField,
  OsdsInput,
  OsdsMessage,
  OsdsSelect,
  OsdsSelectOption,
  OsdsSpinner,
  OsdsText,
} from '@ovhcloud/ods-components/react';
import { useContext, useEffect, useState } from 'react';
import {
  ODS_THEME_COLOR_INTENT,
  ODS_THEME_TYPOGRAPHY_LEVEL,
  ODS_THEME_TYPOGRAPHY_SIZE,
} from '@ovhcloud/ods-common-theming';
import {
  ODS_BUTTON_SIZE,
  ODS_BUTTON_TYPE,
  ODS_BUTTON_VARIANT,
  ODS_INPUT_TYPE,
  ODS_MESSAGE_TYPE,
  ODS_SPINNER_SIZE,
} from '@ovhcloud/ods-components';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ShellContext } from '@ovh-ux/manager-react-shell-client';
import { StepsEnum, useNewGatewayStore } from '@/pages/add/useStore';
import { useSubnets } from '@/api/hooks/useSubnets';
import { usePrivateNetworks } from '@/api/hooks/useNetworks';
import { SubnetModal } from '@/pages/add/SubnetModal';
import { getAutoGeneratedName } from '@/pages/add/util';
import { useGatewayCreation } from '@/pages/add/useGatewayCreation';
import useRepricingInstancesAvailable from '@/hooks/useRepricingInstancesAvailable';

export const AVAILABLE_SUBNET = [
  '192.168.0.1/24',
  '10.0.0.1/24',
  '172.16.0.1/24',
];

export const NetworkStep = (): JSX.Element => {
  const [isModalVisible, setIsModalVisible] = useState(false);
  const [isInputTouched, setIsInputTouched] = useState(false);

  const { t } = useTranslation(['add', 'global', 'stepper']);

  const navigate = useNavigate();
  const store = useNewGatewayStore();
  const [searchParams] = useSearchParams();
  const hasRepricing = useRepricingInstancesAvailable();
  const { tracking } = useContext(ShellContext).shell;

  const { create, isCreating } = useGatewayCreation(StepsEnum.NETWORK);

  const { data: privateNetworks } = usePrivateNetworks(
    store.project?.id,
    store.form.regionName,
  );

  const { data: subnets, isPending: isSubnetsLoading } = useSubnets(
    store.project?.id,
    store.form.regionName,
    store.form.network.id,
  );

  const isGatewayIncomplete =
    isSubnetsLoading ||
    !store.form.name ||
    !store.form.size ||
    !store.form.regionName ||
    !store.form.network.id;

  const isCreationDisabled = isGatewayIncomplete || store.project?.isDiscovery;

  useEffect(() => {
    const subnetId =
      !isSubnetsLoading && subnets.length > 0 ? subnets[0].id : undefined;

    store.updateForm.network(store.form.network.id, subnetId);
  }, [isSubnetsLoading, subnets]);

  // Init gateway name randomly on region change
  useEffect(() => {
    store.updateForm.name(
      getAutoGeneratedName(`gateway-${store.form.regionName?.toLowerCase()}`),
    );
  }, [store.form.regionName]);

  useEffect(() => {
    const networkId = searchParams.get('network');
    if (networkId) {
      const targetNetwork = privateNetworks?.find(
        (network) => network.id === networkId,
      );
      if (targetNetwork) {
        store.updateForm.network(targetNetwork.id, store.form.network.subnetId);
      }
    }
  }, [searchParams, privateNetworks]);

  return (
    <StepComponent
      id={StepsEnum.NETWORK}
      order={3}
      isOpen={store.steps.get(StepsEnum.NETWORK).isOpen}
      isChecked={store.steps.get(StepsEnum.NETWORK).isChecked}
      isLocked={store.steps.get(StepsEnum.NETWORK).isLocked}
      title={t(
        'add:pci_projects_project_public_gateways_add_attach_private_network_to_public_gateway_sub_title',
      )}
      next={
        hasRepricing
          ? {
              action: (id) => {
                store.updateStep.check(id as StepsEnum);
                store.updateStep.lock(id as StepsEnum);
                store.updateStep.open(StepsEnum.CONFIRM);
                tracking.trackClick({
                  name: 'public-gateway_add_select-private-network',
                  type: 'action',
                });
              },
              label: t('stepper:common_stepper_next_button_label'),
              isDisabled: isGatewayIncomplete,
            }
          : undefined
      }
      edit={
        hasRepricing
          ? {
              action: (id) => {
                store.updateStep.unCheck(id as StepsEnum);
                store.updateStep.unlock(id as StepsEnum);

                store.updateStep.close(StepsEnum.CONFIRM);
                store.updateStep.unCheck(StepsEnum.CONFIRM);
                store.updateStep.unlock(StepsEnum.CONFIRM);
              },
              label: t('stepper:common_stepper_modify_this_step'),
              isDisabled: false,
            }
          : undefined
      }
    >
      <p>
        <OsdsText
          level={ODS_THEME_TYPOGRAPHY_LEVEL.body}
          size={ODS_THEME_TYPOGRAPHY_SIZE._400}
          color={ODS_THEME_COLOR_INTENT.text}
        >
          {t(
            'add:pci_projects_project_public_gateways_add_attach_private_network_to_public_gateway_intro1',
          )}
        </OsdsText>
      </p>
      <p>
        <OsdsText
          level={ODS_THEME_TYPOGRAPHY_LEVEL.body}
          size={ODS_THEME_TYPOGRAPHY_SIZE._400}
          color={ODS_THEME_COLOR_INTENT.text}
        >
          {t(
            'add:pci_projects_project_public_gateways_add_attach_private_network_to_public_gateway_intro2',
          )}
        </OsdsText>
      </p>

      {privateNetworks?.length === 0 && (
        <OsdsMessage
          type={ODS_MESSAGE_TYPE.warning}
          color={ODS_THEME_COLOR_INTENT.warning}
          className="my-6 flex-row"
        >
          {t(
            'add:pci_projects_project_public_gateways_add_no_private_network_warning',
          )}
        </OsdsMessage>
      )}

      <OsdsFormField
        inline
        error={
          isInputTouched && !store.form.name
            ? t('global:common_field_error_required')
            : ''
        }
      >
        <OsdsText
          slot="label"
          color={ODS_THEME_COLOR_INTENT.text}
          size={ODS_THEME_TYPOGRAPHY_SIZE._200}
          level={ODS_THEME_TYPOGRAPHY_LEVEL.body}
          className="mt-4 font-bold"
        >
          {t(
            'add:pci_projects_project_public_gateways_add_modal_add_public_gateway_field_label',
          )}
        </OsdsText>
        <OsdsInput
          value={store.form.name}
          inline
          color={ODS_THEME_COLOR_INTENT.primary}
          onOdsValueChange={(e) => {
            setIsInputTouched(true);
            store.updateForm.name(`${e.detail.value}`);
          }}
          type={ODS_INPUT_TYPE.text}
          error={isInputTouched && !store.form.name}
          className="border"
        />
      </OsdsFormField>
      <br />
      <div className="sm:flex sm:flex-wrap-reverse sm:justify-start">
        <OsdsFormField className="pr-4 flex justify-between" inline>
          <OsdsText
            slot="label"
            color={ODS_THEME_COLOR_INTENT.text}
            size={ODS_THEME_TYPOGRAPHY_SIZE._200}
            level={ODS_THEME_TYPOGRAPHY_LEVEL.body}
            className="mt-4 font-bold"
          >
            {t(
              'add:pci_projects_project_public_gateways_add_select_private_network',
            )}
          </OsdsText>
          <OsdsSelect
            value={store.form.network.id}
            inline
            onOdsValueChange={(event) => {
              store.updateForm.network(
                event.detail.value as string,
                store.form.network.subnetId,
              );
            }}
          >
            <span slot="placeholder">
              {t(
                'add:pci_projects_project_public_gateways_add_select_private_network',
              )}
            </span>
            {store.form.newNetwork.name && store.form.newNetwork.subnet && (
              <OsdsSelectOption key="new" value="new">
                {store.form.newNetwork.name}
              </OsdsSelectOption>
            )}
            {privateNetworks ? (
              privateNetworks
                .filter((network) => network.name !== '')
                .map((network) => (
                  <OsdsSelectOption key={network.id} value={network.id}>
                    {network.name}
                  </OsdsSelectOption>
                ))
            ) : (
              <></>
            )}
          </OsdsSelect>
        </OsdsFormField>
        <OsdsButton
          size={ODS_BUTTON_SIZE.sm}
          inline
          variant={ODS_BUTTON_VARIANT.stroked}
          color={ODS_THEME_COLOR_INTENT.primary}
          className="xs:mt-2 sm:mt-0 w-fit h-fit"
          onClick={() => setIsModalVisible(true)}
        >
          {t(
            'add:pci_projects_project_public_gateways_add_private_network_add_action',
          )}
        </OsdsButton>
      </div>

      <br />
      {hasRepricing ? (
        store.form.network?.id &&
        isSubnetsLoading && <OsdsSpinner inline size={ODS_SPINNER_SIZE.md} />
      ) : (
        <>
          {!isCreating ? (
            <div className="h-20">
              {store.form.network?.id && isSubnetsLoading && (
                <OsdsSpinner inline size={ODS_SPINNER_SIZE.md} />
              )}
              {(!store.form.network?.id || !isSubnetsLoading) && (
                <div className="flex gap-x-5 mt-10">
                  <OsdsButton
                    type={ODS_BUTTON_TYPE.button}
                    variant={ODS_BUTTON_VARIANT.stroked}
                    color={ODS_THEME_COLOR_INTENT.primary}
                    inline
                    onClick={() => navigate('..')}
                  >
                    {t('stepper:common_stepper_cancel_button_label')}
                  </OsdsButton>
                  <OsdsButton
                    size={ODS_BUTTON_SIZE.md}
                    inline
                    variant={ODS_BUTTON_VARIANT.flat}
                    color={ODS_THEME_COLOR_INTENT.primary}
                    {...(isCreationDisabled && { disabled: true })}
                    onClick={create}
                  >
                    {t(
                      'add:pci_projects_project_public_gateways_add_submit_label',
                    )}
                  </OsdsButton>
                </div>
              )}
            </div>
          ) : (
            <p>
              <OsdsSpinner inline size={ODS_SPINNER_SIZE.md} />
              <OsdsText
                level={ODS_THEME_TYPOGRAPHY_LEVEL.body}
                size={ODS_THEME_TYPOGRAPHY_SIZE._400}
                color={ODS_THEME_COLOR_INTENT.text}
              >
                {t(
                  'add:pci_projects_project_public_gateways_add_creating_wait_message',
                )}
              </OsdsText>
            </p>
          )}
        </>
      )}

      {isModalVisible && (
        <SubnetModal onClose={() => setIsModalVisible(false)} />
      )}
    </StepComponent>
  );
};
