import { User } from '@ovh-ux/manager-config';

export const nichandleIndividual: User = {
  nichandle: 'aa00001-ovh',
  legalform: 'individual',
  firstname: 'Jane',
  name: 'Smith',
  address: '789 Avenue',
  zip: '67890',
  country: 'FR',
  email: 'jane@example.com',
  phone: '+33987654321',
  phoneCountry: 'SA',
  birthDay: '',
  language: 'fr_FR',
  area: '',
  state: '',
  currency: undefined,
  organisation: '',
  sex: '',
  customerCode: '',
  nationalIdentificationNumber: '',
  vat: '',
  city: '',
  ovhSubsidiary: 'FR',
  fax: '',
  corporationType: '',
  ovhCompany: '',
  companyNationalIdentificationNumber: '',
  complementaryAddress: '',
  birthCity: '',
  spareEmail: '',
  italianSDI: '',
  supportLevel: undefined,
  certificates: [],
  auth: undefined,
  isTrusted: false,
  enterprise: false,
  kycValidated: false,
};

export const nichandleCorporation: User = {
  nichandle: 'aa00001-ovh',
  legalform: 'corporation',
  firstname: 'Jane',
  name: 'Smith',
  address: '789 Avenue',
  zip: '67890',
  country: 'FR',
  email: 'jane@example.com',
  phone: '+33987654321',
  phoneCountry: 'SA',
  birthDay: '',
  language: 'fr_FR',
  area: '',
  state: '',
  currency: undefined,
  organisation: 'Acme Inc',
  sex: '',
  customerCode: '',
  nationalIdentificationNumber: 'DEF',
  vat: 'GHI',
  city: '',
  ovhSubsidiary: 'FR',
  fax: '',
  corporationType: 'SA',
  ovhCompany: '',
  companyNationalIdentificationNumber: 'ABC',
  complementaryAddress: '',
  birthCity: '',
  spareEmail: '',
  italianSDI: '',
  supportLevel: undefined,
  certificates: [],
  auth: undefined,
  isTrusted: false,
  enterprise: false,
  kycValidated: false,
};
