export const BETA_VERSION_STORAGE_KEY = 'NAV_RESHUFFLE_BETA_VERSION';
export const BETA_ACKNOWLEDGED_STORAGE_KEY = 'NAV_RESHUFFLE_BETA_ACKNOWLEDGED';
export const NAV_RESHUFFLE_BETA_ACCESS_PREFERENCE_KEY =
  'NAV_RESHUFFLE_BETA_ACCESS';
export const BETA_VERSION = 1;
