export const urls = {
  root: '/pci/projects',
  listing: '',
  project: ':projectId',
  home: '',
  edit: 'edit',
  activate: 'activate',
  onboarding: 'onboarding',
  creation: 'new',
  creating: 'creating/:orderId',
  creatingWithVoucher: 'creating/:orderId/:voucherCode',
  updating: 'updating/:orderId',
  updatingWithVoucher: 'updating/:orderId/:voucherCode',
  increaseQuota: 'increase-quota',
  remove: 'remove',
} as const;
