export const GUIDES = [
  {
    id: 'manager_start',
    highlight: true,
    link: {
      default: 'https://docs.ovh.com/gb/en/storage/netapp-control-panel/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/netapp-control-panel/',
      AU: 'https://docs.ovh.com/au/en/storage/netapp-control-panel/',
      CA: 'https://docs.ovh.com/ca/en/storage/netapp-control-panel/',
      DE: 'https://docs.ovh.com/de/storage/netapp-control-panel/',
      ES: 'https://docs.ovh.com/es/storage/netapp-control-panel/',
      FR: 'https://docs.ovh.com/fr/storage/netapp-control-panel/',
      GB: 'https://docs.ovh.com/gb/en/storage/netapp-control-panel/',
      IE: 'https://docs.ovh.com/ie/en/storage/netapp-control-panel/',
      IT: 'https://docs.ovh.com/it/storage/netapp-control-panel/',
      PL: 'https://docs.ovh.com/pl/storage/netapp-control-panel/',
      PT: 'https://docs.ovh.com/pt/storage/netapp-control-panel/',
      QC: 'https://docs.ovh.com/ca/fr/storage/netapp-control-panel/',
      SG: 'https://docs.ovh.com/sg/en/storage/netapp-control-panel/',
      US: 'https://docs.ovh.com/us/en/storage/netapp-control-panel/',
      WS: 'https://docs.ovh.com/us/es/storage/netapp-control-panel/',
    },
    hitSuffix: 'netapp-control-panel',
  },
  {
    id: 'api_start',
    highlight: true,
    link: {
      default: 'https://docs.ovh.com/gb/en/storage/netapp-quickstart/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/netapp-quickstart/',
      AU: 'https://docs.ovh.com/au/en/storage/netapp-quickstart/',
      CA: 'https://docs.ovh.com/ca/en/storage/netapp-quickstart/',
      DE: 'https://docs.ovh.com/de/storage/netapp-quickstart/',
      ES: 'https://docs.ovh.com/es/storage/netapp-quickstart/',
      FR: 'https://docs.ovh.com/fr/storage/netapp-quickstart/',
      GB: 'https://docs.ovh.com/gb/en/storage/netapp-quickstart/',
      IE: 'https://docs.ovh.com/ie/en/storage/netapp-quickstart/',
      IT: 'https://docs.ovh.com/it/storage/netapp-quickstart/',
      PL: 'https://docs.ovh.com/pl/storage/netapp-quickstart/',
      PT: 'https://docs.ovh.com/pt/storage/netapp-quickstart/',
      QC: 'https://docs.ovh.com/ca/fr/storage/netapp-quickstart/',
      SG: 'https://docs.ovh.com/sg/en/storage/netapp-quickstart/',
      US: 'https://docs.ovh.com/us/en/storage/netapp-quickstart/',
      WS: 'https://docs.ovh.com/us/es/storage/netapp-quickstart/',
    },
    hitSuffix: 'netapp-api',
  },
  {
    id: 'volumes',
    highlight: true,
    link: {
      default: 'https://docs.ovh.com/gb/en/storage/netapp-volumes/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/netapp-volumes/',
      AU: 'https://docs.ovh.com/au/en/storage/netapp-volumes/',
      CA: 'https://docs.ovh.com/ca/en/storage/netapp-volumes/',
      DE: 'https://docs.ovh.com/de/storage/netapp-volumes/',
      ES: 'https://docs.ovh.com/es/storage/netapp-volumes/',
      FR: 'https://docs.ovh.com/fr/storage/netapp-volumes/',
      GB: 'https://docs.ovh.com/gb/en/storage/netapp-volumes/',
      IE: 'https://docs.ovh.com/ie/en/storage/netapp-volumes/',
      IT: 'https://docs.ovh.com/it/storage/netapp-volumes/',
      QC: 'https://docs.ovh.com/ca/fr/storage/netapp-volumes/',
      PL: 'https://docs.ovh.com/pl/storage/netapp-volumes/',
      PT: 'https://docs.ovh.com/pt/storage/netapp-volumes/',
      SG: 'https://docs.ovh.com/sg/en/storage/netapp-volumes/',
      US: 'https://docs.ovh.com/us/en/storage/netapp-volumes/',
      WS: 'https://docs.ovh.com/us/es/storage/netapp-volumes/',
    },
    hitSuffix: 'netapp-volume',
  },
  {
    id: 'volume_acl',
    highlight: false,
    link: {
      default: 'https://docs.ovh.com/gb/en/storage/netapp-volume-acl/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/netapp-volume-acl/',
      AU: 'https://docs.ovh.com/au/en/storage/netapp-volume-acl/',
      CA: 'https://docs.ovh.com/ca/en/storage/netapp-volume-acl/',
      DE: 'https://docs.ovh.com/de/storage/netapp-volume-acl/',
      ES: 'https://docs.ovh.com/es/storage/netapp-volume-acl/',
      FR: 'https://docs.ovh.com/fr/storage/netapp-volume-acl/',
      GB: 'https://docs.ovh.com/gb/en/storage/netapp-volume-acl/',
      IE: 'https://docs.ovh.com/ie/en/storage/netapp-volume-acl/',
      IT: 'https://docs.ovh.com/it/storage/netapp-volume-acl/',
      QC: 'https://docs.ovh.com/ca/fr/storage/netapp-volume-acl/',
      PL: 'https://docs.ovh.com/pl/storage/netapp-volume-acl/',
      PT: 'https://docs.ovh.com/pt/storage/netapp-volume-acl/',
      SG: 'https://docs.ovh.com/sg/en/storage/netapp-volume-acl/',
      US: 'https://docs.ovh.com/us/en/storage/netapp-volume-acl/',
      WS: 'https://docs.ovh.com/us/es/storage/netapp-volume-acl/',
    },
    hitSuffix: 'netapp-volume-acl',
  },
  {
    id: 'volume_snapshots',
    highlight: false,
    link: {
      default: 'https://docs.ovh.com/gb/en/storage/netapp-volume-snapshots/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/netapp-volume-snapshots/',
      AU: 'https://docs.ovh.com/au/en/storage/netapp-volume-snapshots/',
      CA: 'https://docs.ovh.com/ca/en/storage/netapp-volume-snapshots/',
      DE: 'https://docs.ovh.com/de/storage/netapp-volume-snapshots/',
      ES: 'https://docs.ovh.com/es/storage/netapp-volume-snapshots/',
      FR: 'https://docs.ovh.com/fr/storage/netapp-volume-snapshots/',
      GB: 'https://docs.ovh.com/gb/en/storage/netapp-volume-snapshots/',
      IE: 'https://docs.ovh.com/ie/en/storage/netapp-volume-snapshots/',
      IT: 'https://docs.ovh.com/it/storage/netapp-volume-snapshots/',
      QC: 'https://docs.ovh.com/ca/fr/storage/netapp-volume-snapshots/',
      PL: 'https://docs.ovh.com/pl/storage/netapp-volume-snapshots/',
      PT: 'https://docs.ovh.com/pt/storage/netapp-volume-snapshots/',
      SG: 'https://docs.ovh.com/sg/en/storage/netapp-volume-snapshots/',
      US: 'https://docs.ovh.com/us/en/storage/netapp-volume-snapshots/',
      WS: 'https://docs.ovh.com/us/es/storage/netapp-volume-snapshots/',
    },
    hitSuffix: 'netapp-volume-snapshots',
  },
];

export default {
  GUIDES,
};
