export const codeDuplicationDefaultOptions = {
  mode: 'strict',
  threshold: 0,
  format: ['javascript', 'typescript', 'jsx', 'tsx'],
  ignore: [
    '**/node_modules/**',
    '**/target/**',
    '**/dist/**',
    '**/__mocks__/**',
    '**/mocks/**',
    '**/mock**/**',
    '**/_mock_/**',
    '**/**Mock**/**',
    '**/public/**',
    '**/.husky/**',
    '**/.vscode/.*',
    '**/.idea/**',
    '**/.gitlab/**',
    '**/.github/**',
    '**/eslint-config/**',
    '**/jest-config/**',
    '**/tailwind-config/**',
    '**/typescript-config/**',
    '**/.eslintrc.**',
    '**/.gitlab-ci.**',
    '**/tailwind.**',
    '**/tsconfig.json',
    '**/turbo.json',
    '**/jest.**',
    '**/__test__/**',
    '**/__tests__/**',
    '**/tests/**',
    '**/test**/**',
    '**/**test.**',
    '**/**Test**',
    '**/test**',
    '**/**spec.**',
    '**/**hmr**',
    '**/**config**',
    '**/**cucumber**',
    '**/webpack/**',
    '**/**webpack**',
    '**/next**.**',
    '**/.next/**',
    'babel',
    '.*.d.ts.*',
  ],
};
