export const CHALLENGER_CREDIT_CARD_LENGTH = 6;
export const CHALLENGER_CREDIT_CARD_PLACEHODER = 'XXXX XX';

export const CHALLENGER_ERROR_CODES = {
  400: 'RETRY_CHALLENGE',
  404: 'PAYMENT_METHOD_DEACTIVATED',
  DEFAULT: 'RETRY_CHALLENGE',
};

export default {
  CHALLENGER_CREDIT_CARD_LENGTH,
  CHALLENGER_CREDIT_CARD_PLACEHODER,
  CHALLENGER_ERROR_CODES,
};
