export const NODE_RESPONSE_MOCK = {
  expiration: '2025-03-01T00:00:00.000Z',
  netbootLabel: 'hd - Boot to disk',
  order: [
    'failoverIP',
    'kvm',
    'ip',
    'backupStorage',
    'ipMigration',
    'supportLevel',
  ],
  canOrder: true,
  canOrderBandwith: false,
  canOrderVrackBandwith: false,
  canOrderUsbDisk: false,
  canOrderQuota: false,
  canResiliateBandwidth: true,
  canResiliateVrackBandwidth: true,
  engagement: null,
  availableProfessionalUse: false,
  hasProfessionalUse: false,
  commercialRange: 'Scale-i2',
  isExpired: false,
  isCachecade: false,
  raidController: false,
  typeDisk: 'NVME',
  nbPhysicalDisk: 2,
  diskSize: 1030792,
  nbDisk: 2,
  totalSize: 2061584,
  otherDisk: [{ typeDisk: 'NVME', nbDisk: 4, sizeDisk: 2061584 }],
  ipv6: '2001:41d0:809:e900::/56',
  description: 'Scale-i2',
  state: 'OK',
  diskGroups: [
    {
      defaultHardwareRaidSize: null,
      raidController: null,
      description: '2 X Disk NVME 960 GB, JBOD',
      diskType: 'NVME',
      diskSize: { value: 960, unit: 'GB' },
      defaultHardwareRaidType: null,
      numberOfDisks: 2,
      diskGroupId: 1,
    },
    {
      diskType: 'NVME',
      defaultHardwareRaidType: null,
      numberOfDisks: 4,
      diskSize: { value: 1920, unit: 'GB' },
      diskGroupId: 2,
      defaultHardwareRaidSize: null,
      description: '4 X Disk NVME 1920 GB, JBOD',
      raidController: null,
    },
  ],
  ip: '57.129.130.233',
  os: 'Nutanix AOS 6.10 (single node)',
  reverse: 'ns31715910.ip-57-129-130.eu',
  datacenter: 'ERI_1',
  rack: 'ERI0111D04B',
  bootId: 1,
  serverId: 1758538,
  monitored: false,
  rootDevice: null,
  name: 'ns31715910.ip-57-129-130.eu',
  displayName: 'ERI - cluster-2116.nutanix.ovh.net - node1',
  serviceId: 130073469,
  canTakeRendezVous: false,
  shouldReengage: null,
  noIntervention: false,
  region: 'eu-west-eri',
  availabilityZone: 'eu-west-eri-a',
  iam: {
    displayName: 'ERI - cluster-2116.nutanix.ovh.net - node1',
    id: '8eeafeeb-c117-466c-910e-6bda27e75327',
    urn: 'urn:v1:eu:resource:dedicatedServer:ns31715910.ip-57-129-130.eu',
  },
  newUpgradeSystem: true,
  powerState: 'poweron',
  serviceStatus: 'active',
};
