export enum StepsEnum {
  LOCATION_STEP = 'LOCATION_STEP',
  VOLUME_TYPE_STEP = 'VOLUME_TYPE_STEP',
  VOLUME_CAPACITY_STEP = 'VOLUME_CAPACITY_STEP',
  VOLUME_NAME_STEP = 'VOLUME_NAME_STEP',
  VALIDATION_STEP = 'VALIDATION_STEP',
}
