/* eslint-disable max-lines */
export const vrackCartServiceOptionResponse = [
  {
    mandatory: false,
    family: 'ap-south-mum-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-south-mum-1g',
    exclusive: true,
    prices: [
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
        minimumQuantity: 1,
        duration: 'P0D',
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
      },
      {
        price: { currencyCode: 'EUR', value: 400, text: '400.00 €' },
        interval: 1,
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-south-mum / 1Gbps',
        minimumRepeat: 1,
        priceInUcents: 40000000000,
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - ap-south-mum / 1Gbps',
  },
  {
    planCode: 'vrack-outgoing-bandwidth-limit-ap-south-mum-2g',
    family: 'ap-south-mum-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - ap-south-mum / 2Gbps',
    exclusive: true,
    prices: [
      {
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
      },
      {
        capacities: ['upgrade'],
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
      },
      {
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        interval: 1,
        price: { value: 800, text: '800.00 €', currencyCode: 'EUR' },
        priceInUcents: 80000000000,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-south-mum / 2Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    mandatory: false,
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-ap-south-mum-4g',
    family: 'ap-south-mum-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - ap-south-mum / 4Gbps',
    prices: [
      {
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 0,
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        capacities: ['renew'],
        interval: 1,
        price: { currencyCode: 'EUR', value: 2000, text: '2000.00 €' },
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 200000000000,
        description: 'vRack outgoing bandwidth limit option - ap-south-mum / 4Gbps',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P1M',
      },
    ],
    productType: 'delivery',
    exclusive: true,
  },
  {
    mandatory: false,
    family: 'ap-south-mum-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-south-mum-500m',
    productType: 'delivery',
    prices: [
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        capacities: ['installation'],
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        capacities: ['upgrade'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        interval: 1,
        price: { value: 200, currencyCode: 'EUR', text: '200.00 €' },
        priceInUcents: 20000000000,
        minimumRepeat: 1,
        description: 'vRack outgoing bandwidth limit option - ap-south-mum / 500Mbps',
        pricingMode: 'default',
        duration: 'P1M',
        minimumQuantity: 1,
        pricingType: 'rental',
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - ap-south-mum / 500Mbps',
  },
  {
    mandatory: false,
    family: 'ap-southeast-sgp-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-sgp-1g',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        capacities: ['installation'],
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 1Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 40000000000,
        interval: 1,
        price: { value: 400, currencyCode: 'EUR', text: '400.00 €' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 1Gbps',
  },
  {
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 2Gbps',
    exclusive: true,
    prices: [
      {
        minimumQuantity: 1,
        duration: 'P0D',
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
      },
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        capacities: ['upgrade'],
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
      {
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 2Gbps',
        priceInUcents: 80000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: 1,
        price: { value: 800, currencyCode: 'EUR', text: '800.00 €' },
        interval: 1,
        capacities: ['renew'],
      },
    ],
    productType: 'delivery',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-sgp-2g',
    family: 'ap-southeast-sgp-outgoing-bandwidth',
    mandatory: false,
  },
  {
    mandatory: false,
    prices: [
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        capacities: ['installation'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['upgrade'],
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 4Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 200000000000,
        interval: 1,
        price: { currencyCode: 'EUR', value: 2000, text: '2000.00 €' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 4Gbps',
    family: 'ap-southeast-sgp-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-sgp-4g',
  },
  {
    mandatory: false,
    family: 'ap-southeast-sgp-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-sgp-500m',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['upgrade'],
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        capacities: ['renew'],
        interval: 1,
        price: { value: 200, currencyCode: 'EUR', text: '200.00 €' },
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        priceInUcents: 20000000000,
        minimumRepeat: 1,
        description: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 500Mbps',
        pricingMode: 'default',
        duration: 'P1M',
        minimumQuantity: 1,
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-sgp / 500Mbps',
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 1Gbps',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
      },
      {
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        price: { currencyCode: 'EUR', value: 400, text: '400.00 €' },
        interval: 1,
        capacities: ['renew'],
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 1Gbps',
        priceInUcents: 40000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
    ],
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-syd-1g',
    family: 'ap-southeast-syd-outgoing-bandwidth',
  },
  {
    family: 'ap-southeast-syd-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-syd-2g',
    productType: 'delivery',
    prices: [
      {
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
      },
      {
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 2Gbps',
        priceInUcents: 80000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: 1,
        price: { value: 800, text: '800.00 €', currencyCode: 'EUR' },
        interval: 1,
        capacities: ['renew'],
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 2Gbps',
    mandatory: false,
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 4Gbps',
    prices: [
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        capacities: ['installation'],
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
      },
      {
        interval: 1,
        price: { text: '2000.00 €', value: 2000, currencyCode: 'EUR' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 4Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        priceInUcents: 200000000000,
        minimumRepeat: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-syd-4g',
    family: 'ap-southeast-syd-outgoing-bandwidth',
  },
  {
    planCode: 'vrack-outgoing-bandwidth-limit-ap-southeast-syd-500m',
    family: 'ap-southeast-syd-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 500Mbps',
    exclusive: true,
    prices: [
      {
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 0,
      },
      {
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        interval: 1,
        price: { value: 200, text: '200.00 €', currencyCode: 'EUR' },
        minimumRepeat: 1,
        priceInUcents: 20000000000,
        description: 'vRack outgoing bandwidth limit option - ap-southeast-syd / 500Mbps',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P1M',
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    mandatory: false,
  },
  {
    mandatory: false,
    exclusive: true,
    prices: [
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        capacities: ['installation'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 50000000000,
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-bhs / 10Gbps',
        capacities: ['renew'],
        price: { value: 500, currencyCode: 'EUR', text: '500.00 €' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - ca-east-bhs / 10Gbps',
    family: 'ca-east-bhs-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-bhs-10g',
  },
  {
    family: 'ca-east-bhs-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-bhs-15g',
    productType: 'delivery',
    prices: [
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
      },
      {
        capacities: ['upgrade'],
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
      },
      {
        minimumRepeat: 1,
        priceInUcents: 75000000000,
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-bhs / 15Gbps',
        pricingType: 'rental',
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        price: { value: 750, currencyCode: 'EUR', text: '750.00 €' },
        interval: 1,
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - ca-east-bhs / 15Gbps',
    mandatory: false,
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - ca-east-bhs / 20Gbps',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
      },
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
      {
        capacities: ['renew'],
        price: { text: '1000.00 €', value: 1000, currencyCode: 'EUR' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-bhs / 20Gbps',
      },
    ],
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-bhs-20g',
    family: 'ca-east-bhs-outgoing-bandwidth',
  },
  {
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { text: '1250.00 €', value: 1250, currencyCode: 'EUR' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-bhs / 25Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        priceInUcents: 125000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - ca-east-bhs / 25Gbps',
    family: 'ca-east-bhs-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-bhs-25g',
    mandatory: false,
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - ca-east-tor / 10Gbps',
    productType: 'delivery',
    prices: [
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { value: 500, currencyCode: 'EUR', text: '500.00 €' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-tor / 10Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 50000000000,
        pricingType: 'rental',
      },
    ],
    exclusive: true,
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-tor-10g',
    family: 'ca-east-tor-outgoing-bandwidth',
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-tor-15g',
    family: 'ca-east-tor-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - ca-east-tor / 15Gbps',
    exclusive: true,
    prices: [
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
      },
      {
        pricingType: 'rental',
        priceInUcents: 75000000000,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-tor / 15Gbps',
        capacities: ['renew'],
        price: { currencyCode: 'EUR', value: 750, text: '750.00 €' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productType: 'delivery',
  },
  {
    mandatory: false,
    family: 'ca-east-tor-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-tor-20g',
    prices: [
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - ca-east-tor / 20Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        capacities: ['renew'],
        interval: 1,
        price: { text: '1000.00 €', value: 1000, currencyCode: 'EUR' },
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - ca-east-tor / 20Gbps',
  },
  {
    productType: 'delivery',
    prices: [
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        capacities: ['upgrade'],
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
      },
      {
        price: { value: 1250, currencyCode: 'EUR', text: '1250.00 €' },
        interval: 1,
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P1M',
        description: 'vRack outgoing bandwidth limit option - ca-east-tor / 25Gbps',
        pricingMode: 'default',
        priceInUcents: 125000000000,
        minimumRepeat: 1,
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - ca-east-tor / 25Gbps',
    family: 'ca-east-tor-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-ca-east-tor-25g',
    mandatory: false,
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-central-waw-10g',
    family: 'eu-central-waw-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-central-waw / 10Gbps',
    exclusive: true,
    prices: [
      {
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        capacities: ['upgrade'],
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-central-waw / 10Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 50000000000,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
  },
  {
    mandatory: false,
    prices: [
      {
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        capacities: ['upgrade'],
      },
      {
        priceInUcents: 75000000000,
        minimumRepeat: 1,
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-central-waw / 15Gbps',
        pricingType: 'rental',
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        price: { currencyCode: 'EUR', value: 750, text: '750.00 €' },
        interval: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - eu-central-waw / 15Gbps',
    family: 'eu-central-waw-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-central-waw-15g',
  },
  {
    mandatory: false,
    family: 'eu-central-waw-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-central-waw-20g',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
      },
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        pricingType: 'rental',
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-central-waw / 20Gbps',
        capacities: ['renew'],
        price: { value: 1000, currencyCode: 'EUR', text: '1000.00 €' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - eu-central-waw / 20Gbps',
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-central-waw-25g',
    family: 'eu-central-waw-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-central-waw / 25Gbps',
    productType: 'delivery',
    prices: [
      {
        capacities: ['installation'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
      },
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        pricingType: 'rental',
        priceInUcents: 125000000000,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-central-waw / 25Gbps',
        capacities: ['renew'],
        price: { value: 1250, text: '1250.00 €', currencyCode: 'EUR' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    exclusive: true,
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-south-mil-10g',
    family: 'eu-south-mil-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-south-mil / 10Gbps',
    prices: [
      {
        priceInUcents: 0,
        minimumRepeat: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
      },
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        interval: 1,
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        description: 'vRack outgoing bandwidth limit option - eu-south-mil / 10Gbps',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P1M',
        priceInUcents: 50000000000,
        minimumRepeat: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
  },
  {
    planCode: 'vrack-outgoing-bandwidth-limit-eu-south-mil-15g',
    family: 'eu-south-mil-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-south-mil / 15Gbps',
    prices: [
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        capacities: ['installation'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        capacities: ['upgrade'],
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { currencyCode: 'EUR', value: 750, text: '750.00 €' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-south-mil / 15Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        priceInUcents: 75000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    exclusive: true,
    mandatory: false,
  },
  {
    productName: 'vRack outgoing bandwidth limit option - eu-south-mil / 20Gbps',
    exclusive: true,
    prices: [
      {
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['installation'],
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        minimumQuantity: 1,
        duration: 'P1M',
        description: 'vRack outgoing bandwidth limit option - eu-south-mil / 20Gbps',
        pricingMode: 'default',
        capacities: ['renew'],
        price: { text: '1000.00 €', value: 1000, currencyCode: 'EUR' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productType: 'delivery',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-south-mil-20g',
    family: 'eu-south-mil-outgoing-bandwidth',
    mandatory: false,
  },
  {
    mandatory: false,
    family: 'eu-south-mil-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-south-mil-25g',
    exclusive: true,
    prices: [
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
      },
      {
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { currencyCode: 'EUR', value: 1250, text: '1250.00 €' },
        capacities: ['renew'],
        description: 'vRack outgoing bandwidth limit option - eu-south-mil / 25Gbps',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 125000000000,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - eu-south-mil / 25Gbps',
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-eri-10g',
    family: 'eu-west-eri-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-eri / 10Gbps',
    exclusive: true,
    prices: [
      {
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { text: '500.00 €', value: 500, currencyCode: 'EUR' },
        capacities: ['renew'],
        description: 'vRack outgoing bandwidth limit option - eu-west-eri / 10Gbps',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 50000000000,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-eri-15g',
    family: 'eu-west-eri-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-eri / 15Gbps',
    prices: [
      {
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['installation'],
      },
      {
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        capacities: ['renew'],
        interval: 1,
        price: { text: '750.00 €', value: 750, currencyCode: 'EUR' },
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        priceInUcents: 75000000000,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-eri / 15Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
      },
    ],
    productType: 'delivery',
    exclusive: true,
  },
  {
    mandatory: false,
    family: 'eu-west-eri-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-eri-20g',
    exclusive: true,
    prices: [
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
        capacities: ['installation'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingType: 'rental',
      },
      {
        capacities: ['renew'],
        price: { value: 1000, text: '1000.00 €', currencyCode: 'EUR' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        priceInUcents: 100000000000,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-eri / 20Gbps',
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - eu-west-eri / 20Gbps',
  },
  {
    exclusive: true,
    prices: [
      {
        capacities: ['installation'],
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
      },
      {
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['upgrade'],
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { value: 1250, text: '1250.00 €', currencyCode: 'EUR' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-eri / 25Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        priceInUcents: 125000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - eu-west-eri / 25Gbps',
    family: 'eu-west-eri-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-eri-25g',
    mandatory: false,
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-gra-10g',
    family: 'eu-west-gra-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-gra / 10Gbps',
    productType: 'delivery',
    prices: [
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
      },
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
      },
      {
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        interval: 1,
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-gra / 10Gbps',
        minimumRepeat: 1,
        priceInUcents: 50000000000,
      },
    ],
    exclusive: true,
  },
  {
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-gra-15g',
    family: 'eu-west-gra-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-gra / 15Gbps',
    productType: 'delivery',
    prices: [
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        minimumRepeat: 1,
        priceInUcents: 0,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        capacities: ['upgrade'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        price: { currencyCode: 'EUR', value: 750, text: '750.00 €' },
        interval: 1,
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-gra / 15Gbps',
        priceInUcents: 75000000000,
        minimumRepeat: 1,
      },
    ],
    exclusive: true,
    mandatory: false,
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - eu-west-gra / 20Gbps',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        priceInUcents: 0,
        minimumRepeat: 1,
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        priceInUcents: 0,
        minimumRepeat: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingType: 'rental',
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { value: 1000, currencyCode: 'EUR', text: '1000.00 €' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-gra / 20Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        pricingType: 'rental',
      },
    ],
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-gra-20g',
    family: 'eu-west-gra-outgoing-bandwidth',
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - eu-west-gra / 25Gbps',
    prices: [
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        minimumRepeat: 1,
        priceInUcents: 0,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
      },
      {
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        minimumRepeat: 1,
        priceInUcents: 0,
      },
      {
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-gra / 25Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        priceInUcents: 125000000000,
        minimumRepeat: 1,
        interval: 1,
        price: { value: 1250, currencyCode: 'EUR', text: '1250.00 €' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-gra-25g',
    family: 'eu-west-gra-outgoing-bandwidth',
  },
  {
    mandatory: false,
    exclusive: true,
    prices: [
      {
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 50000000000,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-lim / 10Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        capacities: ['renew'],
        interval: 1,
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - eu-west-lim / 10Gbps',
    family: 'eu-west-lim-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-lim-10g',
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - eu-west-lim / 15Gbps',
    productType: 'delivery',
    prices: [
      {
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
      },
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        interval: 1,
        price: { value: 750, currencyCode: 'EUR', text: '750.00 €' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-lim / 15Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 75000000000,
      },
    ],
    exclusive: true,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-lim-15g',
    family: 'eu-west-lim-outgoing-bandwidth',
  },
  {
    mandatory: false,
    productName: 'vRack outgoing bandwidth limit option - eu-west-lim / 20Gbps',
    exclusive: true,
    prices: [
      {
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
      },
      {
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { text: '1000.00 €', value: 1000, currencyCode: 'EUR' },
        capacities: ['renew'],
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-lim / 20Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-lim-20g',
    family: 'eu-west-lim-outgoing-bandwidth',
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-lim-25g',
    family: 'eu-west-lim-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-lim / 25Gbps',
    productType: 'delivery',
    prices: [
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
      },
      {
        capacities: ['upgrade'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
      },
      {
        interval: 1,
        price: { currencyCode: 'EUR', value: 1250, text: '1250.00 €' },
        capacities: ['renew'],
        maximumRepeat: 1,
        maximumQuantity: 1,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-lim / 25Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        priceInUcents: 125000000000,
        minimumRepeat: 1,
      },
    ],
    exclusive: true,
  },
  {
    exclusive: true,
    prices: [
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        priceInUcents: 0,
        minimumRepeat: 1,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-par / 10Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        priceInUcents: 50000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        capacities: ['renew'],
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - eu-west-par / 10Gbps',
    family: 'eu-west-par-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-par-10g',
    mandatory: false,
  },
  {
    prices: [
      {
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P0D',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        capacities: ['upgrade'],
      },
      {
        capacities: ['renew'],
        price: { value: 750, currencyCode: 'EUR', text: '750.00 €' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        priceInUcents: 75000000000,
        minimumRepeat: 1,
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-par / 15Gbps',
      },
    ],
    productType: 'delivery',
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - eu-west-par / 15Gbps',
    family: 'eu-west-par-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-par-15g',
    mandatory: false,
  },
  {
    family: 'eu-west-par-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-par-20g',
    productType: 'delivery',
    prices: [
      {
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        capacities: ['installation'],
      },
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
      },
      {
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-par / 20Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { text: '1000.00 €', value: 1000, currencyCode: 'EUR' },
        capacities: ['renew'],
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - eu-west-par / 20Gbps',
    mandatory: false,
  },
  {
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        priceInUcents: 0,
        minimumRepeat: 1,
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        pricingType: 'rental',
      },
      {
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
      },
      {
        priceInUcents: 125000000000,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-par / 25Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        pricingType: 'rental',
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        interval: 1,
        price: { value: 1250, currencyCode: 'EUR', text: '1250.00 €' },
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - eu-west-par / 25Gbps',
    family: 'eu-west-par-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-par-25g',
    mandatory: false,
  },
  {
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-rbx-10g',
    family: 'eu-west-rbx-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-rbx / 10Gbps',
    prices: [
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        capacities: ['installation'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        interval: 1,
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        minimumRepeat: 1,
        priceInUcents: 50000000000,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-rbx / 10Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        pricingType: 'rental',
      },
    ],
    productType: 'delivery',
    exclusive: true,
    mandatory: false,
  },
  {
    productName: 'vRack outgoing bandwidth limit option - eu-west-rbx / 15Gbps',
    prices: [
      {
        capacities: ['installation'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
      },
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['upgrade'],
        interval: 0,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 75000000000,
        description: 'vRack outgoing bandwidth limit option - eu-west-rbx / 15Gbps',
        pricingMode: 'default',
        duration: 'P1M',
        minimumQuantity: 1,
        capacities: ['renew'],
        interval: 1,
        price: { value: 750, currencyCode: 'EUR', text: '750.00 €' },
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productType: 'delivery',
    exclusive: true,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-rbx-15g',
    family: 'eu-west-rbx-outgoing-bandwidth',
    mandatory: false,
  },
  {
    family: 'eu-west-rbx-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-rbx-20g',
    productType: 'delivery',
    prices: [
      {
        minimumQuantity: 1,
        duration: 'P0D',
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
      },
      {
        capacities: ['upgrade'],
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
      },
      {
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { currencyCode: 'EUR', value: 1000, text: '1000.00 €' },
        capacities: ['renew'],
        description: 'vRack outgoing bandwidth limit option - eu-west-rbx / 20Gbps',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P1M',
        priceInUcents: 100000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - eu-west-rbx / 20Gbps',
    mandatory: false,
  },
  {
    mandatory: false,
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-rbx-25g',
    family: 'eu-west-rbx-outgoing-bandwidth',
    productName: 'vRack outgoing bandwidth limit option - eu-west-rbx / 25Gbps',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        priceInUcents: 0,
        minimumRepeat: 1,
        price: { text: '0.00 €', value: 0, currencyCode: 'EUR' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
      },
      {
        minimumQuantity: 1,
        duration: 'P1M',
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-rbx / 25Gbps',
        priceInUcents: 125000000000,
        minimumRepeat: 1,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: 1,
        price: { value: 1250, text: '1250.00 €', currencyCode: 'EUR' },
        interval: 1,
        capacities: ['renew'],
      },
    ],
  },
  {
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        interval: 0,
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        capacities: ['installation'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumQuantity: 1,
        duration: 'P0D',
        minimumRepeat: 1,
        priceInUcents: 0,
      },
      {
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        priceInUcents: 0,
        minimumRepeat: 1,
      },
      {
        maximumQuantity: 1,
        maximumRepeat: 1,
        capacities: ['renew'],
        price: { currencyCode: 'EUR', value: 500, text: '500.00 €' },
        interval: 1,
        priceInUcents: 50000000000,
        minimumRepeat: 1,
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-sbg / 10Gbps',
        pricingType: 'rental',
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - eu-west-sbg / 10Gbps',
    family: 'eu-west-sbg-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-sbg-10g',
    mandatory: false,
  },
  {
    family: 'eu-west-sbg-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-sbg-15g',
    exclusive: true,
    productType: 'delivery',
    prices: [
      {
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        capacities: ['installation'],
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['upgrade'],
        maximumRepeat: 1,
        maximumQuantity: null,
        pricingType: 'rental',
        minimumQuantity: 1,
        duration: 'P0D',
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 75000000000,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-sbg / 15Gbps',
        minimumQuantity: 1,
        duration: 'P1M',
        capacities: ['renew'],
        interval: 1,
        price: { text: '750.00 €', value: 750, currencyCode: 'EUR' },
        maximumQuantity: 1,
        maximumRepeat: 1,
      },
    ],
    productName: 'vRack outgoing bandwidth limit option - eu-west-sbg / 15Gbps',
    mandatory: false,
  },
  {
    family: 'eu-west-sbg-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-sbg-20g',
    productType: 'delivery',
    prices: [
      {
        maximumRepeat: 1,
        maximumQuantity: null,
        price: { value: 0, currencyCode: 'EUR', text: '0.00 €' },
        interval: 0,
        capacities: ['installation'],
        duration: 'P0D',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        minimumRepeat: 1,
        priceInUcents: 0,
        pricingType: 'rental',
      },
      {
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
        pricingType: 'rental',
        priceInUcents: 0,
        minimumRepeat: 1,
        pricingMode: 'default',
        description: 'rental (only applicable 1 time)',
        duration: 'P0D',
        minimumQuantity: 1,
      },
      {
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-sbg / 20Gbps',
        duration: 'P1M',
        minimumQuantity: 1,
        minimumRepeat: 1,
        priceInUcents: 100000000000,
        pricingType: 'rental',
        maximumRepeat: 1,
        maximumQuantity: 1,
        interval: 1,
        price: { text: '1000.00 €', value: 1000, currencyCode: 'EUR' },
        capacities: ['renew'],
      },
    ],
    exclusive: true,
    productName: 'vRack outgoing bandwidth limit option - eu-west-sbg / 20Gbps',
    mandatory: false,
  },
  {
    family: 'eu-west-sbg-outgoing-bandwidth',
    planCode: 'vrack-outgoing-bandwidth-limit-eu-west-sbg-25g',
    exclusive: true,
    prices: [
      {
        minimumRepeat: 1,
        priceInUcents: 0,
        duration: 'P0D',
        minimumQuantity: 1,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        pricingType: 'rental',
        maximumQuantity: null,
        maximumRepeat: 1,
        capacities: ['installation'],
        price: { value: 0, text: '0.00 €', currencyCode: 'EUR' },
        interval: 0,
      },
      {
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 0,
        description: 'rental (only applicable 1 time)',
        pricingMode: 'default',
        minimumQuantity: 1,
        duration: 'P0D',
        capacities: ['upgrade'],
        interval: 0,
        price: { currencyCode: 'EUR', value: 0, text: '0.00 €' },
        maximumQuantity: null,
        maximumRepeat: 1,
      },
      {
        capacities: ['renew'],
        price: { value: 1250, currencyCode: 'EUR', text: '1250.00 €' },
        interval: 1,
        maximumQuantity: 1,
        maximumRepeat: 1,
        pricingType: 'rental',
        minimumRepeat: 1,
        priceInUcents: 125000000000,
        duration: 'P1M',
        minimumQuantity: 1,
        pricingMode: 'default',
        description: 'vRack outgoing bandwidth limit option - eu-west-sbg / 25Gbps',
      },
    ],
    productType: 'delivery',
    productName: 'vRack outgoing bandwidth limit option - eu-west-sbg / 25Gbps',
    mandatory: false,
  },
];
