export const GUIDES = [
  {
    title: 'nasha_onboarding_guide1_title',
    description: 'nasha_onboarding_guide1_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/nas/get-started/',
      DE: 'https://docs.ovh.com/de/storage/nas/erste-schritte/',
      ES: 'https://docs.ovh.com/es/storage/nas/primeros-pasos/',
      IE: 'https://docs.ovh.com/ie/en/storage/nas/get-started/',
      IT: 'https://docs.ovh.com/it/storage/nas/iniziare/',
      PL: 'https://docs.ovh.com/pl/storage/nas/pierwsze-kroki/',
      PT: 'https://docs.ovh.com/pt/storage/nas/primeiros-passos/',
      GB: 'https://docs.ovh.com/gb/en/storage/nas/get-started/',
      CA: 'https://docs.ovh.com/ca/en/storage/nas/get-started/',
      QC: 'https://docs.ovh.com/ca/fr/storage/nas/decouverte/',
      FR: 'https://docs.ovh.com/fr/storage/nas/decouverte/',
      WE: 'https://docs.ovh.com/us/en/storage/nas/get-started/',
      WS: 'https://docs.ovh.com/us/en/storage/nas/get-started/',
      US: 'https://docs.ovh.com/us/en/storage/nas/get-started/',
    },
  },
  {
    title: 'nasha_onboarding_guide2_title',
    description: 'nasha_onboarding_guide2_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/nas/nas-cifs/',
      DE: 'https://docs.ovh.com/de/storage/nas/nas-cifs/',
      ES: 'https://docs.ovh.com/es/storage/nas/nas-cifs/',
      IE: 'https://docs.ovh.com/ie/en/storage/nas/nas-cifs/',
      IT: 'https://docs.ovh.com/it/storage/nas/nas-cifs/',
      PL: 'https://docs.ovh.com/pl/storage/nas/nas-cifs/',
      PT: 'https://docs.ovh.com/pt/storage/nas/nas-cifs/',
      GB: 'https://docs.ovh.com/gb/en/storage/nas/nas-cifs/',
      CA: 'https://docs.ovh.com/ca/en/storage/nas/nas-cifs/',
      QC: 'https://docs.ovh.com/ca/fr/storage/nas/nas-cifs/',
      FR: 'https://docs.ovh.com/fr/storage/nas/nas-cifs/',
      WE: 'https://docs.ovh.com/us/en/storage/nas/nas-cifs/',
      WS: 'https://docs.ovh.com/us/en/storage/nas/nas-cifs/',
      US: 'https://docs.ovh.com/us/en/storage/nas/nas-cifs/',
    },
  },
  {
    title: 'nasha_onboarding_guide3_title',
    description: 'nasha_onboarding_guide3_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/faq-nas/',
      DE: 'https://docs.ovh.com/de/storage/faq-nas/',
      ES: 'https://docs.ovh.com/es/storage/faq-nas/',
      IE: 'https://docs.ovh.com/ie/en/storage/faq-nas/',
      IT: 'https://docs.ovh.com/it/storage/faq-nas/',
      PL: 'https://docs.ovh.com/pl/storage/faq-nas/',
      PT: 'https://docs.ovh.com/pt/storage/faq-nas/',
      GB: 'https://docs.ovh.com/gb/en/storage/faq-nas/',
      CA: 'https://docs.ovh.com/ca/en/storage/faq-nas/',
      QC: 'https://docs.ovh.com/ca/fr/storage/faq-nas/',
      FR: 'https://docs.ovh.com/fr/storage/faq-nas/',
      WE: 'https://docs.ovh.com/us/en/storage/faq-nas/',
      WS: 'https://docs.ovh.com/us/en/storage/faq-nas/',
      US: 'https://docs.ovh.com/us/en/storage/faq-nas/',
    },
  },
];

export default { GUIDES };
