export const TASK_STATUS = {
  CANCELLED: 'CANCELLED',
  CUSTOMER_ERROR: 'CUSTOMER_ERROR',
  DOING: 'DOING',
  DONE: 'DONE',
  INIT: 'INIT',
  OVH_ERROR: 'OVH_ERROR',
  TODO: 'TODO',
};

export default {
  TASK_STATUS,
};
