import { User } from '@ovh-ux/manager-config';

export const nichandle: User = {
  address: 'adress',
  area: null,
  birthCity: 'Rbx',
  birthDay: '1988-10-29',
  city: 'Roubaix',
  companyNationalIdentificationNumber: null,
  complementaryAddress: null,
  corporationType: 'OVHcloud SAS',
  country: 'FR',
  currency: {
    code: 'EUR',
    symbol: '€',
    format: '',
  },
  customerCode: '0001-0000-11',
  email: 'foobar@bar.net',
  fax: null,
  firstname: 'domain',
  italianSDI: null,
  kycValidated: true,
  language: 'fr_FR',
  legalform: 'corporation',
  name: 'Domain',
  nationalIdentificationNumber: '1234456',
  nichandle: 'aa00001-ovh',
  organisation: 'OVHCloud',
  ovhCompany: 'ovh',
  ovhSubsidiary: 'FR',
  phone: '+33.000000000',
  phoneCountry: 'FR',
  sex: 'male',
  spareEmail: 'foo.bar@.ovh.com',
  state: 'complete',
  vat: null,
  zip: '59100',
  auth: {
    account: 'aa00001-ovh',
    allowedRoutes: null,
    description: null,
    identities: ['urn:v1:eu:identity:account:aa00001-ovh'],
    method: 'account',
    roles: ['ADMIN'],
    user: null,
  },
  certificates: ['nic-internal'],
  enterprise: false,
  isTrusted: false,
  supportLevel: {
    level: 'standard',
  },
};
