/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OVHcloud API specification
 * Specification for OVHcloud API
 * OpenAPI spec version: 1.0
 */
export type GetLicenseCpanelServiceNameTasksParams = {
/**
 * Filter the value of action property (=)
 */
action?: LicenseActionTypeOVH;
/**
 * Filter the value of status property (=)
 */
status?: LicenseTaskStateEnumOVH;
};

export type PostLicenseCpanelServiceNameChangeIpBody = {
  /** The Ip on which you want to move this license */
  destinationIp: Ipv4OVH;
};

export type GetLicenseCpanelServiceNameCanLicenseBeMovedToParams = {
/**
 * The Ip on which you want to move this license
 */
destinationIp: Ipv4OVH;
};

export type GetLicenseCpanelOrderableVersionsParams = {
/**
 * Your license Ip
 */
ip: Ipv4OVH;
};

export type GetLicenseCpanelParams = {
/**
 * Filter resources on IAM tags
 */
iamTags?: {[key: string]: IamResourceTagFilterOVH[]};
};

/**
 * Time (e.g., 15:04:05)
 */
export type TimeOVH = string;

/**
 * All reasons you can provide for a service termination
 */
export type ServiceTerminationReasonEnumOVH = typeof ServiceTerminationReasonEnumOVH[keyof typeof ServiceTerminationReasonEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTerminationReasonEnumOVH = {
  FEATURES_DONT_SUIT_ME: 'FEATURES_DONT_SUIT_ME',
  LACK_OF_PERFORMANCES: 'LACK_OF_PERFORMANCES',
  MIGRATED_TO_ANOTHER_OVH_PRODUCT: 'MIGRATED_TO_ANOTHER_OVH_PRODUCT',
  MIGRATED_TO_COMPETITOR: 'MIGRATED_TO_COMPETITOR',
  NOT_ENOUGH_RECOGNITION: 'NOT_ENOUGH_RECOGNITION',
  NOT_NEEDED_ANYMORE: 'NOT_NEEDED_ANYMORE',
  NOT_RELIABLE: 'NOT_RELIABLE',
  NO_ANSWER: 'NO_ANSWER',
  OTHER: 'OTHER',
  PRODUCT_DIMENSION_DONT_SUIT_ME: 'PRODUCT_DIMENSION_DONT_SUIT_ME',
  PRODUCT_TOOLS_DONT_SUIT_ME: 'PRODUCT_TOOLS_DONT_SUIT_ME',
  TOO_EXPENSIVE: 'TOO_EXPENSIVE',
  TOO_HARD_TO_USE: 'TOO_HARD_TO_USE',
  UNSATIFIED_BY_CUSTOMER_SUPPORT: 'UNSATIFIED_BY_CUSTOMER_SUPPORT',
} as const;

/**
 * All future uses you can provide for a service termination
 */
export type ServiceTerminationFutureUseEnumOVH = typeof ServiceTerminationFutureUseEnumOVH[keyof typeof ServiceTerminationFutureUseEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTerminationFutureUseEnumOVH = {
  NOT_REPLACING_SERVICE: 'NOT_REPLACING_SERVICE',
  OTHER: 'OTHER',
  SUBSCRIBE_AN_OTHER_SERVICE: 'SUBSCRIBE_AN_OTHER_SERVICE',
  SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR: 'SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR',
  SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR: 'SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR',
} as const;

export type PostLicenseCpanelServiceNameConfirmTerminationBody = {
  /** Commentary about your termination request */
  commentary?: string;
  /** What next after your termination request */
  futureUse?: ServiceTerminationFutureUseEnumOVH;
  /** Reason of your termination request */
  reason?: ServiceTerminationReasonEnumOVH;
  /** The termination token sent by email to the admin contact */
  token: string;
};

export type ServiceStateEnumOVH = typeof ServiceStateEnumOVH[keyof typeof ServiceStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceStateEnumOVH = {
  autorenewInProgress: 'autorenewInProgress',
  expired: 'expired',
  inCreation: 'inCreation',
  ok: 'ok',
  pendingDebt: 'pendingDebt',
  unPaid: 'unPaid',
} as const;

/**
 * Detailed renewal type of a service
 */
export type ServiceRenewalTypeEnumOVH = typeof ServiceRenewalTypeEnumOVH[keyof typeof ServiceRenewalTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRenewalTypeEnumOVH = {
  automaticForcedProduct: 'automaticForcedProduct',
  automaticV2012: 'automaticV2012',
  automaticV2014: 'automaticV2014',
  automaticV2016: 'automaticV2016',
  automaticV2024: 'automaticV2024',
  manual: 'manual',
  oneShot: 'oneShot',
  option: 'option',
} as const;

/**
 * Details about a Service
 */
export interface ServicesServiceOVH {
  /** Indicates that the service can be set up to be deleted at expiration */
  readonly canDeleteAtExpiration?: boolean;
  readonly contactAdmin?: string;
  readonly contactBilling?: string;
  readonly contactTech?: string;
  readonly creation?: string;
  readonly domain?: string;
  /** @nullable */
  readonly engagedUpTo?: string | null;
  readonly expiration?: string;
  /**
   * All the possible renew period of your service in month
   * @nullable
   */
  readonly possibleRenewPeriod?: readonly number[] | null;
  /**
   * Way of handling the renew
   * @nullable
   */
  renew?: ServicesServiceOVHRenew;
  readonly renewalType?: ServiceRenewalTypeEnumOVH;
  readonly serviceId?: number;
  readonly status?: ServiceStateEnumOVH;
}

/**
 * Map a possible renew for a specific service
 */
export interface ServiceRenewTypeOVH {
  /** The service is automatically renewed */
  automatic?: boolean;
  /** The service will be deleted at expiration */
  deleteAtExpiration?: boolean;
  /** The service forced to be renewed */
  forced?: boolean;
  /**
   * The service needs to be manually renewed and paid
   * @nullable
   */
  manualPayment?: boolean | null;
  /**
   * period of renew in month
   * @nullable
   */
  period?: number | null;
}

/**
 * Way of handling the renew
 * @nullable
 */
export type ServicesServiceOVHRenew = ServiceRenewTypeOVH | null;

/**
 * Phone number
 */
export type PhoneNumberOVH = string;

/**
 * MAC address (e.g., 2001:4860:4860::8844)
 */
export type MacAddressOVH = string;

/**
 * IAM resource metadata
 * @nullable
 */
export type LicenseCpanelCpanelWithIAMOVHIam = IamResourceMetadataOVH | null;

/**
 * All states a license Task can be in
 */
export type LicenseTaskStateEnumOVH = typeof LicenseTaskStateEnumOVH[keyof typeof LicenseTaskStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseTaskStateEnumOVH = {
  cancelled: 'cancelled',
  doing: 'doing',
  done: 'done',
  error: 'error',
  todo: 'todo',
} as const;

/**
 * licenses Todos
 */
export interface LicenseTaskOVH {
  /** This Task description */
  readonly action?: LicenseActionTypeOVH;
  /**
   * When was this Task done
   * @nullable
   */
  readonly doneDate?: string | null;
  /** The last time this Task was updated */
  readonly lastUpdate?: string;
  /** This Task name */
  readonly name?: string;
  /** Current Taks status */
  readonly status?: LicenseTaskStateEnumOVH;
  /** This Task id */
  readonly taskId?: number;
  /** When was this Task created */
  readonly todoDate?: string;
}

/**
 * All states a license can be in
 */
export type LicenseStateEnumOVH = typeof LicenseStateEnumOVH[keyof typeof LicenseStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseStateEnumOVH = {
  ok: 'ok',
  released: 'released',
  terminated: 'terminated',
  toDeliver: 'toDeliver',
} as const;

/**
 * All versions available for Cpanel products
 */
export type LicenseOrderableCpanelVersionEnumOVH = typeof LicenseOrderableCpanelVersionEnumOVH[keyof typeof LicenseOrderableCpanelVersionEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseOrderableCpanelVersionEnumOVH = {
  VERSION_11_FOR_LINUX: 'VERSION_11_FOR_LINUX',
  VERSION_11_FOR_VIRTUOZZO: 'VERSION_11_FOR_VIRTUOZZO',
  VERSION_11_FOR_VPS: 'VERSION_11_FOR_VPS',
  'cpanel-license-admin-cloud': 'cpanel-license-admin-cloud',
  'cpanel-license-plus-cloud': 'cpanel-license-plus-cloud',
  'cpanel-license-premier-cloud-100-accounts': 'cpanel-license-premier-cloud-100-accounts',
  'cpanel-license-premier-cloud-1000-accounts': 'cpanel-license-premier-cloud-1000-accounts',
  'cpanel-license-premier-cloud-10000-accounts': 'cpanel-license-premier-cloud-10000-accounts',
  'cpanel-license-premier-cloud-1100-accounts': 'cpanel-license-premier-cloud-1100-accounts',
  'cpanel-license-premier-cloud-1200-accounts': 'cpanel-license-premier-cloud-1200-accounts',
  'cpanel-license-premier-cloud-1300-accounts': 'cpanel-license-premier-cloud-1300-accounts',
  'cpanel-license-premier-cloud-1400-accounts': 'cpanel-license-premier-cloud-1400-accounts',
  'cpanel-license-premier-cloud-150-accounts': 'cpanel-license-premier-cloud-150-accounts',
  'cpanel-license-premier-cloud-1500-accounts': 'cpanel-license-premier-cloud-1500-accounts',
  'cpanel-license-premier-cloud-1600-accounts': 'cpanel-license-premier-cloud-1600-accounts',
  'cpanel-license-premier-cloud-1700-accounts': 'cpanel-license-premier-cloud-1700-accounts',
  'cpanel-license-premier-cloud-1800-accounts': 'cpanel-license-premier-cloud-1800-accounts',
  'cpanel-license-premier-cloud-1900-accounts': 'cpanel-license-premier-cloud-1900-accounts',
  'cpanel-license-premier-cloud-200-accounts': 'cpanel-license-premier-cloud-200-accounts',
  'cpanel-license-premier-cloud-2000-accounts': 'cpanel-license-premier-cloud-2000-accounts',
  'cpanel-license-premier-cloud-2100-accounts': 'cpanel-license-premier-cloud-2100-accounts',
  'cpanel-license-premier-cloud-2200-accounts': 'cpanel-license-premier-cloud-2200-accounts',
  'cpanel-license-premier-cloud-2300-accounts': 'cpanel-license-premier-cloud-2300-accounts',
  'cpanel-license-premier-cloud-2400-accounts': 'cpanel-license-premier-cloud-2400-accounts',
  'cpanel-license-premier-cloud-250-accounts': 'cpanel-license-premier-cloud-250-accounts',
  'cpanel-license-premier-cloud-2500-accounts': 'cpanel-license-premier-cloud-2500-accounts',
  'cpanel-license-premier-cloud-2600-accounts': 'cpanel-license-premier-cloud-2600-accounts',
  'cpanel-license-premier-cloud-2700-accounts': 'cpanel-license-premier-cloud-2700-accounts',
  'cpanel-license-premier-cloud-2800-accounts': 'cpanel-license-premier-cloud-2800-accounts',
  'cpanel-license-premier-cloud-2900-accounts': 'cpanel-license-premier-cloud-2900-accounts',
  'cpanel-license-premier-cloud-300-accounts': 'cpanel-license-premier-cloud-300-accounts',
  'cpanel-license-premier-cloud-3000-accounts': 'cpanel-license-premier-cloud-3000-accounts',
  'cpanel-license-premier-cloud-3100-accounts': 'cpanel-license-premier-cloud-3100-accounts',
  'cpanel-license-premier-cloud-3200-accounts': 'cpanel-license-premier-cloud-3200-accounts',
  'cpanel-license-premier-cloud-3300-accounts': 'cpanel-license-premier-cloud-3300-accounts',
  'cpanel-license-premier-cloud-3400-accounts': 'cpanel-license-premier-cloud-3400-accounts',
  'cpanel-license-premier-cloud-3500-accounts': 'cpanel-license-premier-cloud-3500-accounts',
  'cpanel-license-premier-cloud-3600-accounts': 'cpanel-license-premier-cloud-3600-accounts',
  'cpanel-license-premier-cloud-3700-accounts': 'cpanel-license-premier-cloud-3700-accounts',
  'cpanel-license-premier-cloud-3800-accounts': 'cpanel-license-premier-cloud-3800-accounts',
  'cpanel-license-premier-cloud-3900-accounts': 'cpanel-license-premier-cloud-3900-accounts',
  'cpanel-license-premier-cloud-400-accounts': 'cpanel-license-premier-cloud-400-accounts',
  'cpanel-license-premier-cloud-4000-accounts': 'cpanel-license-premier-cloud-4000-accounts',
  'cpanel-license-premier-cloud-4100-accounts': 'cpanel-license-premier-cloud-4100-accounts',
  'cpanel-license-premier-cloud-4200-accounts': 'cpanel-license-premier-cloud-4200-accounts',
  'cpanel-license-premier-cloud-4300-accounts': 'cpanel-license-premier-cloud-4300-accounts',
  'cpanel-license-premier-cloud-4400-accounts': 'cpanel-license-premier-cloud-4400-accounts',
  'cpanel-license-premier-cloud-4500-accounts': 'cpanel-license-premier-cloud-4500-accounts',
  'cpanel-license-premier-cloud-4600-accounts': 'cpanel-license-premier-cloud-4600-accounts',
  'cpanel-license-premier-cloud-4700-accounts': 'cpanel-license-premier-cloud-4700-accounts',
  'cpanel-license-premier-cloud-4800-accounts': 'cpanel-license-premier-cloud-4800-accounts',
  'cpanel-license-premier-cloud-4900-accounts': 'cpanel-license-premier-cloud-4900-accounts',
  'cpanel-license-premier-cloud-500-accounts': 'cpanel-license-premier-cloud-500-accounts',
  'cpanel-license-premier-cloud-5000-accounts': 'cpanel-license-premier-cloud-5000-accounts',
  'cpanel-license-premier-cloud-5100-accounts': 'cpanel-license-premier-cloud-5100-accounts',
  'cpanel-license-premier-cloud-5200-accounts': 'cpanel-license-premier-cloud-5200-accounts',
  'cpanel-license-premier-cloud-5300-accounts': 'cpanel-license-premier-cloud-5300-accounts',
  'cpanel-license-premier-cloud-5400-accounts': 'cpanel-license-premier-cloud-5400-accounts',
  'cpanel-license-premier-cloud-5500-accounts': 'cpanel-license-premier-cloud-5500-accounts',
  'cpanel-license-premier-cloud-5600-accounts': 'cpanel-license-premier-cloud-5600-accounts',
  'cpanel-license-premier-cloud-5700-accounts': 'cpanel-license-premier-cloud-5700-accounts',
  'cpanel-license-premier-cloud-5800-accounts': 'cpanel-license-premier-cloud-5800-accounts',
  'cpanel-license-premier-cloud-5900-accounts': 'cpanel-license-premier-cloud-5900-accounts',
  'cpanel-license-premier-cloud-600-accounts': 'cpanel-license-premier-cloud-600-accounts',
  'cpanel-license-premier-cloud-6000-accounts': 'cpanel-license-premier-cloud-6000-accounts',
  'cpanel-license-premier-cloud-6100-accounts': 'cpanel-license-premier-cloud-6100-accounts',
  'cpanel-license-premier-cloud-6200-accounts': 'cpanel-license-premier-cloud-6200-accounts',
  'cpanel-license-premier-cloud-6300-accounts': 'cpanel-license-premier-cloud-6300-accounts',
  'cpanel-license-premier-cloud-6400-accounts': 'cpanel-license-premier-cloud-6400-accounts',
  'cpanel-license-premier-cloud-6500-accounts': 'cpanel-license-premier-cloud-6500-accounts',
  'cpanel-license-premier-cloud-6600-accounts': 'cpanel-license-premier-cloud-6600-accounts',
  'cpanel-license-premier-cloud-6700-accounts': 'cpanel-license-premier-cloud-6700-accounts',
  'cpanel-license-premier-cloud-6800-accounts': 'cpanel-license-premier-cloud-6800-accounts',
  'cpanel-license-premier-cloud-6900-accounts': 'cpanel-license-premier-cloud-6900-accounts',
  'cpanel-license-premier-cloud-700-accounts': 'cpanel-license-premier-cloud-700-accounts',
  'cpanel-license-premier-cloud-7000-accounts': 'cpanel-license-premier-cloud-7000-accounts',
  'cpanel-license-premier-cloud-7100-accounts': 'cpanel-license-premier-cloud-7100-accounts',
  'cpanel-license-premier-cloud-7200-accounts': 'cpanel-license-premier-cloud-7200-accounts',
  'cpanel-license-premier-cloud-7300-accounts': 'cpanel-license-premier-cloud-7300-accounts',
  'cpanel-license-premier-cloud-7400-accounts': 'cpanel-license-premier-cloud-7400-accounts',
  'cpanel-license-premier-cloud-7500-accounts': 'cpanel-license-premier-cloud-7500-accounts',
  'cpanel-license-premier-cloud-7600-accounts': 'cpanel-license-premier-cloud-7600-accounts',
  'cpanel-license-premier-cloud-7700-accounts': 'cpanel-license-premier-cloud-7700-accounts',
  'cpanel-license-premier-cloud-7800-accounts': 'cpanel-license-premier-cloud-7800-accounts',
  'cpanel-license-premier-cloud-7900-accounts': 'cpanel-license-premier-cloud-7900-accounts',
  'cpanel-license-premier-cloud-800-accounts': 'cpanel-license-premier-cloud-800-accounts',
  'cpanel-license-premier-cloud-8000-accounts': 'cpanel-license-premier-cloud-8000-accounts',
  'cpanel-license-premier-cloud-8100-accounts': 'cpanel-license-premier-cloud-8100-accounts',
  'cpanel-license-premier-cloud-8200-accounts': 'cpanel-license-premier-cloud-8200-accounts',
  'cpanel-license-premier-cloud-8300-accounts': 'cpanel-license-premier-cloud-8300-accounts',
  'cpanel-license-premier-cloud-8400-accounts': 'cpanel-license-premier-cloud-8400-accounts',
  'cpanel-license-premier-cloud-8500-accounts': 'cpanel-license-premier-cloud-8500-accounts',
  'cpanel-license-premier-cloud-8600-accounts': 'cpanel-license-premier-cloud-8600-accounts',
  'cpanel-license-premier-cloud-8700-accounts': 'cpanel-license-premier-cloud-8700-accounts',
  'cpanel-license-premier-cloud-8800-accounts': 'cpanel-license-premier-cloud-8800-accounts',
  'cpanel-license-premier-cloud-8900-accounts': 'cpanel-license-premier-cloud-8900-accounts',
  'cpanel-license-premier-cloud-900-accounts': 'cpanel-license-premier-cloud-900-accounts',
  'cpanel-license-premier-cloud-9000-accounts': 'cpanel-license-premier-cloud-9000-accounts',
  'cpanel-license-premier-cloud-9100-accounts': 'cpanel-license-premier-cloud-9100-accounts',
  'cpanel-license-premier-cloud-9200-accounts': 'cpanel-license-premier-cloud-9200-accounts',
  'cpanel-license-premier-cloud-9300-accounts': 'cpanel-license-premier-cloud-9300-accounts',
  'cpanel-license-premier-cloud-9400-accounts': 'cpanel-license-premier-cloud-9400-accounts',
  'cpanel-license-premier-cloud-9500-accounts': 'cpanel-license-premier-cloud-9500-accounts',
  'cpanel-license-premier-cloud-9600-accounts': 'cpanel-license-premier-cloud-9600-accounts',
  'cpanel-license-premier-cloud-9700-accounts': 'cpanel-license-premier-cloud-9700-accounts',
  'cpanel-license-premier-cloud-9800-accounts': 'cpanel-license-premier-cloud-9800-accounts',
  'cpanel-license-premier-cloud-9900-accounts': 'cpanel-license-premier-cloud-9900-accounts',
  'cpanel-license-premier-metal-100-accounts': 'cpanel-license-premier-metal-100-accounts',
  'cpanel-license-premier-metal-1000-accounts': 'cpanel-license-premier-metal-1000-accounts',
  'cpanel-license-premier-metal-10000-accounts': 'cpanel-license-premier-metal-10000-accounts',
  'cpanel-license-premier-metal-1100-accounts': 'cpanel-license-premier-metal-1100-accounts',
  'cpanel-license-premier-metal-1200-accounts': 'cpanel-license-premier-metal-1200-accounts',
  'cpanel-license-premier-metal-1300-accounts': 'cpanel-license-premier-metal-1300-accounts',
  'cpanel-license-premier-metal-1400-accounts': 'cpanel-license-premier-metal-1400-accounts',
  'cpanel-license-premier-metal-150-accounts': 'cpanel-license-premier-metal-150-accounts',
  'cpanel-license-premier-metal-1500-accounts': 'cpanel-license-premier-metal-1500-accounts',
  'cpanel-license-premier-metal-1600-accounts': 'cpanel-license-premier-metal-1600-accounts',
  'cpanel-license-premier-metal-1700-accounts': 'cpanel-license-premier-metal-1700-accounts',
  'cpanel-license-premier-metal-1800-accounts': 'cpanel-license-premier-metal-1800-accounts',
  'cpanel-license-premier-metal-1900-accounts': 'cpanel-license-premier-metal-1900-accounts',
  'cpanel-license-premier-metal-200-accounts': 'cpanel-license-premier-metal-200-accounts',
  'cpanel-license-premier-metal-2000-accounts': 'cpanel-license-premier-metal-2000-accounts',
  'cpanel-license-premier-metal-2100-accounts': 'cpanel-license-premier-metal-2100-accounts',
  'cpanel-license-premier-metal-2200-accounts': 'cpanel-license-premier-metal-2200-accounts',
  'cpanel-license-premier-metal-2300-accounts': 'cpanel-license-premier-metal-2300-accounts',
  'cpanel-license-premier-metal-2400-accounts': 'cpanel-license-premier-metal-2400-accounts',
  'cpanel-license-premier-metal-250-accounts': 'cpanel-license-premier-metal-250-accounts',
  'cpanel-license-premier-metal-2500-accounts': 'cpanel-license-premier-metal-2500-accounts',
  'cpanel-license-premier-metal-2600-accounts': 'cpanel-license-premier-metal-2600-accounts',
  'cpanel-license-premier-metal-2700-accounts': 'cpanel-license-premier-metal-2700-accounts',
  'cpanel-license-premier-metal-2800-accounts': 'cpanel-license-premier-metal-2800-accounts',
  'cpanel-license-premier-metal-2900-accounts': 'cpanel-license-premier-metal-2900-accounts',
  'cpanel-license-premier-metal-300-accounts': 'cpanel-license-premier-metal-300-accounts',
  'cpanel-license-premier-metal-3000-accounts': 'cpanel-license-premier-metal-3000-accounts',
  'cpanel-license-premier-metal-3100-accounts': 'cpanel-license-premier-metal-3100-accounts',
  'cpanel-license-premier-metal-3200-accounts': 'cpanel-license-premier-metal-3200-accounts',
  'cpanel-license-premier-metal-3300-accounts': 'cpanel-license-premier-metal-3300-accounts',
  'cpanel-license-premier-metal-3400-accounts': 'cpanel-license-premier-metal-3400-accounts',
  'cpanel-license-premier-metal-3500-accounts': 'cpanel-license-premier-metal-3500-accounts',
  'cpanel-license-premier-metal-3600-accounts': 'cpanel-license-premier-metal-3600-accounts',
  'cpanel-license-premier-metal-3700-accounts': 'cpanel-license-premier-metal-3700-accounts',
  'cpanel-license-premier-metal-3800-accounts': 'cpanel-license-premier-metal-3800-accounts',
  'cpanel-license-premier-metal-3900-accounts': 'cpanel-license-premier-metal-3900-accounts',
  'cpanel-license-premier-metal-400-accounts': 'cpanel-license-premier-metal-400-accounts',
  'cpanel-license-premier-metal-4000-accounts': 'cpanel-license-premier-metal-4000-accounts',
  'cpanel-license-premier-metal-4100-accounts': 'cpanel-license-premier-metal-4100-accounts',
  'cpanel-license-premier-metal-4200-accounts': 'cpanel-license-premier-metal-4200-accounts',
  'cpanel-license-premier-metal-4300-accounts': 'cpanel-license-premier-metal-4300-accounts',
  'cpanel-license-premier-metal-4400-accounts': 'cpanel-license-premier-metal-4400-accounts',
  'cpanel-license-premier-metal-4500-accounts': 'cpanel-license-premier-metal-4500-accounts',
  'cpanel-license-premier-metal-4600-accounts': 'cpanel-license-premier-metal-4600-accounts',
  'cpanel-license-premier-metal-4700-accounts': 'cpanel-license-premier-metal-4700-accounts',
  'cpanel-license-premier-metal-4800-accounts': 'cpanel-license-premier-metal-4800-accounts',
  'cpanel-license-premier-metal-4900-accounts': 'cpanel-license-premier-metal-4900-accounts',
  'cpanel-license-premier-metal-500-accounts': 'cpanel-license-premier-metal-500-accounts',
  'cpanel-license-premier-metal-5000-accounts': 'cpanel-license-premier-metal-5000-accounts',
  'cpanel-license-premier-metal-5100-accounts': 'cpanel-license-premier-metal-5100-accounts',
  'cpanel-license-premier-metal-5200-accounts': 'cpanel-license-premier-metal-5200-accounts',
  'cpanel-license-premier-metal-5300-accounts': 'cpanel-license-premier-metal-5300-accounts',
  'cpanel-license-premier-metal-5400-accounts': 'cpanel-license-premier-metal-5400-accounts',
  'cpanel-license-premier-metal-5500-accounts': 'cpanel-license-premier-metal-5500-accounts',
  'cpanel-license-premier-metal-5600-accounts': 'cpanel-license-premier-metal-5600-accounts',
  'cpanel-license-premier-metal-5700-accounts': 'cpanel-license-premier-metal-5700-accounts',
  'cpanel-license-premier-metal-5800-accounts': 'cpanel-license-premier-metal-5800-accounts',
  'cpanel-license-premier-metal-5900-accounts': 'cpanel-license-premier-metal-5900-accounts',
  'cpanel-license-premier-metal-600-accounts': 'cpanel-license-premier-metal-600-accounts',
  'cpanel-license-premier-metal-6000-accounts': 'cpanel-license-premier-metal-6000-accounts',
  'cpanel-license-premier-metal-6100-accounts': 'cpanel-license-premier-metal-6100-accounts',
  'cpanel-license-premier-metal-6200-accounts': 'cpanel-license-premier-metal-6200-accounts',
  'cpanel-license-premier-metal-6300-accounts': 'cpanel-license-premier-metal-6300-accounts',
  'cpanel-license-premier-metal-6400-accounts': 'cpanel-license-premier-metal-6400-accounts',
  'cpanel-license-premier-metal-6500-accounts': 'cpanel-license-premier-metal-6500-accounts',
  'cpanel-license-premier-metal-6600-accounts': 'cpanel-license-premier-metal-6600-accounts',
  'cpanel-license-premier-metal-6700-accounts': 'cpanel-license-premier-metal-6700-accounts',
  'cpanel-license-premier-metal-6800-accounts': 'cpanel-license-premier-metal-6800-accounts',
  'cpanel-license-premier-metal-6900-accounts': 'cpanel-license-premier-metal-6900-accounts',
  'cpanel-license-premier-metal-700-accounts': 'cpanel-license-premier-metal-700-accounts',
  'cpanel-license-premier-metal-7000-accounts': 'cpanel-license-premier-metal-7000-accounts',
  'cpanel-license-premier-metal-7100-accounts': 'cpanel-license-premier-metal-7100-accounts',
  'cpanel-license-premier-metal-7200-accounts': 'cpanel-license-premier-metal-7200-accounts',
  'cpanel-license-premier-metal-7300-accounts': 'cpanel-license-premier-metal-7300-accounts',
  'cpanel-license-premier-metal-7400-accounts': 'cpanel-license-premier-metal-7400-accounts',
  'cpanel-license-premier-metal-7500-accounts': 'cpanel-license-premier-metal-7500-accounts',
  'cpanel-license-premier-metal-7600-accounts': 'cpanel-license-premier-metal-7600-accounts',
  'cpanel-license-premier-metal-7700-accounts': 'cpanel-license-premier-metal-7700-accounts',
  'cpanel-license-premier-metal-7800-accounts': 'cpanel-license-premier-metal-7800-accounts',
  'cpanel-license-premier-metal-7900-accounts': 'cpanel-license-premier-metal-7900-accounts',
  'cpanel-license-premier-metal-800-accounts': 'cpanel-license-premier-metal-800-accounts',
  'cpanel-license-premier-metal-8000-accounts': 'cpanel-license-premier-metal-8000-accounts',
  'cpanel-license-premier-metal-8100-accounts': 'cpanel-license-premier-metal-8100-accounts',
  'cpanel-license-premier-metal-8200-accounts': 'cpanel-license-premier-metal-8200-accounts',
  'cpanel-license-premier-metal-8300-accounts': 'cpanel-license-premier-metal-8300-accounts',
  'cpanel-license-premier-metal-8400-accounts': 'cpanel-license-premier-metal-8400-accounts',
  'cpanel-license-premier-metal-8500-accounts': 'cpanel-license-premier-metal-8500-accounts',
  'cpanel-license-premier-metal-8600-accounts': 'cpanel-license-premier-metal-8600-accounts',
  'cpanel-license-premier-metal-8700-accounts': 'cpanel-license-premier-metal-8700-accounts',
  'cpanel-license-premier-metal-8800-accounts': 'cpanel-license-premier-metal-8800-accounts',
  'cpanel-license-premier-metal-8900-accounts': 'cpanel-license-premier-metal-8900-accounts',
  'cpanel-license-premier-metal-900-accounts': 'cpanel-license-premier-metal-900-accounts',
  'cpanel-license-premier-metal-9000-accounts': 'cpanel-license-premier-metal-9000-accounts',
  'cpanel-license-premier-metal-9100-accounts': 'cpanel-license-premier-metal-9100-accounts',
  'cpanel-license-premier-metal-9200-accounts': 'cpanel-license-premier-metal-9200-accounts',
  'cpanel-license-premier-metal-9300-accounts': 'cpanel-license-premier-metal-9300-accounts',
  'cpanel-license-premier-metal-9400-accounts': 'cpanel-license-premier-metal-9400-accounts',
  'cpanel-license-premier-metal-9500-accounts': 'cpanel-license-premier-metal-9500-accounts',
  'cpanel-license-premier-metal-9600-accounts': 'cpanel-license-premier-metal-9600-accounts',
  'cpanel-license-premier-metal-9700-accounts': 'cpanel-license-premier-metal-9700-accounts',
  'cpanel-license-premier-metal-9800-accounts': 'cpanel-license-premier-metal-9800-accounts',
  'cpanel-license-premier-metal-9900-accounts': 'cpanel-license-premier-metal-9900-accounts',
  'cpanel-license-pro-cloud': 'cpanel-license-pro-cloud',
  'cpanel-license-solo-cloud': 'cpanel-license-solo-cloud',
  'cpanel-license-solo-metal': 'cpanel-license-solo-metal',
  'cpanel-license-version-11': 'cpanel-license-version-11',
  'cpanel-license-version-11-for-virtuozzo': 'cpanel-license-version-11-for-virtuozzo',
  'cpanel-license-version-11-for-vps': 'cpanel-license-version-11-for-vps',
  'version-admin-cloud': 'version-admin-cloud',
  'version-plus-cloud': 'version-plus-cloud',
  'version-premier-cloud-100': 'version-premier-cloud-100',
  'version-premier-cloud-1000': 'version-premier-cloud-1000',
  'version-premier-cloud-10000': 'version-premier-cloud-10000',
  'version-premier-cloud-1100': 'version-premier-cloud-1100',
  'version-premier-cloud-1200': 'version-premier-cloud-1200',
  'version-premier-cloud-1300': 'version-premier-cloud-1300',
  'version-premier-cloud-1400': 'version-premier-cloud-1400',
  'version-premier-cloud-150': 'version-premier-cloud-150',
  'version-premier-cloud-1500': 'version-premier-cloud-1500',
  'version-premier-cloud-1600': 'version-premier-cloud-1600',
  'version-premier-cloud-1700': 'version-premier-cloud-1700',
  'version-premier-cloud-1800': 'version-premier-cloud-1800',
  'version-premier-cloud-1900': 'version-premier-cloud-1900',
  'version-premier-cloud-200': 'version-premier-cloud-200',
  'version-premier-cloud-2000': 'version-premier-cloud-2000',
  'version-premier-cloud-2100': 'version-premier-cloud-2100',
  'version-premier-cloud-2200': 'version-premier-cloud-2200',
  'version-premier-cloud-2300': 'version-premier-cloud-2300',
  'version-premier-cloud-2400': 'version-premier-cloud-2400',
  'version-premier-cloud-250': 'version-premier-cloud-250',
  'version-premier-cloud-2500': 'version-premier-cloud-2500',
  'version-premier-cloud-2600': 'version-premier-cloud-2600',
  'version-premier-cloud-2700': 'version-premier-cloud-2700',
  'version-premier-cloud-2800': 'version-premier-cloud-2800',
  'version-premier-cloud-2900': 'version-premier-cloud-2900',
  'version-premier-cloud-300': 'version-premier-cloud-300',
  'version-premier-cloud-3000': 'version-premier-cloud-3000',
  'version-premier-cloud-3100': 'version-premier-cloud-3100',
  'version-premier-cloud-3200': 'version-premier-cloud-3200',
  'version-premier-cloud-3300': 'version-premier-cloud-3300',
  'version-premier-cloud-3400': 'version-premier-cloud-3400',
  'version-premier-cloud-3500': 'version-premier-cloud-3500',
  'version-premier-cloud-3600': 'version-premier-cloud-3600',
  'version-premier-cloud-3700': 'version-premier-cloud-3700',
  'version-premier-cloud-3800': 'version-premier-cloud-3800',
  'version-premier-cloud-3900': 'version-premier-cloud-3900',
  'version-premier-cloud-400': 'version-premier-cloud-400',
  'version-premier-cloud-4000': 'version-premier-cloud-4000',
  'version-premier-cloud-4100': 'version-premier-cloud-4100',
  'version-premier-cloud-4200': 'version-premier-cloud-4200',
  'version-premier-cloud-4300': 'version-premier-cloud-4300',
  'version-premier-cloud-4400': 'version-premier-cloud-4400',
  'version-premier-cloud-4500': 'version-premier-cloud-4500',
  'version-premier-cloud-4600': 'version-premier-cloud-4600',
  'version-premier-cloud-4700': 'version-premier-cloud-4700',
  'version-premier-cloud-4800': 'version-premier-cloud-4800',
  'version-premier-cloud-4900': 'version-premier-cloud-4900',
  'version-premier-cloud-500': 'version-premier-cloud-500',
  'version-premier-cloud-5000': 'version-premier-cloud-5000',
  'version-premier-cloud-5100': 'version-premier-cloud-5100',
  'version-premier-cloud-5200': 'version-premier-cloud-5200',
  'version-premier-cloud-5300': 'version-premier-cloud-5300',
  'version-premier-cloud-5400': 'version-premier-cloud-5400',
  'version-premier-cloud-5500': 'version-premier-cloud-5500',
  'version-premier-cloud-5600': 'version-premier-cloud-5600',
  'version-premier-cloud-5700': 'version-premier-cloud-5700',
  'version-premier-cloud-5800': 'version-premier-cloud-5800',
  'version-premier-cloud-5900': 'version-premier-cloud-5900',
  'version-premier-cloud-600': 'version-premier-cloud-600',
  'version-premier-cloud-6000': 'version-premier-cloud-6000',
  'version-premier-cloud-6100': 'version-premier-cloud-6100',
  'version-premier-cloud-6200': 'version-premier-cloud-6200',
  'version-premier-cloud-6300': 'version-premier-cloud-6300',
  'version-premier-cloud-6400': 'version-premier-cloud-6400',
  'version-premier-cloud-6500': 'version-premier-cloud-6500',
  'version-premier-cloud-6600': 'version-premier-cloud-6600',
  'version-premier-cloud-6700': 'version-premier-cloud-6700',
  'version-premier-cloud-6800': 'version-premier-cloud-6800',
  'version-premier-cloud-6900': 'version-premier-cloud-6900',
  'version-premier-cloud-700': 'version-premier-cloud-700',
  'version-premier-cloud-7000': 'version-premier-cloud-7000',
  'version-premier-cloud-7100': 'version-premier-cloud-7100',
  'version-premier-cloud-7200': 'version-premier-cloud-7200',
  'version-premier-cloud-7300': 'version-premier-cloud-7300',
  'version-premier-cloud-7400': 'version-premier-cloud-7400',
  'version-premier-cloud-7500': 'version-premier-cloud-7500',
  'version-premier-cloud-7600': 'version-premier-cloud-7600',
  'version-premier-cloud-7700': 'version-premier-cloud-7700',
  'version-premier-cloud-7800': 'version-premier-cloud-7800',
  'version-premier-cloud-7900': 'version-premier-cloud-7900',
  'version-premier-cloud-800': 'version-premier-cloud-800',
  'version-premier-cloud-8000': 'version-premier-cloud-8000',
  'version-premier-cloud-8100': 'version-premier-cloud-8100',
  'version-premier-cloud-8200': 'version-premier-cloud-8200',
  'version-premier-cloud-8300': 'version-premier-cloud-8300',
  'version-premier-cloud-8400': 'version-premier-cloud-8400',
  'version-premier-cloud-8500': 'version-premier-cloud-8500',
  'version-premier-cloud-8600': 'version-premier-cloud-8600',
  'version-premier-cloud-8700': 'version-premier-cloud-8700',
  'version-premier-cloud-8800': 'version-premier-cloud-8800',
  'version-premier-cloud-8900': 'version-premier-cloud-8900',
  'version-premier-cloud-900': 'version-premier-cloud-900',
  'version-premier-cloud-9000': 'version-premier-cloud-9000',
  'version-premier-cloud-9100': 'version-premier-cloud-9100',
  'version-premier-cloud-9200': 'version-premier-cloud-9200',
  'version-premier-cloud-9300': 'version-premier-cloud-9300',
  'version-premier-cloud-9400': 'version-premier-cloud-9400',
  'version-premier-cloud-9500': 'version-premier-cloud-9500',
  'version-premier-cloud-9600': 'version-premier-cloud-9600',
  'version-premier-cloud-9700': 'version-premier-cloud-9700',
  'version-premier-cloud-9800': 'version-premier-cloud-9800',
  'version-premier-cloud-9900': 'version-premier-cloud-9900',
  'version-premier-metal-100': 'version-premier-metal-100',
  'version-premier-metal-1000': 'version-premier-metal-1000',
  'version-premier-metal-10000': 'version-premier-metal-10000',
  'version-premier-metal-1100': 'version-premier-metal-1100',
  'version-premier-metal-1200': 'version-premier-metal-1200',
  'version-premier-metal-1300': 'version-premier-metal-1300',
  'version-premier-metal-1400': 'version-premier-metal-1400',
  'version-premier-metal-150': 'version-premier-metal-150',
  'version-premier-metal-1500': 'version-premier-metal-1500',
  'version-premier-metal-1600': 'version-premier-metal-1600',
  'version-premier-metal-1700': 'version-premier-metal-1700',
  'version-premier-metal-1800': 'version-premier-metal-1800',
  'version-premier-metal-1900': 'version-premier-metal-1900',
  'version-premier-metal-200': 'version-premier-metal-200',
  'version-premier-metal-2000': 'version-premier-metal-2000',
  'version-premier-metal-2100': 'version-premier-metal-2100',
  'version-premier-metal-2200': 'version-premier-metal-2200',
  'version-premier-metal-2300': 'version-premier-metal-2300',
  'version-premier-metal-2400': 'version-premier-metal-2400',
  'version-premier-metal-250': 'version-premier-metal-250',
  'version-premier-metal-2500': 'version-premier-metal-2500',
  'version-premier-metal-2600': 'version-premier-metal-2600',
  'version-premier-metal-2700': 'version-premier-metal-2700',
  'version-premier-metal-2800': 'version-premier-metal-2800',
  'version-premier-metal-2900': 'version-premier-metal-2900',
  'version-premier-metal-300': 'version-premier-metal-300',
  'version-premier-metal-3000': 'version-premier-metal-3000',
  'version-premier-metal-3100': 'version-premier-metal-3100',
  'version-premier-metal-3200': 'version-premier-metal-3200',
  'version-premier-metal-3300': 'version-premier-metal-3300',
  'version-premier-metal-3400': 'version-premier-metal-3400',
  'version-premier-metal-3500': 'version-premier-metal-3500',
  'version-premier-metal-3600': 'version-premier-metal-3600',
  'version-premier-metal-3700': 'version-premier-metal-3700',
  'version-premier-metal-3800': 'version-premier-metal-3800',
  'version-premier-metal-3900': 'version-premier-metal-3900',
  'version-premier-metal-400': 'version-premier-metal-400',
  'version-premier-metal-4000': 'version-premier-metal-4000',
  'version-premier-metal-4100': 'version-premier-metal-4100',
  'version-premier-metal-4200': 'version-premier-metal-4200',
  'version-premier-metal-4300': 'version-premier-metal-4300',
  'version-premier-metal-4400': 'version-premier-metal-4400',
  'version-premier-metal-4500': 'version-premier-metal-4500',
  'version-premier-metal-4600': 'version-premier-metal-4600',
  'version-premier-metal-4700': 'version-premier-metal-4700',
  'version-premier-metal-4800': 'version-premier-metal-4800',
  'version-premier-metal-4900': 'version-premier-metal-4900',
  'version-premier-metal-500': 'version-premier-metal-500',
  'version-premier-metal-5000': 'version-premier-metal-5000',
  'version-premier-metal-5100': 'version-premier-metal-5100',
  'version-premier-metal-5200': 'version-premier-metal-5200',
  'version-premier-metal-5300': 'version-premier-metal-5300',
  'version-premier-metal-5400': 'version-premier-metal-5400',
  'version-premier-metal-5500': 'version-premier-metal-5500',
  'version-premier-metal-5600': 'version-premier-metal-5600',
  'version-premier-metal-5700': 'version-premier-metal-5700',
  'version-premier-metal-5800': 'version-premier-metal-5800',
  'version-premier-metal-5900': 'version-premier-metal-5900',
  'version-premier-metal-600': 'version-premier-metal-600',
  'version-premier-metal-6000': 'version-premier-metal-6000',
  'version-premier-metal-6100': 'version-premier-metal-6100',
  'version-premier-metal-6200': 'version-premier-metal-6200',
  'version-premier-metal-6300': 'version-premier-metal-6300',
  'version-premier-metal-6400': 'version-premier-metal-6400',
  'version-premier-metal-6500': 'version-premier-metal-6500',
  'version-premier-metal-6600': 'version-premier-metal-6600',
  'version-premier-metal-6700': 'version-premier-metal-6700',
  'version-premier-metal-6800': 'version-premier-metal-6800',
  'version-premier-metal-6900': 'version-premier-metal-6900',
  'version-premier-metal-700': 'version-premier-metal-700',
  'version-premier-metal-7000': 'version-premier-metal-7000',
  'version-premier-metal-7100': 'version-premier-metal-7100',
  'version-premier-metal-7200': 'version-premier-metal-7200',
  'version-premier-metal-7300': 'version-premier-metal-7300',
  'version-premier-metal-7400': 'version-premier-metal-7400',
  'version-premier-metal-7500': 'version-premier-metal-7500',
  'version-premier-metal-7600': 'version-premier-metal-7600',
  'version-premier-metal-7700': 'version-premier-metal-7700',
  'version-premier-metal-7800': 'version-premier-metal-7800',
  'version-premier-metal-7900': 'version-premier-metal-7900',
  'version-premier-metal-800': 'version-premier-metal-800',
  'version-premier-metal-8000': 'version-premier-metal-8000',
  'version-premier-metal-8100': 'version-premier-metal-8100',
  'version-premier-metal-8200': 'version-premier-metal-8200',
  'version-premier-metal-8300': 'version-premier-metal-8300',
  'version-premier-metal-8400': 'version-premier-metal-8400',
  'version-premier-metal-8500': 'version-premier-metal-8500',
  'version-premier-metal-8600': 'version-premier-metal-8600',
  'version-premier-metal-8700': 'version-premier-metal-8700',
  'version-premier-metal-8800': 'version-premier-metal-8800',
  'version-premier-metal-8900': 'version-premier-metal-8900',
  'version-premier-metal-900': 'version-premier-metal-900',
  'version-premier-metal-9000': 'version-premier-metal-9000',
  'version-premier-metal-9100': 'version-premier-metal-9100',
  'version-premier-metal-9200': 'version-premier-metal-9200',
  'version-premier-metal-9300': 'version-premier-metal-9300',
  'version-premier-metal-9400': 'version-premier-metal-9400',
  'version-premier-metal-9500': 'version-premier-metal-9500',
  'version-premier-metal-9600': 'version-premier-metal-9600',
  'version-premier-metal-9700': 'version-premier-metal-9700',
  'version-premier-metal-9800': 'version-premier-metal-9800',
  'version-premier-metal-9900': 'version-premier-metal-9900',
  'version-pro-cloud': 'version-pro-cloud',
  'version-solo-cloud': 'version-solo-cloud',
  'version-solo-metal': 'version-solo-metal',
  'cpanel-license-admin-cloud-accounts': 'cpanel-license-admin-cloud-accounts',
  'cpanel-license-admin-cloud_agora-accounts': 'cpanel-license-admin-cloud_agora-accounts',
  'cpanel-license-plus-cloud-accounts': 'cpanel-license-plus-cloud-accounts',
  'cpanel-license-plus-cloud_agora-accounts': 'cpanel-license-plus-cloud_agora-accounts',
  'cpanel-license-premier-cloud-10000_agora-accounts': 'cpanel-license-premier-cloud-10000_agora-accounts',
  'cpanel-license-premier-cloud-1000_agora-accounts': 'cpanel-license-premier-cloud-1000_agora-accounts',
  'cpanel-license-premier-cloud-100_agora-accounts': 'cpanel-license-premier-cloud-100_agora-accounts',
  'cpanel-license-premier-cloud-1100_agora-accounts': 'cpanel-license-premier-cloud-1100_agora-accounts',
  'cpanel-license-premier-cloud-1200_agora-accounts': 'cpanel-license-premier-cloud-1200_agora-accounts',
  'cpanel-license-premier-cloud-1300_agora-accounts': 'cpanel-license-premier-cloud-1300_agora-accounts',
  'cpanel-license-premier-cloud-1400_agora-accounts': 'cpanel-license-premier-cloud-1400_agora-accounts',
  'cpanel-license-premier-cloud-1500_agora-accounts': 'cpanel-license-premier-cloud-1500_agora-accounts',
  'cpanel-license-premier-cloud-150_agora-accounts': 'cpanel-license-premier-cloud-150_agora-accounts',
  'cpanel-license-premier-cloud-1600_agora-accounts': 'cpanel-license-premier-cloud-1600_agora-accounts',
  'cpanel-license-premier-cloud-1700_agora-accounts': 'cpanel-license-premier-cloud-1700_agora-accounts',
  'cpanel-license-premier-cloud-1800_agora-accounts': 'cpanel-license-premier-cloud-1800_agora-accounts',
  'cpanel-license-premier-cloud-1900_agora-accounts': 'cpanel-license-premier-cloud-1900_agora-accounts',
  'cpanel-license-premier-cloud-2000_agora-accounts': 'cpanel-license-premier-cloud-2000_agora-accounts',
  'cpanel-license-premier-cloud-200_agora-accounts': 'cpanel-license-premier-cloud-200_agora-accounts',
  'cpanel-license-premier-cloud-2100_agora-accounts': 'cpanel-license-premier-cloud-2100_agora-accounts',
  'cpanel-license-premier-cloud-2200_agora-accounts': 'cpanel-license-premier-cloud-2200_agora-accounts',
  'cpanel-license-premier-cloud-2300_agora-accounts': 'cpanel-license-premier-cloud-2300_agora-accounts',
  'cpanel-license-premier-cloud-2400_agora-accounts': 'cpanel-license-premier-cloud-2400_agora-accounts',
  'cpanel-license-premier-cloud-2500_agora-accounts': 'cpanel-license-premier-cloud-2500_agora-accounts',
  'cpanel-license-premier-cloud-250_agora-accounts': 'cpanel-license-premier-cloud-250_agora-accounts',
  'cpanel-license-premier-cloud-2600_agora-accounts': 'cpanel-license-premier-cloud-2600_agora-accounts',
  'cpanel-license-premier-cloud-2700_agora-accounts': 'cpanel-license-premier-cloud-2700_agora-accounts',
  'cpanel-license-premier-cloud-2800_agora-accounts': 'cpanel-license-premier-cloud-2800_agora-accounts',
  'cpanel-license-premier-cloud-2900_agora-accounts': 'cpanel-license-premier-cloud-2900_agora-accounts',
  'cpanel-license-premier-cloud-3000_agora-accounts': 'cpanel-license-premier-cloud-3000_agora-accounts',
  'cpanel-license-premier-cloud-300_agora-accounts': 'cpanel-license-premier-cloud-300_agora-accounts',
  'cpanel-license-premier-cloud-3100_agora-accounts': 'cpanel-license-premier-cloud-3100_agora-accounts',
  'cpanel-license-premier-cloud-3200_agora-accounts': 'cpanel-license-premier-cloud-3200_agora-accounts',
  'cpanel-license-premier-cloud-3300_agora-accounts': 'cpanel-license-premier-cloud-3300_agora-accounts',
  'cpanel-license-premier-cloud-3400_agora-accounts': 'cpanel-license-premier-cloud-3400_agora-accounts',
  'cpanel-license-premier-cloud-3500_agora-accounts': 'cpanel-license-premier-cloud-3500_agora-accounts',
  'cpanel-license-premier-cloud-3600_agora-accounts': 'cpanel-license-premier-cloud-3600_agora-accounts',
  'cpanel-license-premier-cloud-3700_agora-accounts': 'cpanel-license-premier-cloud-3700_agora-accounts',
  'cpanel-license-premier-cloud-3800_agora-accounts': 'cpanel-license-premier-cloud-3800_agora-accounts',
  'cpanel-license-premier-cloud-3900_agora-accounts': 'cpanel-license-premier-cloud-3900_agora-accounts',
  'cpanel-license-premier-cloud-4000_agora-accounts': 'cpanel-license-premier-cloud-4000_agora-accounts',
  'cpanel-license-premier-cloud-400_agora-accounts': 'cpanel-license-premier-cloud-400_agora-accounts',
  'cpanel-license-premier-cloud-4100_agora-accounts': 'cpanel-license-premier-cloud-4100_agora-accounts',
  'cpanel-license-premier-cloud-4200_agora-accounts': 'cpanel-license-premier-cloud-4200_agora-accounts',
  'cpanel-license-premier-cloud-4300_agora-accounts': 'cpanel-license-premier-cloud-4300_agora-accounts',
  'cpanel-license-premier-cloud-4400_agora-accounts': 'cpanel-license-premier-cloud-4400_agora-accounts',
  'cpanel-license-premier-cloud-4500_agora-accounts': 'cpanel-license-premier-cloud-4500_agora-accounts',
  'cpanel-license-premier-cloud-4600_agora-accounts': 'cpanel-license-premier-cloud-4600_agora-accounts',
  'cpanel-license-premier-cloud-4700_agora-accounts': 'cpanel-license-premier-cloud-4700_agora-accounts',
  'cpanel-license-premier-cloud-4800_agora-accounts': 'cpanel-license-premier-cloud-4800_agora-accounts',
  'cpanel-license-premier-cloud-4900_agora-accounts': 'cpanel-license-premier-cloud-4900_agora-accounts',
  'cpanel-license-premier-cloud-5000_agora-accounts': 'cpanel-license-premier-cloud-5000_agora-accounts',
  'cpanel-license-premier-cloud-500_agora-accounts': 'cpanel-license-premier-cloud-500_agora-accounts',
  'cpanel-license-premier-cloud-5100_agora-accounts': 'cpanel-license-premier-cloud-5100_agora-accounts',
  'cpanel-license-premier-cloud-5200_agora-accounts': 'cpanel-license-premier-cloud-5200_agora-accounts',
  'cpanel-license-premier-cloud-5300_agora-accounts': 'cpanel-license-premier-cloud-5300_agora-accounts',
  'cpanel-license-premier-cloud-5400_agora-accounts': 'cpanel-license-premier-cloud-5400_agora-accounts',
  'cpanel-license-premier-cloud-5500_agora-accounts': 'cpanel-license-premier-cloud-5500_agora-accounts',
  'cpanel-license-premier-cloud-5600_agora-accounts': 'cpanel-license-premier-cloud-5600_agora-accounts',
  'cpanel-license-premier-cloud-5700_agora-accounts': 'cpanel-license-premier-cloud-5700_agora-accounts',
  'cpanel-license-premier-cloud-5800_agora-accounts': 'cpanel-license-premier-cloud-5800_agora-accounts',
  'cpanel-license-premier-cloud-5900_agora-accounts': 'cpanel-license-premier-cloud-5900_agora-accounts',
  'cpanel-license-premier-cloud-6000_agora-accounts': 'cpanel-license-premier-cloud-6000_agora-accounts',
  'cpanel-license-premier-cloud-600_agora-accounts': 'cpanel-license-premier-cloud-600_agora-accounts',
  'cpanel-license-premier-cloud-6100_agora-accounts': 'cpanel-license-premier-cloud-6100_agora-accounts',
  'cpanel-license-premier-cloud-6200_agora-accounts': 'cpanel-license-premier-cloud-6200_agora-accounts',
  'cpanel-license-premier-cloud-6300_agora-accounts': 'cpanel-license-premier-cloud-6300_agora-accounts',
  'cpanel-license-premier-cloud-6400_agora-accounts': 'cpanel-license-premier-cloud-6400_agora-accounts',
  'cpanel-license-premier-cloud-6500_agora-accounts': 'cpanel-license-premier-cloud-6500_agora-accounts',
  'cpanel-license-premier-cloud-6600_agora-accounts': 'cpanel-license-premier-cloud-6600_agora-accounts',
  'cpanel-license-premier-cloud-6700_agora-accounts': 'cpanel-license-premier-cloud-6700_agora-accounts',
  'cpanel-license-premier-cloud-6800_agora-accounts': 'cpanel-license-premier-cloud-6800_agora-accounts',
  'cpanel-license-premier-cloud-6900_agora-accounts': 'cpanel-license-premier-cloud-6900_agora-accounts',
  'cpanel-license-premier-cloud-7000_agora-accounts': 'cpanel-license-premier-cloud-7000_agora-accounts',
  'cpanel-license-premier-cloud-700_agora-accounts': 'cpanel-license-premier-cloud-700_agora-accounts',
  'cpanel-license-premier-cloud-7100_agora-accounts': 'cpanel-license-premier-cloud-7100_agora-accounts',
  'cpanel-license-premier-cloud-7200_agora-accounts': 'cpanel-license-premier-cloud-7200_agora-accounts',
  'cpanel-license-premier-cloud-7300_agora-accounts': 'cpanel-license-premier-cloud-7300_agora-accounts',
  'cpanel-license-premier-cloud-7400_agora-accounts': 'cpanel-license-premier-cloud-7400_agora-accounts',
  'cpanel-license-premier-cloud-7500_agora-accounts': 'cpanel-license-premier-cloud-7500_agora-accounts',
  'cpanel-license-premier-cloud-7600_agora-accounts': 'cpanel-license-premier-cloud-7600_agora-accounts',
  'cpanel-license-premier-cloud-7700_agora-accounts': 'cpanel-license-premier-cloud-7700_agora-accounts',
  'cpanel-license-premier-cloud-7800_agora-accounts': 'cpanel-license-premier-cloud-7800_agora-accounts',
  'cpanel-license-premier-cloud-7900_agora-accounts': 'cpanel-license-premier-cloud-7900_agora-accounts',
  'cpanel-license-premier-cloud-8000_agora-accounts': 'cpanel-license-premier-cloud-8000_agora-accounts',
  'cpanel-license-premier-cloud-800_agora-accounts': 'cpanel-license-premier-cloud-800_agora-accounts',
  'cpanel-license-premier-cloud-8100_agora-accounts': 'cpanel-license-premier-cloud-8100_agora-accounts',
  'cpanel-license-premier-cloud-8200_agora-accounts': 'cpanel-license-premier-cloud-8200_agora-accounts',
  'cpanel-license-premier-cloud-8300_agora-accounts': 'cpanel-license-premier-cloud-8300_agora-accounts',
  'cpanel-license-premier-cloud-8400_agora-accounts': 'cpanel-license-premier-cloud-8400_agora-accounts',
  'cpanel-license-premier-cloud-8500_agora-accounts': 'cpanel-license-premier-cloud-8500_agora-accounts',
  'cpanel-license-premier-cloud-8600_agora-accounts': 'cpanel-license-premier-cloud-8600_agora-accounts',
  'cpanel-license-premier-cloud-8700_agora-accounts': 'cpanel-license-premier-cloud-8700_agora-accounts',
  'cpanel-license-premier-cloud-8800_agora-accounts': 'cpanel-license-premier-cloud-8800_agora-accounts',
  'cpanel-license-premier-cloud-8900_agora-accounts': 'cpanel-license-premier-cloud-8900_agora-accounts',
  'cpanel-license-premier-cloud-9000_agora-accounts': 'cpanel-license-premier-cloud-9000_agora-accounts',
  'cpanel-license-premier-cloud-900_agora-accounts': 'cpanel-license-premier-cloud-900_agora-accounts',
  'cpanel-license-premier-cloud-9100_agora-accounts': 'cpanel-license-premier-cloud-9100_agora-accounts',
  'cpanel-license-premier-cloud-9200_agora-accounts': 'cpanel-license-premier-cloud-9200_agora-accounts',
  'cpanel-license-premier-cloud-9300_agora-accounts': 'cpanel-license-premier-cloud-9300_agora-accounts',
  'cpanel-license-premier-cloud-9400_agora-accounts': 'cpanel-license-premier-cloud-9400_agora-accounts',
  'cpanel-license-premier-cloud-9500_agora-accounts': 'cpanel-license-premier-cloud-9500_agora-accounts',
  'cpanel-license-premier-cloud-9600_agora-accounts': 'cpanel-license-premier-cloud-9600_agora-accounts',
  'cpanel-license-premier-cloud-9700_agora-accounts': 'cpanel-license-premier-cloud-9700_agora-accounts',
  'cpanel-license-premier-cloud-9800_agora-accounts': 'cpanel-license-premier-cloud-9800_agora-accounts',
  'cpanel-license-premier-cloud-9900_agora-accounts': 'cpanel-license-premier-cloud-9900_agora-accounts',
  'cpanel-license-premier-metal-10000_agora-accounts': 'cpanel-license-premier-metal-10000_agora-accounts',
  'cpanel-license-premier-metal-1000_agora-accounts': 'cpanel-license-premier-metal-1000_agora-accounts',
  'cpanel-license-premier-metal-100_agora-accounts': 'cpanel-license-premier-metal-100_agora-accounts',
  'cpanel-license-premier-metal-1100_agora-accounts': 'cpanel-license-premier-metal-1100_agora-accounts',
  'cpanel-license-premier-metal-1200_agora-accounts': 'cpanel-license-premier-metal-1200_agora-accounts',
  'cpanel-license-premier-metal-1300_agora-accounts': 'cpanel-license-premier-metal-1300_agora-accounts',
  'cpanel-license-premier-metal-1400_agora-accounts': 'cpanel-license-premier-metal-1400_agora-accounts',
  'cpanel-license-premier-metal-1500_agora-accounts': 'cpanel-license-premier-metal-1500_agora-accounts',
  'cpanel-license-premier-metal-150_agora-accounts': 'cpanel-license-premier-metal-150_agora-accounts',
  'cpanel-license-premier-metal-1600_agora-accounts': 'cpanel-license-premier-metal-1600_agora-accounts',
  'cpanel-license-premier-metal-1700_agora-accounts': 'cpanel-license-premier-metal-1700_agora-accounts',
  'cpanel-license-premier-metal-1800_agora-accounts': 'cpanel-license-premier-metal-1800_agora-accounts',
  'cpanel-license-premier-metal-1900_agora-accounts': 'cpanel-license-premier-metal-1900_agora-accounts',
  'cpanel-license-premier-metal-2000_agora-accounts': 'cpanel-license-premier-metal-2000_agora-accounts',
  'cpanel-license-premier-metal-200_agora-accounts': 'cpanel-license-premier-metal-200_agora-accounts',
  'cpanel-license-premier-metal-2100_agora-accounts': 'cpanel-license-premier-metal-2100_agora-accounts',
  'cpanel-license-premier-metal-2200_agora-accounts': 'cpanel-license-premier-metal-2200_agora-accounts',
  'cpanel-license-premier-metal-2300_agora-accounts': 'cpanel-license-premier-metal-2300_agora-accounts',
  'cpanel-license-premier-metal-2400_agora-accounts': 'cpanel-license-premier-metal-2400_agora-accounts',
  'cpanel-license-premier-metal-2500_agora-accounts': 'cpanel-license-premier-metal-2500_agora-accounts',
  'cpanel-license-premier-metal-250_agora-accounts': 'cpanel-license-premier-metal-250_agora-accounts',
  'cpanel-license-premier-metal-2600_agora-accounts': 'cpanel-license-premier-metal-2600_agora-accounts',
  'cpanel-license-premier-metal-2700_agora-accounts': 'cpanel-license-premier-metal-2700_agora-accounts',
  'cpanel-license-premier-metal-2800_agora-accounts': 'cpanel-license-premier-metal-2800_agora-accounts',
  'cpanel-license-premier-metal-2900_agora-accounts': 'cpanel-license-premier-metal-2900_agora-accounts',
  'cpanel-license-premier-metal-3000_agora-accounts': 'cpanel-license-premier-metal-3000_agora-accounts',
  'cpanel-license-premier-metal-300_agora-accounts': 'cpanel-license-premier-metal-300_agora-accounts',
  'cpanel-license-premier-metal-3100_agora-accounts': 'cpanel-license-premier-metal-3100_agora-accounts',
  'cpanel-license-premier-metal-3200_agora-accounts': 'cpanel-license-premier-metal-3200_agora-accounts',
  'cpanel-license-premier-metal-3300_agora-accounts': 'cpanel-license-premier-metal-3300_agora-accounts',
  'cpanel-license-premier-metal-3400_agora-accounts': 'cpanel-license-premier-metal-3400_agora-accounts',
  'cpanel-license-premier-metal-3500_agora-accounts': 'cpanel-license-premier-metal-3500_agora-accounts',
  'cpanel-license-premier-metal-3600_agora-accounts': 'cpanel-license-premier-metal-3600_agora-accounts',
  'cpanel-license-premier-metal-3700_agora-accounts': 'cpanel-license-premier-metal-3700_agora-accounts',
  'cpanel-license-premier-metal-3800_agora-accounts': 'cpanel-license-premier-metal-3800_agora-accounts',
  'cpanel-license-premier-metal-3900_agora-accounts': 'cpanel-license-premier-metal-3900_agora-accounts',
  'cpanel-license-premier-metal-4000_agora-accounts': 'cpanel-license-premier-metal-4000_agora-accounts',
  'cpanel-license-premier-metal-400_agora-accounts': 'cpanel-license-premier-metal-400_agora-accounts',
  'cpanel-license-premier-metal-4100_agora-accounts': 'cpanel-license-premier-metal-4100_agora-accounts',
  'cpanel-license-premier-metal-4200_agora-accounts': 'cpanel-license-premier-metal-4200_agora-accounts',
  'cpanel-license-premier-metal-4300_agora-accounts': 'cpanel-license-premier-metal-4300_agora-accounts',
  'cpanel-license-premier-metal-4400_agora-accounts': 'cpanel-license-premier-metal-4400_agora-accounts',
  'cpanel-license-premier-metal-4500_agora-accounts': 'cpanel-license-premier-metal-4500_agora-accounts',
  'cpanel-license-premier-metal-4600_agora-accounts': 'cpanel-license-premier-metal-4600_agora-accounts',
  'cpanel-license-premier-metal-4700_agora-accounts': 'cpanel-license-premier-metal-4700_agora-accounts',
  'cpanel-license-premier-metal-4800_agora-accounts': 'cpanel-license-premier-metal-4800_agora-accounts',
  'cpanel-license-premier-metal-4900_agora-accounts': 'cpanel-license-premier-metal-4900_agora-accounts',
  'cpanel-license-premier-metal-5000_agora-accounts': 'cpanel-license-premier-metal-5000_agora-accounts',
  'cpanel-license-premier-metal-500_agora-accounts': 'cpanel-license-premier-metal-500_agora-accounts',
  'cpanel-license-premier-metal-5100_agora-accounts': 'cpanel-license-premier-metal-5100_agora-accounts',
  'cpanel-license-premier-metal-5200_agora-accounts': 'cpanel-license-premier-metal-5200_agora-accounts',
  'cpanel-license-premier-metal-5300_agora-accounts': 'cpanel-license-premier-metal-5300_agora-accounts',
  'cpanel-license-premier-metal-5400_agora-accounts': 'cpanel-license-premier-metal-5400_agora-accounts',
  'cpanel-license-premier-metal-5500_agora-accounts': 'cpanel-license-premier-metal-5500_agora-accounts',
  'cpanel-license-premier-metal-5600_agora-accounts': 'cpanel-license-premier-metal-5600_agora-accounts',
  'cpanel-license-premier-metal-5700_agora-accounts': 'cpanel-license-premier-metal-5700_agora-accounts',
  'cpanel-license-premier-metal-5800_agora-accounts': 'cpanel-license-premier-metal-5800_agora-accounts',
  'cpanel-license-premier-metal-5900_agora-accounts': 'cpanel-license-premier-metal-5900_agora-accounts',
  'cpanel-license-premier-metal-6000_agora-accounts': 'cpanel-license-premier-metal-6000_agora-accounts',
  'cpanel-license-premier-metal-600_agora-accounts': 'cpanel-license-premier-metal-600_agora-accounts',
  'cpanel-license-premier-metal-6100_agora-accounts': 'cpanel-license-premier-metal-6100_agora-accounts',
  'cpanel-license-premier-metal-6200_agora-accounts': 'cpanel-license-premier-metal-6200_agora-accounts',
  'cpanel-license-premier-metal-6300_agora-accounts': 'cpanel-license-premier-metal-6300_agora-accounts',
  'cpanel-license-premier-metal-6400_agora-accounts': 'cpanel-license-premier-metal-6400_agora-accounts',
  'cpanel-license-premier-metal-6500_agora-accounts': 'cpanel-license-premier-metal-6500_agora-accounts',
  'cpanel-license-premier-metal-6600_agora-accounts': 'cpanel-license-premier-metal-6600_agora-accounts',
  'cpanel-license-premier-metal-6700_agora-accounts': 'cpanel-license-premier-metal-6700_agora-accounts',
  'cpanel-license-premier-metal-6800_agora-accounts': 'cpanel-license-premier-metal-6800_agora-accounts',
  'cpanel-license-premier-metal-6900_agora-accounts': 'cpanel-license-premier-metal-6900_agora-accounts',
  'cpanel-license-premier-metal-7000_agora-accounts': 'cpanel-license-premier-metal-7000_agora-accounts',
  'cpanel-license-premier-metal-700_agora-accounts': 'cpanel-license-premier-metal-700_agora-accounts',
  'cpanel-license-premier-metal-7100_agora-accounts': 'cpanel-license-premier-metal-7100_agora-accounts',
  'cpanel-license-premier-metal-7200_agora-accounts': 'cpanel-license-premier-metal-7200_agora-accounts',
  'cpanel-license-premier-metal-7300_agora-accounts': 'cpanel-license-premier-metal-7300_agora-accounts',
  'cpanel-license-premier-metal-7400_agora-accounts': 'cpanel-license-premier-metal-7400_agora-accounts',
  'cpanel-license-premier-metal-7500_agora-accounts': 'cpanel-license-premier-metal-7500_agora-accounts',
  'cpanel-license-premier-metal-7600_agora-accounts': 'cpanel-license-premier-metal-7600_agora-accounts',
  'cpanel-license-premier-metal-7700_agora-accounts': 'cpanel-license-premier-metal-7700_agora-accounts',
  'cpanel-license-premier-metal-7800_agora-accounts': 'cpanel-license-premier-metal-7800_agora-accounts',
  'cpanel-license-premier-metal-7900_agora-accounts': 'cpanel-license-premier-metal-7900_agora-accounts',
  'cpanel-license-premier-metal-8000_agora-accounts': 'cpanel-license-premier-metal-8000_agora-accounts',
  'cpanel-license-premier-metal-800_agora-accounts': 'cpanel-license-premier-metal-800_agora-accounts',
  'cpanel-license-premier-metal-8100_agora-accounts': 'cpanel-license-premier-metal-8100_agora-accounts',
  'cpanel-license-premier-metal-8200_agora-accounts': 'cpanel-license-premier-metal-8200_agora-accounts',
  'cpanel-license-premier-metal-8300_agora-accounts': 'cpanel-license-premier-metal-8300_agora-accounts',
  'cpanel-license-premier-metal-8400_agora-accounts': 'cpanel-license-premier-metal-8400_agora-accounts',
  'cpanel-license-premier-metal-8500_agora-accounts': 'cpanel-license-premier-metal-8500_agora-accounts',
  'cpanel-license-premier-metal-8600_agora-accounts': 'cpanel-license-premier-metal-8600_agora-accounts',
  'cpanel-license-premier-metal-8700_agora-accounts': 'cpanel-license-premier-metal-8700_agora-accounts',
  'cpanel-license-premier-metal-8800_agora-accounts': 'cpanel-license-premier-metal-8800_agora-accounts',
  'cpanel-license-premier-metal-8900_agora-accounts': 'cpanel-license-premier-metal-8900_agora-accounts',
  'cpanel-license-premier-metal-9000_agora-accounts': 'cpanel-license-premier-metal-9000_agora-accounts',
  'cpanel-license-premier-metal-900_agora-accounts': 'cpanel-license-premier-metal-900_agora-accounts',
  'cpanel-license-premier-metal-9100_agora-accounts': 'cpanel-license-premier-metal-9100_agora-accounts',
  'cpanel-license-premier-metal-9200_agora-accounts': 'cpanel-license-premier-metal-9200_agora-accounts',
  'cpanel-license-premier-metal-9300_agora-accounts': 'cpanel-license-premier-metal-9300_agora-accounts',
  'cpanel-license-premier-metal-9400_agora-accounts': 'cpanel-license-premier-metal-9400_agora-accounts',
  'cpanel-license-premier-metal-9500_agora-accounts': 'cpanel-license-premier-metal-9500_agora-accounts',
  'cpanel-license-premier-metal-9600_agora-accounts': 'cpanel-license-premier-metal-9600_agora-accounts',
  'cpanel-license-premier-metal-9700_agora-accounts': 'cpanel-license-premier-metal-9700_agora-accounts',
  'cpanel-license-premier-metal-9800_agora-accounts': 'cpanel-license-premier-metal-9800_agora-accounts',
  'cpanel-license-premier-metal-9900_agora-accounts': 'cpanel-license-premier-metal-9900_agora-accounts',
  'cpanel-license-pro-cloud-accounts': 'cpanel-license-pro-cloud-accounts',
  'cpanel-license-pro-cloud_agora-accounts': 'cpanel-license-pro-cloud_agora-accounts',
  'cpanel-license-solo-cloud-accounts': 'cpanel-license-solo-cloud-accounts',
  'cpanel-license-solo-cloud_agora-accounts': 'cpanel-license-solo-cloud_agora-accounts',
  'cpanel-license-solo-metal-accounts': 'cpanel-license-solo-metal-accounts',
  'cpanel-license-solo-metal_agora-accounts': 'cpanel-license-solo-metal_agora-accounts',
} as const;

/**
 * All versions available for Cpanel products
 */
export interface LicenseOrderableCpanelCompatibilityInfosOVH {
  version?: LicenseOrderableCpanelVersionEnumOVH;
}

/**
 * Possible values for license type
 */
export type LicenseLicenseTypeEnumOVH = typeof LicenseLicenseTypeEnumOVH[keyof typeof LicenseLicenseTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseLicenseTypeEnumOVH = {
  dedicated: 'dedicated',
  dedicatedCloud: 'dedicatedCloud',
  dedicatedFailover: 'dedicatedFailover',
  failover: 'failover',
  vm: 'vm',
  vps: 'vps',
  vps_ceph: 'vps_ceph',
  vps_classic: 'vps_classic',
  vps_cloud: 'vps_cloud',
  vps_cloud_2016: 'vps_cloud_2016',
  vps_ssd: 'vps_ssd',
} as const;

/**
 * All versions available for Cpanel products
 */
export type LicenseCpanelVersionEnumOVH = typeof LicenseCpanelVersionEnumOVH[keyof typeof LicenseCpanelVersionEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseCpanelVersionEnumOVH = {
  VERSION_11_FOR_LINUX: 'VERSION_11_FOR_LINUX',
  VERSION_11_FOR_VIRTUOZZO: 'VERSION_11_FOR_VIRTUOZZO',
  VERSION_11_FOR_VPS: 'VERSION_11_FOR_VPS',
  'cpanel-license-version-11': 'cpanel-license-version-11',
  'cpanel-license-version-11-for-virtuozzo': 'cpanel-license-version-11-for-virtuozzo',
  'cpanel-license-version-11-for-vps': 'cpanel-license-version-11-for-vps',
  'version-admin-cloud': 'version-admin-cloud',
  'version-plus-cloud': 'version-plus-cloud',
  'version-premier-cloud-100': 'version-premier-cloud-100',
  'version-premier-cloud-1000': 'version-premier-cloud-1000',
  'version-premier-cloud-10000': 'version-premier-cloud-10000',
  'version-premier-cloud-1100': 'version-premier-cloud-1100',
  'version-premier-cloud-1200': 'version-premier-cloud-1200',
  'version-premier-cloud-1300': 'version-premier-cloud-1300',
  'version-premier-cloud-1400': 'version-premier-cloud-1400',
  'version-premier-cloud-150': 'version-premier-cloud-150',
  'version-premier-cloud-1500': 'version-premier-cloud-1500',
  'version-premier-cloud-1600': 'version-premier-cloud-1600',
  'version-premier-cloud-1700': 'version-premier-cloud-1700',
  'version-premier-cloud-1800': 'version-premier-cloud-1800',
  'version-premier-cloud-1900': 'version-premier-cloud-1900',
  'version-premier-cloud-200': 'version-premier-cloud-200',
  'version-premier-cloud-2000': 'version-premier-cloud-2000',
  'version-premier-cloud-2100': 'version-premier-cloud-2100',
  'version-premier-cloud-2200': 'version-premier-cloud-2200',
  'version-premier-cloud-2300': 'version-premier-cloud-2300',
  'version-premier-cloud-2400': 'version-premier-cloud-2400',
  'version-premier-cloud-250': 'version-premier-cloud-250',
  'version-premier-cloud-2500': 'version-premier-cloud-2500',
  'version-premier-cloud-2600': 'version-premier-cloud-2600',
  'version-premier-cloud-2700': 'version-premier-cloud-2700',
  'version-premier-cloud-2800': 'version-premier-cloud-2800',
  'version-premier-cloud-2900': 'version-premier-cloud-2900',
  'version-premier-cloud-300': 'version-premier-cloud-300',
  'version-premier-cloud-3000': 'version-premier-cloud-3000',
  'version-premier-cloud-3100': 'version-premier-cloud-3100',
  'version-premier-cloud-3200': 'version-premier-cloud-3200',
  'version-premier-cloud-3300': 'version-premier-cloud-3300',
  'version-premier-cloud-3400': 'version-premier-cloud-3400',
  'version-premier-cloud-3500': 'version-premier-cloud-3500',
  'version-premier-cloud-3600': 'version-premier-cloud-3600',
  'version-premier-cloud-3700': 'version-premier-cloud-3700',
  'version-premier-cloud-3800': 'version-premier-cloud-3800',
  'version-premier-cloud-3900': 'version-premier-cloud-3900',
  'version-premier-cloud-400': 'version-premier-cloud-400',
  'version-premier-cloud-4000': 'version-premier-cloud-4000',
  'version-premier-cloud-4100': 'version-premier-cloud-4100',
  'version-premier-cloud-4200': 'version-premier-cloud-4200',
  'version-premier-cloud-4300': 'version-premier-cloud-4300',
  'version-premier-cloud-4400': 'version-premier-cloud-4400',
  'version-premier-cloud-4500': 'version-premier-cloud-4500',
  'version-premier-cloud-4600': 'version-premier-cloud-4600',
  'version-premier-cloud-4700': 'version-premier-cloud-4700',
  'version-premier-cloud-4800': 'version-premier-cloud-4800',
  'version-premier-cloud-4900': 'version-premier-cloud-4900',
  'version-premier-cloud-500': 'version-premier-cloud-500',
  'version-premier-cloud-5000': 'version-premier-cloud-5000',
  'version-premier-cloud-5100': 'version-premier-cloud-5100',
  'version-premier-cloud-5200': 'version-premier-cloud-5200',
  'version-premier-cloud-5300': 'version-premier-cloud-5300',
  'version-premier-cloud-5400': 'version-premier-cloud-5400',
  'version-premier-cloud-5500': 'version-premier-cloud-5500',
  'version-premier-cloud-5600': 'version-premier-cloud-5600',
  'version-premier-cloud-5700': 'version-premier-cloud-5700',
  'version-premier-cloud-5800': 'version-premier-cloud-5800',
  'version-premier-cloud-5900': 'version-premier-cloud-5900',
  'version-premier-cloud-600': 'version-premier-cloud-600',
  'version-premier-cloud-6000': 'version-premier-cloud-6000',
  'version-premier-cloud-6100': 'version-premier-cloud-6100',
  'version-premier-cloud-6200': 'version-premier-cloud-6200',
  'version-premier-cloud-6300': 'version-premier-cloud-6300',
  'version-premier-cloud-6400': 'version-premier-cloud-6400',
  'version-premier-cloud-6500': 'version-premier-cloud-6500',
  'version-premier-cloud-6600': 'version-premier-cloud-6600',
  'version-premier-cloud-6700': 'version-premier-cloud-6700',
  'version-premier-cloud-6800': 'version-premier-cloud-6800',
  'version-premier-cloud-6900': 'version-premier-cloud-6900',
  'version-premier-cloud-700': 'version-premier-cloud-700',
  'version-premier-cloud-7000': 'version-premier-cloud-7000',
  'version-premier-cloud-7100': 'version-premier-cloud-7100',
  'version-premier-cloud-7200': 'version-premier-cloud-7200',
  'version-premier-cloud-7300': 'version-premier-cloud-7300',
  'version-premier-cloud-7400': 'version-premier-cloud-7400',
  'version-premier-cloud-7500': 'version-premier-cloud-7500',
  'version-premier-cloud-7600': 'version-premier-cloud-7600',
  'version-premier-cloud-7700': 'version-premier-cloud-7700',
  'version-premier-cloud-7800': 'version-premier-cloud-7800',
  'version-premier-cloud-7900': 'version-premier-cloud-7900',
  'version-premier-cloud-800': 'version-premier-cloud-800',
  'version-premier-cloud-8000': 'version-premier-cloud-8000',
  'version-premier-cloud-8100': 'version-premier-cloud-8100',
  'version-premier-cloud-8200': 'version-premier-cloud-8200',
  'version-premier-cloud-8300': 'version-premier-cloud-8300',
  'version-premier-cloud-8400': 'version-premier-cloud-8400',
  'version-premier-cloud-8500': 'version-premier-cloud-8500',
  'version-premier-cloud-8600': 'version-premier-cloud-8600',
  'version-premier-cloud-8700': 'version-premier-cloud-8700',
  'version-premier-cloud-8800': 'version-premier-cloud-8800',
  'version-premier-cloud-8900': 'version-premier-cloud-8900',
  'version-premier-cloud-900': 'version-premier-cloud-900',
  'version-premier-cloud-9000': 'version-premier-cloud-9000',
  'version-premier-cloud-9100': 'version-premier-cloud-9100',
  'version-premier-cloud-9200': 'version-premier-cloud-9200',
  'version-premier-cloud-9300': 'version-premier-cloud-9300',
  'version-premier-cloud-9400': 'version-premier-cloud-9400',
  'version-premier-cloud-9500': 'version-premier-cloud-9500',
  'version-premier-cloud-9600': 'version-premier-cloud-9600',
  'version-premier-cloud-9700': 'version-premier-cloud-9700',
  'version-premier-cloud-9800': 'version-premier-cloud-9800',
  'version-premier-cloud-9900': 'version-premier-cloud-9900',
  'version-premier-metal-100': 'version-premier-metal-100',
  'version-premier-metal-1000': 'version-premier-metal-1000',
  'version-premier-metal-10000': 'version-premier-metal-10000',
  'version-premier-metal-1100': 'version-premier-metal-1100',
  'version-premier-metal-1200': 'version-premier-metal-1200',
  'version-premier-metal-1300': 'version-premier-metal-1300',
  'version-premier-metal-1400': 'version-premier-metal-1400',
  'version-premier-metal-150': 'version-premier-metal-150',
  'version-premier-metal-1500': 'version-premier-metal-1500',
  'version-premier-metal-1600': 'version-premier-metal-1600',
  'version-premier-metal-1700': 'version-premier-metal-1700',
  'version-premier-metal-1800': 'version-premier-metal-1800',
  'version-premier-metal-1900': 'version-premier-metal-1900',
  'version-premier-metal-200': 'version-premier-metal-200',
  'version-premier-metal-2000': 'version-premier-metal-2000',
  'version-premier-metal-2100': 'version-premier-metal-2100',
  'version-premier-metal-2200': 'version-premier-metal-2200',
  'version-premier-metal-2300': 'version-premier-metal-2300',
  'version-premier-metal-2400': 'version-premier-metal-2400',
  'version-premier-metal-250': 'version-premier-metal-250',
  'version-premier-metal-2500': 'version-premier-metal-2500',
  'version-premier-metal-2600': 'version-premier-metal-2600',
  'version-premier-metal-2700': 'version-premier-metal-2700',
  'version-premier-metal-2800': 'version-premier-metal-2800',
  'version-premier-metal-2900': 'version-premier-metal-2900',
  'version-premier-metal-300': 'version-premier-metal-300',
  'version-premier-metal-3000': 'version-premier-metal-3000',
  'version-premier-metal-3100': 'version-premier-metal-3100',
  'version-premier-metal-3200': 'version-premier-metal-3200',
  'version-premier-metal-3300': 'version-premier-metal-3300',
  'version-premier-metal-3400': 'version-premier-metal-3400',
  'version-premier-metal-3500': 'version-premier-metal-3500',
  'version-premier-metal-3600': 'version-premier-metal-3600',
  'version-premier-metal-3700': 'version-premier-metal-3700',
  'version-premier-metal-3800': 'version-premier-metal-3800',
  'version-premier-metal-3900': 'version-premier-metal-3900',
  'version-premier-metal-400': 'version-premier-metal-400',
  'version-premier-metal-4000': 'version-premier-metal-4000',
  'version-premier-metal-4100': 'version-premier-metal-4100',
  'version-premier-metal-4200': 'version-premier-metal-4200',
  'version-premier-metal-4300': 'version-premier-metal-4300',
  'version-premier-metal-4400': 'version-premier-metal-4400',
  'version-premier-metal-4500': 'version-premier-metal-4500',
  'version-premier-metal-4600': 'version-premier-metal-4600',
  'version-premier-metal-4700': 'version-premier-metal-4700',
  'version-premier-metal-4800': 'version-premier-metal-4800',
  'version-premier-metal-4900': 'version-premier-metal-4900',
  'version-premier-metal-500': 'version-premier-metal-500',
  'version-premier-metal-5000': 'version-premier-metal-5000',
  'version-premier-metal-5100': 'version-premier-metal-5100',
  'version-premier-metal-5200': 'version-premier-metal-5200',
  'version-premier-metal-5300': 'version-premier-metal-5300',
  'version-premier-metal-5400': 'version-premier-metal-5400',
  'version-premier-metal-5500': 'version-premier-metal-5500',
  'version-premier-metal-5600': 'version-premier-metal-5600',
  'version-premier-metal-5700': 'version-premier-metal-5700',
  'version-premier-metal-5800': 'version-premier-metal-5800',
  'version-premier-metal-5900': 'version-premier-metal-5900',
  'version-premier-metal-600': 'version-premier-metal-600',
  'version-premier-metal-6000': 'version-premier-metal-6000',
  'version-premier-metal-6100': 'version-premier-metal-6100',
  'version-premier-metal-6200': 'version-premier-metal-6200',
  'version-premier-metal-6300': 'version-premier-metal-6300',
  'version-premier-metal-6400': 'version-premier-metal-6400',
  'version-premier-metal-6500': 'version-premier-metal-6500',
  'version-premier-metal-6600': 'version-premier-metal-6600',
  'version-premier-metal-6700': 'version-premier-metal-6700',
  'version-premier-metal-6800': 'version-premier-metal-6800',
  'version-premier-metal-6900': 'version-premier-metal-6900',
  'version-premier-metal-700': 'version-premier-metal-700',
  'version-premier-metal-7000': 'version-premier-metal-7000',
  'version-premier-metal-7100': 'version-premier-metal-7100',
  'version-premier-metal-7200': 'version-premier-metal-7200',
  'version-premier-metal-7300': 'version-premier-metal-7300',
  'version-premier-metal-7400': 'version-premier-metal-7400',
  'version-premier-metal-7500': 'version-premier-metal-7500',
  'version-premier-metal-7600': 'version-premier-metal-7600',
  'version-premier-metal-7700': 'version-premier-metal-7700',
  'version-premier-metal-7800': 'version-premier-metal-7800',
  'version-premier-metal-7900': 'version-premier-metal-7900',
  'version-premier-metal-800': 'version-premier-metal-800',
  'version-premier-metal-8000': 'version-premier-metal-8000',
  'version-premier-metal-8100': 'version-premier-metal-8100',
  'version-premier-metal-8200': 'version-premier-metal-8200',
  'version-premier-metal-8300': 'version-premier-metal-8300',
  'version-premier-metal-8400': 'version-premier-metal-8400',
  'version-premier-metal-8500': 'version-premier-metal-8500',
  'version-premier-metal-8600': 'version-premier-metal-8600',
  'version-premier-metal-8700': 'version-premier-metal-8700',
  'version-premier-metal-8800': 'version-premier-metal-8800',
  'version-premier-metal-8900': 'version-premier-metal-8900',
  'version-premier-metal-900': 'version-premier-metal-900',
  'version-premier-metal-9000': 'version-premier-metal-9000',
  'version-premier-metal-9100': 'version-premier-metal-9100',
  'version-premier-metal-9200': 'version-premier-metal-9200',
  'version-premier-metal-9300': 'version-premier-metal-9300',
  'version-premier-metal-9400': 'version-premier-metal-9400',
  'version-premier-metal-9500': 'version-premier-metal-9500',
  'version-premier-metal-9600': 'version-premier-metal-9600',
  'version-premier-metal-9700': 'version-premier-metal-9700',
  'version-premier-metal-9800': 'version-premier-metal-9800',
  'version-premier-metal-9900': 'version-premier-metal-9900',
  'version-pro-cloud': 'version-pro-cloud',
  'version-solo-cloud': 'version-solo-cloud',
  'version-solo-metal': 'version-solo-metal',
} as const;

/**
 * Your Cpanel license
 */
export interface LicenseCpanelCpanelWithIAMOVH {
  /** This license creation date */
  readonly creation?: string;
  /** Shall we delete this on expiration ? */
  deleteAtExpiration?: boolean;
  /** The internal name of your license */
  readonly domain?: string;
  /**
   * IAM resource metadata
   * @nullable
   */
  readonly iam?: LicenseCpanelCpanelWithIAMOVHIam;
  /** The ip on which this license is attached */
  readonly ip?: Ipv4OVH;
  /** The license id on license provider side */
  readonly licenseId?: string;
  /** This license state */
  readonly status?: LicenseStateEnumOVH;
  /** This license version */
  readonly version?: LicenseCpanelVersionEnumOVH;
}

/**
 * Your Cpanel license
 */
export interface LicenseCpanelCpanelOVH {
  /** This license creation date */
  readonly creation?: string;
  /** Shall we delete this on expiration ? */
  deleteAtExpiration?: boolean;
  /** The internal name of your license */
  readonly domain?: string;
  /** The ip on which this license is attached */
  readonly ip?: Ipv4OVH;
  /** The license id on license provider side */
  readonly licenseId?: string;
  /** This license state */
  readonly status?: LicenseStateEnumOVH;
  /** This license version */
  readonly version?: LicenseCpanelVersionEnumOVH;
}

/**
 * The serviceTypes allowed to Order a CPanel version
 */
export interface LicenseCpanelOrderConfigurationOVH {
  orderableVersions?: LicenseOrderableCpanelCompatibilityInfosOVH[];
  serviceType?: LicenseLicenseTypeEnumOVH;
}

/**
 * Messages from change IP
 */
export type LicenseChangeIpMessageEnumOVH = typeof LicenseChangeIpMessageEnumOVH[keyof typeof LicenseChangeIpMessageEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseChangeIpMessageEnumOVH = {
  OK: 'OK',
  destinationNotAllowed: 'destinationNotAllowed',
  licenseAlreadyExists: 'licenseAlreadyExists',
  notAllowedToHandleThis: 'notAllowedToHandleThis',
  notSameType: 'notSameType',
  sameIp: 'sameIp',
  versionNotAllowed: 'versionNotAllowed',
} as const;

/**
 * License change ip status return
 */
export interface LicenseChangeIpStatusOVH {
  message?: LicenseChangeIpMessageEnumOVH;
  success?: boolean;
}

/**
 * A short description of what does the Task on your license
 */
export type LicenseActionTypeOVH = typeof LicenseActionTypeOVH[keyof typeof LicenseActionTypeOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseActionTypeOVH = {
  addWindowFromExistingSerial: 'addWindowFromExistingSerial',
  changeIp: 'changeIp',
  changeOs: 'changeOs',
  installLicense: 'installLicense',
  optionUpgrade: 'optionUpgrade',
  releaseOption: 'releaseOption',
  versionUpgrade: 'versionUpgrade',
} as const;

/**
 * IPv6 CIDR notation (e.g., 2001:41d0::/128)
 */
export type Ipv6BlockOVH = string;

/**
 * IPv6 address (e.g., 2001:41d0:1:1994::1)
 */
export type Ipv6OVH = string;

/**
 * IPv4 CIDR notation (e.g., 192.0.2.0/24)
 */
export type Ipv4BlockOVH = string;

/**
 * IPv4 address (e.g., 192.0.2.0)
 */
export type Ipv4OVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpInterfaceOVH = string;

/**
 * IP (v4 or v6) CIDR notation (e.g., 192.0.2.0/24)
 */
export type IpBlockOVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpOVH = string;

/**
 * International phone number
 */
export type InternationalPhoneNumberOVH = string;

/**
 * Operator that can be used in order to filter resources tags
 */
export type IamResourceTagFilterOperatorEnumOVH = typeof IamResourceTagFilterOperatorEnumOVH[keyof typeof IamResourceTagFilterOperatorEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IamResourceTagFilterOperatorEnumOVH = {
  EQ: 'EQ',
  EXISTS: 'EXISTS',
  ILIKE: 'ILIKE',
  LIKE: 'LIKE',
  NEQ: 'NEQ',
  NEXISTS: 'NEXISTS',
} as const;

/**
 * Operator to use in order to filter on the value (defaults to 'EQ')
 * @nullable
 */
export type IamResourceTagFilterOVHOperator = IamResourceTagFilterOperatorEnumOVH | null;

/**
 * Resource tag filter
 */
export interface IamResourceTagFilterOVH {
  /**
   * Operator to use in order to filter on the value (defaults to 'EQ')
   * @nullable
   */
  readonly operator?: IamResourceTagFilterOVHOperator;
  /** Value to use in order to filter tags */
  readonly value?: string;
}

/**
 * Resource tags. Tags that were internally computed are prefixed with ovh:
 * @nullable
 */
export type IamResourceMetadataOVHTags = {[key: string]: string} | null;

/**
 * IAM resource metadata embedded in services models
 */
export interface IamResourceMetadataOVH {
  /**
   * Resource display name
   * @nullable
   */
  readonly displayName?: string | null;
  /** Unique identifier of the resource */
  readonly id?: string;
  /**
   * Resource tags. Tags that were internally computed are prefixed with ovh:
   * @nullable
   */
  readonly tags?: IamResourceMetadataOVHTags;
  /** Unique resource name used in policies */
  readonly urn?: string;
}

/**
 * Email address (e.g., api@ml.ovh.net)
 */
export type EmailOVH = string;

/**
 * Duration (e.g., P1Y2M3DT4H6M9S)
 */
export type DurationOVH = string;

