export const GUIDES = {
  additional_public_ips: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/additional-ip-vs-floating-ip/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/21134381741715-Concepts-Additional-IP-or-Floating-IP',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/additional-ip-vs-floating-ip/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/additional-ip-vs-floating-ip/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/additional-ip-vs-floating-ip/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/additional-ip-vs-floating-ip/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/additional-ip-vs-floating-ip/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/public-cloud/failover-ip-vs-floating-ip/',
  },
  configure_additional_ip: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/configure-additional-ip/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/configure-additional-ip/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/configure-additional-ip/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/configure-additional-ip/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/configure-additional-ip/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/configure-additional-ip/',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/19770592015891-Configuring-an-Additional-IP-for-OVHcloud-Public-Cloud-Projects',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/configure-additional-ip/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/configure-additional-ip/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/configure-additional-ip/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/configure-additional-ip/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/configure-additional-ip/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/publiccloud/network-services/configure-additional-ip/',
  },
  configure_floating_ip: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/18466423089811-How-to-Attach-a-Floating-IP-to-a-Public-Cloud-Instance',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/public-cloud/attaching-pci-floating-ip-to-instance/',
  },
};
