export const GUIDES = {
  additional_public_ips: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/additional-ip-vs-floating-ip/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    US:
      'https://docs.ovh.com/us/en/publiccloud/network-services/additional-ip-vs-floating-ip/',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/additional-ip-vs-floating-ip/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/additional-ip-vs-floating-ip/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/additional-ip-vs-floating-ip/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/additional-ip-vs-floating-ip/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/additional-ip-vs-floating-ip/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/public-cloud/failover-ip-vs-floating-ip/',
  },
  configure_additional_ip: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/configure-additional-ip/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/configure-additional-ip/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/configure-additional-ip/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/configure-additional-ip/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/configure-additional-ip/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/configure-additional-ip/',
    US:
      'https://docs.ovh.com/us/en/publiccloud/network-services/configure-additional-ip/',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/configure-additional-ip/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/configure-additional-ip/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/configure-additional-ip/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/configure-additional-ip/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/configure-additional-ip/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/publiccloud/network-services/configure-additional-ip/',
  },
  configure_floating_ip: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    US:
      'https://docs.ovh.com/us/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/public-cloud/attaching-pci-floating-ip-to-instance/',
  },
};
