export const PRIVATE_NETWORK_HELP = {
  DEFAULT:
    'https://docs.ovh.com/gb/en/publiccloud/network-services/networking-concepts/',
  ASIA:
    'https://docs.ovh.com/asia/en/publiccloud/network-services/networking-concepts/',
  AU:
    'https://docs.ovh.com/au/en/publiccloud/network-services/networking-concepts/',
  CA:
    'https://docs.ovh.com/ca/en/publiccloud/network-services/networking-concepts/',
  DE:
    'https://docs.ovh.com/de/publiccloud/network-services/networking-concepts/',
  ES:
    'https://docs.ovh.com/es/publiccloud/network-services/networking-concepts/',
  FR:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  GB:
    'https://docs.ovh.com/gb/en/publiccloud/network-services/networking-concepts/',
  IE:
    'https://docs.ovh.com/ie/en/publiccloud/network-services/networking-concepts/',
  IT:
    'https://docs.ovh.com/it/publiccloud/network-services/networking-concepts/',
  MA:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  NL:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  PL:
    'https://docs.ovh.com/pl/publiccloud/network-services/networking-concepts/',
  PT:
    'https://docs.ovh.com/pt/publiccloud/network-services/networking-concepts/',
  QC:
    'https://docs.ovh.com/ca/fr/publiccloud/network-services/networking-concepts/',
  SN:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  SG:
    'https://docs.ovh.com/sg/en/publiccloud/network-services/networking-concepts/',
  TN:
    'https://docs.ovh.com/fr/publiccloud/network-services/networking-concepts/',
  US:
    'https://docs.ovh.com/us/en/publiccloud/network-services/networking-concepts/',
  WE:
    'https://docs.ovh.com/asia/en/publiccloud/network-services/networking-concepts/',
  WS:
    'https://docs.ovh.com/us/es/publiccloud/network-services/networking-concepts/',
};

export default {
  PRIVATE_NETWORK_HELP,
};
