export const LABELS = {
  MAX_RETRIES_DOWN: 'Max Retries Down',
  MAX_RETRIES: 'Max Retries',
  PERIODICITY: 'Periodicity',
  TIMEOUT: 'Timeout',
  URLPATH: 'URL Path',
};

export const BOUNDS = {
  MAX_RETRIES_DOWN: {
    MIN: 1,
    MAX: 10,
  },
  MAX_RETRIES: {
    MIN: 1,
    MAX: 10,
  },
  PERIODICITY: {
    MIN: 1,
  },
  TIMEOUT: {
    MIN: 0,
  },
};

export const HEALTH_MONITOR_NAME_REGEX = /^[A-Za-z0-9_.-]+$/;
export const EXPECTED_STATUS_CODE_REGEX = /^[1-5][0-9]{2}$/;

export const HEALTH_MONITOR_TYPE = {
  HTTP: 'http',
  HTTPS: 'https',
  PING: 'ping',
  SCTP: 'sctp',
  TCP: 'tcp',
  TLSHELLO: 'tls-hello',
  UDPCONNECT: 'udp-connect',
};

export const POOL_HEALTH_MONITOR_TYPE = {
  http: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.HTTPS,
    HEALTH_MONITOR_TYPE.PING,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.TLSHELLO,
  ],
  https: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.HTTPS,
    HEALTH_MONITOR_TYPE.PING,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.TLSHELLO,
  ],
  proxy: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.HTTPS,
    HEALTH_MONITOR_TYPE.PING,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.TLSHELLO,
  ],
  proxyV2: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.HTTPS,
    HEALTH_MONITOR_TYPE.PING,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.TLSHELLO,
  ],
  sctp: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.SCTP,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.UDPCONNECT,
  ],
  tcp: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.HTTPS,
    HEALTH_MONITOR_TYPE.PING,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.TLSHELLO,
  ],
  udp: [
    HEALTH_MONITOR_TYPE.HTTP,
    HEALTH_MONITOR_TYPE.SCTP,
    HEALTH_MONITOR_TYPE.TCP,
    HEALTH_MONITOR_TYPE.UDPCONNECT,
  ],
};

export default {
  LABELS,
  BOUNDS,
  HEALTH_MONITOR_NAME_REGEX,
  POOL_HEALTH_MONITOR_TYPE,
  HEALTH_MONITOR_TYPE,
};
