export const CREDITCARD_FOOTPRINT_AMOUNT = '1€';
export const PAYMENT_RUPAY_CREDIT_CARD_CHARGES_FEATURE_ID =
  'payments:rupay-message';

export default {
  CREDITCARD_FOOTPRINT_AMOUNT,
  PAYMENT_RUPAY_CREDIT_CARD_CHARGES_FEATURE_ID,
};
