export const CREDITCARD_FOOTPRINT_AMOUNT = '1€';
export const PAYMENT_RUPAY_CREDIT_CARD_CHARGES_FEATURE_ID =
  'payments:rupay-message';
export const CHARGES = 2;

export default {
  CREDITCARD_FOOTPRINT_AMOUNT,
  PAYMENT_RUPAY_CREDIT_CARD_CHARGES_FEATURE_ID,
  CHARGES,
};

export const GlobalStatePaymentMethodStatus = Object.freeze({
  PROCESSING: 'PROCESSING',
  REGISTERED: 'REGISTERED',
  ERROR: 'ERROR',
  PENDING: 'PENDING',
  CHALLENGE_WAITING: 'CHALLENGE_WAITING',
  CHALLENGE_OK: 'CHALLENGE_OK',
  CHALLENGE_ERROR: 'CHALLENGE_ERROR',
  CHALLENGE_CANCELED: 'CHALLENGE_CANCELED',
  CHALLENGE_REFUSED: 'CHALLENGE_REFUSED',
  PAYMENT_METHOD_SAVED: 'PAYMENT_METHOD_SAVED',
});

export const GlobalStateComponentStatus = Object.freeze({
  REDIRECTION_NEEDED: 'REDIRECTION_NEEDED',
  ERROR: 'ERROR',
});
