export const PAYMENT_METHOD_AUTHORIZED_ENUM = {
  BANK_ACCOUNT: 'bankAccount',
  CREDIT: 'credit',
  CREDIT_CARD: 'creditCard',
  PAYPAL: 'paypal',
  RUPAY: 'rupay',
};

export const PREFERRED_PAYMENT_METHOD_ORDER = [
  PAYMENT_METHOD_AUTHORIZED_ENUM.CREDIT_CARD,
  PAYMENT_METHOD_AUTHORIZED_ENUM.PAYPAL,
  PAYMENT_METHOD_AUTHORIZED_ENUM.BANK_ACCOUNT,
  PAYMENT_METHOD_AUTHORIZED_ENUM.CREDIT,
  PAYMENT_METHOD_AUTHORIZED_ENUM.RUPAY,
];

export default {
  PAYMENT_METHOD_AUTHORIZED_ENUM,
  PREFERRED_PAYMENT_METHOD_ORDER,
};
