export const GUIDES = {
  create_private_network_with_gateway: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/creating-private-network-with-gateway/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/creating-private-network-with-gateway/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/creating-private-network-with-gateway/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/creating-private-network-with-gateway/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/creating-private-network-with-gateway/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/creating-private-network-with-gateway/',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/18534335915667-How-to-Create-a-Private-Network-with-a-Gateway',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/creating-private-network-with-gateway/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/creating-private-network-with-gateway/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/creating-private-network-with-gateway/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/creating-private-network-with-gateway/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/creating-private-network-with-gateway/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/publiccloud/network-services/creating-private-network-with-gateway/',
  },
  attach_pci_floating_ip_to_instance: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/18466423089811-How-to-Attach-a-Floating-IP-to-a-Public-Cloud-Instance',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/attaching-pci-floating-ip-to-instance/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/public-cloud/attaching-pci-floating-ip-to-instance/',
  },
  start_load_balancer_service: {
    DE:
      'https://docs.ovh.com/de/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    ASIA:
      'https://docs.ovh.com/asia/en/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    AU:
      'https://docs.ovh.com/au/en/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    CA:
      'https://docs.ovh.com/ca/en/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    IE:
      'https://docs.ovh.com/ie/en/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    SG:
      'https://docs.ovh.com/sg/en/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/18610207964051-Getting-Started-with-Load-Balancer-on-Public-Cloud',
    ES:
      'https://docs.ovh.com/es/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    FR:
      'https://docs.ovh.com/fr/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    IT:
      'https://docs.ovh.com/it/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    PL:
      'https://docs.ovh.com/pl/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    PT:
      'https://docs.ovh.com/pt/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
    DEFAULT:
      'https://docs.ovh.com/gb/en/publiccloud/network-services/getting-started-with-load-balancer-public-cloud/',
  },
};
export const DELETING_STATUS = ['DELETING'];
