import {
  TIMEPICKER_I18N,
  TIMEZONE,
  TIMEZONES,
  TIMEZONES_PRESET,
  TIMEZONES_PRESETS,
} from '@ovhcloud/ods-react';

export { TIMEPICKER_I18N, TIMEZONE, TIMEZONES, TIMEZONES_PRESET, TIMEZONES_PRESETS };
