/** List of capabilities available for services */
export enum CapabilityEnum {
  'advancedConfiguration' = 'advancedConfiguration',
  'backupRestore' = 'backupRestore',
  'backupTime' = 'backupTime',
  'backups' = 'backups',
  'certificates' = 'certificates',
  'connectionPools' = 'connectionPools',
  'currentQueries' = 'currentQueries',
  'currentQueriesCancel' = 'currentQueriesCancel',
  'databases' = 'databases',
  'enableWrites' = 'enableWrites',
  'fork' = 'fork',
  'integrations' = 'integrations',
  'ipRestrictions' = 'ipRestrictions',
  'maintenanceApply' = 'maintenanceApply',
  'maintenanceTime' = 'maintenanceTime',
  'maintenances' = 'maintenances',
  'namespaces' = 'namespaces',
  'nodes' = 'nodes',
  'queryStatistics' = 'queryStatistics',
  'queryStatisticsReset' = 'queryStatisticsReset',
  'service' = 'service',
  'userCredentialsReset' = 'userCredentialsReset',
  'users' = 'users',
}
