/** List of capabilities available for services */
export enum CapabilityEnum {
  'advancedConfiguration' = 'advancedConfiguration',
  'backupRestore' = 'backupRestore',
  'backupTime' = 'backupTime',
  'backups' = 'backups',
  'certificates' = 'certificates',
  'connectionPools' = 'connectionPools',
  'currentQueries' = 'currentQueries',
  'currentQueriesCancel' = 'currentQueriesCancel',
  'databases' = 'databases',
  'deletionProtection' = 'deletionProtection',
  'enableWrites' = 'enableWrites',
  'fork' = 'fork',
  'indexes' = 'indexes',
  'integrations' = 'integrations',
  'ipRestrictions' = 'ipRestrictions',
  'maintenanceApply' = 'maintenanceApply',
  'maintenanceTime' = 'maintenanceTime',
  'maintenances' = 'maintenances',
  'namespaces' = 'namespaces',
  'nodes' = 'nodes',
  'patterns' = 'pattern',
  'prometheus' = 'prometheus',
  'prometheusCredentialsReset' = 'prometheusCredentialsReset',
  'queryStatistics' = 'queryStatistics',
  'queryStatisticsReset' = 'queryStatisticsReset',
  'service' = 'service',
  'userCredentialsReset' = 'userCredentialsReset',
  'userAcls' = 'userAcls',
  'users' = 'users',
  'restApi' = 'restApi',
  'schemaRegistry' = 'schemaRegistry',
  'topics' = 'topics',
  'userAccess' = 'userAccess',
}
