/** Supported unit types for metrics */
export enum MetricUnitEnum {
  'BYTES' = 'BYTES',
  'BYTES_PER_SECOND' = 'BYTES_PER_SECOND',
  'GIGABYTES' = 'GIGABYTES',
  'GIGABYTES_PER_HOUR' = 'GIGABYTES_PER_HOUR',
  'MEGABYTES' = 'MEGABYTES',
  'MEGABYTES_PER_SECOND' = 'MEGABYTES_PER_SECOND',
  'MILLISECONDS' = 'MILLISECONDS',
  'PERCENT' = 'PERCENT',
  'SCALAR' = 'SCALAR',
  'SCALAR_PER_SECOND' = 'SCALAR_PER_SECOND',
  'SECONDS' = 'SECONDS',
  'UNKNOWN' = 'UNKNOWN',
}
