export const GUIDES = [
  {
    title: 'veeam_onboarding_guide1_title',
    description: 'veeam_onboarding_guide1_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/veeam-cloud-connect/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/veeam-cloud-connect/',
      DE: 'https://docs.ovh.com/de/storage/veeam-cloud-connect/',
      ES: 'https://docs.ovh.com/es/storage/veeam-cloud-connect/',
      IE: 'https://docs.ovh.com/ie/en/storage/veeam-cloud-connect/',
      IT: 'https://docs.ovh.com/it/storage/veeam-cloud-connect/',
      PL: 'https://docs.ovh.com/pl/storage/veeam-cloud-connect/',
      PT: 'https://docs.ovh.com/pt/storage/veeam-cloud-connect/',
      GB: 'https://docs.ovh.com/gb/en/storage/veeam-cloud-connect/',
      CA: 'https://docs.ovh.com/ca/en/storage/veeam-cloud-connect/',
      QC: 'https://docs.ovh.com/ca/fr/storage/veeam-cloud-connect/',
      AU: 'https://docs.ovh.com/au/en/storage/veeam-cloud-connect/',
      SG: 'https://docs.ovh.com/sg/en/storage/veeam-cloud-connect/',
      FR: 'https://docs.ovh.com/fr/storage/veeam-cloud-connect/',
      WE: 'https://docs.ovh.com/us/en/storage/veeam-cloud-connect/',
      WS: 'https://docs.ovh.com/us/en/storage/veeam-cloud-connect/',
      US: 'https://docs.ovh.com/us/en/storage/veeam-cloud-connect/',
    },
  },
];

export const CTAS = {
  DEFAULT: 'https://ovhcloud.com/en/storage-solutions/veeam-cloud-connect',
  ASIA: 'https://ovhcloud.com/asia/storage-solutions/veeam-cloud-connect',
  IN: 'https://www.ovhcloud.com/en-in/storage-solutions/veeam-cloud-connect',
  DE: 'https://ovhcloud.com/de/storage-solutions/veeam-cloud-connect',
  ES: 'https://ovhcloud.com/es-es/storage-solutions/veeam-cloud-connect',
  IE: 'https://ovhcloud.com/en-ie/storage-solutions/veeam-cloud-connect',
  IT: 'https://ovhcloud.com/it/storage-solutions/veeam-cloud-connect',
  NL: 'https://ovhcloud.com/nl/storage-solutions/veeam-cloud-connect',
  PL: 'https://ovhcloud.com/pl/storage-solutions/veeam-cloud-connect',
  PT: 'https://ovhcloud.com/pt/storage-solutions/veeam-cloud-connect',
  GB: 'https://ovhcloud.com/en-gb/storage-solutions/veeam-cloud-connect',
  CA: 'https://ovhcloud.com/en-ca/storage-solutions/veeam-cloud-connect',
  QC: 'https://ovhcloud.com/fr-ca/storage-solutions/veeam-cloud-connect',
  MA: 'https://ovhcloud.com/fr-ma/storage-solutions/veeam-cloud-connect',
  SN: 'https://ovhcloud.com/fr-sn/storage-solutions/veeam-cloud-connect',
  TN: 'https://ovhcloud.com/fr-tn/storage-solutions/veeam-cloud-connect',
  AU: 'https://ovhcloud.com/en-au/storage-solutions/veeam-cloud-connect',
  SG: 'https://ovhcloud.com/en-sg/storage-solutions/veeam-cloud-connect',
  FR: 'https://ovhcloud.com/fr/storage-solutions/veeam-cloud-connect',
  WE: 'https://ovhcloud.com/en/storage-solutions/veeam-cloud-connect',
  WS: 'https://ovhcloud.com/es/storage-solutions/veeam-cloud-connect',
};
