/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OVHcloud API specification
 * Specification for OVHcloud API
 * OpenAPI spec version: 1.0
 */
export type GetLicensePleskServiceNameTasksParams = {
/**
 * Filter the value of action property (=)
 */
action?: LicenseActionTypeOVH;
/**
 * Filter the value of status property (=)
 */
status?: LicenseTaskStateEnumOVH;
};

export type PostLicensePleskServiceNameConfirmTerminationBody = {
  /** Commentary about your termination request */
  commentary?: string;
  /** What next after your termination request */
  futureUse?: ServiceTerminationFutureUseEnumOVH;
  /** Reason of your termination request */
  reason?: ServiceTerminationReasonEnumOVH;
  /** The termination token sent by email to the admin contact */
  token: string;
};

export type PostLicensePleskServiceNameChangeIpBody = {
  /** The Ip on which you want to move this license */
  destinationIp: Ipv4OVH;
};

export type GetLicensePleskServiceNameCanLicenseBeMovedToParams = {
/**
 * The Ip on which you want to move this license
 */
destinationIp: Ipv4OVH;
};

export type GetLicensePleskOrderableVersionsParams = {
/**
 * Your license Ip
 */
ip: Ipv4OVH;
};

export type GetLicensePleskParams = {
/**
 * Filter resources on IAM tags
 */
iamTags?: {[key: string]: IamResourceTagFilterOVH[]};
};

/**
 * Time (e.g., 15:04:05)
 */
export type TimeOVH = string;

/**
 * Way of handling the renew
 * @nullable
 */
export type ServicesServiceOVHRenew = ServiceRenewTypeOVH | null;

/**
 * Details about a Service
 */
export interface ServicesServiceOVH {
  /** Indicates that the service can be set up to be deleted at expiration */
  readonly canDeleteAtExpiration?: boolean;
  readonly contactAdmin?: string;
  readonly contactBilling?: string;
  readonly contactTech?: string;
  readonly creation?: string;
  readonly domain?: string;
  /** @nullable */
  readonly engagedUpTo?: string | null;
  readonly expiration?: string;
  /**
   * All the possible renew period of your service in month
   * @nullable
   */
  readonly possibleRenewPeriod?: readonly number[] | null;
  /**
   * Way of handling the renew
   * @nullable
   */
  renew?: ServicesServiceOVHRenew;
  readonly renewalType?: ServiceRenewalTypeEnumOVH;
  readonly serviceId?: number;
  readonly status?: ServiceStateEnumOVH;
}

/**
 * All reasons you can provide for a service termination
 */
export type ServiceTerminationReasonEnumOVH = typeof ServiceTerminationReasonEnumOVH[keyof typeof ServiceTerminationReasonEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTerminationReasonEnumOVH = {
  FEATURES_DONT_SUIT_ME: 'FEATURES_DONT_SUIT_ME',
  LACK_OF_PERFORMANCES: 'LACK_OF_PERFORMANCES',
  MIGRATED_TO_ANOTHER_OVH_PRODUCT: 'MIGRATED_TO_ANOTHER_OVH_PRODUCT',
  MIGRATED_TO_COMPETITOR: 'MIGRATED_TO_COMPETITOR',
  NOT_ENOUGH_RECOGNITION: 'NOT_ENOUGH_RECOGNITION',
  NOT_NEEDED_ANYMORE: 'NOT_NEEDED_ANYMORE',
  NOT_RELIABLE: 'NOT_RELIABLE',
  NO_ANSWER: 'NO_ANSWER',
  OTHER: 'OTHER',
  PRODUCT_DIMENSION_DONT_SUIT_ME: 'PRODUCT_DIMENSION_DONT_SUIT_ME',
  PRODUCT_TOOLS_DONT_SUIT_ME: 'PRODUCT_TOOLS_DONT_SUIT_ME',
  TOO_EXPENSIVE: 'TOO_EXPENSIVE',
  TOO_HARD_TO_USE: 'TOO_HARD_TO_USE',
  UNSATIFIED_BY_CUSTOMER_SUPPORT: 'UNSATIFIED_BY_CUSTOMER_SUPPORT',
} as const;

/**
 * All future uses you can provide for a service termination
 */
export type ServiceTerminationFutureUseEnumOVH = typeof ServiceTerminationFutureUseEnumOVH[keyof typeof ServiceTerminationFutureUseEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTerminationFutureUseEnumOVH = {
  NOT_REPLACING_SERVICE: 'NOT_REPLACING_SERVICE',
  OTHER: 'OTHER',
  SUBSCRIBE_AN_OTHER_SERVICE: 'SUBSCRIBE_AN_OTHER_SERVICE',
  SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR: 'SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR',
  SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR: 'SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR',
} as const;

export type ServiceStateEnumOVH = typeof ServiceStateEnumOVH[keyof typeof ServiceStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceStateEnumOVH = {
  autorenewInProgress: 'autorenewInProgress',
  expired: 'expired',
  inCreation: 'inCreation',
  ok: 'ok',
  pendingDebt: 'pendingDebt',
  unPaid: 'unPaid',
} as const;

/**
 * Detailed renewal type of a service
 */
export type ServiceRenewalTypeEnumOVH = typeof ServiceRenewalTypeEnumOVH[keyof typeof ServiceRenewalTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRenewalTypeEnumOVH = {
  automaticForcedProduct: 'automaticForcedProduct',
  automaticV2012: 'automaticV2012',
  automaticV2014: 'automaticV2014',
  automaticV2016: 'automaticV2016',
  automaticV2024: 'automaticV2024',
  manual: 'manual',
  oneShot: 'oneShot',
  option: 'option',
} as const;

/**
 * Map a possible renew for a specific service
 */
export interface ServiceRenewTypeOVH {
  /** The service is automatically renewed */
  automatic?: boolean;
  /** The service will be deleted at expiration */
  deleteAtExpiration?: boolean;
  /** The service forced to be renewed */
  forced?: boolean;
  /**
   * The service needs to be manually renewed and paid
   * @nullable
   */
  manualPayment?: boolean | null;
  /**
   * period of renew in month
   * @nullable
   */
  period?: number | null;
}

/**
 * Phone number
 */
export type PhoneNumberOVH = string;

/**
 * MAC address (e.g., 2001:4860:4860::8844)
 */
export type MacAddressOVH = string;

/**
 * IAM resource metadata
 * @nullable
 */
export type LicensePleskPleskWithIAMOVHIam = IamResourceMetadataOVH | null;

/**
 * The amount of domain this license can manage
 * @nullable
 */
export type LicensePleskPleskWithIAMOVHDomainNumber = LicenseDomainNumberEnumOVH | null;

/**
 * The amount of domain this license can manage
 * @nullable
 */
export type LicensePleskPleskOVHDomainNumber = LicenseDomainNumberEnumOVH | null;

/**
 * All states a license Task can be in
 */
export type LicenseTaskStateEnumOVH = typeof LicenseTaskStateEnumOVH[keyof typeof LicenseTaskStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseTaskStateEnumOVH = {
  cancelled: 'cancelled',
  doing: 'doing',
  done: 'done',
  error: 'error',
  todo: 'todo',
} as const;

/**
 * All states a license can be in
 */
export type LicenseStateEnumOVH = typeof LicenseStateEnumOVH[keyof typeof LicenseStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseStateEnumOVH = {
  ok: 'ok',
  released: 'released',
  terminated: 'terminated',
  toDeliver: 'toDeliver',
} as const;

/**
 * Tests that have failed for Plesk products
 */
export type LicensePotentialProblemPleskEnumOVH = typeof LicensePotentialProblemPleskEnumOVH[keyof typeof LicensePotentialProblemPleskEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicensePotentialProblemPleskEnumOVH = {
  isHostOsHyperVLike: 'isHostOsHyperVLike',
  isHostOsVMwareLike: 'isHostOsVMwareLike',
  isHostOsVirtuozzo4Like: 'isHostOsVirtuozzo4Like',
  isHostOsXenLike: 'isHostOsXenLike',
  isLinuxOs: 'isLinuxOs',
  isOsCloudLinux: 'isOsCloudLinux',
  isOsPlesk10andLater: 'isOsPlesk10andLater',
  isOsPlesk12: 'isOsPlesk12',
  isOsPleskOnyx: 'isOsPleskOnyx',
  isWindowsOs: 'isWindowsOs',
} as const;

/**
 * All versions available for Plesk products
 */
export type LicensePleskVersionEnumOVH = typeof LicensePleskVersionEnumOVH[keyof typeof LicensePleskVersionEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicensePleskVersionEnumOVH = {
  PLESK_10_AND_LATER: 'PLESK_10_AND_LATER',
  PLESK_10_AND_LATER_FOR_KVM: 'PLESK_10_AND_LATER_FOR_KVM',
  PLESK_10_AND_LATER_FOR_VMWARE: 'PLESK_10_AND_LATER_FOR_VMWARE',
  PLESK_10_AND_LATER_FOR_VZ: 'PLESK_10_AND_LATER_FOR_VZ',
  PLESK_10_AND_LATER_FOR_WIN: 'PLESK_10_AND_LATER_FOR_WIN',
  PLESK_10_AND_LATER_FOR_WIN_FOR_VMWARE: 'PLESK_10_AND_LATER_FOR_WIN_FOR_VMWARE',
  PLESK_10_AND_LATER_FOR_WIN_FOR_VZ: 'PLESK_10_AND_LATER_FOR_WIN_FOR_VZ',
  PLESK_10_AND_LATER_FOR_WIN_FOR_XEN: 'PLESK_10_AND_LATER_FOR_WIN_FOR_XEN',
  PLESK_10_AND_LATER_FOR_XEN: 'PLESK_10_AND_LATER_FOR_XEN',
  PLESK_12_VPS_WEB_ADMIN: 'PLESK_12_VPS_WEB_ADMIN',
  PLESK_12_VPS_WEB_APP: 'PLESK_12_VPS_WEB_APP',
  PLESK_12_VPS_WEB_HOST: 'PLESK_12_VPS_WEB_HOST',
  PLESK_12_VPS_WEB_HOST_CLNX: 'PLESK_12_VPS_WEB_HOST_CLNX',
  PLESK_12_VPS_WEB_PRO: 'PLESK_12_VPS_WEB_PRO',
  PLESK_12_VPS_WEB_PRO_CLNX: 'PLESK_12_VPS_WEB_PRO_CLNX',
  PLESK_12_WEB_ADMIN: 'PLESK_12_WEB_ADMIN',
  PLESK_12_WEB_APP: 'PLESK_12_WEB_APP',
  PLESK_12_WEB_HOST: 'PLESK_12_WEB_HOST',
  PLESK_12_WEB_HOST_CLNX: 'PLESK_12_WEB_HOST_CLNX',
  PLESK_12_WEB_PRO: 'PLESK_12_WEB_PRO',
  PLESK_12_WEB_PRO_CLNX: 'PLESK_12_WEB_PRO_CLNX',
  PLESK_75_RELOADED: 'PLESK_75_RELOADED',
  PLESK_80: 'PLESK_80',
  PLESK_80_FOR_VZ: 'PLESK_80_FOR_VZ',
  PLESK_81_FOR_WIN: 'PLESK_81_FOR_WIN',
  PLESK_9: 'PLESK_9',
  PLESK_95: 'PLESK_95',
  PLESK_95_FOR_VZ: 'PLESK_95_FOR_VZ',
  PLESK_95_FOR_WIN: 'PLESK_95_FOR_WIN',
  PLESK_9_FOR_VZ: 'PLESK_9_FOR_VZ',
  PLESK_9_FOR_WIN: 'PLESK_9_FOR_WIN',
  PLESK_ONYX_VPS_WEB_ADMIN: 'PLESK_ONYX_VPS_WEB_ADMIN',
  PLESK_ONYX_VPS_WEB_APP: 'PLESK_ONYX_VPS_WEB_APP',
  PLESK_ONYX_VPS_WEB_HOST: 'PLESK_ONYX_VPS_WEB_HOST',
  PLESK_ONYX_VPS_WEB_HOST_CLNX: 'PLESK_ONYX_VPS_WEB_HOST_CLNX',
  PLESK_ONYX_VPS_WEB_PRO: 'PLESK_ONYX_VPS_WEB_PRO',
  PLESK_ONYX_VPS_WEB_PRO_CLNX: 'PLESK_ONYX_VPS_WEB_PRO_CLNX',
  PLESK_ONYX_WEB_ADMIN: 'PLESK_ONYX_WEB_ADMIN',
  PLESK_ONYX_WEB_APP: 'PLESK_ONYX_WEB_APP',
  PLESK_ONYX_WEB_HOST: 'PLESK_ONYX_WEB_HOST',
  PLESK_ONYX_WEB_HOST_CLNX: 'PLESK_ONYX_WEB_HOST_CLNX',
  PLESK_ONYX_WEB_PRO: 'PLESK_ONYX_WEB_PRO',
  PLESK_ONYX_WEB_PRO_CLNX: 'PLESK_ONYX_WEB_PRO_CLNX',
  'plesk-12-webadmin': 'plesk-12-webadmin',
  'plesk-12-webadmin-for-vps': 'plesk-12-webadmin-for-vps',
  'plesk-12-webhost': 'plesk-12-webhost',
  'plesk-12-webhost-for-vps': 'plesk-12-webhost-for-vps',
  'plesk-12-webpro': 'plesk-12-webpro',
  'plesk-12-webpro-for-vps': 'plesk-12-webpro-for-vps',
} as const;

/**
 * Your Plesk license
 */
export interface LicensePleskPleskWithIAMOVH {
  /** This license creation date */
  readonly creation?: string;
  /** Shall we delete this on expiration ? */
  deleteAtExpiration?: boolean;
  /** The internal name of your license */
  readonly domain?: string;
  /**
   * The amount of domain this license can manage
   * @nullable
   */
  readonly domainNumber?: LicensePleskPleskWithIAMOVHDomainNumber;
  /**
   * IAM resource metadata
   * @nullable
   */
  readonly iam?: LicensePleskPleskWithIAMOVHIam;
  /**
   * This license Information key
   * @nullable
   */
  readonly informationKey?: string | null;
  /** The ip on which this license is attached */
  readonly ip?: Ipv4OVH;
  /** This license key */
  readonly key?: string;
  /** The license id on license provider side */
  readonly licenseId?: string;
  /**
   * This license product key
   * @nullable
   */
  readonly productKey?: string | null;
  /** This license state */
  readonly status?: LicenseStateEnumOVH;
  /** This license version */
  readonly version?: LicensePleskVersionEnumOVH;
}

/**
 * Your Plesk license
 */
export interface LicensePleskPleskOVH {
  /** This license creation date */
  readonly creation?: string;
  /** Shall we delete this on expiration ? */
  deleteAtExpiration?: boolean;
  /** The internal name of your license */
  readonly domain?: string;
  /**
   * The amount of domain this license can manage
   * @nullable
   */
  readonly domainNumber?: LicensePleskPleskOVHDomainNumber;
  /**
   * This license Information key
   * @nullable
   */
  readonly informationKey?: string | null;
  /** The ip on which this license is attached */
  readonly ip?: Ipv4OVH;
  /** This license key */
  readonly key?: string;
  /** The license id on license provider side */
  readonly licenseId?: string;
  /**
   * This license product key
   * @nullable
   */
  readonly productKey?: string | null;
  /** This license state */
  readonly status?: LicenseStateEnumOVH;
  /** This license version */
  readonly version?: LicensePleskVersionEnumOVH;
}

/**
 * The serviceTypes allowed to Order a plesk version and associated Versions
 */
export interface LicensePleskOrderConfigurationOVH {
  orderableVersions?: LicenseOrderablePleskCompatibilityInfosOVH[];
  serviceType?: LicenseLicenseTypeEnumOVH;
}

/**
 * Application set available for Plesk products
 */
export type LicensePleskApplicationSetEnumOVH = typeof LicensePleskApplicationSetEnumOVH[keyof typeof LicensePleskApplicationSetEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicensePleskApplicationSetEnumOVH = {
  applicationpack: 'applicationpack',
  developerpack: 'developerpack',
  'power-pack-for-plesk12': 'power-pack-for-plesk12',
  powerpack: 'powerpack',
  'developer-pack-for-vps': 'developer-pack-for-vps',
  'power-pack-for-plesk12-for-vps': 'power-pack-for-plesk12-for-vps',
} as const;

/**
 * All language pack numbers available for Plesk products
 */
export type LicenseOrderablePleskLanguagePackEnumOVH = typeof LicenseOrderablePleskLanguagePackEnumOVH[keyof typeof LicenseOrderablePleskLanguagePackEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseOrderablePleskLanguagePackEnumOVH = {
  NUMBER_1: '1',
  '1-extra-language-for-plesk12': '1-extra-language-for-plesk12',
  '1-extra-language-for-plesk12-for-vps': '1-extra-language-for-plesk12-for-vps',
  NUMBER_2: '2',
  '2-extra-languages-for-plesk12': '2-extra-languages-for-plesk12',
  '2-extra-languages-for-plesk12-for-vps': '2-extra-languages-for-plesk12-for-vps',
  NUMBER_3: '3',
  '3-extra-languages-for-plesk12': '3-extra-languages-for-plesk12',
  '3-extra-languages-for-plesk12-for-vps': '3-extra-languages-for-plesk12-for-vps',
  NUMBER_4: '4',
  '4-extra-languages-for-plesk12': '4-extra-languages-for-plesk12',
  '4-extra-languages-for-plesk12-for-vps': '4-extra-languages-for-plesk12-for-vps',
  NUMBER_5: '5',
  '5-extra-languages-for-plesk12': '5-extra-languages-for-plesk12',
  '5-extra-languages-for-plesk12-for-vps': '5-extra-languages-for-plesk12-for-vps',
  unlimited: 'unlimited',
  'unlimited-extra-languages-for-plesk12': 'unlimited-extra-languages-for-plesk12',
  'unlimited-extra-languages-for-plesk12-for-vps': 'unlimited-extra-languages-for-plesk12-for-vps',
} as const;

/**
 * All domain available for Plesk products
 */
export type LicenseOrderablePleskDomainNumberEnumOVH = typeof LicenseOrderablePleskDomainNumberEnumOVH[keyof typeof LicenseOrderablePleskDomainNumberEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseOrderablePleskDomainNumberEnumOVH = {
  NUMBER_10: '10',
  NUMBER_100: '100',
  NUMBER_30: '30',
  NUMBER_300: '300',
  hostingsuite: 'hostingsuite',
  unlimited: 'unlimited',
} as const;

/**
 * All antivirus available for Plesk products
 */
export type LicenseOrderableAntivirusEnumOVH = typeof LicenseOrderableAntivirusEnumOVH[keyof typeof LicenseOrderableAntivirusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseOrderableAntivirusEnumOVH = {
  DR_WEB: 'DR_WEB',
  KASPERSKY_UNLIMITED_MAILBOXES: 'KASPERSKY_UNLIMITED_MAILBOXES',
  kaspersky: 'kaspersky',
  'kaspersky-for-vps': 'kaspersky-for-vps',
} as const;

/**
 * All versions available for Plesk products
 */
export interface LicenseOrderablePleskCompatibilityInfosOVH {
  canHavePowerPack?: boolean;
  canHaveResellerManagement?: boolean;
  canHaveWordpressToolkit?: boolean;
  compliantAntivirus?: LicenseOrderableAntivirusEnumOVH[];
  compliantApplicationSets?: LicensePleskApplicationSetEnumOVH[];
  compliantDomains?: LicenseOrderablePleskDomainNumberEnumOVH[];
  compliantLanguagePack?: LicenseOrderablePleskLanguagePackEnumOVH[];
  potentialProblems?: LicensePotentialProblemPleskEnumOVH[];
  version?: LicensePleskVersionEnumOVH;
}

/**
 * The name of an option currently enabled on your license
 */
export type LicenseOptionLabelOVH = typeof LicenseOptionLabelOVH[keyof typeof LicenseOptionLabelOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseOptionLabelOVH = {
  ANTISPAM_SPAMASSASSIN: 'ANTISPAM_SPAMASSASSIN',
  ANTIVIRUS_DRWEB: 'ANTIVIRUS_DRWEB',
  ANTIVIRUS_KASPERSKY: 'ANTIVIRUS_KASPERSKY',
  DOMAINS: 'DOMAINS',
  LANGUAGE_PACK: 'LANGUAGE_PACK',
  POWERPACK: 'POWERPACK',
  SQL_SERVER: 'SQL_SERVER',
  VIRTUOZZO_CONTAINERS: 'VIRTUOZZO_CONTAINERS',
} as const;

/**
 * Your License options
 */
export interface LicenseOptionOVH {
  /**
   * Quantity or corresponding label of the designated option enabled on your license
   * @nullable
   */
  readonly amount?: string | null;
  /** Specifies whether this option can be released or not */
  readonly canBeDeleted?: boolean;
  /** This option expiration date */
  readonly expirationDate?: string;
  /** This option designation */
  readonly label?: LicenseOptionLabelOVH;
  /**
   * This option related version
   * @nullable
   */
  readonly version?: string | null;
}

/**
 * Possible values for license type
 */
export type LicenseLicenseTypeEnumOVH = typeof LicenseLicenseTypeEnumOVH[keyof typeof LicenseLicenseTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseLicenseTypeEnumOVH = {
  dedicated: 'dedicated',
  dedicatedCloud: 'dedicatedCloud',
  dedicatedFailover: 'dedicatedFailover',
  failover: 'failover',
  vm: 'vm',
  vps: 'vps',
  vps_ceph: 'vps_ceph',
  vps_classic: 'vps_classic',
  vps_cloud: 'vps_cloud',
  vps_cloud_2016: 'vps_cloud_2016',
  vps_ssd: 'vps_ssd',
} as const;

/**
 * All quantities of domain available for a license
 */
export type LicenseDomainNumberEnumOVH = typeof LicenseDomainNumberEnumOVH[keyof typeof LicenseDomainNumberEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseDomainNumberEnumOVH = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_10: '10',
  NUMBER_100: '100',
  NUMBER_30: '30',
  NUMBER_300: '300',
  unlimited: 'unlimited',
} as const;

/**
 * Messages from change IP
 */
export type LicenseChangeIpMessageEnumOVH = typeof LicenseChangeIpMessageEnumOVH[keyof typeof LicenseChangeIpMessageEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseChangeIpMessageEnumOVH = {
  OK: 'OK',
  destinationNotAllowed: 'destinationNotAllowed',
  licenseAlreadyExists: 'licenseAlreadyExists',
  notAllowedToHandleThis: 'notAllowedToHandleThis',
  notSameType: 'notSameType',
  sameIp: 'sameIp',
  versionNotAllowed: 'versionNotAllowed',
} as const;

/**
 * License change ip status return
 */
export interface LicenseChangeIpStatusOVH {
  message?: LicenseChangeIpMessageEnumOVH;
  success?: boolean;
}

/**
 * A short description of what does the Task on your license
 */
export type LicenseActionTypeOVH = typeof LicenseActionTypeOVH[keyof typeof LicenseActionTypeOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LicenseActionTypeOVH = {
  addWindowFromExistingSerial: 'addWindowFromExistingSerial',
  changeIp: 'changeIp',
  changeOs: 'changeOs',
  installLicense: 'installLicense',
  optionUpgrade: 'optionUpgrade',
  releaseOption: 'releaseOption',
  versionUpgrade: 'versionUpgrade',
} as const;

/**
 * licenses Todos
 */
export interface LicenseTaskOVH {
  /** This Task description */
  readonly action?: LicenseActionTypeOVH;
  /**
   * When was this Task done
   * @nullable
   */
  readonly doneDate?: string | null;
  /** The last time this Task was updated */
  readonly lastUpdate?: string;
  /** This Task name */
  readonly name?: string;
  /** Current Taks status */
  readonly status?: LicenseTaskStateEnumOVH;
  /** This Task id */
  readonly taskId?: number;
  /** When was this Task created */
  readonly todoDate?: string;
}

/**
 * IPv6 CIDR notation (e.g., 2001:41d0::/128)
 */
export type Ipv6BlockOVH = string;

/**
 * IPv6 address (e.g., 2001:41d0:1:1994::1)
 */
export type Ipv6OVH = string;

/**
 * IPv4 CIDR notation (e.g., 192.0.2.0/24)
 */
export type Ipv4BlockOVH = string;

/**
 * IPv4 address (e.g., 192.0.2.0)
 */
export type Ipv4OVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpInterfaceOVH = string;

/**
 * IP (v4 or v6) CIDR notation (e.g., 192.0.2.0/24)
 */
export type IpBlockOVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpOVH = string;

/**
 * International phone number
 */
export type InternationalPhoneNumberOVH = string;

/**
 * Operator that can be used in order to filter resources tags
 */
export type IamResourceTagFilterOperatorEnumOVH = typeof IamResourceTagFilterOperatorEnumOVH[keyof typeof IamResourceTagFilterOperatorEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IamResourceTagFilterOperatorEnumOVH = {
  EQ: 'EQ',
  EXISTS: 'EXISTS',
  ILIKE: 'ILIKE',
  LIKE: 'LIKE',
  NEQ: 'NEQ',
  NEXISTS: 'NEXISTS',
} as const;

/**
 * Operator to use in order to filter on the value (defaults to 'EQ')
 * @nullable
 */
export type IamResourceTagFilterOVHOperator = IamResourceTagFilterOperatorEnumOVH | null;

/**
 * Resource tag filter
 */
export interface IamResourceTagFilterOVH {
  /**
   * Operator to use in order to filter on the value (defaults to 'EQ')
   * @nullable
   */
  readonly operator?: IamResourceTagFilterOVHOperator;
  /** Value to use in order to filter tags */
  readonly value?: string;
}

/**
 * Resource tags. Tags that were internally computed are prefixed with ovh:
 * @nullable
 */
export type IamResourceMetadataOVHTags = {[key: string]: string} | null;

/**
 * IAM resource metadata embedded in services models
 */
export interface IamResourceMetadataOVH {
  /**
   * Resource display name
   * @nullable
   */
  readonly displayName?: string | null;
  /** Unique identifier of the resource */
  readonly id?: string;
  /**
   * Resource tags. Tags that were internally computed are prefixed with ovh:
   * @nullable
   */
  readonly tags?: IamResourceMetadataOVHTags;
  /** Unique resource name used in policies */
  readonly urn?: string;
}

/**
 * Email address (e.g., api@ml.ovh.net)
 */
export type EmailOVH = string;

/**
 * Duration (e.g., P1Y2M3DT4H6M9S)
 */
export type DurationOVH = string;

