export const DOC_URL = 'https://labs.ovh.com/kubernetes-k8s/documentation';

export const CONFIG_FILENAME = 'kubeconfig';

export const PROCESSING_STATUS = [
  'INSTALLING',
  'DELETING',
  'UPDATING',
  'RESETTING',
  'SUSPENDING',
  'REOPENING',
  'REDEPLOYING',
];

export const ERROR_STATUS = [
  'ERROR',
  'USER_ERROR',
  'USER_QUOTA_ERROR',
  'SUSPENDED',
];

export const STATUS = {
  READY: 'READY',
  INSTALLING: 'INSTALLING',
  DELETING: 'DELETING',
  UPDATING: 'UPDATING',
  RESETTING: 'RESETTING',
  ERROR: 'ERROR',
  SUSPENDING: 'SUSPENDING',
  REOPENING: 'REOPENING',
  REDEPLOYING: 'REDEPLOYING',
  SUSPENDED: 'SUSPENDED',
  USER_ERROR: 'USER_ERROR',
  USER_QUOTA_ERROR: 'USER_QUOTA_ERROR',
};

export default {
  CONFIG_FILENAME,
  DOC_URL,
  ERROR_STATUS,
  PROCESSING_STATUS,
  STATUS,
};
