export const DOC_URL = 'https://labs.ovh.com/kubernetes-k8s/documentation';
export const TRACKING_PREFIX =
  'PublicCloud::projects::managed_kubernetes_cluster';
export const TRACKING_SUFFIX = '_managed_kubernetes_cluster::kubernetes';

const TRACKING_TAB_PREFIX = '::go-to-tab';

export const TRACKING_TABS = {
  SERVICE: `${TRACKING_PREFIX}${TRACKING_TAB_PREFIX}::service${TRACKING_SUFFIX}`,
  NODE_POOL: `${TRACKING_PREFIX}${TRACKING_TAB_PREFIX}::node_pool${TRACKING_SUFFIX}`,
  LOGS: `${TRACKING_PREFIX}${TRACKING_TAB_PREFIX}::logs_access${TRACKING_SUFFIX}`,
  API_SERVER: `${TRACKING_PREFIX}${TRACKING_TAB_PREFIX}::APIserver_access${TRACKING_SUFFIX}`,
};

export const CONFIG_FILENAME = 'kubeconfig';

export const PROCESSING_STATUS = [
  'INSTALLING',
  'DELETING',
  'UPDATING',
  'RESETTING',
  'SUSPENDING',
  'MAINTENANCE',
  'REOPENING',
  'REDEPLOYING',
];

export const ERROR_STATUS = [
  'ERROR',
  'USER_ERROR',
  'USER_QUOTA_ERROR',
  'SUSPENDED',
];

export const STATUS = {
  READY: 'READY',
  INSTALLING: 'INSTALLING',
  DELETING: 'DELETING',
  UPDATING: 'UPDATING',
  RESETTING: 'RESETTING',
  ERROR: 'ERROR',
  SUSPENDING: 'SUSPENDING',
  REOPENING: 'REOPENING',
  REDEPLOYING: 'REDEPLOYING',
  SUSPENDED: 'SUSPENDED',
  USER_ERROR: 'USER_ERROR',
  USER_QUOTA_ERROR: 'USER_QUOTA_ERROR',
};

export default {
  CONFIG_FILENAME,
  DOC_URL,
  ERROR_STATUS,
  PROCESSING_STATUS,
  STATUS,
  TRACKING_PREFIX,
  TRACKING_SUFFIX,
  TRACKING_TABS,
};
