angular.module('ua.dateTimePicker', []).constant('ovhDirectives.constant.dateTimePicker.VIEW_MODE', {
    days  : 0,
    day   : 0,
    d     : 0,
    months: 1,
    month : 1,
    m     : 1,
    years : 2,
    year  : 2,
    y     : 2,
    //for retro compat
    0     : 0,
    1     : 1,
    2     : 2
}).constant('ovhDirectives.constant.dateTimePicker.CONFIG_OPTIONS', [ //available config for directive
    'format',
    'type',
    'modelTimezone',
    'weekStart',
    'calendarWeeks',
    'startDate',
    'endDate',
    'daysOfWeekDisabled',
    'autoclose',
    'startView',
    'minViewMode',
    'todayBtn',
    'todayHighlight',
    'keyboardNavigation',
    'language',
    'forceParse',
    'placement',
    'maskInput',
    'pickDate',
    'pickTime',
    'pick12HourFormat',
    'pickSeconds',
    'collapse'
]);
