import { TRACKING_CHAPTER_1, TRACKING_NAME } from '../../../constants';
import { TRACKING_SUFFIX as LISTENERS_TRACKING_SUFFIX } from '../../constants';

const TRACKING_SUFFIX = 'policies';

const POLICIES_TRACKING_ROOT = `${TRACKING_CHAPTER_1}::${TRACKING_NAME}::${LISTENERS_TRACKING_SUFFIX}::${TRACKING_SUFFIX}`;
const RENAME_POLICIES_TRACKING_ROOT = `${TRACKING_NAME}::${LISTENERS_TRACKING_SUFFIX}::${TRACKING_SUFFIX}`;

const ADD_SUFFIX = 'add';
const EDIT_SUFFIX = 'edit';
const DELETE_SUFFIX = 'delete';

export const POLICIES_TRACKING = {
  LIST: POLICIES_TRACKING_ROOT,
  RENAME_LIST: RENAME_POLICIES_TRACKING_ROOT,
  ADD: `${POLICIES_TRACKING_ROOT}::${ADD_SUFFIX}`,
  RENAME_ADD: `${RENAME_POLICIES_TRACKING_ROOT}::${ADD_SUFFIX}`,
  EDIT: `${POLICIES_TRACKING_ROOT}::${EDIT_SUFFIX}`,
  RENAME_EDIT: `${RENAME_POLICIES_TRACKING_ROOT}::${EDIT_SUFFIX}`,
  DELETE: `${POLICIES_TRACKING_ROOT}::${DELETE_SUFFIX}`,
  RENAME_DELETE: `${RENAME_POLICIES_TRACKING_ROOT}::${DELETE_SUFFIX}`,
  POOL_DASHBOARD: `${TRACKING_CHAPTER_1}::${TRACKING_NAME}::pools::overview`,
};

const RULES_TRACKING_SUFFIX = 'rules';
const RULES_TRACKING_ROOT = `${POLICIES_TRACKING_ROOT}::${RULES_TRACKING_SUFFIX}`;
const RENAME_RULES_TRACKING_ROOT = `${RENAME_POLICIES_TRACKING_ROOT}::${RULES_TRACKING_SUFFIX}`;

export const RULES_TRACKING = {
  LIST: RULES_TRACKING_ROOT,
  RENAME_LIST: RENAME_RULES_TRACKING_ROOT,
  ADD: `${RULES_TRACKING_ROOT}::${ADD_SUFFIX}`,
  ADD_FROM_ELLIPSIS: `${RULES_TRACKING_ROOT}::${ADD_SUFFIX}-rule`,
  ADD_FROM_BANNER: `${RULES_TRACKING_ROOT}::${ADD_SUFFIX}-rule-banner`,
  RENAME_ADD: `${RENAME_RULES_TRACKING_ROOT}::${ADD_SUFFIX}`,
  EDIT: `${RULES_TRACKING_ROOT}::${EDIT_SUFFIX}`,
  RENAME_EDIT: `${RENAME_RULES_TRACKING_ROOT}::${EDIT_SUFFIX}`,
  DELETE: `${RULES_TRACKING_ROOT}::${DELETE_SUFFIX}`,
  RENAME_DELETE: `${RENAME_RULES_TRACKING_ROOT}::${DELETE_SUFFIX}`,
};

export const ACTIONS = {
  REDIRECT_TO_URL: 'redirectToURL',
  REDIRECT_TO_POOL: 'redirectToPool',
  REDIRECT_PREFIX: 'redirectPrefix',
  REJECT: 'reject',
};

export const ACTION_LABELS = {
  [ACTIONS.REDIRECT_TO_URL]: 'Redirect to URL',
  [ACTIONS.REDIRECT_TO_POOL]: 'Redirect to Pool',
  [ACTIONS.REDIRECT_PREFIX]: 'Redirect Prefix',
  [ACTIONS.REJECT]: 'Reject',
};

export default {
  ACTIONS,
  ACTION_LABELS,
  POLICIES_TRACKING,
  RULES_TRACKING,
};
