export const GUIDES = [
  {
    title: 'vps_onboarding_guide1_title',
    description: 'vps_onboarding_guide1_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/vps/getting-started-vps/',
      ASIA: 'https://docs.ovh.com/asia/en/vps/getting-started-vps/',
      DE: 'https://docs.ovh.com/de/vps/erste-schritte-mit-einem-vps/',
      ES: 'https://docs.ovh.com/es/vps/primeros-pasos-con-vps/',
      IE: 'https://docs.ovh.com/ie/en/vps/getting-started-vps/',
      IT: 'https://docs.ovh.com/it/vps/iniziare-a-utilizzare-vps/',
      PL: 'https://docs.ovh.com/pl/vps/pierwsze-kroki-vps/',
      PT: 'https://docs.ovh.com/pt/vps/instalar-gerir-vps/',
      GB: 'https://docs.ovh.com/gb/en/vps/getting-started-vps/',
      CA: 'https://docs.ovh.com/ca/en/vps/getting-started-vps/',
      QC: 'https://docs.ovh.com/ca/fr/vps/debuter-avec-vps/',
      AU: 'https://docs.ovh.com/au/en/vps/getting-started-vps/',
      SG: 'https://docs.ovh.com/sg/en/vps/getting-started-vps/',
      FR: 'https://docs.ovh.com/fr/vps/debuter-avec-vps/',
      WE: 'https://docs.ovh.com/us/en/vps/getting-started-vps/',
      WS: 'https://docs.ovh.com/us/en/vps/getting-started-vps/',
      US: 'https://docs.ovh.com/us/en/vps/getting-started-vps/',
    },
  },
  {
    title: 'vps_onboarding_guide2_title',
    description: 'vps_onboarding_guide2_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/vps/tips-for-securing-a-vps/',
      ASIA: 'https://docs.ovh.com/asia/en/vps/tips-for-securing-a-vps/',
      DE: 'https://docs.ovh.com/de/vps/vps-sicherheit/',
      ES: 'https://docs.ovh.com/es/vps/consejos-proteccion-vps/',
      IE: 'https://docs.ovh.com/ie/en/vps/tips-for-securing-a-vps/',
      IT: 'https://docs.ovh.com/it/vps/consigli-sicurezza-vps/',
      PL: 'https://docs.ovh.com/pl/vps/porady-zabezpieczenie-vps/',
      PT: 'https://docs.ovh.com/pt/vps/como-proteger-vps/',
      GB: 'https://docs.ovh.com/gb/en/vps/tips-for-securing-a-vps/',
      CA: 'https://docs.ovh.com/ca/en/vps/tips-for-securing-a-vps/',
      QC: 'https://docs.ovh.com/ca/fr/vps/conseils-securisation-vps/',
      AU: 'https://docs.ovh.com/au/en/vps/tips-for-securing-a-vps/',
      SG: 'https://docs.ovh.com/sg/en/vps/tips-for-securing-a-vps/',
      FR: 'https://docs.ovh.com/fr/vps/conseils-securisation-vps/',
      WE: 'https://docs.ovh.com/us/en/vps/tips-for-securing-a-vps/',
      WS: 'https://docs.ovh.com/us/en/vps/tips-for-securing-a-vps/',
      US: 'https://docs.ovh.com/us/en/vps/tips-for-securing-a-vps/',
    },
  },
  {
    title: 'vps_onboarding_guide3_title',
    description: 'vps_onboarding_guide3_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/vps/using-snapshots-on-a-vps/',
      ASIA: 'https://docs.ovh.com/asia/en/vps/using-snapshots-on-a-vps/',
      DE: 'https://docs.ovh.com/de/vps/verwendung-snapshots-vps/',
      ES: 'https://docs.ovh.com/es/vps/usar-instantaneas-en-un-vps/',
      IE: 'https://docs.ovh.com/ie/en/vps/using-snapshots-on-a-vps/',
      IT: 'https://docs.ovh.com/it/vps/usare-snapshot-su-un-vps/',
      PL: 'https://docs.ovh.com/pl/vps/uzywanie-migawki-vps/',
      PT: 'https://docs.ovh.com/pt/vps/utilizar-snapshots-num-alojamento-vps/',
      GB: 'https://docs.ovh.com/gb/en/vps/using-snapshots-on-a-vps/',
      CA: 'https://docs.ovh.com/ca/en/vps/using-snapshots-on-a-vps/',
      QC: 'https://docs.ovh.com/ca/fr/vps/snapshot-vps/',
      AU: 'https://docs.ovh.com/au/en/vps/using-snapshots-on-a-vps/',
      SG: 'https://docs.ovh.com/sg/en/vps/using-snapshots-on-a-vps/',
      FR: 'https://docs.ovh.com/fr/vps/snapshot-vps/',
      WE: 'https://docs.ovh.com/us/en/vps/using-snapshots-on-a-vps/',
      WS: 'https://docs.ovh.com/us/en/vps/using-snapshots-on-a-vps/',
      US: 'https://docs.ovh.com/us/en/vps/using-snapshots-on-a-vps/',
    },
  },
];

export const CTAS = {
  DEFAULT: 'https://ovhcloud.com/en/vps',
  ASIA: 'https://ovhcloud.com/asia/vps',
  DE: 'https://ovhcloud.com/de/vps',
  ES: 'https://ovhcloud.com/es-es/vps',
  IE: 'https://ovhcloud.com/en-ie/vps',
  IT: 'https://ovhcloud.com/it/vps',
  NL: 'https://ovhcloud.com/nl/vps',
  PL: 'https://ovhcloud.com/pl/vps',
  PT: 'https://ovhcloud.com/pt/vps',
  GB: 'https://ovhcloud.com/en-gb/vps',
  CA: 'https://ovhcloud.com/en-ca/vps',
  QC: 'https://ovhcloud.com/fr-ca/vps',
  MA: 'https://ovhcloud.com/fr-ma/vps',
  SN: 'https://ovhcloud.com/fr-sn/vps',
  TN: 'https://ovhcloud.com/fr-tn/vps',
  AU: 'https://ovhcloud.com/en-au/vps',
  SG: 'https://ovhcloud.com/en-sg/vps',
  FR: 'https://ovhcloud.com/fr/vps',
  CZ: 'https://ovhcloud.com/cz-cs/vps',
  FI: 'https://ovhcloud.com/fi/vps',
  LT: 'https://ovhcloud.com/lt/vps',
  WE: 'https://ovhcloud.com/us-en/vps',
  WS: 'https://ovhcloud.com/us-en/vps',
};

export const US_GUIDES = [
  {
    title: 'vps_onboarding_us_guide1_title',
    description: 'vps_onboarding_us_guide1_description',
    link:
      'https://support.us.ovhcloud.com/hc/en-us/articles/360009253639-Getting-Started-with-a-VPS',
  },
  {
    title: 'vps_onboarding_us_guide2_title',
    description: 'vps_onboarding_us_guide2_description',
    link:
      'https://support.us.ovhcloud.com/hc/en-us/articles/4412351365139-How-to-Secure-a-VPS',
  },
  {
    title: 'vps_onboarding_us_guide3_title',
    description: 'vps_onboarding_us_guide3_description',
    link:
      'https://support.us.ovhcloud.com/hc/en-us/articles/360012573640-How-to-Use-Snapshots-on-a-VPS',
  },
];
export const US_CTA = 'https://us.ovhcloud.com/vps/';
