export const GUIDES = [
  {
    title: 'vrack_services_onboarding_guide1_title',
    description: 'vrack_services_onboarding_guide1_description',
    links: {
      DEFAULT: 'TODO',
      ASIA: 'TODO',
      AU: 'TODO',
      CA: 'TODO',
      DE: 'TODO',
      ES: 'TODO',
      FR: 'TODO',
      GB: 'TODO',
      IE: 'TODO',
      IT: 'TODO',
      MA: 'TODO',
      NL: 'TODO',
      PL: 'TODO',
      PT: 'TODO',
      QC: 'TODO',
      SN: 'TODO',
      SG: 'TODO',
      TN: 'TODO',
      US: 'TODO',
      WE: 'TODO',
      WS: 'TODO',
    },
  },
  {
    title: 'vrack_services_onboarding_guide2_title',
    description: 'vrack_services_onboarding_guide2_description',
    links: {
      DEFAULT: 'TODO',
      ASIA: 'TODO',
      AU: 'TODO',
      CA: 'TODO',
      DE: 'TODO',
      ES: 'TODO',
      FR: 'TODO',
      GB: 'TODO',
      IE: 'TODO',
      IT: 'TODO',
      MA: 'TODO',
      NL: 'TODO',
      PL: 'TODO',
      PT: 'TODO',
      QC: 'TODO',
      SN: 'TODO',
      SG: 'TODO',
      TN: 'TODO',
      US: 'TODO',
      WE: 'TODO',
      WS: 'TODO',
    },
  },
];

export const DISCOVER_CTA = {
  DEFAULT: 'TODO',
  ASIA: 'TODO',
  AU: 'TODO',
  CA: 'TODO',
  DE: 'TODO',
  ES: 'TODO',
  FR: 'TODO',
  GB: 'TODO',
  IE: 'TODO',
  IT: 'TODO',
  MA: 'TODO',
  NL: 'TODO',
  PL: 'TODO',
  PT: 'TODO',
  QC: 'TODO',
  SN: 'TODO',
  SG: 'TODO',
  TN: 'TODO',
  US: 'TODO',
  WE: 'TODO',
  WS: 'TODO',
};

export const TRACKING_NAME = 'todo::vrack-services::onboarding';

export default { GUIDES, DISCOVER_CTA, TRACKING_NAME };
