export type TActionName =
  | 'details'
  | 'edit'
  | 'assign_floating_ip'
  | 'activate_monthly_billing'
  | 'create_backup'
  | 'create_autobackup'
  | 'start'
  | 'stop'
  | 'rescue'
  | 'unrescue'
  | 'soft_reboot'
  | 'hard_reboot'
  | 'shelve'
  | 'unshelve'
  | 'resume'
  | 'reinstall'
  | 'delete';

export type TStatus =
  | 'ACTIVE'
  | 'BUILDING'
  | 'DELETED'
  | 'DELETING'
  | 'ERROR'
  | 'HARD_REBOOT'
  | 'PASSWORD'
  | 'PAUSED'
  | 'REBOOT'
  | 'REBUILD'
  | 'RESCUED'
  | 'RESIZED'
  | 'REVERT_RESIZE'
  | 'SOFT_DELETED'
  | 'STOPPED'
  | 'SUSPENDED'
  | 'UNKNOWN'
  | 'VERIFY_RESIZE'
  | 'MIGRATING'
  | 'RESIZE'
  | 'BUILD'
  | 'SHUTOFF'
  | 'RESCUE'
  | 'SHELVED'
  | 'SHELVING'
  | 'UNSHELVING'
  | 'SHELVED_OFFLOADED'
  | 'RESCUING'
  | 'UNRESCUING'
  | 'SNAPSHOTTING'
  | 'RESUMING';

export type TAddressType = 'public' | 'private' | 'floating';
export type TInstanceActionGroup =
  | 'boot'
  | 'delete'
  | 'details'
  | 'lifecycle'
  | 'shelve';
