import { OvhSubsidiary } from '@ovh-ux/manager-react-components';

export const CONTACT_URL_BY_SUBSIDIARY: Record<OvhSubsidiary, string> = {
  ASIA: 'https://www.ovhcloud.com/asia/contact/',
  CZ: 'https://www.ovhcloud.com/en-ie/contact',
  DE: 'https://www.ovhcloud.com/de/contact/',
  ES: 'https://www.ovhcloud.com/es-es/contact/',
  FI: 'https://www.ovhcloud.com/en-ie/contact',
  WS: 'https://www.ovhcloud.com/es/contact/',
  IE: 'https://www.ovhcloud.com/en-ie/contact/',
  IT: 'https://www.ovhcloud.com/it/contact/',
  LT: 'https://www.ovhcloud.com/en-ie/contact',
  PL: 'https://www.ovhcloud.com/pl/contact/',
  PT: 'https://www.ovhcloud.com/pt/contact/',
  FR: 'https://www.ovhcloud.com/fr/contact/',
  GB: 'https://www.ovhcloud.com/en-gb/contact/',
  CA: 'https://www.ovhcloud.com/en-ca/contact/',
  QC: 'https://www.ovhcloud.com/fr-ca/contact/',
  US: 'https://www.ovhcloud.com/en/contact/',
  AU: 'https://www.ovhcloud.com/en-au/contact/',
  SG: 'https://www.ovhcloud.com/en-sg/contact/',
  MA: 'https://www.ovhcloud.com/fr-ma/contact/',
  SN: 'https://www.ovhcloud.com/fr-sn/contact/',
  TN: 'https://www.ovhcloud.com/fr-tn/contact/',
  NL: 'https://www.ovhcloud.com/nl/contact/',
  IN: 'https://www.ovhcloud.com/en-in/contact/',
  WE: 'https://www.ovhcloud.com/en/contact/',
  EU: 'https://www.ovhcloud.com/fr/contact/',
  DEFAULT: 'https://www.ovhcloud.com/fr/contact/',
};
