/** State of the job */
export enum JobStateEnum {
  'DONE' = 'DONE',
  'ERROR' = 'ERROR',
  'FAILED' = 'FAILED',
  'FINALIZING' = 'FINALIZING',
  'INITIALIZING' = 'INITIALIZING',
  'INTERRUPTED' = 'INTERRUPTED',
  'INTERRUPTING' = 'INTERRUPTING',
  'PENDING' = 'PENDING',
  'QUEUED' = 'QUEUED',
  'RESTARTING' = 'RESTARTING',
  'RUNNING' = 'RUNNING',
  'SYNC_FAILED' = 'SYNC_FAILED',
  'TIMEOUT' = 'TIMEOUT',
}
