export const urls = {
  root: '',
  onboarding: '/onboarding',
  dashboard: '/:serviceName',
  overview: '/:serviceName',
  organizations: '/:serviceName/organizations',
  organizationsDelete: '/:serviceName/organizations/delete',
  domains: '/:serviceName/domains',
  domains_diagnostic: '/:serviceName/domains/diagnostic',
  email_accounts: '/:serviceName/email_accounts',
  email_accounts_add: '/:serviceName/email_accounts/add',
  email_accounts_edit: '/:serviceName/email_accounts/settings',
  email_accounts_alias: '/:serviceName/email_accounts/alias',
  email_accounts_alias_add: '/:serviceName/email_accounts/alias/add',
  email_accounts_alias_delete: '/:serviceName/email_accounts/alias/delete',
  mailing_lists: '/:serviceName/mailing_lists',
};
