import {
  PHONE_NUMBER_COUNTRIES_PRESET,
  PHONE_NUMBER_COUNTRIES_PRESETS,
  PHONE_NUMBER_COUNTRY_ISO_CODE,
  PHONE_NUMBER_COUNTRY_ISO_CODES,
  PHONE_NUMBER_I18N,
  PHONE_NUMBER_PARSING_ERROR,
  PHONE_NUMBER_PARSING_ERRORS,
} from '@ovhcloud/ods-react';

export {
  PHONE_NUMBER_COUNTRIES_PRESET,
  PHONE_NUMBER_COUNTRIES_PRESETS,
  PHONE_NUMBER_COUNTRY_ISO_CODE,
  PHONE_NUMBER_COUNTRY_ISO_CODES,
  PHONE_NUMBER_I18N,
  PHONE_NUMBER_PARSING_ERROR,
  PHONE_NUMBER_PARSING_ERRORS,
};
