import {
  OsdsButton,
  OsdsFormField,
  OsdsInput,
  OsdsText,
} from '@ovhcloud/ods-components/react';
import { ODS_THEME_COLOR_INTENT } from '@ovhcloud/ods-common-theming';
import {
  ODS_BUTTON_VARIANT,
  ODS_INPUT_TYPE,
  ODS_TEXT_LEVEL,
  ODS_TEXT_SIZE,
} from '@ovhcloud/ods-components';
import { StepComponent } from '@ovh-ux/manager-react-components';
import { useTranslation } from 'react-i18next';
import { useEffect, useMemo, useState } from 'react';
import { LOAD_BALANCER_NAME_REGEX } from '@/constants';
import { StepsEnum, useCreateStore } from '@/pages/create/store';
import { useCreateActions } from '@/pages/create/hooks/useCreateActions';
import { getAutoGeneratedName } from '@/utils/utils';

export const NameStep = (): JSX.Element => {
  const { t } = useTranslation(['load-balancer/create', 'pci-common']);

  const [didTryCreate, setDidTryCreate] = useState(false);

  const store = useCreateStore();

  const { create, cancel } = useCreateActions();

  const [hasLengthError, hasMatchError] = useMemo(
    () => [
      store.name.length > 70,
      store.name.length && !store.name.match(LOAD_BALANCER_NAME_REGEX),
    ],
    [store.name],
  );

  useEffect(() => {
    const name = getAutoGeneratedName(
      `LB_${store.addon?.size.toUpperCase() || ''}_${store.region?.name || ''}`,
    );

    store.set.name(name);
  }, [store.addon, store.region, store.set]);

  const errorMessage = useMemo(() => {
    if (hasLengthError)
      return t('pci-common:common_field_error_maxlength', {
        maxlength: 70,
      });
    if (hasMatchError) return t('pci-common:common_field_error_pattern');

    return '';
  }, [hasLengthError, hasMatchError, t]);

  return (
    <StepComponent
      title={t('octavia_load_balancer_create_name_field_label')}
      isOpen={store.steps.get(StepsEnum.NAME).isOpen}
      isChecked={store.steps.get(StepsEnum.NAME).isChecked}
      isLocked={store.steps.get(StepsEnum.NAME).isLocked}
      order={6}
    >
      <OsdsFormField className="mt-8 w-[20rem]" inline error={errorMessage}>
        <OsdsText
          color={ODS_THEME_COLOR_INTENT.text}
          size={ODS_TEXT_SIZE._100}
          level={ODS_TEXT_LEVEL.subheading}
          slot="label"
        >
          {t('octavia_load_balancer_create_name_field_label')}
        </OsdsText>
        <OsdsInput
          value={store.name}
          type={ODS_INPUT_TYPE.text}
          onOdsValueChange={(event) => {
            store.set.name(event.detail.value as string);
          }}
          className={
            hasLengthError || hasMatchError
              ? 'bg-red-100 border-red-500 text-red-500 focus:text-red-500'
              : 'border-color-[var(--ods-color-default-200)] bg-white'
          }
        />
      </OsdsFormField>
      {!didTryCreate && (
        <div className="mt-8">
          <OsdsButton
            inline
            color={ODS_THEME_COLOR_INTENT.info}
            onClick={() => {
              create();
              setDidTryCreate(true);
            }}
            {...(hasLengthError || hasMatchError ? { disabled: true } : {})}
          >
            {t('octavia_load_balancer_create_title')}
          </OsdsButton>
          <OsdsButton
            inline
            variant={ODS_BUTTON_VARIANT.ghost}
            color={ODS_THEME_COLOR_INTENT.info}
            onClick={cancel}
          >
            {t('pci-common:common_cancel')}
          </OsdsButton>
        </div>
      )}
    </StepComponent>
  );
};
