export const SERVICE_TYPE = {
  EMAIL_DOMAIN: 'EMAIL_DOMAIN',
  ENTERPRISE_CLOUD_DATABASE: 'ENTERPRISE_CLOUD_DATABASE',
  EXCHANGE: 'EMAIL_EXCHANGE',
  HOSTING_PRIVATE_DATABASE: 'HOSTING_PRIVATE_DATABASE',
  HOSTING_WEB: 'HOSTING_WEB',
  NUTANIX: 'NUTANIX',
  OVH_CLOUD_CONNECT: 'OVH_CLOUD_CONNECT',
  SMS: 'SMS',
  WEBCOACH: 'WEBCOACH',
  ALL_DOM: 'ALL_DOM',
};
