const config = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      spacing: {
        0: '0',
        1: '0.0625rem',
        2: '0.125rem',
        3: '0.25rem',
        4: '0.5rem',
        5: '0.75rem',
        6: '1rem',
        7: '1.25rem',
        8: '1.5rem',
        9: '2rem',
        10: '2.5rem',
        11: '3rem',
      },
      colors: {
        'color-alpha': 'var(--ods-color-alpha)',
        'color-background-disabled-default':
          'var(--ods-color-background-disabled-default)',
        'color-background-readonly-default':
          'var(--ods-color-background-readonly-default)',
        'color-border-disabled-default':
          'var(--ods-color-border-disabled-default)',
        'color-border-readonly-default':
          'var(--ods-color-border-readonly-default)',
        'color-beta': 'var(--ods-color-beta)',
        'color-critical-000': 'var(--ods-color-critical-000)',
        'color-critical-050': 'var(--ods-color-critical-050)',
        'color-critical-100': 'var(--ods-color-critical-100)',
        'color-critical-200': 'var(--ods-color-critical-200)',
        'color-critical-300': 'var(--ods-color-critical-300)',
        'color-critical-400': 'var(--ods-color-critical-400)',
        'color-critical-500': 'var(--ods-color-critical-500)',
        'color-critical-600': 'var(--ods-color-critical-600)',
        'color-critical-700': 'var(--ods-color-critical-700)',
        'color-critical-800': 'var(--ods-color-critical-800)',
        'color-critical-900': 'var(--ods-color-critical-900)',
        'color-form-element-background-critical':
          'var(--ods-color-form-element-background-critical)',
        'color-form-element-background-default':
          'var(--ods-color-form-element-background-default)',
        'color-form-element-background-focus-default':
          'var(--ods-color-form-element-background-focus-default)',
        'color-form-element-background-hover-default':
          'var(--ods-color-form-element-background-hover-default)',
        'color-form-element-border-critical':
          'var(--ods-color-form-element-border-critical)',
        'color-form-element-border-default':
          'var(--ods-color-form-element-border-default)',
        'color-form-element-border-focus-default':
          'var(--ods-color-form-element-border-focus-default)',
        'color-form-element-border-hover-default':
          'var(--ods-color-form-element-border-hover-default)',
        'color-form-element-text-default':
          'var(--ods-color-form-element-text-default)',
        'color-form-element-text-placeholder-default':
          'var(--ods-color-form-element-text-placeholder-default)',
        'color-heading': 'var(--ods-color-heading)',
        'color-information-000': 'var(--ods-color-information-000)',
        'color-information-050': 'var(--ods-color-information-050)',
        'color-information-100': 'var(--ods-color-information-100)',
        'color-information-200': 'var(--ods-color-information-200)',
        'color-information-300': 'var(--ods-color-information-300)',
        'color-information-400': 'var(--ods-color-information-400)',
        'color-information-500': 'var(--ods-color-information-500)',
        'color-information-600': 'var(--ods-color-information-600)',
        'color-information-700': 'var(--ods-color-information-700)',
        'color-information-800': 'var(--ods-color-information-800)',
        'color-information-900': 'var(--ods-color-information-900)',
        'color-neutral-000': 'var(--ods-color-neutral-000)',
        'color-neutral-050': 'var(--ods-color-neutral-050)',
        'color-neutral-100': 'var(--ods-color-neutral-100)',
        'color-neutral-200': 'var(--ods-color-neutral-200)',
        'color-neutral-300': 'var(--ods-color-neutral-300)',
        'color-neutral-400': 'var(--ods-color-neutral-400)',
        'color-neutral-500': 'var(--ods-color-neutral-500)',
        'color-neutral-600': 'var(--ods-color-neutral-600)',
        'color-neutral-700': 'var(--ods-color-neutral-700)',
        'color-neutral-800': 'var(--ods-color-neutral-800)',
        'color-neutral-900': 'var(--ods-color-neutral-900)',
        'color-new': 'var(--ods-color-new)',
        'color-primary-000': 'var(--ods-color-primary-000)',
        'color-primary-050': 'var(--ods-color-primary-050)',
        'color-primary-100': 'var(--ods-color-primary-100)',
        'color-primary-200': 'var(--ods-color-primary-200)',
        'color-primary-300': 'var(--ods-color-primary-300)',
        'color-primary-400': 'var(--ods-color-primary-400)',
        'color-primary-500': 'var(--ods-color-primary-500)',
        'color-primary-600': 'var(--ods-color-primary-600)',
        'color-primary-700': 'var(--ods-color-primary-700)',
        'color-primary-800': 'var(--ods-color-primary-800)',
        'color-primary-900': 'var(--ods-color-primary-900)',
        'color-promotion': 'var(--ods-color-promotion)',
        'color-success-000': 'var(--ods-color-success-000)',
        'color-success-050': 'var(--ods-color-success-050)',
        'color-success-100': 'var(--ods-color-success-100)',
        'color-success-200': 'var(--ods-color-success-200)',
        'color-success-300': 'var(--ods-color-success-300)',
        'color-success-400': 'var(--ods-color-success-400)',
        'color-success-500': 'var(--ods-color-success-500)',
        'color-success-600': 'var(--ods-color-success-600)',
        'color-success-700': 'var(--ods-color-success-700)',
        'color-success-800': 'var(--ods-color-success-800)',
        'color-success-900': 'var(--ods-color-success-900)',
        'color-text': 'var(--ods-color-text)',
        'color-text-disabled-default': 'var(--ods-color-text-disabled-default)',
        'color-warning-000': 'var(--ods-color-warning-000)',
        'color-warning-050': 'var(--ods-color-warning-050)',
        'color-warning-100': 'var(--ods-color-warning-100)',
        'color-warning-200': 'var(--ods-color-warning-200)',
        'color-warning-300': 'var(--ods-color-warning-300)',
        'color-warning-400': 'var(--ods-color-warning-400)',
        'color-warning-500': 'var(--ods-color-warning-500)',
        'color-warning-600': 'var(--ods-color-warning-600)',
        'color-warning-700': 'var(--ods-color-warning-700)',
        'color-warning-800': 'var(--ods-color-warning-800)',
        'color-warning-900': 'var(--ods-color-warning-900)',
      },
    },
    screens: {
      xs: '0',
      sm: '36em',
      md: '48em',
      lg: '62em',
      xl: '75em',
      xxl: '87.5em',
      // not work with ods var in media queries
      // 'xs': 'var(--ods-breakpoint-xs)',
    },
    borderRadius: {
      none: '0',
      sm: 'var(--ods-border-radius-sm, var(--ods-size-border-radius-01, 4px))',
      DEFAULT:
        'var(--ods-border-radius-sm, var(--ods-size-border-radius-01, 4px))',
      md: 'var(--ods-border-radius-md, var(--ods-size-border-radius-02, 8px))',
      lg: 'var(--ods-border-radius-lg, var(--ods-size-border-radius-02, 16px))',
      full: '50%',
    },
  },
  plugins: [],
};

export default config;
