/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OVHcloud API specification
 * Specification for OVHcloud API
 * OpenAPI spec version: 1.0
 */
export type GetStorageNetappServiceNameShareShareIdSnapshotParams = {
/**
 * Get detailed information about each snapshot
 */
detail?: boolean;
};

export type GetStorageNetappServiceNameShareParams = {
/**
 * Get detailed information about each share
 */
detail?: boolean;
};

export type GetStorageNetappServiceNameNetworkParams = {
/**
 * Get detailed information about each network
 */
detail?: boolean;
};

export type GetStorageNetappParams = {
/**
 * Filter resources on IAM tags
 */
iamTags?: {[key: string]: IamResourceTagFilterOVH[]};
};

/**
 * Time (e.g., 15:04:05)
 */
export type TimeOVH = string;

/**
 * Region of customer's service
 */
export type StorageRegionEnumOVH = typeof StorageRegionEnumOVH[keyof typeof StorageRegionEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageRegionEnumOVH = {
  BHS: 'BHS',
  GRA: 'GRA',
  LIM: 'LIM',
  RBX: 'RBX',
  SBG: 'SBG',
  'ca-east-bhs': 'ca-east-bhs',
  'eu-west-gra': 'eu-west-gra',
  'eu-west-lim': 'eu-west-lim',
  'eu-west-rbx': 'eu-west-rbx',
  'eu-west-sbg': 'eu-west-sbg',
} as const;

/**
 * Storage protocol
 */
export type StorageProtocolEnumOVH = typeof StorageProtocolEnumOVH[keyof typeof StorageProtocolEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageProtocolEnumOVH = {
  NFS: 'NFS',
} as const;

/**
 * Snapshot type
 */
export type StorageNetAppSnapshotTypeEnumOVH = typeof StorageNetAppSnapshotTypeEnumOVH[keyof typeof StorageNetAppSnapshotTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppSnapshotTypeEnumOVH = {
  automatic: 'automatic',
  manual: 'manual',
  system: 'system',
} as const;

/**
 * Snapshot status
 */
export type StorageNetAppSnapshotStatusEnumOVH = typeof StorageNetAppSnapshotStatusEnumOVH[keyof typeof StorageNetAppSnapshotStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppSnapshotStatusEnumOVH = {
  available: 'available',
  creating: 'creating',
  deleting: 'deleting',
  error: 'error',
  error_deleting: 'error_deleting',
  manage_error: 'manage_error',
  manage_starting: 'manage_starting',
  restoring: 'restoring',
  unmanage_error: 'unmanage_error',
  unmanage_starting: 'unmanage_starting',
} as const;

/**
 * Snapshot policy updatable properties
 */
export interface StorageNetAppSnapshotPolicyUpdateOVH {
  /**
   * New snapshot policy description
   * @nullable
   */
  description?: string | null;
  /**
   * New snapshot policy name
   * @nullable
   */
  name?: string | null;
}

/**
 * Snapshot policy status
 */
export type StorageNetAppSnapshotPolicyStatusEnumOVH = typeof StorageNetAppSnapshotPolicyStatusEnumOVH[keyof typeof StorageNetAppSnapshotPolicyStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppSnapshotPolicyStatusEnumOVH = {
  available: 'available',
  creating: 'creating',
  deleting: 'deleting',
  error: 'error',
  updating: 'updating',
} as const;

/**
 * A snapshot policy schedule
 */
export interface StorageNetAppSnapshotPolicyScheduleOVH {
  /**
   * The days of the month the schedule runs (1 through 31). Empty for all.
   * @nullable
   */
  days?: number[] | null;
  /**
   * The hours of the day the schedule runs (0 through 23). Empty for all.
   * @nullable
   */
  hours?: number[] | null;
  /** The minutes the schedule runs (0 through 59). Required to have at least one value. */
  minutes: number[];
  /**
   * The months of the year the schedule runs (1 through 12). Empty for all.
   * @nullable
   */
  months?: number[] | null;
  /**
   * The days of the week the schedule runs (0 through 6, where 0 is Sunday and 6 is Saturday). Empty for all.
   * @nullable
   */
  weekdays?: number[] | null;
}

/**
 * Snapshot policy schedule
 * @nullable
 */
export type StorageNetAppSnapshotPolicyRuleOVHSchedule = StorageNetAppSnapshotPolicyScheduleOVH | null;

/**
 * A snapshot policy rule
 */
export interface StorageNetAppSnapshotPolicyRuleOVH {
  /**
   * Number of snapshot copies to keep
   * @nullable
   */
  copies: number | null;
  /**
   * Prefix to use for snapshots
   * @nullable
   */
  prefix: string | null;
  /**
   * Snapshot policy schedule
   * @nullable
   */
  schedule: StorageNetAppSnapshotPolicyRuleOVHSchedule;
}

/**
 * Snapshot policy status
 * @nullable
 */
export type StorageNetAppSnapshotPolicyOVHStatus = StorageNetAppSnapshotPolicyStatusEnumOVH | null;

/**
 * A snapshot policy
 */
export interface StorageNetAppSnapshotPolicyOVH {
  /**
   * Snapshot policy creation date
   * @nullable
   */
  readonly createdAt?: string | null;
  /**
   * Snapshot policy description
   * @nullable
   */
  description?: string | null;
  /** Snapshot policy ID */
  readonly id?: string;
  /**
   * Is this the default snapshot policy?
   * @nullable
   */
  readonly isDefault?: boolean | null;
  /**
   * Snapshot policy name
   * @nullable
   */
  name?: string | null;
  /**
   * Snapshot policy rules
   * @nullable
   */
  rules: StorageNetAppSnapshotPolicyRuleOVH[] | null;
  /**
   * Snapshot policy status
   * @nullable
   */
  readonly status?: StorageNetAppSnapshotPolicyOVHStatus;
}

/**
 * NetApp share updatable properties
 */
export interface StorageNetAppShareUpdateOVH {
  /**
   * New share description
   * @nullable
   */
  description?: string | null;
  /**
   * New share name
   * @nullable
   */
  name?: string | null;
}

/**
 * Share status
 */
export type StorageNetAppShareStatusEnumOVH = typeof StorageNetAppShareStatusEnumOVH[keyof typeof StorageNetAppShareStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppShareStatusEnumOVH = {
  available: 'available',
  creating: 'creating',
  creating_from_snapshot: 'creating_from_snapshot',
  deleted: 'deleted',
  deleting: 'deleting',
  error: 'error',
  error_deleting: 'error_deleting',
  extending: 'extending',
  extending_error: 'extending_error',
  inactive: 'inactive',
  manage_error: 'manage_error',
  manage_starting: 'manage_starting',
  migrating: 'migrating',
  migrating_to: 'migrating_to',
  replication_change: 'replication_change',
  reverting: 'reverting',
  reverting_error: 'reverting_error',
  shrinking: 'shrinking',
  shrinking_error: 'shrinking_error',
  shrinking_possible_data_loss_error: 'shrinking_possible_data_loss_error',
  unmanage_error: 'unmanage_error',
  unmanage_starting: 'unmanage_starting',
  unmanaged: 'unmanaged',
} as const;

/**
 * Share snapshot updatable properties
 */
export interface StorageNetAppShareSnapshotUpdateOVH {
  /**
   * New snapshot description
   * @nullable
   */
  description?: string | null;
  /**
   * New snapshot name
   * @nullable
   */
  name?: string | null;
}

/**
 * A snapshot policy
 */
export interface StorageNetAppShareSnapshotReserveUpdateOVH {
  /** Share space percentage reserved for snapshots */
  percent: number;
}

/**
 * Snapshot reserve properties status
 */
export type StorageNetAppShareSnapshotReserveStatusEnumOVH = typeof StorageNetAppShareSnapshotReserveStatusEnumOVH[keyof typeof StorageNetAppShareSnapshotReserveStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppShareSnapshotReserveStatusEnumOVH = {
  active: 'active',
  error: 'error',
  updating: 'updating',
} as const;

/**
 * Snapshot reserve properties
 */
export interface StorageNetAppShareSnapshotReserveOVH {
  /** Share space percentage reserved for snapshots */
  readonly percent?: number;
  /** Status */
  readonly status?: StorageNetAppShareSnapshotReserveStatusEnumOVH;
}

/**
 * A snapshot policy
 */
export interface StorageNetAppShareSnapshotPolicyUpdateOVH {
  /** Snapshot policy ID */
  snapshotPolicyID: string;
}

/**
 * Association status between the share and the snapshot policy
 */
export type StorageNetAppShareSnapshotPolicyStatusEnumOVH = typeof StorageNetAppShareSnapshotPolicyStatusEnumOVH[keyof typeof StorageNetAppShareSnapshotPolicyStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppShareSnapshotPolicyStatusEnumOVH = {
  active: 'active',
  error: 'error',
  updating: 'updating',
} as const;

/**
 * A snapshot policy
 */
export interface StorageNetAppShareSnapshotPolicyOVH {
  /** Snapshot policy ID */
  readonly id?: string;
  /** Association status between the share and the snapshot policy */
  readonly status?: StorageNetAppShareSnapshotPolicyStatusEnumOVH;
}

/**
 * Snapshot type
 * @nullable
 */
export type StorageNetAppShareSnapshotOVHType = StorageNetAppSnapshotTypeEnumOVH | null;

/**
 * Snapshot status
 * @nullable
 */
export type StorageNetAppShareSnapshotOVHStatus = StorageNetAppSnapshotStatusEnumOVH | null;

/**
 * A share snapshot
 */
export interface StorageNetAppShareSnapshotOVH {
  /**
   * Snapshot creation date
   * @nullable
   */
  readonly createdAt?: string | null;
  /**
   * Snapshot description
   * @nullable
   */
  description?: string | null;
  /** Snapshot ID */
  readonly id?: string;
  /**
   * Snapshot name
   * @nullable
   */
  name?: string | null;
  /**
   * Snapshot path
   * @nullable
   */
  readonly path?: string | null;
  /**
   * Snapshot status
   * @nullable
   */
  readonly status?: StorageNetAppShareSnapshotOVHStatus;
  /**
   * Snapshot type
   * @nullable
   */
  readonly type?: StorageNetAppShareSnapshotOVHType;
}

/**
 * A share
 */
export interface StorageNetAppShareRevertToSnapshotOVH {
  /** Latest share snapshot */
  snapshotID: string;
}

/**
 * A share
 */
export interface StorageNetAppShareExtendOrShrinkOVH {
  /**
   * Share size in Gigabytes
   * @nullable
   */
  size: number | null;
}

/**
 * A share access path
 */
export interface StorageNetAppShareAccessPathOVH {
  /** Access path ID */
  readonly id?: string;
  /** Access path */
  readonly path?: string;
  /** Is this the preferred access path? */
  readonly preferred?: boolean;
}

/**
 * ACL type
 */
export type StorageNetAppShareACLTypeEnumOVH = typeof StorageNetAppShareACLTypeEnumOVH[keyof typeof StorageNetAppShareACLTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppShareACLTypeEnumOVH = {
  ip: 'ip',
} as const;

/**
 * ACL status
 */
export type StorageNetAppShareACLStatusEnumOVH = typeof StorageNetAppShareACLStatusEnumOVH[keyof typeof StorageNetAppShareACLStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppShareACLStatusEnumOVH = {
  active: 'active',
  applying: 'applying',
  denying: 'denying',
  error: 'error',
  queued_to_apply: 'queued_to_apply',
  queued_to_deny: 'queued_to_deny',
} as const;

/**
 * Rule status
 * @nullable
 */
export type StorageNetAppShareACLRuleOVHStatus = StorageNetAppShareACLStatusEnumOVH | null;

/**
 * Rule access type
 * @nullable
 */
export type StorageNetAppShareACLRuleOVHAccessType = StorageNetAppShareACLTypeEnumOVH | null;

/**
 * A share ACL rule
 */
export interface StorageNetAppShareACLRuleOVH {
  /**
   * Rule access level
   * @nullable
   */
  accessLevel: StorageNetAppShareACLRuleOVHAccessLevel;
  /**
   * Rule destination
   * @nullable
   */
  accessTo: string | null;
  /**
   * Rule access type
   * @nullable
   */
  readonly accessType?: StorageNetAppShareACLRuleOVHAccessType;
  /**
   * Rule creation date
   * @nullable
   */
  readonly createdAt?: string | null;
  /** Rule ID */
  readonly id?: string;
  /**
   * Rule status
   * @nullable
   */
  readonly status?: StorageNetAppShareACLRuleOVHStatus;
}

/**
 * ACL permission
 */
export type StorageNetAppShareACLPermissionEnumOVH = typeof StorageNetAppShareACLPermissionEnumOVH[keyof typeof StorageNetAppShareACLPermissionEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppShareACLPermissionEnumOVH = {
  ro: 'ro',
  rw: 'rw',
} as const;

/**
 * Rule access level
 * @nullable
 */
export type StorageNetAppShareACLRuleOVHAccessLevel = StorageNetAppShareACLPermissionEnumOVH | null;

/**
 * Share status
 * @nullable
 */
export type StorageNetAppShareOVHStatus = StorageNetAppShareStatusEnumOVH | null;

/**
 * Share protocol
 * @nullable
 */
export type StorageNetAppShareOVHProtocol = StorageProtocolEnumOVH | null;

/**
 * A share
 */
export interface StorageNetAppShareOVH {
  /**
   * Share creation date
   * @nullable
   */
  readonly createdAt?: string | null;
  /**
   * Share description
   * @nullable
   */
  description?: string | null;
  /** Share ID */
  readonly id?: string;
  /**
   * Share name
   * @nullable
   */
  name?: string | null;
  /**
   * Share protocol
   * @nullable
   */
  protocol: StorageNetAppShareOVHProtocol;
  /**
   * Share size in Gigabytes
   * @nullable
   */
  size: number | null;
  /**
   * Share status
   * @nullable
   */
  readonly status?: StorageNetAppShareOVHStatus;
}

/**
 * IAM resource metadata
 * @nullable
 */
export type StorageNetAppServiceWithIAMOVHIam = IamResourceMetadataOVH | null;

/**
 * Service updatable properties
 */
export interface StorageNetAppServiceUpdateOVH {
  /** New service name */
  name: string;
}

/**
 * Service status
 */
export type StorageNetAppServiceStatusEnumOVH = typeof StorageNetAppServiceStatusEnumOVH[keyof typeof StorageNetAppServiceStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppServiceStatusEnumOVH = {
  creating: 'creating',
  deleted: 'deleted',
  deleting: 'deleting',
  reopening: 'reopening',
  running: 'running',
  suspended: 'suspended',
  suspending: 'suspending',
} as const;

/**
 * Service performance level
 */
export type StorageNetAppServicePerformanceLevelEnumOVH = typeof StorageNetAppServicePerformanceLevelEnumOVH[keyof typeof StorageNetAppServicePerformanceLevelEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppServicePerformanceLevelEnumOVH = {
  premium: 'premium',
} as const;

/**
 * A service
 */
export interface StorageNetAppServiceWithIAMOVH {
  /** Service creation date */
  readonly createdAt?: string;
  /**
   * IAM resource metadata
   * @nullable
   */
  readonly iam?: StorageNetAppServiceWithIAMOVHIam;
  /** Service ID */
  readonly id?: string;
  /** Service name */
  readonly name?: string;
  /** Service performance level */
  readonly performanceLevel?: StorageNetAppServicePerformanceLevelEnumOVH;
  /** Product name */
  readonly product?: string;
  /** Service quota */
  readonly quota?: number;
  /** Service region */
  readonly region?: StorageRegionEnumOVH;
  /** Service status */
  readonly status?: StorageNetAppServiceStatusEnumOVH;
}

/**
 * A service
 */
export interface StorageNetAppServiceOVH {
  /** Service creation date */
  readonly createdAt?: string;
  /** Service ID */
  readonly id?: string;
  /** Service name */
  readonly name?: string;
  /** Service performance level */
  readonly performanceLevel?: StorageNetAppServicePerformanceLevelEnumOVH;
  /** Product name */
  readonly product?: string;
  /** Service quota */
  readonly quota?: number;
  /** Service region */
  readonly region?: StorageRegionEnumOVH;
  /** Service status */
  readonly status?: StorageNetAppServiceStatusEnumOVH;
}

/**
 * Network status
 */
export type StorageNetAppNetworkStatusEnumOVH = typeof StorageNetAppNetworkStatusEnumOVH[keyof typeof StorageNetAppNetworkStatusEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StorageNetAppNetworkStatusEnumOVH = {
  associated: 'associated',
  associating: 'associating',
  dissociating: 'dissociating',
  to_configure: 'to_configure',
} as const;

/**
 * Network status
 * @nullable
 */
export type StorageNetAppNetworkOVHStatus = StorageNetAppNetworkStatusEnumOVH | null;

/**
 * A network
 */
export interface StorageNetAppNetworkOVH {
  /** Network ID */
  readonly id?: string;
  /**
   * Network status
   * @nullable
   */
  readonly status?: StorageNetAppNetworkOVHStatus;
  /**
   * vRack Services URN the network is attached to
   * @nullable
   */
  readonly vRackServicesURN?: string | null;
}

/**
 * Service change contact payload
 */
export interface ServicesChangeContactOVH {
  /** The contact to set as admin contact */
  contactAdmin?: string;
  /** The contact to set as billing contact */
  contactBilling?: string;
  /** The contact to set as tech contact */
  contactTech?: string;
}

/**
 * Way of handling the renew
 * @nullable
 */
export type ServicesServiceOVHRenew = ServiceRenewTypeOVH | null;

/**
 * Details about a Service
 */
export interface ServicesServiceOVH {
  /** Indicates that the service can be set up to be deleted at expiration */
  readonly canDeleteAtExpiration?: boolean;
  readonly contactAdmin?: string;
  readonly contactBilling?: string;
  readonly contactTech?: string;
  readonly creation?: string;
  readonly domain?: string;
  /** @nullable */
  readonly engagedUpTo?: string | null;
  readonly expiration?: string;
  /**
   * All the possible renew period of your service in month
   * @nullable
   */
  readonly possibleRenewPeriod?: readonly number[] | null;
  /**
   * Way of handling the renew
   * @nullable
   */
  renew?: ServicesServiceOVHRenew;
  readonly renewalType?: ServiceRenewalTypeEnumOVH;
  readonly serviceId?: number;
  readonly status?: ServiceStateEnumOVH;
}

/**
 * All reasons you can provide for a service termination
 */
export type ServiceTerminationReasonEnumOVH = typeof ServiceTerminationReasonEnumOVH[keyof typeof ServiceTerminationReasonEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTerminationReasonEnumOVH = {
  FEATURES_DONT_SUIT_ME: 'FEATURES_DONT_SUIT_ME',
  LACK_OF_PERFORMANCES: 'LACK_OF_PERFORMANCES',
  MIGRATED_TO_ANOTHER_OVH_PRODUCT: 'MIGRATED_TO_ANOTHER_OVH_PRODUCT',
  MIGRATED_TO_COMPETITOR: 'MIGRATED_TO_COMPETITOR',
  NOT_ENOUGH_RECOGNITION: 'NOT_ENOUGH_RECOGNITION',
  NOT_NEEDED_ANYMORE: 'NOT_NEEDED_ANYMORE',
  NOT_RELIABLE: 'NOT_RELIABLE',
  NO_ANSWER: 'NO_ANSWER',
  OTHER: 'OTHER',
  PRODUCT_DIMENSION_DONT_SUIT_ME: 'PRODUCT_DIMENSION_DONT_SUIT_ME',
  PRODUCT_TOOLS_DONT_SUIT_ME: 'PRODUCT_TOOLS_DONT_SUIT_ME',
  TOO_EXPENSIVE: 'TOO_EXPENSIVE',
  TOO_HARD_TO_USE: 'TOO_HARD_TO_USE',
  UNSATIFIED_BY_CUSTOMER_SUPPORT: 'UNSATIFIED_BY_CUSTOMER_SUPPORT',
} as const;

/**
 * All future uses you can provide for a service termination
 */
export type ServiceTerminationFutureUseEnumOVH = typeof ServiceTerminationFutureUseEnumOVH[keyof typeof ServiceTerminationFutureUseEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTerminationFutureUseEnumOVH = {
  NOT_REPLACING_SERVICE: 'NOT_REPLACING_SERVICE',
  OTHER: 'OTHER',
  SUBSCRIBE_AN_OTHER_SERVICE: 'SUBSCRIBE_AN_OTHER_SERVICE',
  SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR: 'SUBSCRIBE_OTHER_KIND_OF_SERVICE_WITH_COMPETITOR',
  SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR: 'SUBSCRIBE_SIMILAR_SERVICE_WITH_COMPETITOR',
} as const;

/**
 * Service confirm termination payload
 */
export interface ServicesConfirmTerminationOVH {
  /** Commentary about your termination request */
  commentary?: string;
  /** All future uses you can provide for a service termination */
  futureUse?: ServiceTerminationFutureUseEnumOVH;
  /** All reasons you can provide for a service termination */
  reason?: ServiceTerminationReasonEnumOVH;
  /** The termination token sent by email to the admin contact */
  token: string;
}

/**
 * service.StateEnum
 */
export type ServiceStateEnumOVH = typeof ServiceStateEnumOVH[keyof typeof ServiceStateEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceStateEnumOVH = {
  autorenewInProgress: 'autorenewInProgress',
  expired: 'expired',
  inCreation: 'inCreation',
  ok: 'ok',
  pendingDebt: 'pendingDebt',
  unPaid: 'unPaid',
} as const;

/**
 * Detailed renewal type of a service
 */
export type ServiceRenewalTypeEnumOVH = typeof ServiceRenewalTypeEnumOVH[keyof typeof ServiceRenewalTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceRenewalTypeEnumOVH = {
  automaticForcedProduct: 'automaticForcedProduct',
  automaticV2012: 'automaticV2012',
  automaticV2014: 'automaticV2014',
  automaticV2016: 'automaticV2016',
  manual: 'manual',
  oneShot: 'oneShot',
  option: 'option',
} as const;

/**
 * Map a possible renew for a specific service
 */
export interface ServiceRenewTypeOVH {
  /** The service is automatically renewed */
  automatic?: boolean;
  /** The service will be deleted at expiration */
  deleteAtExpiration?: boolean;
  /** The service forced to be renewed */
  forced?: boolean;
  /**
   * The service needs to be manually renewed and paid
   * @nullable
   */
  manualPayment?: boolean | null;
  /**
   * period of renew in month
   * @nullable
   */
  period?: number | null;
}

/**
 * Phone number
 */
export type PhoneNumberOVH = string;

/**
 * MAC address (e.g., 2001:4860:4860::8844)
 */
export type MacAddressOVH = string;

/**
 * IPv6 CIDR notation (e.g., 2001:41d0::/128)
 */
export type Ipv6BlockOVH = string;

/**
 * IPv6 address (e.g., 2001:41d0:1:1994::1)
 */
export type Ipv6OVH = string;

/**
 * IPv4 CIDR notation (e.g., 192.0.2.0/24)
 */
export type Ipv4BlockOVH = string;

/**
 * IPv4 address (e.g., 192.0.2.0)
 */
export type Ipv4OVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpInterfaceOVH = string;

/**
 * IP (v4 or v6) CIDR notation (e.g., 192.0.2.0/24)
 */
export type IpBlockOVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpOVH = string;

/**
 * International phone number
 */
export type InternationalPhoneNumberOVH = string;

/**
 * Operator that can be used in order to filter resources tags
 */
export type IamResourceTagFilterOperatorEnumOVH = typeof IamResourceTagFilterOperatorEnumOVH[keyof typeof IamResourceTagFilterOperatorEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IamResourceTagFilterOperatorEnumOVH = {
  EQ: 'EQ',
  EXISTS: 'EXISTS',
  ILIKE: 'ILIKE',
  LIKE: 'LIKE',
  NEQ: 'NEQ',
  NEXISTS: 'NEXISTS',
} as const;

/**
 * Operator to use in order to filter on the value (defaults to 'EQ')
 * @nullable
 */
export type IamResourceTagFilterOVHOperator = IamResourceTagFilterOperatorEnumOVH | null;

/**
 * Resource tag filter
 */
export interface IamResourceTagFilterOVH {
  /**
   * Operator to use in order to filter on the value (defaults to 'EQ')
   * @nullable
   */
  readonly operator?: IamResourceTagFilterOVHOperator;
  /** Value to use in order to filter tags */
  readonly value?: string;
}

/**
 * Resource tags. Tags that were internally computed are prefixed with ovh:
 * @nullable
 */
export type IamResourceMetadataOVHTags = {[key: string]: string} | null;

/**
 * IAM resource metadata embedded in services models
 */
export interface IamResourceMetadataOVH {
  /**
   * Resource display name
   * @nullable
   */
  readonly displayName?: string | null;
  /** Unique identifier of the resource */
  readonly id?: string;
  /**
   * Resource tags. Tags that were internally computed are prefixed with ovh:
   * @nullable
   */
  readonly tags?: IamResourceMetadataOVHTags;
  /** Unique resource name used in policies */
  readonly urn?: string;
}

/**
 * Email address (e.g., api@ml.ovh.net)
 */
export type EmailOVH = string;

/**
 * Duration (e.g., P1Y2M3DT4H6M9S)
 */
export type DurationOVH = string;

