export const vpsResponseUnified = {
  glueRecordMultiIpSupported: true,
  parentService: null,
  suspensionState: 'not_suspended',
  glueRecordIpv6Supported: true,
  whoisOwner: '13466563',
  offer: 'platinum',
  lastUpdate: '2022-12-06T17:00:45+01:00',
  nameServerType: 'external',
  hostSupported: true,
  owoSupported: false,
  transferLockStatus: 'locked',
  dnssecSupported: true,
  renewalType: 'automaticV2016',
  contactBilling: 'ls148374-ovh',
  contactTech: 'ls148374-ovh',
  domain: 'vps-0baa4fcf.vps.ovh.net',
  expiration: '2023-08-01',
  canDeleteAtExpiration: true,
  serviceId: '118977335',
  creation: '2023-01-16',
  possibleRenewPeriod: [1, 3, 6, 12],
  renew: {
    automatic: true,
    deleteAtExpiration: false,
    forced: false,
    manualPayment: false,
    period: 1,
  },
  status: 'ok',
  contactAdmin: 'ls148374-ovh',
  route: {
    path: '/vps/{serviceName}',
    url: '/vps/vps-0baa4fcf.vps.ovh.net',
    vars: [
      {
        key: 'serviceName',
        value: 'vps-0baa4fcf.vps.ovh.net',
      },
    ],
  },
  billing: {
    nextBillingDate: '2023-08-01T17:31:17+02:00',
    expirationDate: '2023-08-01T17:31:17+02:00',
    plan: {
      code: 'vps-elite-8-8-160',
      invoiceName: 'VPS Elite 8-8-160',
    },
    pricing: {
      capacities: ['renew'],
      description: 'Monthly fees',
      interval: 1,
      duration: 'P1M',
      minimumQuantity: 1,
      maximumQuantity: 100,
      minimumRepeat: 1,
      maximumRepeat: null,
      price: {
        currencyCode: 'EUR',
        text: '34.50 €',
        value: 34.5,
      },
      priceInUcents: 3450000000,
      pricingMode: 'default',
      pricingType: 'rental',
      engagementConfiguration: null,
    },
    group: null,
    lifecycle: {
      current: {
        pendingActions: [],
        terminationDate: null,
        creationDate: '2023-01-16T17:31:17+02:00',
        state: 'active',
      },
      capacities: {
        actions: ['earlyRenewal', 'terminateAtExpirationDate'],
      },
    },
    renew: {
      current: {
        mode: 'automatic',
        nextDate: '2023-08-01T17:31:17+02:00',
        period: 'P1M',
      },
      capacities: {
        mode: ['automatic', 'manual'],
      },
    },
    engagement: null,
    engagementRequest: null,
  },
  resource: {
    displayName: 'vps-0baa4fcf.vps.ovh.net',
    name: 'vps-0baa4fcf.vps.ovh.net',
    state: 'active',
    product: {
      name: 'vps-elite-8-8-160',
      description: 'VPS Elite 8 vCPU 8 GB RAM 160 GB disk',
    },
    resellingProvider: null,
  },
  parentServiceId: null,
  customer: {
    contacts: [
      {
        customerCode: 'ls148374-ovh',
        type: 'administrator',
      },
      {
        customerCode: 'ls148374-ovh',
        type: 'technical',
      },
      {
        customerCode: 'ls148374-ovh',
        type: 'billing',
      },
    ],
  },
  tags: [],
};

export const domainResponseUnified = {
  domain: 'agora3.ovh',
  contactAdmin: 'ls148374-ovh',
  renew: {
    manualPayment: true,
    deleteAtExpiration: true,
    period: 12,
    automatic: false,
    forced: false,
  },
  status: 'ok',
  renewalType: 'automaticV2016',
  contactTech: 'ls148374-ovh',
  contactBilling: 'ls148376-ovh',
  canDeleteAtExpiration: true,
  serviceId: 29162449,
  expiration: '2023-01-27',
  possibleRenewPeriod: [12, 24, 36, 48, 60, 72, 84],
  creation: '2020-01-27',
  engagedUpTo: null,
  route: {
    path: '/domain/{serviceName}',
    url: '/domain/agora3.ovh',
    vars: [
      {
        key: 'serviceName',
        value: 'agora3.ovh',
      },
    ],
  },
  billing: {
    nextBillingDate: '2023-01-27T14:48:11+02:00',
    expirationDate: '2023-01-27T14:48:11+02:00',
    plan: {
      code: 'ovh',
      invoiceName: '.ovh',
    },
    pricing: {
      capacities: ['renew'],
      description: 'Renewal of a .ovh domain name - 1 year',
      interval: 12,
      duration: 'P12M',
      minimumQuantity: 1,
      maximumQuantity: 10,
      minimumRepeat: 1,
      maximumRepeat: null,
      price: {
        currencyCode: 'EUR',
        text: '2.99 €',
        value: 2.99,
      },
      priceInUcents: 299000000,
      pricingMode: 'create-default',
      pricingType: 'rental',
      engagementConfiguration: null,
    },
    group: null,
    lifecycle: {
      current: {
        pendingActions: [],
        terminationDate: '2023-01-27T14:48:11+02:00',
        creationDate: '2020-01-27T14:48:11+02:00',
        state: 'active',
      },
      capacities: {
        actions: ['earlyRenewal'],
      },
    },
    renew: {
      current: {
        mode: 'manual',
        nextDate: null,
        period: null,
      },
      capacities: {
        mode: ['automatic', 'manual'],
      },
    },
    engagement: null,
    engagementRequest: null,
  },
  resource: {
    displayName: 'agora3.ovh',
    name: 'agora3.ovh',
    state: 'active',
    product: {
      name: 'ovh-product',
      description: 'Domain .ovh',
    },
    resellingProvider: null,
  },
  parentServiceId: null,
  customer: {
    contacts: [
      {
        customerCode: 'ls148374-ovh',
        type: 'administrator',
      },
      {
        customerCode: 'ls148374-ovh',
        type: 'technical',
      },
      {
        customerCode: 'ls148374-ovh',
        type: 'billing',
      },
    ],
  },
  tags: [],
  state: 'ok',
  glueRecordMultiIpSupported: true,
  parentService: null,
  suspensionState: 'not_suspended',
  glueRecordIpv6Supported: true,
  whoisOwner: '13466563',
  offer: 'platinum',
  lastUpdate: '2022-12-06T17:00:45+01:00',
  nameServerType: 'external',
  hostSupported: true,
  owoSupported: false,
  transferLockStatus: 'locked',
  dnssecSupported: true,
};
