import { OvhSubsidiary } from '@/commons/settings/Regions.constants';

export enum CurrencyCode {
  AUD = 'AUD',
  CAD = 'CAD',
  CZK = 'CZK',
  EUR = 'EUR',
  GBP = 'GBP',
  INR = 'INR',
  MAD = 'MAD',
  PLN = 'PLN',
  SGD = 'SGD',
  USD = 'USD',
  TND = 'TND',
  XOF = 'XOF',
  LTL = 'LTL',
  NA = 'N/A',
  points = 'points',
}

export const OVH_CURRENCY_BY_SUBSIDIARY: Record<OvhSubsidiary, CurrencyCode> = {
  ASIA: CurrencyCode.USD,
  AU: CurrencyCode.AUD,
  CA: CurrencyCode.CAD,
  CZ: CurrencyCode.EUR,
  DE: CurrencyCode.EUR,
  ES: CurrencyCode.EUR,
  FI: CurrencyCode.EUR,
  FR: CurrencyCode.EUR,
  GB: CurrencyCode.GBP,
  IE: CurrencyCode.EUR,
  IN: CurrencyCode.INR,
  IT: CurrencyCode.EUR,
  LT: CurrencyCode.EUR,
  MA: CurrencyCode.MAD,
  NL: CurrencyCode.EUR,
  PL: CurrencyCode.PLN,
  PT: CurrencyCode.EUR,
  QC: CurrencyCode.CAD,
  SG: CurrencyCode.SGD,
  SN: CurrencyCode.XOF,
  TN: CurrencyCode.TND,
  EU: CurrencyCode.EUR,
  US: CurrencyCode.USD,
  WE: CurrencyCode.USD,
  WS: CurrencyCode.USD,
  DEFAULT: CurrencyCode.USD,
};
