/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * OVHcloud API specification
 * Specification for OVHcloud API
 * OpenAPI spec version: 1.0
 */
/**
 * Time (e.g., 15:04:05)
 */
export type TimeOVH = string;

/**
 * Phone number
 */
export type PhoneNumberOVH = string;

/**
 * MAC address (e.g., 2001:4860:4860::8844)
 */
export type MacAddressOVH = string;

/**
 * IPv6 CIDR notation (e.g., 2001:41d0::/128)
 */
export type Ipv6BlockOVH = string;

/**
 * IPv6 address (e.g., 2001:41d0:1:1994::1)
 */
export type Ipv6OVH = string;

/**
 * IPv4 CIDR notation (e.g., 192.0.2.0/24)
 */
export type Ipv4BlockOVH = string;

/**
 * IPv4 address (e.g., 192.0.2.0)
 */
export type Ipv4OVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpInterfaceOVH = string;

/**
 * IP (v4 or v6) CIDR notation (e.g., 192.0.2.0/24)
 */
export type IpBlockOVH = string;

/**
 * IP address (e.g., 192.0.2.0)
 */
export type IpOVH = string;

/**
 * International phone number
 */
export type InternationalPhoneNumberOVH = string;

/**
 * Email address (e.g., api@ml.ovh.net)
 */
export type EmailOVH = string;

/**
 * Duration (e.g., P1Y2M3DT4H6M9S)
 */
export type DurationOVH = string;

/**
 * partition raid type
 */
export type DedicatedServerPartitionRaidEnumOVH = typeof DedicatedServerPartitionRaidEnumOVH[keyof typeof DedicatedServerPartitionRaidEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedServerPartitionRaidEnumOVH = {
  NUMBER_0: '0',
  NUMBER_1: '1',
  NUMBER_10: '10',
  NUMBER_5: '5',
  NUMBER_6: '6',
  NUMBER_7: '7',
} as const;

/**
 * FileSystems
 */
export type DedicatedServerFileSystemEnumOVH = typeof DedicatedServerFileSystemEnumOVH[keyof typeof DedicatedServerFileSystemEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedServerFileSystemEnumOVH = {
  btrfs: 'btrfs',
  ext3: 'ext3',
  ext4: 'ext4',
  fat16: 'fat16',
  none: 'none',
  ntfs: 'ntfs',
  reiserfs: 'reiserfs',
  swap: 'swap',
  ufs: 'ufs',
  vmfs5: 'vmfs5',
  vmfs6: 'vmfs6',
  vmfsl: 'vmfsl',
  xfs: 'xfs',
  zfs: 'zfs',
} as const;

/**
 * Available os bit format
 */
export type DedicatedServerBitFormatEnumOVH = typeof DedicatedServerBitFormatEnumOVH[keyof typeof DedicatedServerBitFormatEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedServerBitFormatEnumOVH = {
  NUMBER_32: 32,
  NUMBER_64: 64,
} as const;

/**
 * Partition raid
 * @nullable
 */
export type DedicatedInstallationTemplateTemplatePartitionsOVHRaid = DedicatedServerPartitionRaidEnumOVH | null;

/**
 *  Partitions defined in this partitioning scheme
 */
export interface DedicatedInstallationTemplateTemplatePartitionsOVH {
  /** Partition filesytem */
  filesystem?: DedicatedServerFileSystemEnumOVH;
  /** Partition mount point */
  mountpoint?: string;
  /** specifies the creation order of the partition on the disk */
  order?: number;
  /**
   * Partition raid
   * @nullable
   */
  raid?: DedicatedInstallationTemplateTemplatePartitionsOVHRaid;
  /** Partition size (unit: MB GB TB, MB by default), 0 => rest of the space */
  size?: ComplexTypeUnitAndValueLongOVH;
  /** Partition type */
  type?: DedicatedTemplatePartitionTypeEnumOVH;
  /**
   * Logical volume name (required if type is lv) or optional zpool name if filesystem is ZFS
   * @nullable
   */
  volumeName?: string | null;
}

/**
 * Partitioning schemes available on this template
 */
export interface DedicatedInstallationTemplateTemplatePartitioningSchemesOVH {
  /** This partitioning scheme name */
  name?: string;
  /** on a reinstall, if a partitioning scheme is not specified, the one with the higher priority will be used by default, among all the compatible partitioning schemes (given the underlying hardware specifications) */
  priority?: number;
}

/**
 * Hardware RAID defined in this partitioning scheme
 */
export interface DedicatedInstallationTemplateHardwareRaidOVH {
  /** Disk list */
  disks?: string[];
  /** RAID mode */
  mode?: DedicatedTemplateOsHardwareRaidEnumOVH;
  /** Hardware RAID name */
  name?: string;
  /** Specifies the creation order of the hardware RAID */
  step?: number;
}

/**
 * This distribution project details
 * @nullable
 */
export type DedicatedInstallationTemplateTemplatesOVHProject = DedicatedTemplateOsInfoProjectOVH | null;

/**
 * This distribution licensing details
 * @nullable
 */
export type DedicatedInstallationTemplateTemplatesOVHLicense = DedicatedTemplateOsInfoLicenseOVH | null;

/**
 * Customizable template properties 
 * @nullable
 */
export type DedicatedInstallationTemplateTemplatesOVHCustomization = DedicatedTemplateOsPropertiesOVH | null;

/**
 * partition type
 */
export type DedicatedTemplatePartitionTypeEnumOVH = typeof DedicatedTemplatePartitionTypeEnumOVH[keyof typeof DedicatedTemplatePartitionTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplatePartitionTypeEnumOVH = {
  logical: 'logical',
  lv: 'lv',
  primary: 'primary',
} as const;

/**
 * Os usage definition
 */
export type DedicatedTemplateOsUsageEnumOVH = typeof DedicatedTemplateOsUsageEnumOVH[keyof typeof DedicatedTemplateOsUsageEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplateOsUsageEnumOVH = {
  backup: 'backup',
  basic: 'basic',
  customer: 'customer',
  database: 'database',
  erp: 'erp',
  hosting: 'hosting',
  management: 'management',
  other: 'other',
  readyToUse: 'readyToUse',
  virtualisation: 'virtualisation',
  virtualization: 'virtualization',
} as const;

/**
 * Os type
 */
export type DedicatedTemplateOsTypeEnumOVH = typeof DedicatedTemplateOsTypeEnumOVH[keyof typeof DedicatedTemplateOsTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplateOsTypeEnumOVH = {
  bsd: 'bsd',
  custom: 'custom',
  ibm: 'ibm',
  linux: 'linux',
  solaris: 'solaris',
  unix: 'unix',
  windows: 'windows',
} as const;

/**
 * Os subfamily definition
 */
export type DedicatedTemplateOsSubfamilyEnumOVH = typeof DedicatedTemplateOsSubfamilyEnumOVH[keyof typeof DedicatedTemplateOsSubfamilyEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplateOsSubfamilyEnumOVH = {
  alma: 'alma',
  aos: 'aos',
  arch: 'arch',
  byoi: 'byoi',
  byolinux: 'byolinux',
  centos: 'centos',
  cloudlinux: 'cloudlinux',
  coreos: 'coreos',
  debian: 'debian',
  dgx: 'dgx',
  esxi: 'esxi',
  fedora: 'fedora',
  freebsd: 'freebsd',
  gentoo: 'gentoo',
  hyperv: 'hyperv',
  omnios: 'omnios',
  openio: 'openio',
  openmediavault: 'openmediavault',
  opensuse: 'opensuse',
  ovh: 'ovh',
  pcs: 'pcs',
  power: 'power',
  proxmox: 'proxmox',
  rhel: 'rhel',
  rocky: 'rocky',
  slackware: 'slackware',
  'sles-sap': 'sles-sap',
  smartos: 'smartos',
  solusvm: 'solusvm',
  ubuntu: 'ubuntu',
  'windows-server-core': 'windows-server-core',
  'windows-server-desktop-exp': 'windows-server-desktop-exp',
  xcp: 'xcp',
  xen: 'xen',
} as const;

/**
 * A structure describing properties customizables about this dedicated installation template
 */
export interface DedicatedTemplateOsPropertiesOVH {
  /**
   * Set up the server using the provided hostname instead of the default hostname
   * @nullable
   */
  customHostname?: string | null;
  /**
   * Indicate the URL where your postinstall customisation script is located
   * @nullable
   */
  postInstallationScriptLink?: string | null;
  /**
   * indicate the string returned by your postinstall customisation script on successful execution. Advice: your script should return a unique validation string in case of succes. A good example is "loh1Xee7eo OK OK OK UGh8Ang1Gu
   * @nullable
   */
  postInstallationScriptReturn?: string | null;
}

/**
 * Template OS Input type enum
 */
export type DedicatedTemplateOsInputTypeEnumOVH = typeof DedicatedTemplateOsInputTypeEnumOVH[keyof typeof DedicatedTemplateOsInputTypeEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplateOsInputTypeEnumOVH = {
  boolean: 'boolean',
  date: 'date',
  email: 'email',
  enum: 'enum',
  hexstring: 'hexstring',
  hostname: 'hostname',
  ip: 'ip',
  keyValue: 'keyValue',
  number: 'number',
  sshPubKey: 'sshPubKey',
  string: 'string',
  text: 'text',
  time: 'time',
  url: 'url',
  uuid: 'uuid',
} as const;

/**
 * A structure describing input questions for the specific OS template
 */
export interface DedicatedTemplateOsInputOVH {
  /**
   * Default value
   * @nullable
   */
  default?: string | null;
  /**
   * Input question description
   * @nullable
   */
  description?: string | null;
  /** When type is enum: name of the possible enum values */
  enum?: string[];
  /** Whether answering to that question is mandatory in order to trigger an install with that specific OS or not */
  mandatory?: boolean;
  /** Input question name */
  name?: string;
  /** Input type */
  type?: DedicatedTemplateOsInputTypeEnumOVH;
}

/**
 * Available installation templates
 */
export interface DedicatedInstallationTemplateTemplatesOVH {
  /** this template bit format */
  readonly bitFormat?: DedicatedServerBitFormatEnumOVH;
  /** category of this template (informative only) */
  readonly category?: DedicatedTemplateOsUsageEnumOVH;
  /**
   * Customizable template properties 
   * @nullable
   */
  customization?: DedicatedInstallationTemplateTemplatesOVHCustomization;
  /** information about this template */
  readonly description?: string;
  /** the distribution this template is based on */
  readonly distribution?: string;
  /** after this date, install of this template will not be possible at OVH */
  readonly endOfInstall?: string;
  /** this template family type */
  readonly family?: DedicatedTemplateOsTypeEnumOVH;
  /** list of all filesystems available for this template */
  readonly filesystems?: readonly DedicatedServerFileSystemEnumOVH[];
  /**
   * Inputs
   * @nullable
   */
  readonly inputs?: readonly DedicatedTemplateOsInputOVH[] | null;
  /**
   * This distribution licensing details
   * @nullable
   */
  readonly license?: DedicatedInstallationTemplateTemplatesOVHLicense;
  /**
   * This distribution supports Logical Volumes (Linux LVM)
   * @nullable
   */
  readonly lvmReady?: boolean | null;
  /** Partitioning customization is not available for this OS template */
  readonly noPartitioning?: boolean;
  /**
   * This distribution project details
   * @nullable
   */
  readonly project?: DedicatedInstallationTemplateTemplatesOVHProject;
  /** Partitioning customization is available but limited to mirroring for this OS template */
  readonly softRaidOnlyMirroring?: boolean;
  /** this template subfamily type */
  readonly subfamily?: DedicatedTemplateOsSubfamilyEnumOVH;
  /** This template name */
  templateName?: string;
}

/**
 * A structure describing some interesting facts about an OS template project item
 */
export interface DedicatedTemplateOsInfoProjectItemOVH {
  /**
   * OS template project item governance
   * @nullable
   */
  governance?: string[] | null;
  /**
   * OS template project item name
   * @nullable
   */
  name?: string | null;
  /**
   * OS template project item release notes
   * @nullable
   */
  releaseNotes?: string | null;
  /**
   * OS template project item url
   * @nullable
   */
  url?: string | null;
  /**
   * OS template project item version
   * @nullable
   */
  version?: string | null;
}

/**
 * OS template project usage details
 * @nullable
 */
export type DedicatedTemplateOsInfoProjectOVHUsage = DedicatedTemplateOsInfoProjectItemOVH | null;

/**
 * OS template project OS details
 * @nullable
 */
export type DedicatedTemplateOsInfoProjectOVHOs = DedicatedTemplateOsInfoProjectItemOVH | null;

/**
 * A structure describing some interesting facts about an OS template project
 */
export interface DedicatedTemplateOsInfoProjectOVH {
  /**
   * OS template project OS details
   * @nullable
   */
  os?: DedicatedTemplateOsInfoProjectOVHOs;
  /**
   * OS template project usage details
   * @nullable
   */
  usage?: DedicatedTemplateOsInfoProjectOVHUsage;
}

/**
 * Standard license name according to SPDX
 */
export type DedicatedTemplateOsInfoLicenseItemEnumOVH = typeof DedicatedTemplateOsInfoLicenseItemEnumOVH[keyof typeof DedicatedTemplateOsInfoLicenseItemEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplateOsInfoLicenseItemEnumOVH = {
  '0BSD': '0BSD',
  AAL: 'AAL',
  ADSL: 'ADSL',
  'AFL-11': 'AFL-1.1',
  'AFL-12': 'AFL-1.2',
  'AFL-20': 'AFL-2.0',
  'AFL-21': 'AFL-2.1',
  'AFL-30': 'AFL-3.0',
  'AGPL-10-only': 'AGPL-1.0-only',
  'AGPL-10-or-later': 'AGPL-1.0-or-later',
  'AGPL-30-only': 'AGPL-3.0-only',
  'AGPL-30-or-later': 'AGPL-3.0-or-later',
  AMDPLPA: 'AMDPLPA',
  AML: 'AML',
  AMPAS: 'AMPAS',
  'ANTLR-PD': 'ANTLR-PD',
  'ANTLR-PD-fallback': 'ANTLR-PD-fallback',
  APAFML: 'APAFML',
  'APL-10': 'APL-1.0',
  'APSL-10': 'APSL-1.0',
  'APSL-11': 'APSL-1.1',
  'APSL-12': 'APSL-1.2',
  'APSL-20': 'APSL-2.0',
  Abstyles: 'Abstyles',
  'Adobe-2006': 'Adobe-2006',
  'Adobe-Glyph': 'Adobe-Glyph',
  Afmparse: 'Afmparse',
  Aladdin: 'Aladdin',
  'Apache-10': 'Apache-1.0',
  'Apache-11': 'Apache-1.1',
  'Apache-20': 'Apache-2.0',
  'Artistic-10': 'Artistic-1.0',
  'Artistic-10-Perl': 'Artistic-1.0-Perl',
  'Artistic-10-cl8': 'Artistic-1.0-cl8',
  'Artistic-20': 'Artistic-2.0',
  'BSD-1-Clause': 'BSD-1-Clause',
  'BSD-2-Clause': 'BSD-2-Clause',
  'BSD-2-Clause-Patent': 'BSD-2-Clause-Patent',
  'BSD-2-Clause-Views': 'BSD-2-Clause-Views',
  'BSD-3-Clause': 'BSD-3-Clause',
  'BSD-3-Clause-Attribution': 'BSD-3-Clause-Attribution',
  'BSD-3-Clause-Clear': 'BSD-3-Clause-Clear',
  'BSD-3-Clause-LBNL': 'BSD-3-Clause-LBNL',
  'BSD-3-Clause-Modification': 'BSD-3-Clause-Modification',
  'BSD-3-Clause-No-Nuclear-License': 'BSD-3-Clause-No-Nuclear-License',
  'BSD-3-Clause-No-Nuclear-License-2014': 'BSD-3-Clause-No-Nuclear-License-2014',
  'BSD-3-Clause-No-Nuclear-Warranty': 'BSD-3-Clause-No-Nuclear-Warranty',
  'BSD-3-Clause-Open-MPI': 'BSD-3-Clause-Open-MPI',
  'BSD-4-Clause': 'BSD-4-Clause',
  'BSD-4-Clause-Shortened': 'BSD-4-Clause-Shortened',
  'BSD-4-Clause-UC': 'BSD-4-Clause-UC',
  'BSD-Protection': 'BSD-Protection',
  'BSD-Source-Code': 'BSD-Source-Code',
  'BSL-10': 'BSL-1.0',
  'BUSL-11': 'BUSL-1.1',
  Bahyph: 'Bahyph',
  Barr: 'Barr',
  Beerware: 'Beerware',
  'BitTorrent-10': 'BitTorrent-1.0',
  'BitTorrent-11': 'BitTorrent-1.1',
  'BlueOak-100': 'BlueOak-1.0.0',
  Borceux: 'Borceux',
  'C-UDA-10': 'C-UDA-1.0',
  'CAL-10': 'CAL-1.0',
  'CAL-10-Combined-Work-Exception': 'CAL-1.0-Combined-Work-Exception',
  'CATOSL-11': 'CATOSL-1.1',
  'CC-BY-10': 'CC-BY-1.0',
  'CC-BY-20': 'CC-BY-2.0',
  'CC-BY-25': 'CC-BY-2.5',
  'CC-BY-30': 'CC-BY-3.0',
  'CC-BY-40': 'CC-BY-4.0',
  'CC-BY-NC-10': 'CC-BY-NC-1.0',
  'CC-BY-NC-20': 'CC-BY-NC-2.0',
  'CC-BY-NC-25': 'CC-BY-NC-2.5',
  'CC-BY-NC-30': 'CC-BY-NC-3.0',
  'CC-BY-NC-40': 'CC-BY-NC-4.0',
  'CC-BY-NC-ND-10': 'CC-BY-NC-ND-1.0',
  'CC-BY-NC-ND-20': 'CC-BY-NC-ND-2.0',
  'CC-BY-NC-ND-25': 'CC-BY-NC-ND-2.5',
  'CC-BY-NC-ND-30': 'CC-BY-NC-ND-3.0',
  'CC-BY-NC-ND-40': 'CC-BY-NC-ND-4.0',
  'CC-BY-NC-SA-10': 'CC-BY-NC-SA-1.0',
  'CC-BY-NC-SA-20': 'CC-BY-NC-SA-2.0',
  'CC-BY-NC-SA-25': 'CC-BY-NC-SA-2.5',
  'CC-BY-NC-SA-30': 'CC-BY-NC-SA-3.0',
  'CC-BY-NC-SA-40': 'CC-BY-NC-SA-4.0',
  'CC-BY-ND-10': 'CC-BY-ND-1.0',
  'CC-BY-ND-20': 'CC-BY-ND-2.0',
  'CC-BY-ND-25': 'CC-BY-ND-2.5',
  'CC-BY-ND-30': 'CC-BY-ND-3.0',
  'CC-BY-ND-40': 'CC-BY-ND-4.0',
  'CC-BY-SA-10': 'CC-BY-SA-1.0',
  'CC-BY-SA-20': 'CC-BY-SA-2.0',
  'CC-BY-SA-25': 'CC-BY-SA-2.5',
  'CC-BY-SA-30': 'CC-BY-SA-3.0',
  'CC-BY-SA-40': 'CC-BY-SA-4.0',
  'CC-PDDC': 'CC-PDDC',
  'CC0-10': 'CC0-1.0',
  'CDDL-10': 'CDDL-1.0',
  'CDDL-11': 'CDDL-1.1',
  'CDLA-Permissive-10': 'CDLA-Permissive-1.0',
  'CDLA-Sharing-10': 'CDLA-Sharing-1.0',
  'CECILL-10': 'CECILL-1.0',
  'CECILL-11': 'CECILL-1.1',
  'CECILL-20': 'CECILL-2.0',
  'CECILL-21': 'CECILL-2.1',
  'CECILL-B': 'CECILL-B',
  'CECILL-C': 'CECILL-C',
  'CERN-OHL-11': 'CERN-OHL-1.1',
  'CERN-OHL-12': 'CERN-OHL-1.2',
  'CERN-OHL-P-20': 'CERN-OHL-P-2.0',
  'CERN-OHL-S-20': 'CERN-OHL-S-2.0',
  'CERN-OHL-W-20': 'CERN-OHL-W-2.0',
  'CNRI-Jython': 'CNRI-Jython',
  'CNRI-Python': 'CNRI-Python',
  'CNRI-Python-GPL-Compatible': 'CNRI-Python-GPL-Compatible',
  'CPAL-10': 'CPAL-1.0',
  'CPL-10': 'CPL-1.0',
  'CPOL-102': 'CPOL-1.02',
  'CUA-OPL-10': 'CUA-OPL-1.0',
  Caldera: 'Caldera',
  ClArtistic: 'ClArtistic',
  'Condor-11': 'Condor-1.1',
  Crossword: 'Crossword',
  CrystalStacker: 'CrystalStacker',
  Cube: 'Cube',
  'D-FSL-10': 'D-FSL-1.0',
  DFSG: 'DFSG',
  DOC: 'DOC',
  'DRL-10': 'DRL-1.0',
  DSDP: 'DSDP',
  Dotseqn: 'Dotseqn',
  'ECL-10': 'ECL-1.0',
  'ECL-20': 'ECL-2.0',
  'EFL-10': 'EFL-1.0',
  'EFL-20': 'EFL-2.0',
  EPICS: 'EPICS',
  'EPL-10': 'EPL-1.0',
  'EPL-20': 'EPL-2.0',
  EUDatagrid: 'EUDatagrid',
  'EUPL-10': 'EUPL-1.0',
  'EUPL-11': 'EUPL-1.1',
  'EUPL-12': 'EUPL-1.2',
  Entessa: 'Entessa',
  'ErlPL-11': 'ErlPL-1.1',
  Eurosym: 'Eurosym',
  FSFAP: 'FSFAP',
  FSFUL: 'FSFUL',
  FSFULLR: 'FSFULLR',
  FTL: 'FTL',
  Fair: 'Fair',
  'Frameworx-10': 'Frameworx-1.0',
  'FreeBSD-DOC': 'FreeBSD-DOC',
  FreeImage: 'FreeImage',
  GD: 'GD',
  'GFDL-11-invariants-only': 'GFDL-1.1-invariants-only',
  'GFDL-11-invariants-or-later': 'GFDL-1.1-invariants-or-later',
  'GFDL-11-no-invariants-only': 'GFDL-1.1-no-invariants-only',
  'GFDL-11-no-invariants-or-later': 'GFDL-1.1-no-invariants-or-later',
  'GFDL-11-only': 'GFDL-1.1-only',
  'GFDL-11-or-later': 'GFDL-1.1-or-later',
  'GFDL-12-invariants-only': 'GFDL-1.2-invariants-only',
  'GFDL-12-invariants-or-later': 'GFDL-1.2-invariants-or-later',
  'GFDL-12-no-invariants-only': 'GFDL-1.2-no-invariants-only',
  'GFDL-12-no-invariants-or-later': 'GFDL-1.2-no-invariants-or-later',
  'GFDL-12-only': 'GFDL-1.2-only',
  'GFDL-12-or-later': 'GFDL-1.2-or-later',
  'GFDL-13-invariants-only': 'GFDL-1.3-invariants-only',
  'GFDL-13-invariants-or-later': 'GFDL-1.3-invariants-or-later',
  'GFDL-13-no-invariants-only': 'GFDL-1.3-no-invariants-only',
  'GFDL-13-no-invariants-or-later': 'GFDL-1.3-no-invariants-or-later',
  'GFDL-13-only': 'GFDL-1.3-only',
  'GFDL-13-or-later': 'GFDL-1.3-or-later',
  GL2PS: 'GL2PS',
  GLWTPL: 'GLWTPL',
  'GPL-10-only': 'GPL-1.0-only',
  'GPL-10-or-later': 'GPL-1.0-or-later',
  'GPL-20-only': 'GPL-2.0-only',
  'GPL-20-or-later': 'GPL-2.0-or-later',
  'GPL-30-only': 'GPL-3.0-only',
  'GPL-30-or-later': 'GPL-3.0-or-later',
  Giftware: 'Giftware',
  Glide: 'Glide',
  Glulxe: 'Glulxe',
  HPND: 'HPND',
  'HPND-sell-variant': 'HPND-sell-variant',
  HTMLTIDY: 'HTMLTIDY',
  HaskellReport: 'HaskellReport',
  'Hippocratic-21': 'Hippocratic-2.1',
  'IBM-pibs': 'IBM-pibs',
  ICU: 'ICU',
  IJG: 'IJG',
  IPA: 'IPA',
  'IPL-10': 'IPL-1.0',
  ISC: 'ISC',
  ImageMagick: 'ImageMagick',
  Imlib2: 'Imlib2',
  'Info-ZIP': 'Info-ZIP',
  Intel: 'Intel',
  'Intel-ACPI': 'Intel-ACPI',
  'Interbase-10': 'Interbase-1.0',
  JPNIC: 'JPNIC',
  JSON: 'JSON',
  'JasPer-20': 'JasPer-2.0',
  'LAL-12': 'LAL-1.2',
  'LAL-13': 'LAL-1.3',
  'LGPL-20-only': 'LGPL-2.0-only',
  'LGPL-20-or-later': 'LGPL-2.0-or-later',
  'LGPL-21-only': 'LGPL-2.1-only',
  'LGPL-21-or-later': 'LGPL-2.1-or-later',
  'LGPL-30-only': 'LGPL-3.0-only',
  'LGPL-30-or-later': 'LGPL-3.0-or-later',
  LGPLLR: 'LGPLLR',
  'LPL-10': 'LPL-1.0',
  'LPL-102': 'LPL-1.02',
  'LPPL-10': 'LPPL-1.0',
  'LPPL-11': 'LPPL-1.1',
  'LPPL-12': 'LPPL-1.2',
  'LPPL-13a': 'LPPL-1.3a',
  'LPPL-13c': 'LPPL-1.3c',
  Latex2e: 'Latex2e',
  Leptonica: 'Leptonica',
  'LiLiQ-P-11': 'LiLiQ-P-1.1',
  'LiLiQ-R-11': 'LiLiQ-R-1.1',
  'LiLiQ-Rplus-11': 'LiLiQ-Rplus-1.1',
  Libpng: 'Libpng',
  'Linux-OpenIB': 'Linux-OpenIB',
  MIT: 'MIT',
  'MIT-0': 'MIT-0',
  'MIT-CMU': 'MIT-CMU',
  'MIT-Modern-Variant': 'MIT-Modern-Variant',
  'MIT-advertising': 'MIT-advertising',
  'MIT-enna': 'MIT-enna',
  'MIT-feh': 'MIT-feh',
  'MIT-open-group': 'MIT-open-group',
  MITNFA: 'MITNFA',
  'MPL-10': 'MPL-1.0',
  'MPL-11': 'MPL-1.1',
  'MPL-20': 'MPL-2.0',
  'MPL-20-no-copyleft-exception': 'MPL-2.0-no-copyleft-exception',
  'MS-PL': 'MS-PL',
  'MS-RL': 'MS-RL',
  MTLL: 'MTLL',
  MakeIndex: 'MakeIndex',
  MirOS: 'MirOS',
  Motosoto: 'Motosoto',
  'MulanPSL-10': 'MulanPSL-1.0',
  'MulanPSL-20': 'MulanPSL-2.0',
  Multics: 'Multics',
  Mup: 'Mup',
  'NAIST-2003': 'NAIST-2003',
  'NASA-13': 'NASA-1.3',
  'NBPL-10': 'NBPL-1.0',
  'NCGL-UK-20': 'NCGL-UK-2.0',
  NCSA: 'NCSA',
  NGPL: 'NGPL',
  'NIST-PD': 'NIST-PD',
  'NIST-PD-fallback': 'NIST-PD-fallback',
  'NLOD-10': 'NLOD-1.0',
  NLPL: 'NLPL',
  NOSL: 'NOSL',
  'NPL-10': 'NPL-1.0',
  'NPL-11': 'NPL-1.1',
  'NPOSL-30': 'NPOSL-3.0',
  NRL: 'NRL',
  NTP: 'NTP',
  'NTP-0': 'NTP-0',
  Naumen: 'Naumen',
  'Net-SNMP': 'Net-SNMP',
  NetCDF: 'NetCDF',
  Newsletr: 'Newsletr',
  Nokia: 'Nokia',
  Noweb: 'Noweb',
  'O-UDA-10': 'O-UDA-1.0',
  'OCCT-PL': 'OCCT-PL',
  'OCLC-20': 'OCLC-2.0',
  'ODC-By-10': 'ODC-By-1.0',
  'ODbL-10': 'ODbL-1.0',
  'OFL-10': 'OFL-1.0',
  'OFL-10-RFN': 'OFL-1.0-RFN',
  'OFL-10-no-RFN': 'OFL-1.0-no-RFN',
  'OFL-11': 'OFL-1.1',
  'OFL-11-RFN': 'OFL-1.1-RFN',
  'OFL-11-no-RFN': 'OFL-1.1-no-RFN',
  'OGC-10': 'OGC-1.0',
  'OGDL-Taiwan-10': 'OGDL-Taiwan-1.0',
  'OGL-Canada-20': 'OGL-Canada-2.0',
  'OGL-UK-10': 'OGL-UK-1.0',
  'OGL-UK-20': 'OGL-UK-2.0',
  'OGL-UK-30': 'OGL-UK-3.0',
  OGTSL: 'OGTSL',
  'OLDAP-11': 'OLDAP-1.1',
  'OLDAP-12': 'OLDAP-1.2',
  'OLDAP-13': 'OLDAP-1.3',
  'OLDAP-14': 'OLDAP-1.4',
  'OLDAP-20': 'OLDAP-2.0',
  'OLDAP-201': 'OLDAP-2.0.1',
  'OLDAP-21': 'OLDAP-2.1',
  'OLDAP-22': 'OLDAP-2.2',
  'OLDAP-221': 'OLDAP-2.2.1',
  'OLDAP-222': 'OLDAP-2.2.2',
  'OLDAP-23': 'OLDAP-2.3',
  'OLDAP-24': 'OLDAP-2.4',
  'OLDAP-25': 'OLDAP-2.5',
  'OLDAP-26': 'OLDAP-2.6',
  'OLDAP-27': 'OLDAP-2.7',
  'OLDAP-28': 'OLDAP-2.8',
  OML: 'OML',
  'OPL-10': 'OPL-1.0',
  'OSET-PL-21': 'OSET-PL-2.1',
  'OSL-10': 'OSL-1.0',
  'OSL-11': 'OSL-1.1',
  'OSL-20': 'OSL-2.0',
  'OSL-21': 'OSL-2.1',
  'OSL-30': 'OSL-3.0',
  OpenSSL: 'OpenSSL',
  'PDDL-10': 'PDDL-1.0',
  'PHP-30': 'PHP-3.0',
  'PHP-301': 'PHP-3.01',
  'PSF-20': 'PSF-2.0',
  'Parity-600': 'Parity-6.0.0',
  'Parity-700': 'Parity-7.0.0',
  Plexus: 'Plexus',
  'PolyForm-Noncommercial-100': 'PolyForm-Noncommercial-1.0.0',
  'PolyForm-Small-Business-100': 'PolyForm-Small-Business-1.0.0',
  PostgreSQL: 'PostgreSQL',
  'Python-20': 'Python-2.0',
  'QPL-10': 'QPL-1.0',
  Qhull: 'Qhull',
  'RHeCos-11': 'RHeCos-1.1',
  'RPL-11': 'RPL-1.1',
  'RPL-15': 'RPL-1.5',
  'RPSL-10': 'RPSL-1.0',
  'RSA-MD': 'RSA-MD',
  RSCPL: 'RSCPL',
  Rdisc: 'Rdisc',
  Ruby: 'Ruby',
  'SAX-PD': 'SAX-PD',
  SCEA: 'SCEA',
  'SGI-B-10': 'SGI-B-1.0',
  'SGI-B-11': 'SGI-B-1.1',
  'SGI-B-20': 'SGI-B-2.0',
  'SHL-05': 'SHL-0.5',
  'SHL-051': 'SHL-0.51',
  SISSL: 'SISSL',
  'SISSL-12': 'SISSL-1.2',
  SMLNJ: 'SMLNJ',
  SMPPL: 'SMPPL',
  SNIA: 'SNIA',
  'SPL-10': 'SPL-1.0',
  'SSH-OpenSSH': 'SSH-OpenSSH',
  'SSH-short': 'SSH-short',
  'SSPL-10': 'SSPL-1.0',
  SWL: 'SWL',
  Saxpath: 'Saxpath',
  Sendmail: 'Sendmail',
  'Sendmail-823': 'Sendmail-8.23',
  'SimPL-20': 'SimPL-2.0',
  Sleepycat: 'Sleepycat',
  'Spencer-86': 'Spencer-86',
  'Spencer-94': 'Spencer-94',
  'Spencer-99': 'Spencer-99',
  'SugarCRM-113': 'SugarCRM-1.1.3',
  'TAPR-OHL-10': 'TAPR-OHL-1.0',
  TCL: 'TCL',
  'TCP-wrappers': 'TCP-wrappers',
  TMate: 'TMate',
  'TORQUE-11': 'TORQUE-1.1',
  TOSL: 'TOSL',
  'TU-Berlin-10': 'TU-Berlin-1.0',
  'TU-Berlin-20': 'TU-Berlin-2.0',
  'UCL-10': 'UCL-1.0',
  'UPL-10': 'UPL-1.0',
  'Unicode-DFS-2015': 'Unicode-DFS-2015',
  'Unicode-DFS-2016': 'Unicode-DFS-2016',
  'Unicode-TOU': 'Unicode-TOU',
  Unlicense: 'Unlicense',
  VOSTROM: 'VOSTROM',
  'VSL-10': 'VSL-1.0',
  Vim: 'Vim',
  W3C: 'W3C',
  'W3C-19980720': 'W3C-19980720',
  'W3C-20150513': 'W3C-20150513',
  WTFPL: 'WTFPL',
  'Watcom-10': 'Watcom-1.0',
  Wsuipa: 'Wsuipa',
  X11: 'X11',
  'XFree86-11': 'XFree86-1.1',
  XSkat: 'XSkat',
  Xerox: 'Xerox',
  Xnet: 'Xnet',
  'ZPL-11': 'ZPL-1.1',
  'ZPL-20': 'ZPL-2.0',
  'ZPL-21': 'ZPL-2.1',
  Zed: 'Zed',
  'Zend-20': 'Zend-2.0',
  'Zimbra-13': 'Zimbra-1.3',
  'Zimbra-14': 'Zimbra-1.4',
  Zlib: 'Zlib',
  blessing: 'blessing',
  'bzip2-105': 'bzip2-1.0.5',
  'bzip2-106': 'bzip2-1.0.6',
  'copyleft-next-030': 'copyleft-next-0.3.0',
  'copyleft-next-031': 'copyleft-next-0.3.1',
  curl: 'curl',
  diffmark: 'diffmark',
  dvipdfm: 'dvipdfm',
  eGenix: 'eGenix',
  'etalab-20': 'etalab-2.0',
  freeware: 'freeware',
  'gSOAP-13b': 'gSOAP-1.3b',
  gnuplot: 'gnuplot',
  iMatix: 'iMatix',
  'libpng-20': 'libpng-2.0',
  'libselinux-10': 'libselinux-1.0',
  libtiff: 'libtiff',
  mpich2: 'mpich2',
  proprietary: 'proprietary',
  psfrag: 'psfrag',
  psutils: 'psutils',
  unknown: 'unknown',
  xinetd: 'xinetd',
  xpp: 'xpp',
  'zlib-acknowledgement': 'zlib-acknowledgement',
} as const;

/**
 * A structure describing some interesting facts about an OS template license item
 */
export interface DedicatedTemplateOsInfoLicenseItemOVH {
  /**
   * OS template license item names
   * @nullable
   */
  name?: DedicatedTemplateOsInfoLicenseItemEnumOVH[] | null;
  /**
   * OS template license item url
   * @nullable
   */
  url?: string | null;
}

/**
 * OS template license usage details
 * @nullable
 */
export type DedicatedTemplateOsInfoLicenseOVHUsage = DedicatedTemplateOsInfoLicenseItemOVH | null;

/**
 * OS template license OS details
 * @nullable
 */
export type DedicatedTemplateOsInfoLicenseOVHOs = DedicatedTemplateOsInfoLicenseItemOVH | null;

/**
 * A structure describing some interesting facts about an OS template licensing
 */
export interface DedicatedTemplateOsInfoLicenseOVH {
  /**
   * OS template license OS details
   * @nullable
   */
  os?: DedicatedTemplateOsInfoLicenseOVHOs;
  /**
   * OS template license usage details
   * @nullable
   */
  usage?: DedicatedTemplateOsInfoLicenseOVHUsage;
}

/**
 * OS template project details
 * @nullable
 */
export type DedicatedTemplateOsInfoOVHProject = DedicatedTemplateOsInfoProjectOVH | null;

/**
 * OS template license details
 * @nullable
 */
export type DedicatedTemplateOsInfoOVHLicense = DedicatedTemplateOsInfoLicenseOVH | null;

/**
 * A structure describing some interesting facts about an OS template
 */
export interface DedicatedTemplateOsInfoOVH {
  /** OS Category (also called OS usage) */
  category?: DedicatedTemplateOsUsageEnumOVH;
  /** OS long name */
  description?: string;
  /**
   * OS template end of install at OVH date
   * @nullable
   */
  endOfInstall?: string | null;
  /** OS family (also called OS type) */
  family?: DedicatedTemplateOsTypeEnumOVH;
  /**
   * OS template license details
   * @nullable
   */
  license?: DedicatedTemplateOsInfoOVHLicense;
  /**
   * OS template project details
   * @nullable
   */
  project?: DedicatedTemplateOsInfoOVHProject;
  /** OS subfamily */
  subfamily?: DedicatedTemplateOsSubfamilyEnumOVH;
  /** OS template name */
  templateName?: string;
}

/**
 * Hardware RAID enum
 */
export type DedicatedTemplateOsHardwareRaidEnumOVH = typeof DedicatedTemplateOsHardwareRaidEnumOVH[keyof typeof DedicatedTemplateOsHardwareRaidEnumOVH];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedicatedTemplateOsHardwareRaidEnumOVH = {
  raid0: 'raid0',
  raid1: 'raid1',
  raid10: 'raid10',
  raid5: 'raid5',
  raid50: 'raid50',
  raid6: 'raid6',
  raid60: 'raid60',
} as const;

/**
 * A numeric value tagged with its unit
 */
export interface ComplexTypeUnitAndValueLongOVH {
  unit?: string;
  value?: number;
}

