export const DISCOVER_VCD_REDIRECTION_URL: Record<string, string> = {
  DEFAULT: 'https://www.ovhcloud.com/en/public-vcf-aas/',
  FR: 'https://www.ovhcloud.com/fr/public-vcf-aas/',
  EN: 'https://www.ovhcloud.com/en/public-vcf-aas/',
  DE: 'https://www.ovhcloud.com/de/public-vcf-aas/',
  'ES-ES': 'https://www.ovhcloud.com/es-es/public-vcf-aas/',
  'EN-IE': 'https://www.ovhcloud.com/en-ie/public-vcf-aas/',
  IT: 'https://www.ovhcloud.com/it/public-vcf-aas/',
  NL: 'https://www.ovhcloud.com/nl/public-vcf-aas/',
  PL: 'https://www.ovhcloud.com/pl/public-vcf-aas/',
  PT: 'https://www.ovhcloud.com/pt/public-vcf-aas/',
  'EN-GB': 'https://www.ovhcloud.com/en-gb/public-vcf-aas/',
  'EN-CA': 'https://www.ovhcloud.com/en-ca/public-vcf-aas/',
  'FR-CA': 'https://www.ovhcloud.com/fr-ca/public-vcf-aas/',
  'EN-US':
    'https://us.ovhcloud.com/public-vcf-aas/?_gl=1*kt40jj*_gcl_aw*R0NMLjE3NTAwODY2NzUuRUFJYUlRb2JDaE1JbUxUQjhaejJqUU1WX2JWb0NSM0ZZRFhmRUFBWUFTQUFFZ0tTV2ZEX0J3RQ..*_gcl_au*MTk2MDY1OTc0NS4xNzQ5NjI3ODUw',
  ES: 'https://www.ovhcloud.com/es/public-vcf-aas/',
  'FR-MA': 'https://www.ovhcloud.com/fr-ma/public-vcf-aas/',
  'FR-SN': 'https://www.ovhcloud.com/fr-sn/public-vcf-aas/',
  'FR-TN': 'https://www.ovhcloud.com/fr-tn/public-vcf-aas/',
  'EN-AU': 'https://www.ovhcloud.com/en-au/public-vcf-aas/',
  'EN-IN': 'https://www.ovhcloud.com/en-in/public-vcf-aas/',
  'EN-SG': 'https://www.ovhcloud.com/en-sg/public-vcf-aas/',
  ASIA: 'https://www.ovhcloud.com/asia/public-vcf-aas/',
};
