export const ORDER_VCD_REDIRECTION_URL: Record<string, string> = {
  FR: 'https://www.ovhcloud.com/fr/public-vcf-aas/configurator/',
  EN: 'https://www.ovhcloud.com/en/public-vcf-aas/configurator/',
  DE: 'https://www.ovhcloud.com/de/public-vcf-aas/configurator/',
  ES: 'https://www.ovhcloud.com/es-es/public-vcf-aas/configurator/',
  IE: 'https://www.ovhcloud.com/en-ie/public-vcf-aas/configurator/',
  IT: 'https://www.ovhcloud.com/it/public-vcf-aas/configurator/',
  NL: 'https://www.ovhcloud.com/nl/public-vcf-aas/configurator/',
  PL: 'https://www.ovhcloud.com/pl/public-vcf-aas/configurator/',
  PT: 'https://www.ovhcloud.com/pt/public-vcf-aas/configurator/',
  GB: 'https://www.ovhcloud.com/en-gb/public-vcf-aas/configurator/',
  CA: 'https://www.ovhcloud.com/en-ca/public-vcf-aas/configurator/',
  QC: 'https://www.ovhcloud.com/fr-ca/public-vcf-aas/configurator/',
  MA: 'https://www.ovhcloud.com/fr-ma/public-vcf-aas/configurator/',
  SN: 'https://www.ovhcloud.com/fr-sn/public-vcf-aas/configurator/',
  TN: 'https://www.ovhcloud.com/fr-tn/public-vcf-aas/configurator/',
  AU: 'https://www.ovhcloud.com/en-au/public-vcf-aas/configurator/',
  IN: 'https://www.ovhcloud.com/en-in/public-vcf-aas/configurator/',
  SG: 'https://www.ovhcloud.com/en-sg/public-vcf-aas/configurator/',
  ASIA: 'https://www.ovhcloud.com/asia/public-vcf-aas/configurator/',
  US: 'https://us.ovhcloud.com/public-vcf-aas',
  DEFAULT: 'https://www.ovhcloud.com/en/public-vcf-aas/configurator/',
};
