export const ORDER_VCD_REDIRECTION_URL: Record<string, string> = {
  DEFAULT: 'https://www.ovhcloud.com/en/public-vcf-aas/',
  FR: 'https://www.ovhcloud.com/fr/public-vcf-aas/',
  DE: 'https://www.ovhcloud.com/de/public-vcf-aas/',
  IE: 'https://www.ovhcloud.com/en-ie/public-vcf-aas/',
  PL: 'https://www.ovhcloud.com/pl/public-vcf-aas/',
  ES: 'https://www.ovhcloud.com/es-es/public-vcf-aas/',
  IT: 'https://www.ovhcloud.com/it/public-vcf-aas/',
  PT: 'https://www.ovhcloud.com/pt/public-vcf-aas/',
  NL: 'https://www.ovhcloud.com/nl/public-vcf-aas/',
  GB: 'https://www.ovhcloud.com/en-gb/public-vcf-aas/',
  CA: 'https://www.ovhcloud.com/en-ca/public-vcf-aas/',
  QC: 'https://www.ovhcloud.com/fr-ca/public-vcf-aas/',
  WS: 'https://www.ovhcloud.com/es/public-vcf-aas/',
  MA: 'https://www.ovhcloud.com/fr-ma/public-vcf-aas/',
  SN: 'https://www.ovhcloud.com/fr-sn/public-vcf-aas/',
  TN: 'https://www.ovhcloud.com/fr-tn/public-vcf-aas/',
  AU: 'https://www.ovhcloud.com/en-au/public-vcf-aas/',
  SG: 'https://www.ovhcloud.com/en-sg/public-vcf-aas/',
  ASIA: 'https://www.ovhcloud.com/asia/public-vcf-aas/',
  IN: 'https://www.ovhcloud.com/en-in/public-vcf-aas/',
  WE: 'https://www.ovhcloud.com/en/public-vcf-aas/',
  US: 'https://us.ovhcloud.com/public-vcf-aas/',
};
