export const ORDER_VCD_REDIRECTION_URL: Record<string, string> = {
  FR: 'https://www.ovhcloud.com/fr/public-vcf-aas/configurator/',
  EN: 'https://www.ovhcloud.com/en/public-vcf-aas/configurator/',
  DE: 'https://www.ovhcloud.com/de/public-vcf-aas/configurator/',
  'ES-ES': 'https://www.ovhcloud.com/es-es/public-vcf-aas/configurator/',
  'EN-IE': 'https://www.ovhcloud.com/en-ie/public-vcf-aas/configurator/',
  IT: 'https://www.ovhcloud.com/it/public-vcf-aas/configurator/',
  NL: 'https://www.ovhcloud.com/nl/public-vcf-aas/configurator/',
  PL: 'https://www.ovhcloud.com/pl/public-vcf-aas/configurator/',
  PT: 'https://www.ovhcloud.com/pt/public-vcf-aas/configurator/',
  'EN-GB': 'https://www.ovhcloud.com/en-gb/public-vcf-aas/configurator/',
  'EN-CA': 'https://www.ovhcloud.com/en-ca/public-vcf-aas/configurator/',
  'FR-CA': 'https://www.ovhcloud.com/fr-ca/public-vcf-aas/configurator/',
  ES: 'https://www.ovhcloud.com/es/public-vcf-aas/configurator/',
  'FR-MA': 'https://www.ovhcloud.com/fr-ma/public-vcf-aas/configurator/',
  'FR-SN': 'https://www.ovhcloud.com/fr-sn/public-vcf-aas/configurator/',
  'FR-TN': 'https://www.ovhcloud.com/fr-tn/public-vcf-aas/configurator/',
  'EN-AU': 'https://www.ovhcloud.com/en-au/public-vcf-aas/configurator/',
  'EN-IN': 'https://www.ovhcloud.com/en-in/public-vcf-aas/configurator/',
  'EN-SG': 'https://www.ovhcloud.com/en-sg/public-vcf-aas/configurator/',
  ASIA: 'https://www.ovhcloud.com/asia/public-vcf-aas/configurator/',
};
