const TEST_IDS = {
  listingVcdNameLink: 'listing-vcd-name-link',
  listingDatacentreNameLink: 'listing-datacentre-name-link',
  dashboardVcdInterfaceLink: 'dashboard-vcd-interface-link',
  dashboardVeeamBackupLink: 'dashboard-veeam-backup-link',
  dashboardDatacentreInterfaceLink: 'dashboard-datacentre-interface-link',
  activateLicenseCta: 'activate-license-cta',
  editButton: 'edit-button',
  modalSubmitCta: 'modal-submit-cta',
  cellDeleteCta: 'cell-delete-cta',
  cellDeleteTooltip: 'cell-delete-tooltip',
  computeOrderCta: 'compute-order-cta',
  computeSpecialOfferBanner: 'compute-offer-banner',
  storageOrderCta: 'storage-order-cta',
  backupBadgeLoading: 'backup-badge-loading',
  backupBadgeStatus: 'backup-badge-status',
  backupBadgeError: 'backup-badge-error',
  backupBadgeNone: 'backup-badge-none',
  vcdOrderCta: 'vcd-order-cta',
  networkAclCta: 'network-acl-cta',
  networkAclAddCurrentIpAction: 'add-current-ip-button',
  networkAclfromAnywhereIpAction: 'from-anywhere-ip-button',
  migrationAddCta: 'migration-add-cta',
  migrationCopyCta: 'migration-copy-cta',
  migrationDeleteCta: 'migration-delete-cta',
  migrationAddSubmitCta: 'migration-add-submit-cta',
  migrationDeleteSubmitCta: 'migration-delete-submit-cta',
  migrationRetryCta: 'migration-retry-cta',
  migrationTileStatusBadge: 'migration-tile-status-badge',
  migrationTileProvisioningBadge: 'migration-tile-provisioning-badge',
  migrationTileDeletingBadge: 'migration-tile-deleting-badge',
  migrationTileSkeleton: 'migration-tile-skeleton',
  migrationTileError: 'migration-tile-error',
  migrationTileRetryCta: 'migration-tile-retry-cta',
  migrationTab: 'migration-tab',
} as const;

export default TEST_IDS;
