export const VIRTUAL_MACHINES_ID = 'ID';
export const VIRTUAL_MACHINES_VCPU = 'vCPU';
export const VIRTUAL_MACHINES_TITLE = 'Virtual machines';
const TRACKING_DISPLAY_PREFIX = 'managed_vmware_vsphere::';
export const TRACKING_DISPLAY_LISTING_VIRTUAL_MACHINES_PREFIX = `${TRACKING_DISPLAY_PREFIX}listing::virtual-machine`;
const TRACKING_DISPLAY_POPUP_PREFIX = `${TRACKING_DISPLAY_PREFIX}popup::`;
export const TRACKING_DISPLAY_POPUP_ACTIVATE_LICENSE_PREFIX = `${TRACKING_DISPLAY_POPUP_PREFIX}activate_license`;
export const TRACKING_DISPLAY_POPUP_DELETE_LICENSE_PREFIX = `${TRACKING_DISPLAY_POPUP_PREFIX}delete_license`;
