/* global describe:true, beforeEach:true, afterEach:true, it:true, expect: true */
"use strict";

describe("ovh-angular-mondial-relay", function () {

    var $compile;
    var $httpBackend;
    var $scope;
    var elem;

    beforeEach(angular.mock.module("mondialRelayMock"));

    beforeEach(function () {
        // this module is generated by grunt task. we need to create it to satisfy dependencies
        angular.module("ovh-angular-mondial-relay-images", []);
        angular.module("ovh-angular-mondial-relay-images").constant("MONDIAL_RELAY_PICS", {});
    });

    beforeEach(function () {
        // these are the dependencies to the API
        angular.module("test.api", []);

        angular.module("test.api").service("OvhApiSupplyMondialRelay", function () {
            return {
                v6: function () {
                    return {
                        search: function () {
                            // Do nothing
                        }
                    };
                }
            };
        });

        angular.module("test.api").service("OvhApiMe", function () {
            return {
                v6: function () {
                    return {
                        get: function () {
                            // Do nothing
                        }
                    };
                }
            };
        });

        module("ovh-angular-mondial-relay", "test.api");
    });

    // Create scope
    beforeEach(angular.mock.inject(function (_$rootScope_, _$compile_, _$httpBackend_) {
        $scope = _$rootScope_.$new();
        $compile = _$compile_;
        $httpBackend = _$httpBackend_;

        elem = $("<div>").prependTo("body");
        $scope.$digest();
    }));

    afterEach(function () {
        $scope.$destroy();
        elem.remove();
    });

    var templates = {
        "default": {
            element: "<mondial-relay class=\"mondial-relay\" data-ng-model=\"MyRelay\"></mondial-relay>",
            scope: {}
        }
    };

    function compileDirective (templateName, locals) {
        var template = templates[templateName];
        angular.extend($scope, angular.copy(template.scope) || angular.copy(templates.default.scope), locals);
        var element = $(template.element).appendTo(elem);
        element = $compile(element)($scope);
        $scope.$digest();
        return jQuery(element[0]);
    }

    // ---

    describe("Directive", function () {

        it("should load the default directive", angular.mock.inject(function () {

            var element = compileDirective("default");
            $httpBackend.flush();
            var container = element.children();
            expect(container.hasClass("mondial-relay")).toBeTruthy();

        }));

    });

});
