export const CHALLENGER_INDIA_CREDIT_CARD_LENGTH = 4;
export const CHALLENGER_INDIA_CREDIT_CARD_PLACEHODER = 'XXXX';

export const CHALLENGER_INDIA_ERROR_CODES = {
  400: 'RETRY_CHALLENGE',
  404: 'PAYMENT_METHOD_DEACTIVATED',
  DEFAULT: 'RETRY_CHALLENGE',
};

export default {
  CHALLENGER_INDIA_CREDIT_CARD_LENGTH,
  CHALLENGER_INDIA_CREDIT_CARD_PLACEHODER,
  CHALLENGER_INDIA_ERROR_CODES,
};
