export const GUIDES = {
  OBJ_STO_ONBOARDING_TUTO_1: {
    fr_FR:
      'https://docs.ovh.com/gb/en/public-cloud/place-an-object-storage-container-behind-domain-name/',
    fr_CA:
      'https://docs.ovh.com/gb/en/public-cloud/place-an-object-storage-container-behind-domain-name/',
    default:
      'https://docs.ovh.com/gb/en/public-cloud/place-an-object-storage-container-behind-domain-name/',
  },
  OBJ_STO_ONBOARDING_TUTO_2: {
    fr_FR:
      'https://docs.ovh.com/gb/en/public-cloud/configure-auto-delete-objects/',
    fr_CA:
      'https://docs.ovh.com/gb/en/public-cloud/configure-auto-delete-objects/',
    default:
      'https://docs.ovh.com/gb/en/public-cloud/configure-auto-delete-objects/',
  },
  OBJ_STO_ONBOARDING_TUTO_3: {
    fr_FR:
      'https://docs.ovh.com/gb/en/public-cloud/share_an_object_via_a_temporary_url/',
    fr_CA:
      'https://docs.ovh.com/gb/en/public-cloud/share_an_object_via_a_temporary_url/',
    default:
      'https://docs.ovh.com/gb/en/public-cloud/share_an_object_via_a_temporary_url/',
  },
  OBJ_STO_RCLONE: {
    fr_FR: 'https://docs.ovh.com/fr/storage/sync-rclone-object-storage/',
    fr_CA: 'https://docs.ovh.com/fr/storage/sync-rclone-object-storage/',
    default: 'https://docs.ovh.com/gb/en/storage/sync-rclone-object-storage/',
  },
  OBJ_STO_ENCRYPTION: {
    fr_FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-encrypt-objects-sse-c?id=kb_article_view&sysparm_article=KB0047318',
    fr_CA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-encrypt-objects-sse-c?id=kb_article_view&sysparm_article=KB0047318',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-encrypt-objects-sse-c?id=kb_article_view&sysparm_article=KB0047314',
  },
  OBJ_STO_CLASSES: {
    fr_FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-choosing-right-storage-class?id=kb_article_view&sysparm_article=KB0047302',
    fr_CA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-choosing-right-storage-class?id=kb_article_view&sysparm_article=KB0047302',
    default:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-choosing-right-storage-class?id=kb_article_view&sysparm_article=KB0047293',
  },
  OBJ_STO_PRICES: {
    fr_FR: 'https://www.ovhcloud.com/fr/public-cloud/prices/#439',
    fr_CA: 'https://www.ovhcloud.com/fr/public-cloud/prices/#439',
    default: 'https://www.ovhcloud.com/en/public-cloud/prices/#439',
  },
  // Storage Guides - Async Replication
  STORAGE_ASYNC_REPLICATION: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062424',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062420',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062423',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062426',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062427',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062415',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062418',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062422',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062415',
    IN:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062424',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062425',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062418',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062417',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062421',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062414',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062413',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062416',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062418',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062418',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/34270032176019-Object-Storage-Master-asynchronous-replication-across-your-buckets',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062417',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062419',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062417',
  },
  ALL_GUIDES: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    DE:
      'https://help.ovhcloud.com/csm/de-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    AU:
      'https://help.ovhcloud.com/csm/en-au-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    NL:
      'https://help.ovhcloud.com/csm/en-nl-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    WE:
      'https://help.ovhcloud.com/csm/en-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    ES:
      'https://help.ovhcloud.com/csm/es-es-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    WS:
      'https://help.ovhcloud.com/csm/es-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    MA:
      'https://help.ovhcloud.com/csm/fr-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    FR:
      'https://help.ovhcloud.com/csm/fr-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    SN:
      'https://help.ovhcloud.com/csm/fr-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    TN:
      'https://help.ovhcloud.com/csm/fr-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    IT:
      'https://help.ovhcloud.com/csm/it-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    PL:
      'https://help.ovhcloud.com/csm/pl-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    PT:
      'https://help.ovhcloud.com/csm/pt-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    IN:
      'https://help.ovhcloud.com/csm/en-in-documentation-public-cloud-storage-object-storage?id=kb_browse_cat&kb_id=574a8325551974502d4c6e78b7421938&kb_category=6f34d555f49801102d4ca4d466a7fd9b&spa=1',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/sections/23498311424275-Object-Storage',
    default:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-asynchronous-replication-buckets?id=kb_article_view&sysparm_article=KB0062415',
  },
  GETTING_STARTED: {
    SIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047333',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047336',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047335',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047343',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0034674',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047339',
    NL:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047339',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047361',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047348',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047353',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047352',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047355',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047354',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047354',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047354',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047354',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047356',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047359',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047346',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0069681',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/4603838122643-Getting-started-with-Object-Storage',
    default:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-getting-started-object-storage?id=kb_article_view&sysparm_article=KB0047339',
  },
  // Storage Guides - Localisation
  STORAGE_LOCALISATION: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0034723',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047380',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047381',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047388',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047396',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047393',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047389',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047382',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047393',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0069696',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047402',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047389',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047384',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047390',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047391',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047387',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047394',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047389',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047389',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/10667991081107-Object-Storage-Endpoints-and-geoavailability',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047384',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047386',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047384',
  },
  // Storage Guides - Object Lock
  STORAGE_OBJECT_LOCK: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047392',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047408',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047400',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0034736',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047403',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047398',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047404',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047401',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047398',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0069687',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047405',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047404',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047399',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047406',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047425',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047412',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047395',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047404',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047404',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/10694926634003-Managing-Object-Immutability-with-Object-Lock-WORM',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047399',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047410',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-managing-object-lock?id=kb_article_view&sysparm_article=KB0047399',
  },
  // Storage Guides - Versioning
  STORAGE_VERSIONING: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063860',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063847',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063865',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063859',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063867',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063858',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063869',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063864',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063858',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0069702',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063866',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063869',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063856',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063861',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063868',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063863',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063857',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063869',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063869',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/31431459806355-Object-Storage-Getting-started-with-versioning',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063856',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063862',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-versioning?id=kb_article_view&sysparm_article=KB0063856',
  },
  // Storage Guides - Access Logs
  STORAGE_ACCESS_LOGS: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056617',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056615',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056613',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056618',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056620',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056614',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056623',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056616',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056614',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0069699',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056621',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056623',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056624',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056622',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056627',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056619',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056625',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056623',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056623',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/23888209235347-Object-Storage-Server-access-logging',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056624',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056626',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-server-access-logging?id=kb_article_view&sysparm_article=KB0056624',
  },
  // Storage Guides - Static Website
  STORAGE_STATIC_WEBSITE: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058059',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058069',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058058',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058063',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058072',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058068',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058095',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058056',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058068',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0069704',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058073',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058095',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058067',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058071',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058061',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058096',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058066',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058095',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058095',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/17763186562451-Object-Storage-Hosting-a-static-website-in-an-Object-Storage-bucket',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058067',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058062',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-static-website?id=kb_article_view&sysparm_article=KB0058067',
  },
  // Storage Guides - Lifecycle
  STORAGE_LIFECYCLE: {
    ASIA:
      'https://help.ovhcloud.com/csm/asia-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066011',
    AU:
      'https://help.ovhcloud.com/csm/en-au-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066012',
    CA:
      'https://help.ovhcloud.com/csm/en-ca-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066015',
    DE:
      'https://help.ovhcloud.com/csm/de-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066013',
    ES:
      'https://help.ovhcloud.com/csm/es-es-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066016',
    EU:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066017',
    FR:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066010',
    GB:
      'https://help.ovhcloud.com/csm/en-gb-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066014',
    IE:
      'https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066017',
    IN:
      'https://help.ovhcloud.com/csm/en-in-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0069713',
    IT:
      'https://help.ovhcloud.com/csm/it-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066018',
    MA:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066010',
    NL:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066009',
    PL:
      'https://help.ovhcloud.com/csm/pl-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066019',
    PT:
      'https://help.ovhcloud.com/csm/pt-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066020',
    QC:
      'https://help.ovhcloud.com/csm/fr-ca-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066021',
    SG:
      'https://help.ovhcloud.com/csm/en-sg-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066022',
    SN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066010',
    TN:
      'https://help.ovhcloud.com/csm/fr-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066010',
    US:
      'https://support.us.ovhcloud.com/hc/en-us/articles/32894387766419-Object-Storage-Manage-the-lifecycle-of-your-buckets',
    WE:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066009',
    WS:
      'https://help.ovhcloud.com/csm/es-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066023',
    default:
      'https://help.ovhcloud.com/csm/en-public-cloud-storage-s3-bucket-lifecycle?id=kb_article_view&sysparm_article=KB0066009',
  },
};

export function getGuideUrl(
  guide: typeof GUIDES[keyof typeof GUIDES],
  locale: string,
): string {
  return guide[locale as keyof typeof guide] || guide.default;
}
