name: Enforce PR labels
on: [pull_request]

jobs:
  translation-required:
    if: ${{ contains(github.event.*.labels.*.name, 'translation required') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check for translation required label
        run: |
          echo "Pull request is labeled as 'translation required'"
          exit 1
