name: 'Stale issues'
on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: 30
          stale-issue-label: 'stale'
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          remove-issue-stale-when-updated: true
