export const GUIDES = [
  {
    title: 'veeam_enterprise__onboarding_guide1_title',
    description: 'veeam_enterprise__onboarding_guide1_description',
    links: {
      DEFAULT: 'https://docs.ovh.com/gb/en/storage/veeam-backup-replication/',
      ASIA: 'https://docs.ovh.com/asia/en/storage/veeam-backup-replication/',
      DE: 'https://docs.ovh.com/de/storage/veeam-backup-replication/',
      ES: 'https://docs.ovh.com/es/storage/veeam-backup-replication/',
      IE: 'https://docs.ovh.com/ie/en/storage/veeam-backup-replication/',
      IT: 'https://docs.ovh.com/it/storage/veeam-backup-replication/',
      PL: 'https://docs.ovh.com/pl/storage/veeam-backup-replication/',
      PT: 'https://docs.ovh.com/pt/storage/veeam-backup-replication/',
      GB: 'https://docs.ovh.com/gb/en/storage/veeam-backup-replication/',
      CA: 'https://docs.ovh.com/ca/en/storage/veeam-backup-replication/',
      QC: 'https://docs.ovh.com/ca/fr/storage/veeam-backup-replication/',
      AU: 'https://docs.ovh.com/au/en/storage/veeam-backup-replication/',
      SG: 'https://docs.ovh.com/sg/en/storage/veeam-backup-replication/',
      FR: 'https://docs.ovh.com/fr/storage/veeam-backup-replication/',
      WE: 'https://support.us.ovhcloud.com/hc/en-us/articles/360002270130',
      WS: 'https://support.us.ovhcloud.com/hc/en-us/articles/360002270130',
      US: 'https://support.us.ovhcloud.com/hc/en-us/articles/360002270130',
    },
  },
];

export const CTAS = {
  DEFAULT: 'https://ovhcloud.com/en/storage-solutions/veeam-enterprise',
  ASIA: 'https://ovhcloud.com/asia/storage-solutions/veeam-enterprise',
  DE: 'https://ovhcloud.com/de/storage-solutions/veeam-enterprise',
  ES: 'https://ovhcloud.com/es-es/storage-solutions/veeam-enterprise',
  IE: 'https://ovhcloud.com/en-ie/storage-solutions/veeam-enterprise',
  IT: 'https://ovhcloud.com/it/storage-solutions/veeam-enterprise',
  NL: 'https://ovhcloud.com/nl/storage-solutions/veeam-enterprise',
  PL: 'https://ovhcloud.com/pl/storage-solutions/veeam-enterprise',
  PT: 'https://ovhcloud.com/pt/storage-solutions/veeam-enterprise',
  GB: 'https://ovhcloud.com/en-gb/storage-solutions/veeam-enterprise',
  CA: 'https://ovhcloud.com/en-ca/storage-solutions/veeam-enterprise',
  QC: 'https://ovhcloud.com/fr-ca/storage-solutions/veeam-enterprise',
  MA: 'https://ovhcloud.com/fr-ma/storage-solutions/veeam-enterprise',
  SN: 'https://ovhcloud.com/fr-sn/storage-solutions/veeam-enterprise',
  TN: 'https://ovhcloud.com/fr-tn/storage-solutions/veeam-enterprise',
  AU: 'https://ovhcloud.com/en-au/storage-solutions/veeam-enterprise',
  SG: 'https://ovhcloud.com/en-sg/storage-solutions/veeam-enterprise',
  FR: 'https://ovhcloud.com/fr/storage-solutions/veeam-enterprise',
  CZ: 'https://ovhcloud.com/cz-cs/storage-solutions/veeam-enterprise',
  FI: 'https://ovhcloud.com/fi/storage-solutions/veeam-enterprise',
  LT: 'https://ovhcloud.com/lt/storage-solutions/veeam-enterprise',
};
